#!/bin/sh
# postrm script for prometheus-mysqld-exporter
# Script executed after the package is removed.

set -e

case "$1" in
  purge)
        rm -rf /var/log/prometheus/prometheus-mysqld-exporter.log \
            /var/run/prometheus/prometheus-mysqld-exporter.pid
	# We do NOT remove the system user.
	;;
esac

# Automatically added by dh_installinit/11.4.1
if [ "$1" = "purge" ] ; then
	update-rc.d prometheus-mysqld-exporter remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.4.1
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'prometheus-mysqld-exporter.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'prometheus-mysqld-exporter.service' >/dev/null || true
		deb-systemd-helper unmask 'prometheus-mysqld-exporter.service' >/dev/null || true
	fi
fi
# End automatically added section

