#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.5.4
dpkg-maintscript-helper rm_conffile /etc/gitlab/initializers/devise_async.rb 8.8.2\+dfsg-5 gitlab -- "$@"
dpkg-maintscript-helper rm_conffile /etc/gitlab/gitlab.teatro.yml 8.11.3\+dfsg1-1 gitlab -- "$@"
dpkg-maintscript-helper rm_conffile /etc/gitlab/initializers/haml.rb 8.11.3\+dfsg1-1 gitlab -- "$@"
dpkg-maintscript-helper rm_conffile /etc/gitlab/initializers/math_lexer.rb 9.5.4\+dfsg-7 gitlab -- "$@"
dpkg-maintscript-helper rm_conffile /etc/gitlab/initializers/plantuml_lexer.rb 9.5.4\+dfsg-7 gitlab -- "$@"
dpkg-maintscript-helper rm_conffile /etc/gitlab/initializers/additional_headers_interceptor.rb 11.2.8\+dfsg-1 gitlab -- "$@"
dpkg-maintscript-helper rm_conffile /etc/gitlab/initializers/asset_sync.rb 11.5.3\+dfsg-1 gitlab -- "$@"
dpkg-maintscript-helper rm_conffile /etc/gitlab/initializers/email_template_interceptor.rb 11.2.8\+dfsg-1 gitlab -- "$@"
dpkg-maintscript-helper dir_to_symlink /usr/share/gitlab/app/assets/javascripts/locale /var/lib/gitlab/locale 9.5.4\+dfsg-5 gitlab -- "$@"
# End automatically added section
