#!/bin/sh
set -e
# Automatically added by dh_installinit/11.2.1
if [ -x "/etc/init.d/conntrackd" ] && [ "$1" = remove ]; then
	invoke-rc.d conntrackd stop || exit 1
fi
# End automatically added section
