#!/bin/sh

set -e

case "${1}" in
	remove|upgrade|deconfigure)
		# lzip-alternative
		update-alternatives --quiet --remove lzip /usr/bin/lzip.plzip

		# lzip-compressor
		update-alternatives --quiet --remove lzip-compressor /usr/bin/lzip.plzip

		# lzip-decompressor
		update-alternatives --quiet --remove lzip-decompressor /usr/bin/lzip.plzip
		;;

	failed-upgrade)

		;;

	*)
		echo "prerm called with unknown argument \`${1}'" >&2
		exit 1
		;;
esac



exit 0
