#! /bin/sh

set -e

case "$1" in
    remove)
	if which update-initramfs >/dev/null; then
		update-initramfs -u
	fi

	for file in cryptdisks_start cryptdisks_stop; do
		if [ -L /usr/sbin/$file ]; then
			rm /usr/sbin/$file
		fi
	done
    ;;
esac

# Automatically added by dh_installdeb/10.8
dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/cryptdisks 2:1.7.0-3 -- "$@"
# End automatically added section
# Automatically added by dh_installinit/10.8
if [ "$1" = "purge" ] ; then
	update-rc.d cryptdisks remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/10.8
if [ "$1" = "purge" ] ; then
	update-rc.d cryptdisks-early remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installdebconf/10.8
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

