#!/bin/sh
set -e
# Automatically added by dh_installxfonts
if which update-fonts-dir >/dev/null 2>&1; then
	update-fonts-dir --x11r7-layout cyrillic;update-fonts-alias --include /etc/X11/fonts/cyrillic/xfonts-cyrillic.alias cyrillic
fi
# End automatically added section
