#!/bin/sh

set -e

if [ "$1" = "remove" ] ; then
	update-alternatives --remove pyscss /usr/bin/python2-pyscss
	update-alternatives --remove less2scss /usr/bin/python2-less2scss
fi


# Automatically added by dhpython:
if which pyclean >/dev/null 2>&1; then
	pyclean -p python-pyscss 
else
	dpkg -L python-pyscss | grep \.py$ | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section


exit 0
