#!/bin/sh

set -e

generate_config() {
	confdbc=/usr/share/cacti/conf_templates/spine.conf.dbconfig
	confsrc=/usr/share/cacti/conf_templates/spine.conf.sample
	if [ -f "/etc/dbconfig-common/cacti.conf" ]; then
		dbconfig-generate-include -U -f template -o "template_infile=$confdbc" /etc/dbconfig-common/cacti.conf /etc/cacti/spine.conf
	else
		ucf $confsrc /etc/cacti/spine.conf
	fi
	ucfr cacti-spine /etc/cacti/spine.conf
	chown root:www-data /etc/cacti/spine.conf
	chmod 640 /etc/cacti/spine.conf
}

case "$1" in
"configure"|"reconfigure"|"upgrade")
	. /usr/share/debconf/confmodule
	db_version 2.0

	generate_config
;;
esac


