#!/bin/sh

set -e

if [ "{$1}" = "purge" ] ; then
	rm -f /etc/ivulncheck/ivulncheck-web.ini
	rmdir --ignore-fail-on-non-empty /etc/ivulncheck || true
	rm -f /var/log/ivulncheck/ivulncheck-web.log*
	rmdir --ignore-fail-on-non-empty /var/log/ivulncheck || true

	if [ -x ""$(which a2dissite) ] ; then
                a2dissite ivulncheck_api.conf || true
        fi
fi



exit 0
