#!/bin/sh -e

set -e

if [ "$1" != "upgrade" ]
then
  update-alternatives --remove editor /usr/bin/jove
  update-alternatives --remove emacs /usr/bin/jove
fi

# Automatically added by dh_installinit/11.2.1
if [ -x "/etc/init.d/jove" ] && [ "$1" = remove ]; then
	invoke-rc.d jove stop || exit 1
fi
# End automatically added section

