#!/bin/sh

set -e

if [ "${1}" = "purge" ] ; then
	rm -f /etc/neutron/plugins/ml2/ironic_neutron_agent.ini
fi

# Automatically added by dh_installinit/12
if [ "$1" = "purge" ] ; then
	update-rc.d ironic-neutron-agent remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_systemd_enable/12
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'ironic-neutron-agent.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'ironic-neutron-agent.service' >/dev/null || true
		deb-systemd-helper unmask 'ironic-neutron-agent.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
