#!/bin/sh

set -e

if [ "${1}" = "configure" ] || [ "${1}" = "reconfigure" ] ; then
	if ! [ -e /etc/neutron/plugins/ml2/ironic_neutron_agent.ini ] ; then
		cp /usr/share/ironic-neutron-agent/ironic_neutron_agent.ini /etc/neutron/plugins/ml2/ironic_neutron_agent.ini
	fi
fi

# Automatically added by dh_systemd_enable/12
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# This will only remove masks created by d-s-h on package removal.
	deb-systemd-helper unmask 'ironic-neutron-agent.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'ironic-neutron-agent.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'ironic-neutron-agent.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'ironic-neutron-agent.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installinit/12
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/ironic-neutron-agent" ]; then
		update-rc.d ironic-neutron-agent defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d ironic-neutron-agent $_dh_action || true
	fi
fi
# End automatically added section


exit 0
