#!/bin/sh

set -e

if [ "${1}" = "purge" ] ; then
	[ -d /etc/heat ] && rmdir --ignore-fail-on-non-empty /etc/heat
	rm -rf /var/log/heat/heat-engine.*
	[ -d /var/log/heat ] && rmdir --ignore-fail-on-non-empty /var/log/heat
fi

# Automatically added by dh_installinit/10.10.9
if [ "$1" = "purge" ] ; then
	update-rc.d heat-engine remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/10.10.9
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'heat-engine.service' >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'heat-engine.service' >/dev/null
		deb-systemd-helper unmask 'heat-engine.service' >/dev/null
	fi
fi
# End automatically added section


exit 0
