#!/bin/sh
set -e
# Automatically added by dh_installinit/10.10.9
if [ -x "/etc/init.d/networking-mlnx-eswitchd" ] && [ "$1" = remove ]; then
	invoke-rc.d networking-mlnx-eswitchd stop || true
fi
# End automatically added section
