#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/arc-cache-service" ]; then
		update-rc.d arc-cache-service defaults >/dev/null
		invoke-rc.d arc-cache-service start || exit $?
	fi
fi
# End automatically added section
