#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.4.1
dpkg-maintscript-helper rm_conffile /etc/firejail/lxterminal.profile 0.9.52-2\~ -- "$@"
dpkg-maintscript-helper mv_conffile /etc/firejail/xmr-stak-cpu.profile /etc/firejail/xmr-stak.profile 0.9.54\~rc1-1\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/firejail/Wire.profile 0.9.56-2\~ -- "$@"
dpkg-maintscript-helper mv_conffile /etc/firejail/wire.profile /etc/firejail/wire-desktop.profile 0.9.56-2\~ -- "$@"
# End automatically added section
