#! /bin/sh

set -e

update-alternatives --install /usr/lib/x86_64-linux-gnu/libblas.so.3 \
                    libblas.so.3-x86_64-linux-gnu \
	            /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3 100

update-alternatives --install /usr/lib/x86_64-linux-gnu/liblapack.so.3 \
                    liblapack.so.3-x86_64-linux-gnu \
	            /usr/lib/x86_64-linux-gnu/openblas/liblapack.so.3 100



exit 0
