#!/bin/sh
set -e
# Automatically added by dh_systemd_start
if [ -d /run/systemd/system ]; then
	deb-systemd-invoke stop laptop-mode.timer lmt-poll.service >/dev/null
fi
# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/laptop-mode" ]; then
	invoke-rc.d laptop-mode stop || exit $?
fi
# End automatically added section
