#!/bin/sh -e
. /usr/share/debconf/confmodule

# Purging configuration gom
if [ "$1" = "purge" ]; then
	if ! rmdir /etc/gom 2>/dev/null; then
		db_input critical gom/purge_etc_gom || true
		db_go || true
		db_get gom/purge_etc_gom || true
		if [ "$RET" = true ]; then
			rm -r -f /etc/gom
		fi
	fi
	rm -f /etc/default/gom
fi

# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/init.d/gom -- "$@"
# End automatically added section
# Automatically added by dh_installdebconf
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

