#!/bin/sh

set -e

if [ "$1" = install ] || [ "$1" = upgrade ]; then
	if [ -e "/etc/udev/rules.d/45-hpdjconsole.rules" ]; then
		if [ "`md5sum \"/etc/udev/rules.d/45-hpdjconsole.rules\" | sed -e \"s/ .*//\"`" = \
		     "`dpkg-query -W -f='${Conffiles}' libdjconsole-data | sed -n -e \"\\\\' /etc/udev/rules.d/45-hpdjconsole.rules's/.* //p\"`" ]
		then
			rm -f "/etc/udev/rules.d/45-hpdjconsole.rules"
		fi
	fi
fi


