#!/bin/sh
set -e
# Automatically added by dh_installinit/11.3.5
if [ -x "/etc/init.d/vitrage-snmp-parsing" ] && [ "$1" = remove ]; then
	invoke-rc.d vitrage-snmp-parsing stop || true
fi
# End automatically added section
