#!/bin/sh
set -e
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper mv_conffile /etc/tinyproxy.conf /etc/tinyproxy/tinyproxy.conf 1.8.4-2\~ tinyproxy -- "$@"
# End automatically added section
# Automatically added by dh_installinit/10.10.9
if [ -x "/etc/init.d/tinyproxy" ] && [ "$1" = remove ]; then
	invoke-rc.d tinyproxy stop || exit $?
fi
# End automatically added section
