#!/bin/sh
set -e
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/default/clamav-milter 0.98.5~beta1+dfsg-3~ clamav-milter -- "$@"
# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/clamav-milter" ]; then
	invoke-rc.d clamav-milter stop || exit $?
fi
# End automatically added section
