#!/bin/sh

set -e

if [ "$1" = "configure" ] ; then
	update-alternatives --install /usr/bin/jenkins-jobs jenkins-jobs /usr/bin/python3-jenkins-jobs 200
fi


# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p python3-jenkins-job-builder 
fi

# End automatically added section


exit 0
