#!/bin/sh

set -e

if [ "$1" = "purge" ]; then
	if getent passwd gkrellmd >/dev/null; then
		userdel gkrellmd
	fi
fi

# Automatically added by dh_installinit/11.5.4
if [ "$1" = "purge" ] ; then
	update-rc.d gkrellmd remove >/dev/null
fi
# End automatically added section


exit 0
