#!/bin/sh -e

# the DEBHELPER token is purposely not used
# because we don't want the daemon to be
# stopped during an upgrade

handle_start_failure () {
# The MODE defined in /etc/nut/nut.conf shouldn't affect the exit code when the
# daemon is stopped. If it fails to stop, the maintainer script should fail
# too.
  return 1
}

case "$1" in

  remove)
    # nut-usb specifics
    [ -f /etc/hotplug/usb/libhid.usermap ] && rm -f /etc/hotplug/usb/libhid.usermap
    [ -f /etc/hotplug/usb/libhidups ] && rm -f /etc/hotplug/usb/libhidups

    [ -L /usr/doc/nut ] && rm -f /usr/doc/nut
    # do stop the daemon on remove
    invoke-rc.d nut stop && sleep 1
    [ -d /var/run/nut ] && rm -rf /var/run/nut/
    ;;

  upgrade)
    [ -L /usr/doc/nut ] && rm -f /usr/doc/nut
    # do not stop the daemon on upgrade
    ;;

  failed-upgrade)
    # do nothing
    ;;

  deconfigure)
    # do nothing
    ;;

  *)
    echo "$0: incorrect arguments: $*" >&2
    exit 1
    ;;

esac

# Automatically added by dh_systemd_start
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop nut-driver.service >/dev/null
fi
# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/nut-server" ] && [ "$1" = remove ]; then
	invoke-rc.d nut-server stop || handle_start_failure
fi
# End automatically added section


exit 0
