#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/exabgp" ]; then
	invoke-rc.d exabgp stop || exit $?
fi
# End automatically added section

# Automatically added by dh_python2:
if which pyclean >/dev/null 2>&1; then
	pyclean -p exabgp 
else
	dpkg -L exabgp | grep \.py$ | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section
