#!/bin/sh

set -e

# Automatically added by dh_installdeb/11.4.1
dpkg-maintscript-helper mv_conffile /etc/apache2/conf.d/horde.conf /etc/apache2/conf-available/php-horde.conf 5.1.0\+debian0-1\~ -- "$@"
# End automatically added section


if [ "$1" = "remove" ] || [ "$1" = "purge" ] ; then

        CONF="php-horde"
        COMMON_STATE=$(dpkg-query -f '${Status}' -W 'apache2.2-common' 2>/dev/null | awk '{print $3}' || true)

        if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
                . /usr/share/apache2/apache2-maintscript-helper
                apache2_invoke disconf $CONF || exit $?
        elif [ "$COMMON_STATE" = "installed" ] || [ "$COMMON_STATE" = "unpacked" ] ; then
                [ ! -L /etc/apache2/conf.d/$CONF.conf ] ||  rm /etc/apache2/conf.d/$CONF.conf
        fi

fi
