#!/bin/sh
set -e
# Automatically added by dh_installinit/10.6.4
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/bwbar" ]; then
		update-rc.d bwbar defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d bwbar $_dh_action || exit $?
	fi
fi
# End automatically added section
