#!/bin/sh

set -e

case "$1" in
	remove|deconfigure)
		update-alternatives --remove slurmd /usr/sbin/slurmd-wlm
		;;
esac

# Automatically added by dh_installinit/10.10.5
if [ -x "/etc/init.d/slurmd" ]; then
	invoke-rc.d slurmd stop || exit $?
fi
# End automatically added section


exit 0
