#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.4.1
dpkg-maintscript-helper dir_to_symlink /usr/lib/GNUstep/Applications/Affiche.app/Resources /usr/share/GNUstep/Affiche.app 0.6.0-10\~ affiche.app -- "$@"
# End automatically added section
