#!/bin/sh -e

if [ -x /usr/bin/update-menus ] ; then update-menus ; fi

# Automatically added by dh_installmenu
if [ "$1" = "configure" ] && [ -x "`which update-menus 2>/dev/null`" ]; then
	update-menus
fi
# End automatically added section

