#!/bin/sh
set -e

# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p 2ping 
fi

# End automatically added section
# Automatically added by dh_systemd_enable/10.7.2
if deb-systemd-helper debian-installed 2ping.service; then
	# This will only remove masks created by d-s-h on package removal.
	deb-systemd-helper unmask 2ping.service >/dev/null || true

	if deb-systemd-helper --quiet was-enabled 2ping.service; then
		# Create new symlinks, if any.
		deb-systemd-helper enable 2ping.service >/dev/null || true
	fi
fi

# Update the statefile to add new symlinks (if any), which need to be cleaned
# up on purge. Also remove old symlinks.
deb-systemd-helper update-state 2ping.service >/dev/null || true
# End automatically added section
# Automatically added by dh_installinit/10.7.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/2ping" ]; then
		update-rc.d 2ping defaults >/dev/null
		invoke-rc.d 2ping start || exit $?
	fi
fi
# End automatically added section
