#!/bin/sh

set -e

CONFIG_DIR="/etc/matrix-synapse/conf.d"
CONFIGFILE_SERVERNAME="$CONFIG_DIR/server_name.yaml"
CONFIGFILE_REPORTSTATS="$CONFIG_DIR/report_stats.yaml"

if [ "$1" = "purge" ]
then
	rm -f $CONFIGFILE_SERVERNAME $CONFIGFILE_REPORTSTATS
        if [ -d $CONFIG_DIR ]
	then
		rmdir --ignore-fail-on-non-empty $CONFIG_DIR
	fi
fi

# Automatically added by dh_installinit/12
if [ "$1" = "purge" ] ; then
	update-rc.d matrix-synapse remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_systemd_enable/12
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'matrix-synapse.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'matrix-synapse.service' >/dev/null || true
		deb-systemd-helper unmask 'matrix-synapse.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installdebconf/12
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


exit 0
