#!/bin/sh
set -e
# Automatically added by dh_installinit/10.10.9
if [ -x "/etc/init.d/arc-datadelivery-service" ]; then
	invoke-rc.d arc-datadelivery-service stop || exit $?
fi
# End automatically added section
