#!/bin/sh
set -e
# Automatically added by dh_installxfonts/11.1.4
if which update-fonts-dir >/dev/null 2>&1; then
	update-fonts-dir --x11r7-layout misc;update-fonts-alias --include /etc/X11/fonts/misc/xfonts-shinonome.alias misc
fi
# End automatically added section
