#!/bin/sh

set -e

case "$1" in
  purge)
    if [ -d /var/lib/transmission-daemon/.config ]; then
      rm -rf /var/lib/transmission-daemon/.config/*
    fi
  ;;
esac

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d transmission-daemon remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask transmission-daemon.service >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge transmission-daemon.service >/dev/null
		deb-systemd-helper unmask transmission-daemon.service >/dev/null
	fi
fi
# End automatically added section

