#!/bin/sh

set -e

case "$1" in
    purge)
        rm -rf /var/lib/rkt
    ;;
    remove|purge)
        delgroup --quiet --system --only-if-empty rkt || true
        delgroup --quiet --system --only-if-empty rkt-admin || true
    ;;
esac

# Automatically added by dh_installsystemd/11.3.5
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.3.5
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.3.5
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'rkt-gc.timer' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'rkt-gc.timer' >/dev/null || true
		deb-systemd-helper unmask 'rkt-gc.timer' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.3.5
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'cni-dhcp.service' 'cni-dhcp.socket' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'cni-dhcp.service' 'cni-dhcp.socket' >/dev/null || true
		deb-systemd-helper unmask 'cni-dhcp.service' 'cni-dhcp.socket' >/dev/null || true
	fi
fi
# End automatically added section

