#!/bin/sh
# postinst script for webkit-image-gtk
#
# see: dh_installdeb(1)

set -e

mandir=/usr/share/man

case "$1" in
    configure)
        if [ -f /usr/bin/webkit-image-gtk ]; then
            update-alternatives --install /usr/bin/webkit-image \
                webkit-image /usr/bin/webkit-image-gtk 100 \
                --slave $mandir/man1/webkit-image.1.gz webkit-image.1.gz \
                $mandir/man1/webkit-image-gtk.1.gz
        fi
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac



exit 0
