#!/bin/sh
set -e
# Automatically added by dh_installinit/11.3.5
if [ -x "/etc/init.d/openstack-tempest-ci-live-booter" ]; then
	invoke-rc.d openstack-tempest-ci-live-booter stop || exit 1
fi
# End automatically added section
