#!/bin/sh
set -e
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/init.d/dnscrypt-proxy 1.8.1-3\~ dnscrypt-proxy -- "$@"
dpkg-maintscript-helper rm_conffile /etc/default/dnscrypt-proxy 1.8.1-3\~ dnscrypt-proxy -- "$@"
dpkg-maintscript-helper mv_conffile /etc/dnscrypt-proxy/dnscrypt-proxy.conf/dnscrypt-proxy.conf /etc/dnscrypt-proxy/dnscrypt-proxy.conf 1.8.1-4\~ dnscrypt-proxy -- "$@"
# End automatically added section
# Automatically added by dh_systemd_start
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop dnscrypt-proxy-resolvconf.service dnscrypt-proxy.service dnscrypt-proxy.socket >/dev/null
fi
# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/dnscrypt-proxy" ] && [ "$1" = remove ]; then
	invoke-rc.d dnscrypt-proxy stop || exit $?
fi
# End automatically added section
