#!/bin/sh

set -e

# Workaround bug in previous versions of the init.d script (--oknodo was
# missing), see: #378934.
init_error ()
{
    echo "Retrying to stop daemon with oknodo."
    start-stop-daemon --stop --oknodo --pidfile /var/run/mldonkey/mlnet.pid
}

# Automatically added by dh_installinit
if [ -x "/etc/init.d/mldonkey-server" ]; then
	invoke-rc.d mldonkey-server stop || init_error
fi
# End automatically added section

