#!/bin/sh
# postrm script for prometheus-pushgateway
# Script executed after the package is removed.

set -e

case "$1" in
  purge)
        rm -rf /var/log/prometheus/prometheus-pushgateway.log \
            /var/log/prometheus/prometheus-pushgateway.log.* \
            /var/lib/prometheus/pushgateway.data \
            /var/run/prometheus/prometheus-pushgateway.pid
	# We do NOT remove the system user.
	;;
esac

# Automatically added by dh_installinit/10.6.4
if [ "$1" = "purge" ] ; then
	update-rc.d prometheus-pushgateway remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section

