#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/globus-gatekeeper" ]; then
		update-rc.d globus-gatekeeper defaults >/dev/null
		invoke-rc.d globus-gatekeeper start || exit $?
	fi
fi
# End automatically added section
