#!/bin/sh
set -e

# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p streamtuner2 /usr/share/streamtuner2
fi
if which pypy3compile >/dev/null 2>&1; then
	pypy3compile -p streamtuner2 /usr/share/streamtuner2 || true
fi

# End automatically added section
