#!/bin/sh
set -e

# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p supervisor 
fi

# End automatically added section
# Automatically added by dh_systemd_enable/10.7.2
# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask supervisor.service >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled supervisor.service; then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable supervisor.service >/dev/null || true
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state supervisor.service >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/10.7.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/supervisor" ]; then
		update-rc.d supervisor defaults >/dev/null
		invoke-rc.d supervisor start || exit $?
	fi
fi
# End automatically added section
