#!/bin/sh -e

# some shorthands for sanity
en="/etc/nagios4"
enc="/etc/nagios4/conf.d"
usn="/usr/share/nagios4"

case "${1}" in
    remove)
  	;;
    purge)
        for file in \
	    "${en}/resource.cfg" /var/log/nagios4 /var/run/nagios4 \
	    /var/lib/nagios4 /var/lib/nagios4/spool \
	    /var/lib/nagios4/spool/checkresults \
	    /var/lib/nagios4/rw
	do
	    dpkg-statoverride --force --remove "${file}" 2>/dev/null || true
	done
        rm -rf /var/run/nagios4 /var/log/nagios4 /var/lib/nagios4
	rm -f /etc/nagios4/conf.d/host-gateway_nagios4.cfg
	if which ucf >/dev/null 2>&1
	then
	      ucf --purge /etc/nagios4/conf.d/host-gateway_nagios4.cfg
	fi
    ;;
esac

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d nagios4 remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section

