#!/bin/sh
set -e

dpkg-maintscript-helper rm_conffile \
  /etc/emacs/site-start.d/50wl.el 2.6.1-4~ -- "$@"

if [ ! -e /var/lib/emacsen-common/state/package/installed/emacsen-common ]; then
    # Fallback to emacsen-common 1.x
    if [ "$1" = "configure" ] && [ -x /usr/lib/emacsen-common/emacs-package-install ]; then
	/usr/lib/emacsen-common/emacs-package-install wl
    fi
else
# Automatically added by dh_installemacsen
if [ "$1" = "configure" ] && [ -e /var/lib/emacsen-common/state/package/installed/emacsen-common -a -x /usr/lib/emacsen-common/emacs-package-install ]
then
	/usr/lib/emacsen-common/emacs-package-install --postinst wl
fi
# End automatically added section

fi
