#! /bin/sh
set -e

if [ "$1" = configure ]; then
    update-alternatives --quiet \
     --install /usr/bin/pinentry pinentry /usr/bin/mew-pinentry 0 \
     --slave /usr/share/man/man1/pinentry.1.gz pinentry.1.gz /usr/share/man/man1/mew-pinentry.1.gz
fi


exit 0
