#!/bin/sh
set -e
# Automatically added by dh_systemd_start/11
if [ -d /run/systemd/system ]; then
	deb-systemd-invoke stop 'strongswan-swanctl.service' >/dev/null
fi
# End automatically added section
