#!/bin/sh -e

# Source debconf library.
. /usr/share/debconf/confmodule

# Automatically added by dh_installmenu
if [ -x "`which update-menus 2>/dev/null`" ]; then update-menus ; fi
# End automatically added section
# Automatically added by dh_installdebconf
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


case $1 in
   remove|upgrade|failed-upgrade|abort-install|abort-upgrade ) 
   exit 0
   ;;
   purge|disappear )
   rm -rf /etc/default/tgif
   ;;
   * )
   echo "postinst called with unknown argument \`$1'" >&2
   exit 1
   ;;
esac
