#!/bin/sh
set -e
# Automatically added by dh_installinit/10.9.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/darkice" ]; then
		update-rc.d darkice defaults >/dev/null
		invoke-rc.d darkice start || exit $?
	fi
fi
# End automatically added section
