#!/bin/sh
set -e
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/bumblebee 3.2.1-8~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/modprobe.d/bumblebee.conf 3.2.1-6~ -- "$@"
# End automatically added section
# Automatically added by dh_installinit/10.10.9
if [ -x "/etc/init.d/bumblebeed" ]; then
	invoke-rc.d bumblebeed stop || exit $?
fi
# End automatically added section
