#!/bin/sh
set -e

case "$1" in
    configure)
      update-alternatives --install /usr/bin/run-escript run-escript /usr/bin/run-escript3 40
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
      update-alternatives --install /usr/bin/run-escript run-escript /usr/bin/run-escript3 40
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac


# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p python3-escript /usr/lib/python3-escript/esys -V 3.5
fi

# End automatically added section


exit 0
