#!/bin/sh
set -e
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ast/yahoo-es.xml 45.0esr-2~ iceweasel-l10n-as -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ast/wikipedia-ast.xml 45.0esr-2~ iceweasel-l10n-as -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ast/google.xml 45.0esr-2~ iceweasel-l10n-as -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ast/eBay-es.xml 45.0esr-2~ iceweasel-l10n-as -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ast/diccionariu-alla.xml 45.0esr-2~ iceweasel-l10n-as -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ast/ddg.xml 45.0esr-2~ iceweasel-l10n-as -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ast/bing.xml 45.0esr-2~ iceweasel-l10n-as -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/as/yahoo-in.xml 45.0esr-2~ iceweasel-l10n-as -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/as/wikipedia-as.xml 45.0esr-2~ iceweasel-l10n-as -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/as/google.xml 45.0esr-2~ iceweasel-l10n-as -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/as/eBay-in.xml 45.0esr-2~ iceweasel-l10n-as -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/as/ddg.xml 45.0esr-2~ iceweasel-l10n-as -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/as/creativecommons.xml 45.0esr-2~ iceweasel-l10n-as -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/as/amazondotcom.xml 45.0esr-2~ iceweasel-l10n-as -- "$@"
# End automatically added section
