#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/globus-gridftp-server" ]; then
		update-rc.d globus-gridftp-server defaults >/dev/null
		invoke-rc.d globus-gridftp-server start || exit $?
	fi
fi
# End automatically added section
# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/globus-gridftp-sshftp" ]; then
		update-rc.d globus-gridftp-sshftp defaults >/dev/null
		invoke-rc.d globus-gridftp-sshftp start || exit $?
	fi
fi
# End automatically added section
