#!/bin/sh

set -e

action=$1
version=$2

# Source debconf library.
. /usr/share/debconf/confmodule
db_version 2.0

db_input high ocsinventory-agent/method || true
db_go

db_get ocsinventory-agent/method || true
if [ "$RET" = "http" ]; then
        db_input high ocsinventory-agent/server || true
fi

db_input medium ocsinventory-agent/tag || true

db_go

db_stop

exit 0

