#!/bin/sh
set -e
# Automatically added by dh_installinit/11.3.5
if [ -x "/etc/init.d/magnum-conductor" ] && [ "$1" = remove ]; then
	invoke-rc.d magnum-conductor stop || true
fi
# End automatically added section
