#!/bin/sh

set -e

# check if any kernel is available
# do not call dracut if no kernel was found
if ls /boot/vmlinu[zx]-* >/dev/null 2>&1; then

    # Regenerate initramfs for all kernel that are installed
    for kversion in `ls /boot/vmlinu[zx]-* | sed -e 's#/boot/vmlinu.-##'`; do
        /etc/kernel/postinst.d/dracut $kversion
    done
fi

# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/logrotate.d/dracut 044+3-3~ -- "$@"
# End automatically added section

