#!/bin/sh
set -e
# Automatically added by dh_installinit/11
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	# In case this system is running systemd, we need to ensure that all
	# necessary tmpfiles (if any) are created before starting.
	if [ -d /run/systemd/system ] ; then
		systemd-tmpfiles --create /usr/lib/tmpfiles.d/glusterfs-server.conf >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installinit/11
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/glusterd" ]; then
		update-rc.d glusterd defaults >/dev/null
		invoke-rc.d glusterd start || exit $?
	fi
fi
# End automatically added section
# Automatically added by dh_installinit/11
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	# In case this system is running systemd, we need to ensure that all
	# necessary tmpfiles (if any) are created before starting.
	if [ -d /run/systemd/system ] ; then
		systemd-tmpfiles --create /usr/lib/tmpfiles.d/glusterfs-server.conf >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installinit/11
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/glustereventsd" ]; then
		update-rc.d glustereventsd defaults >/dev/null
		invoke-rc.d glustereventsd start || exit $?
	fi
fi
# End automatically added section
# Automatically added by dh_installdeb/11
dpkg-maintscript-helper rm_conffile /etc/init.d/glusterfs-server 3.10.1-2 -- "$@"
# End automatically added section
