#!/bin/sh
set -e
# Automatically added by dh_installdeb/11
dpkg-maintscript-helper rm_conffile /etc/init.d/glusterfs-server 3.10.1-2 -- "$@"
# End automatically added section
# Automatically added by dh_installinit/11
if [ -x "/etc/init.d/glustereventsd" ]; then
	invoke-rc.d glustereventsd stop || exit $?
fi
# End automatically added section
# Automatically added by dh_installinit/11
if [ -x "/etc/init.d/glusterd" ]; then
	invoke-rc.d glusterd stop || exit $?
fi
# End automatically added section
