#!/bin/sh

set -e

# Create a goiardi system group
if ! getent group goiardi > /dev/null; then
    addgroup --quiet --system goiardi
fi

# Create a goiardi system user
if ! getent passwd goiardi > /dev/null; then
    adduser --quiet --system \
        --ingroup goiardi \
        --home /var/lib/goiardi \
        --disabled-password --shell /bin/false \
        goiardi
    usermod -c "Goiardi Chef server" goiardi
fi

chgrp goiardi /etc/goiardi
chmod 775 /etc/goiardi
chown goiardi:goiardi /var/lib/goiardi \
                      /var/lib/goiardi/lfs
mkdir -p /var/log/goiardi
chown goiardi:goiardi /var/log/goiardi

# Automatically added by dh_installinit/11.3.5
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/goiardi" ]; then
		update-rc.d goiardi defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d goiardi $_dh_action || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.3.5
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# This will only remove masks created by d-s-h on package removal.
	deb-systemd-helper unmask 'goiardi.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'goiardi.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'goiardi.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'goiardi.service' >/dev/null || true
	fi
fi
# End automatically added section

