#!/bin/sh

set -e

if [ "$1" = "remove" ] ; then
	update-alternatives --remove heat /usr/bin/python2-heat
fi


# Automatically added by dh_python2:
if which pyclean >/dev/null 2>&1; then
	pyclean -p python-heatclient 
else
	dpkg -L python-heatclient | grep \.py$ | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section


exit 0
