#!/bin/sh

set -e

if [ "$1" = "remove" -o "$1" = "deconfigure" ]; then
    update-alternatives --remove php-cgi /usr/bin/php-cgi7.3
    update-alternatives --remove php-cgi-bin /usr/lib/cgi-bin/php7.3
fi

php_enable() { return 0; }

if [ "$1" = "remove" ]; then
    if [ -e /usr/lib/php/php-maintscript-helper ]; then
	. /usr/lib/php/php-maintscript-helper

	mods=$(phpquery -M -v 7.3)
	for mod in $mods; do
	    php_invoke dismod 7.3 cgi $mod
	done
    else
	for mod in /etc/php/7.3/cgi/conf.d/*.ini; do 
	    rm -f $mod
	    for ext in '~' '%' .bak .ucf-new .ucf-old .ucf-dist;  do
		rm -f $mod$ext
	    done
	done
    fi
fi

# Automatically added by dh_apache2/UNDECLARED
if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ] ; then
	if php_enable; then
		if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
			. /usr/share/apache2/apache2-maintscript-helper

			for conf in php7.3-cgi  ; do
				apache2_invoke disconf $conf  || exit 1
			done
		fi
	fi
fi
# End automatically added section


exit 0
