#!/bin/sh
set -e
# Automatically added by dh_sysuser/UNDECLARED
# -*- sh -*-
# -*- sh -*-
export CONF_HOME=/nonexistent
export CONF_PACKAGE=bcron-run
export CONF_USERNAME=bcron-updatelog_

/lib/sysuser-helper/sysuser-helper prerm
# End automatically added section
# Automatically added by dh_sysuser/UNDECLARED
# -*- sh -*-
# -*- sh -*-
export CONF_HOME=/nonexistent
export CONF_PACKAGE=bcron-run
export CONF_USERNAME=bcron-spoollog_

/lib/sysuser-helper/sysuser-helper prerm
# End automatically added section
# Automatically added by dh_sysuser/UNDECLARED
# -*- sh -*-
# -*- sh -*-
export CONF_HOME=/nonexistent
export CONF_PACKAGE=bcron-run
export CONF_USERNAME=bcron-schedlog_

/lib/sysuser-helper/sysuser-helper prerm
# End automatically added section
# Automatically added by dh_sysuser/UNDECLARED
# -*- sh -*-
# -*- sh -*-
export CONF_HOME=/var/spool/cron
export CONF_PACKAGE=bcron-run
export CONF_USERNAME=cron

/lib/sysuser-helper/sysuser-helper prerm
# End automatically added section
