#!/bin/sh

set -e

# Those using dependency based boot sequencing with sysv-rc and
# installing omniorb-eventservice using version 1:2.6.2-1 and earlier
# would have the wrong runlevel symlinks.  Recover from this.
if [ "$1" = "configure" ] && dpkg --compare-versions "$2" le "1:2.6.2-1" \
    && [ -f /etc/rc3.d/S[0-9][0-9]omniorb-eventservice ] && [ ! -f /etc/rc2.d/S[0-9][0-9]omniorb-eventservice ]
then
    update-rc.d -f omniorb-eventservice remove
fi

# Automatically added by dh_installinit/11.3.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/omniorb-eventservice" ]; then
		update-rc.d omniorb-eventservice defaults 90 10 >/dev/null
		invoke-rc.d omniorb-eventservice start || exit 1
	fi
fi
# End automatically added section

