#!/bin/sh -e

action=$1
version=$2

if [ "$1" = "remove" ]
then
  rm -f /etc/mgetty/.faxrunqd_not_to_be_run
  rm -f /var/spool/fax/outgoing/.last_run
fi

# Automatically added by dh_installinit
if [ -x "/etc/init.d/mgetty-fax" ]; then
	invoke-rc.d mgetty-fax stop || exit $?
fi
# End automatically added section

