#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/sk/zoznam-sk.xml 45.0esr-2~ iceweasel-l10n-sk -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/sk/wikipedia-sk.xml 45.0esr-2~ iceweasel-l10n-sk -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/sk/slovnik-sk.xml 45.0esr-2~ iceweasel-l10n-sk -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/sk/google.xml 45.0esr-2~ iceweasel-l10n-sk -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/sk/eBay.xml 45.0esr-2~ iceweasel-l10n-sk -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/sk/dunaj-sk.xml 45.0esr-2~ iceweasel-l10n-sk -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/sk/ddg.xml 45.0esr-2~ iceweasel-l10n-sk -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/sk/azet-sk.xml 45.0esr-2~ iceweasel-l10n-sk -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/sk/atlas-sk.xml 45.0esr-2~ iceweasel-l10n-sk -- "$@"
# End automatically added section
