#!/bin/sh
# vim: ft=sh:ts=4:et:sts=4
#
set -e 

# Source debconf library.
. /usr/share/debconf/confmodule

INITFILE=/etc/init.d/solid-pop3d
CONFIGFILE=/etc/default/solid-pop3d
RUN_MODE=inetd

[ -f "$CONFIGFILE" ] && . "$CONFIGFILE"

# preserve user changes in the config file
if [ "$RUN_MODE" = "daemon" ] ; then
    db_set solid-pop3d/run_mode daemon
else
    db_set solid-pop3d/run_mode inetd
fi

db_input medium solid-pop3d/run_mode || true
db_go || true

# Make dpkg-reconfigure stop the solid-pop3d server before
# /etc/default/solid-pop3d is modified by the postinst script.
if [ "$1" = "reconfigure" ] && [ "$RUN_MODE" = "daemon" ] \
   && [ -x "$INITFILE" ] && which invoke-rc.d >/dev/null; then
    invoke-rc.d solid-pop3d stop >&2 || echo "Warning: failed to stop solid-pop3d server" >&2
fi
