#!/bin/sh
# pre-removal script for Solid POP3

set -e

# Automatically added by dh_installinit/11.3.5
if [ -x "/etc/init.d/solid-pop3d" ] && [ "$1" = remove ]; then
	invoke-rc.d solid-pop3d stop || exit 1
fi
# End automatically added section


case "X$1" in 
	Xupgrade|Xremove)
		update-inetd --disable pop3
		;;
	*)
		;;
esac
