#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.3.5
dpkg-maintscript-helper symlink_to_dir /usr/lib/R/site-library/RCurl/examples ../../../../share/doc/r-cran-rcurl/examples 1.95-4.8-1 -- "$@"
# End automatically added section
