#!/bin/sh
set -e
# Automatically added by dh_installinit/11.5.4
if [ -x "/etc/init.d/haproxy" ] && [ "$1" = remove ]; then
	invoke-rc.d haproxy stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installdeb/11.5.4
dpkg-maintscript-helper mv_conffile /etc/rsyslog.d/haproxy.conf /etc/rsyslog.d/49-haproxy.conf 1.5.3-2\~ -- "$@"
# End automatically added section
