#!/bin/sh
set -e

# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p vmdebootstrap 
fi

if which pycompile >/dev/null 2>&1; then
	pycompile -p vmdebootstrap /usr/share/vmdebootstrap -V 2.7
fi

# End automatically added section
