#!/bin/sh

set -e

### Start of included pkgos_postrm library
#!/bin/sh
# -*- mode: shell-script -*-

# Perform cleanups when removing a package
# Prototype: pkgos_postrm <template-prefix-name> <package-name> $@
# Example:   pkgos_postrm neutron                neutron-common $@
pkgos_dbc_postrm () {
	local PKPRM_TEMPLATE_PREFIX PKPRM_PACKAGE_NAME

	PKPRM_TEMPLATE_PREFIX=${1}
	PKPRM_PACKAGE_NAME=${2}
	shift
	shift

	if [ -f /usr/share/debconf/confmodule ] ; then
		. /usr/share/debconf/confmodule
		# If the package has the template, then it means we're having a db,
		# and therefore we can call the dbconfig-common clean function.
		db_get ${PKPRM_TEMPLATE_PREFIX}/configure_db
		if [ "$RET" = "true" ] ; then
			if [ -f /usr/share/dbconfig-common/dpkg/postrm ] ; then
				. /usr/share/dbconfig-common/dpkg/postrm
				dbc_go ${PKPRM_PACKAGE_NAME} $@
			else
				rm -f /etc/dbconfig-common/${PKPRM_PACKAGE_NAME}.conf
				if which ucf >/dev/null 2>&1; then
					ucf --purge /etc/dbconfig-common/${PKPRM_PACKAGE_NAME}.conf
					ucfr --purge ${PKPRM_PACKAGE_NAME} /etc/dbconfig-common/${PKPRM_PACKAGE_NAME}.conf
                                fi
                        fi
                fi
	fi

	rm -rf /var/lib/${PKPRM_TEMPLATE_PREFIX} /var/log/${PKPRM_TEMPLATE_PREFIX} /var/lock/${PKPRM_TEMPLATE_PREFIX}
}
### End of included pkgos_postrm library

if [ "${1}" = "purge" ] ; then
	pkgos_dbc_postrm neutron neutron-common $@

	# Clean /etc/neutron on purge
	rm -f /etc/default/neutron /etc/neutron/api-paste.ini /etc/neutron/neutron.conf \
			/etc/neutron/plugins/ml2/openvswitch_agent.ini

	rm -f /etc/neutron/neutron.conf /etc/neutron/api-paste.ini

	# Clean also inifiles
	rm -f /etc/neutron/l3_agent.ini
	rm -f /etc/neutron/dhcp_agent.ini
	rm -f /etc/neutron/plugins/ml2/openvswitch_agent.ini
	rm -f /etc/neutron/plugins/ml2/ml2_conf.ini
	rm -f /etc/neutron/metadata_agent.ini

	[ -d /etc/neutron/plugins/ml2 ] 	&& rmdir --ignore-fail-on-non-empty /etc/neutron/plugins/ml2
	[ -d /etc/neutron/plugins ] 		&& rmdir --ignore-fail-on-non-empty /etc/neutron/plugins
	[ -d /etc/neutron ] 			&& rmdir --ignore-fail-on-non-empty /etc/neutron
        rm -rf /var/lib/neutron
        rm -rf /var/log/neutron
	rm -rf /etc/neutron/server.conf.d
	rm -rf /etc/neutron/agent.conf.d

fi

# Automatically added by dh_installdebconf/11.5.3
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

