#!/bin/sh -e

PETSC4PY_VERSION=3.10.0
PETSC4PY_VERSION_NUMBER=$( echo ${PETSC4PY_VERSION} | sed "s/\.//g" )

# Remove alternatives links
if [ "$1" = "remove" ]; then
  update-alternatives --remove petsc4py /usr/lib/python3/dist-packages/petsc4py_complex
fi


# Automatically added by dh_python3:
if which py3clean >/dev/null 2>&1; then
	py3clean -p python3-petsc4py-complex 
else
	dpkg -L python3-petsc4py-complex | perl -ne 's,/([^/]*)\.py$,/__pycache__/\1.*, or next; unlink $_ or die $! foreach glob($_)'
	find /usr/lib/python3/dist-packages/ -type d -name __pycache__ -empty -print0 | xargs --null --no-run-if-empty rmdir
fi

# End automatically added section

