#!/bin/sh
set -e
# Automatically added by dh_installemacsen
if [ -x /usr/lib/emacsen-common/emacs-package-remove ] ; then
	/usr/lib/emacsen-common/emacs-package-remove icicles
fi
# End automatically added section
