#!/bin/sh
set -e
# Automatically added by dh_installdeb/10.8
dpkg-maintscript-helper rm_conffile /etc/netdata/python.d/nginx_log.conf 1.8.0+dfsg-1~ netdata -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.8
dpkg-maintscript-helper rm_conffile /etc/netdata/python.d/gunicorn_log.conf 1.8.0+dfsg-1~ netdata -- "$@"
# End automatically added section
