#!/bin/sh

set -e

# Automatically added by dh_installmenu/11.5.1
if [ -x "`which update-menus 2>/dev/null`" ]; then update-menus ; fi
# End automatically added section
# Automatically added by dh_installdebconf/11.5.1
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


case "$1" in
  remove|purge)
	rm -f /var/lib/slrn/newsgroups.dsc
  ;;
  upgrade);;
  *)
	echo "postrm called with unknown argument \`$1'" >&2
	exit 0
  ;;
esac
