#!/bin/sh
set -e

if [ "$1" = remove ]; then
    update-alternatives --remove x-session-manager /usr/bin/gnome-flashback-xmonad
    update-alternatives --remove x-session-manager /usr/bin/xmonad-session
fi

# Automatically added by dh_installwm
if [ "$1" = "remove" ]; then
	update-alternatives --remove x-window-manager /usr/bin/xmonad
fi
# End automatically added section

