#!/bin/sh

set -e

if [ -d /run/systemd/system ]; then
	deb-systemd-invoke stop dovecot.socket || true
fi

# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/dovecot/README 1:2.2.27-3~ -- "$@"
# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/dovecot" ]; then
	invoke-rc.d dovecot stop || exit $?
fi
# End automatically added section

