#! /bin/sh

set -e
pam-auth-update --package --remove mklocaluser


# Automatically added by dh_python2:
if which pyclean >/dev/null 2>&1; then
	pyclean -p libpam-mklocaluser 
else
	dpkg -L libpam-mklocaluser | grep '\.py$' | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section

