#!/bin/sh

set -e

create_user() {
    if ! getent passwd nagios > /dev/null; then
        adduser --quiet --system --group --disabled-login \
            --home /var/lib/nagios nagios
    fi
}

case "$1" in
    configure)
        create_user
        ;;
    abort-upgrade|abort-remove|abort-deconfigure)
        ;;

    *)
        echo "postinst called with unknown argument '$1'" >&2
        exit 1
        ;;
esac

# Automatically added by dh_systemd_enable
# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask mod-gearman-worker.service >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled mod-gearman-worker.service; then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable mod-gearman-worker.service >/dev/null || true
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state mod-gearman-worker.service >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/mod-gearman-worker" ]; then
		update-rc.d mod-gearman-worker defaults >/dev/null
		invoke-rc.d mod-gearman-worker start || exit $?
	fi
fi
# End automatically added section

