#!/bin/sh

set -e

OLD_ALT_NAME="ttf-japanese-mincho"
OLD_FONT_ENTRY="/usr/share/fonts/truetype/hanazono/hanazono.ttf"

PKG="ttf-hanazono"

case "$1" in
install|upgrade)
	# do this on new installations, too, as these could be "upgrades"
	# from ttf-hanazono
	if dpkg --compare-versions "$2" lt "20120421-1.1~"; then
		update-alternatives --remove $OLD_ALT_NAME.ttf $OLD_FONT_ENTRY
	fi

esac


exit 0
