#!/bin/sh

set -e

. /usr/share/debconf/confmodule

DIRS="/var/lib/graphite /var/lib/graphite/whisper /var/log/carbon"

if [ "$1" = configure ]; then
	if ! getent passwd _graphite > /dev/null; then
		adduser --system --quiet --home /var/lib/graphite --no-create-home \
			--shell /bin/false --force-badname --group --gecos "Graphite User" _graphite
	fi

	for i in $DIRS; do
		if ! dpkg-statoverride --list $i >/dev/null 2>&1; then
			dpkg-statoverride --update --add _graphite _graphite 0755 $i
		fi
	done
fi

db_stop


# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p graphite-carbon 
fi

# End automatically added section
# Automatically added by dh_systemd_enable/10.8
# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask carbon-cache.service >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled carbon-cache.service; then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable carbon-cache.service >/dev/null || true
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state carbon-cache.service >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/10.8
if deb-systemd-helper debian-installed carbon-cache.service; then
	# This will only remove masks created by d-s-h on package removal.
	deb-systemd-helper unmask carbon-cache.service >/dev/null || true

	if deb-systemd-helper --quiet was-enabled carbon-cache.service; then
		# Create new symlinks, if any.
		deb-systemd-helper enable carbon-cache.service >/dev/null || true
	fi
fi

# Update the statefile to add new symlinks (if any), which need to be cleaned
# up on purge. Also remove old symlinks.
deb-systemd-helper update-state carbon-cache.service >/dev/null || true
# End automatically added section
# Automatically added by dh_systemd_enable/10.8
if deb-systemd-helper debian-installed carbon-cache.service; then
	# This will only remove masks created by d-s-h on package removal.
	deb-systemd-helper unmask carbon-cache.service >/dev/null || true

	if deb-systemd-helper --quiet was-enabled carbon-cache.service; then
		# Create new symlinks, if any.
		deb-systemd-helper enable carbon-cache.service >/dev/null || true
	fi
fi

# Update the statefile to add new symlinks (if any), which need to be cleaned
# up on purge. Also remove old symlinks.
deb-systemd-helper update-state carbon-cache.service >/dev/null || true
# End automatically added section
# Automatically added by dh_installinit/10.8
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/carbon-cache" ]; then
		update-rc.d carbon-cache defaults >/dev/null
		invoke-rc.d carbon-cache start || exit $?
	fi
fi
# End automatically added section

