#!/bin/sh
set -e
# Automatically added by dh_installinit/10.8
if [ -x "/etc/init.d/carbon-cache" ]; then
	invoke-rc.d carbon-cache stop || exit $?
fi
# End automatically added section

# Automatically added by dh_python2:
if which pyclean >/dev/null 2>&1; then
	pyclean -p graphite-carbon 
else
	dpkg -L graphite-carbon | grep \.py$ | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section
