#!/bin/sh
set -e
# Automatically added by dh_installinit/10.9
if [ -x "/etc/init.d/kube-scheduler" ]; then
	invoke-rc.d kube-scheduler stop || exit $?
fi
# End automatically added section
# Automatically added by dh_installinit/10.9
if [ -x "/etc/init.d/kube-controller-manager" ]; then
	invoke-rc.d kube-controller-manager stop || exit $?
fi
# End automatically added section
# Automatically added by dh_installinit/10.9
if [ -x "/etc/init.d/kube-apiserver" ]; then
	invoke-rc.d kube-apiserver stop || exit $?
fi
# End automatically added section
