#!/bin/sh

set -e

if [ "$1" = "configure" ] ; then
	update-alternatives --quiet --remove alembic /usr/bin/python2-alembic
fi


# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p python-alembic 
fi

# End automatically added section


exit 0
