#!/bin/sh
set -e
# Automatically added by dh_systemd_start/11
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/11
if [ "$1" = "purge" ] ; then
	update-rc.d fcoe-utils remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/11
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'fcoe-utils.service' 'fcoemon.socket' >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'fcoe-utils.service' 'fcoemon.socket' >/dev/null
		deb-systemd-helper unmask 'fcoe-utils.service' 'fcoemon.socket' >/dev/null
	fi
fi
# End automatically added section
