#!/bin/sh

set -e

if dpkg-maintscript-helper supports rm_conffile 2>/dev/null; then
    dpkg-maintscript-helper rm_conffile /usr/lib/systemd/ntp-units.d/openntpd.list 1:5.7p4-1 -- "$@"
    dpkg-maintscript-helper rm_conffile /etc/apparmor.d/usr.sbin.ntpd 1:5.7p4-1 -- "$@"
fi

case "${1}" in
	purge)
		if [ -x deluser ]
		then
			deluser --quiet ntpd > /dev/null || true
		fi

		rm -f /var/lib/openntpd/db/ntpd.drift
        rm -f /var/lib/openntpd/run/ntpd.sock
		;;

	remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

		;;

	*)
		echo "postrm called with unknown argument \`${1}'" >&2
		exit 1
esac

# Automatically added by dh_installinit/10.10.5
if [ "$1" = "purge" ] ; then
	update-rc.d openntpd remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/10.10.5
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'openntpd.service' >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'openntpd.service' >/dev/null
		deb-systemd-helper unmask 'openntpd.service' >/dev/null
	fi
fi
# End automatically added section
# Automatically added by dh_apparmor/2.11.1-2
if [ "$1" = "purge" ] && ! [ -e "/etc/apparmor.d/usr.sbin.ntpd" ] ; then
    rm -f "/etc/apparmor.d/disable/usr.sbin.ntpd" || true
    rm -f "/etc/apparmor.d/force-complain/usr.sbin.ntpd" || true
    rm -f "/etc/apparmor.d/local/usr.sbin.ntpd" || true
    rmdir /etc/apparmor.d/disable 2>/dev/null || true
    rmdir /etc/apparmor.d/local   2>/dev/null || true
    rmdir /etc/apparmor.d         2>/dev/null || true
fi
# End automatically added section


exit 0
