#!/bin/sh

set -e

if dpkg-maintscript-helper supports rm_conffile 2>/dev/null; then
    dpkg-maintscript-helper rm_conffile /usr/lib/systemd/ntp-units.d/openntpd.list 1:5.7p4-1 -- "$@"
    dpkg-maintscript-helper rm_conffile /etc/apparmor.d/usr.sbin.ntpd 1:5.7p4-1 -- "$@"
fi



exit 0
