#!/bin/sh -e
set -e
update-alternatives --remove aterm /usr/bin/katerm
update-alternatives --remove aterm /usr/bin/caterm
update-alternatives --remove aterm /usr/bin/gaterm
update-alternatives --remove aterm /usr/bin/taterm
update-alternatives --remove x-terminal-emulator /usr/bin/katerm
update-alternatives --remove x-terminal-emulator /usr/bin/caterm
update-alternatives --remove x-terminal-emulator /usr/bin/gaterm
update-alternatives --remove x-terminal-emulator /usr/bin/taterm



exit 0
