#!/bin/sh
set -e
# Automatically added by dh_installinit/10.10.9
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/amule-daemon" ]; then
		update-rc.d amule-daemon defaults >/dev/null
		invoke-rc.d amule-daemon start || exit $?
	fi
fi
# End automatically added section
