#! /bin/sh

set -e

case "$1" in
    install|upgrade)
        if dpkg --compare-versions "$2" lt 4.14; then
	    if [ -x "which defoma-font 2>/dev/null" ]; then
		defoma-font purge /etc/defoma/hints/t1-teams.hints
	    fi
        fi
        ;;

    abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac

# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/X11/fonts/X11R7/Type1/t1-teams.scale 4.12+nmu1 -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/X11/fonts/X11R7/Type1/t1-teams.alias 4.12+nmu1 -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/defoma/hints/t1-teams.hints 4.14 -- "$@"
# End automatically added section


exit 0


