#!/bin/sh

set -e

if [ "$1" = "configure" ] ; then
	update-alternatives --install /usr/bin/pulpdoctest pulpdoctest /usr/bin/python3-pulpdoctest 200
	update-alternatives --install /usr/bin/pulptest pulptest /usr/bin/python3-pulptest 200
fi


# Automatically added by dhpython:
if which py3compile >/dev/null 2>&1; then
	py3compile -p python3-pulp 
fi

# End automatically added section


exit 0
