#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/designate-pool-manager" ] && [ "$1" = remove ]; then
	invoke-rc.d designate-pool-manager stop || true
fi
# End automatically added section
