#!/bin/bash

set -e

if [ -x "/etc/init.d/evqueue" ]; then
	service evqueue stop
fi

# Automatically added by dh_installinit/10.10.8
if [ -x "/etc/init.d/evqueue" ] && [ "$1" = remove ]; then
	invoke-rc.d evqueue stop || exit $?
fi
# End automatically added section

