#!/bin/sh
set -e

if [ "$1" = purge ]; then
        rm -f /etc/pbuilderrc
	if [ -e /usr/share/debconf/confmodule ]; then
	    . /usr/share/debconf/confmodule
	    db_purge
	fi
fi

# Automatically added by dh_installdeb/11.3.2
dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/pbuilder 0.215\+nmu4\~ -- "$@"
# End automatically added section
# Automatically added by dh_installdebconf/11.3.2
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

exit 0
