#!/bin/sh

set -e

rm_conffile() {
    PKGNAME="$1"
    CONFFILE="$2"

    if [ -e "$CONFFILE" ]; then
        md5sum="`md5sum \"$CONFFILE\" | sed -e \"s/ .*//\"`"
        old_md5sum="`dpkg-query -W -f='${Conffiles}' $PKGNAME | sed -n -e \"\\\\' $CONFFILE's/.* //p\"`"
        if [ "$md5sum" != "$old_md5sum" ]; then
            echo "Obsolete conffile $CONFFILE has been modified by you."
            echo "Saving as $CONFFILE.dpkg-old ..."
            mv -f "$CONFFILE" "$CONFFILE".dpkg-old
        else
            echo "Removing obsolete conffile $CONFFILE ..."
            rm -f "$CONFFILE"
        fi
    fi
}
# Prepare to move a conffile without triggering a dpkg question.  From
# http://wiki.debian.org/DpkgConffileHandling
prep_mv_conffile() {
    local PKGNAME="$1"
    local CONFFILE="$2"

    [ -e "$CONFFILE" ] || return 0

    local md5sum="$(md5sum $CONFFILE | sed -e 's/ .*//')"
    local old_md5sum="$(dpkg-query -W -f='${Conffiles}' $PKGNAME | \
            sed -n -e "\' $CONFFILE ' { s/ obsolete$//; s/.* //; p }")"
    if [ "$md5sum" = "$old_md5sum" ]; then
        rm -f "$CONFFILE"
    fi
}

case "$1" in
install)
    ;;
upgrade)

    # Just in case linking has already been done manually to now obsolete file.
    if dpkg --compare-versions "$2" le "1.818+deb8u1" && [ -L /etc/firefox-esr/debian-edu-networked.js ] ; then
	rm /etc/firefox-esr/debian-edu-networked.js
    fi
    ;;
esac

# Automatically added by dh_installdeb/12
dpkg-maintscript-helper mv_conffile /etc/apache2/sites-available/debian-edu-default /etc/apache2/sites-available/debian-edu-default.conf 1.719 -- "$@"
dpkg-maintscript-helper mv_conffile /etc/apache2/sites-available/debian-edu-ssl-default /etc/apache2/sites-available/debian-edu-ssl-default.conf 1.719 -- "$@"
dpkg-maintscript-helper mv_conffile /etc/apache2/conf.d/debian-edu-config-doc /etc/apache2/conf-available/debian-edu-config-doc.conf 1.719 -- "$@"
dpkg-maintscript-helper rm_conffile /etc/cfengine/debian-edu/cf.pdns 1.811 -- "$@"
dpkg-maintscript-helper rm_conffile /etc/insserv.conf.d/debian-edu-config 1.811 -- "$@"
dpkg-maintscript-helper rm_conffile /etc/powerdns/pdns.d/pdns-debian-edu.conf 1.811 -- "$@"
dpkg-maintscript-helper rm_conffile /etc/X11/Xsession.d/06debian-edu-iceweasel-ltsp 1.818\+deb8u1 -- "$@"
dpkg-maintscript-helper rm_conffile /etc/apt/apt.conf.d/99-edu-prefer-iceweasel 1.818\+deb8u1 -- "$@"
dpkg-maintscript-helper rm_conffile /etc/init.d/iceweasel-ldapconf 1.818\+deb8u1 -- "$@"
dpkg-maintscript-helper rm_conffile /etc/cfengine/debian-edu/cf.iceweasel 1.818\+deb8u1 -- "$@"
dpkg-maintscript-helper rm_conffile /usr/share/debian-edu-config/iceweacel-networked-prefs.js 1.818\+deb8u1 -- "$@"
dpkg-maintscript-helper rm_conffile /etc/cfengine/debian-edu/cf.kdm 1.906 -- "$@"
dpkg-maintscript-helper rm_conffile /etc/insserv/overrides/kdm 1.906 -- "$@"
dpkg-maintscript-helper rm_conffile /etc/ldap/slapd-debian-edu.conf 1.911 -- "$@"
dpkg-maintscript-helper rm_conffile /etc/ldap/slapd-lenny_debian-edu.conf 1.911 -- "$@"
dpkg-maintscript-helper rm_conffile /etc/cfengine3/debian-edu/cf.pki 2.10.19 -- "$@"
dpkg-maintscript-helper rm_conffile /etc/cfengine3/debian-edu/cf.thunderbird 2.10.19 -- "$@"
dpkg-maintscript-helper rm_conffile /etc/desktop-profiles/debian-edu-config.listing 2.10.22 -- "$@"
dpkg-maintscript-helper rm_conffile /etc/apt/apt.conf.d/90squid 2.10.36 -- "$@"
# End automatically added section

