#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.3.2
dpkg-maintscript-helper rm_conffile /etc/default/arping 2.14-2\~ arping -- "$@"
dpkg-maintscript-helper rm_conffile /etc/network/if-up.d/arping 2.14-2\~ arping -- "$@"
# End automatically added section
