#!/bin/sh -e

pluginctl=$(forge_get_config source_path)/post-install.d/common/plugin.sh

case "$1" in
    configure)
	$pluginctl scmsvn configure
	;;

    triggered)
	$pluginctl scmsvn triggered "$2"
	;;

    abort-upgrade|abort-remove|abort-deconfigure)
	;;

    *)
	echo "postinst called with unknown argument \`$1'" >&2
	exit 1
	;;
esac



exit 0
