#!/bin/sh
set -e
# Automatically added by dh_installinit/11.3.2
if [ -x "/etc/init.d/multipath-tools-boot" ]; then
	invoke-rc.d multipath-tools-boot stop || exit 1
fi
# End automatically added section
