#!/bin/sh
set -e

# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p doris 
fi

if which pycompile >/dev/null 2>&1; then
	pycompile -p doris /usr/share/doris
fi

# End automatically added section
