#!/bin/sh
set -e
# Automatically added by dh_installinit/11.5.4
if [ "$1" = "purge" ] ; then
	update-rc.d lemonldap-ng-fastcgi-server remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_systemd_enable/11.5.4
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'lemonldap-ng-fastcgi-server.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'lemonldap-ng-fastcgi-server.service' >/dev/null || true
		deb-systemd-helper unmask 'lemonldap-ng-fastcgi-server.service' >/dev/null || true
	fi
fi
# End automatically added section
