#! /bin/sh -e

# Rebuild texmf tree as we have removed the old files; this will not
# be done automatically by debhelper as we do not ship any new files

if command -v mktexlsr >/dev/null 2>&1
then
    tempfile=$(mktemp -p /tmp mktexlsr.XXXXXXXX)
    printf "Running mktexlsr. This may take some time... "
    if mktexlsr /usr/share/texmf > $tempfile 2>&1 ; then
        rm -f $tempfile
        echo "done."
    else
        exec >&2
        echo
        echo "mktexlsr /usr/share/texmf failed. Output has been stored in"
        echo "$tempfile"
        echo "Please include this file if you report a bug."
        echo
        exit 1
    fi
fi


