#!/bin/sh

# Automatically added by dh_installmenu/11.2.1
if [ "$1" = "configure" ] && [ -x "`which update-menus 2>/dev/null`" ]; then
	update-menus
fi
# End automatically added section


set -e

[ "$1" = configure ] || exit 0

. /usr/share/debconf/confmodule

db_get cwcp/suid_bit

if [ "$RET" = "true" ]; then
  if !( `dpkg-statoverride --list | grep -q bin/cwcp` ); then
    dpkg-statoverride --add --update root root 4755 /usr/bin/cwcp
  fi
fi
