#!/bin/sh

set -e


update-alternatives --install /usr/bin/irc irc /usr/bin/ircII 20 \
                    --slave /usr/share/man/man1/irc.1.gz irc.1 /usr/share/man/man1/ircII.1.gz

if [ ! -f /etc/irc/servers ]; then
  echo "irc.debian.org" > /etc/irc/servers
fi


