#! /bin/sh
# postrm script for mediawiki
#
# see: dh_installdeb(1)

set -e

case "$1" in
    purge)
	rm -rf /etc/mediawiki /var/lib/mediawiki
    ;;
    *)
    ;;
esac

# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/php5/mods-available/mediawiki.ini 1:1.27.0-1 -- "$@"
# End automatically added section
# Automatically added by dh_apache2
if [ "$1" = "purge" ] ; then
	if true; then
		if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
			. /usr/share/apache2/apache2-maintscript-helper

			for conf in mediawiki  ; do
				apache2_invoke disconf $conf  || exit $?
			done
		fi
	fi
fi
# End automatically added section


exit 0
