#!/bin/sh
set -e
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/be/be-x-old.wikipedia.org.xml 45.0esr-2~ iceweasel-l10n-be -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/be/be.wikipedia.org.xml 45.0esr-2~ iceweasel-l10n-be -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/be/ddg.xml 45.0esr-2~ iceweasel-l10n-be -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/be/google.xml 45.0esr-2~ iceweasel-l10n-be -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/be/ru.wikipedia.org-be.xml 45.0esr-2~ iceweasel-l10n-be -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/be/tut.by.xml 45.0esr-2~ iceweasel-l10n-be -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/be/yahoo.xml 45.0esr-2~ iceweasel-l10n-be -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/be/yandex.by.xml 45.0esr-2~ iceweasel-l10n-be -- "$@"
# End automatically added section
