#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.1.5
dpkg-maintscript-helper rm_conffile /etc/texmf/updmap.d/20latex-fonts-sipa-arundina.cfg 1:0.5.0-1 -- "$@"
# End automatically added section
