#!/bin/sh

set -e

case "$1" in
    purge)
	if [ -d /var/lib/ooni ]; then
		rm -rf /var/lib/ooni/.ooni
		rm -rf /var/lib/ooni/decks
		rm -rf /var/lib/ooni/inputs
		rm -rf /var/lib/ooni/resources
		rm -rf /var/lib/ooni/reports
		rm -rf /var/lib/ooni/GeoIP
		rmdir --ignore-fail-on-non-empty /var/lib/ooni
	fi
	if [ -d /var/log/ooni ]; then
		rmdir --ignore-fail-on-non-empty /var/log/ooni
	fi
	;;
esac

# Automatically added by dh_installinit/11.1.4
if [ "$1" = "purge" ] ; then
	update-rc.d ooniprobe remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installdeb/11.1.4
dpkg-maintscript-helper rm_conffile /etc/cron.daily/ooniprobe 2.0.2-1\~ ooniprobe -- "$@"
dpkg-maintscript-helper rm_conffile /etc/cron.monthly/ooniprobe 2.0.2-1\~ ooniprobe -- "$@"
dpkg-maintscript-helper rm_conffile /etc/ooniprobe.conf 2.1.0\~ ooniprobe -- "$@"
# End automatically added section
# Automatically added by dh_systemd_start/11.1.4
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/11.1.4
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'ooniprobe.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'ooniprobe.service' >/dev/null || true
		deb-systemd-helper unmask 'ooniprobe.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
