#!/bin/sh
set -e
# Automatically added by dh_installinit/11.1.4
if [ -x "/etc/init.d/ooniprobe" ] && [ "$1" = remove ]; then
	invoke-rc.d ooniprobe stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installdeb/11.1.4
dpkg-maintscript-helper rm_conffile /etc/cron.daily/ooniprobe 2.0.2-1\~ ooniprobe -- "$@"
dpkg-maintscript-helper rm_conffile /etc/cron.monthly/ooniprobe 2.0.2-1\~ ooniprobe -- "$@"
dpkg-maintscript-helper rm_conffile /etc/ooniprobe.conf 2.1.0\~ ooniprobe -- "$@"
# End automatically added section
# Automatically added by dh_systemd_start/11.1.4
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'ooniprobe.service' >/dev/null || true
fi
# End automatically added section

# Automatically added by dh_python2:
if which pyclean >/dev/null 2>&1; then
	pyclean -p ooniprobe 
else
	dpkg -L ooniprobe | grep '\.py$' | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section
