#! /bin/sh

#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <new-preinst> `install'
#        * <new-preinst> `install' <old-version>
#        * <new-preinst> `upgrade' <old-version>
#        * <old-preinst> `abort-upgrade' <new-version>
#
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

case "$1" in
    install|upgrade)
	if [ -f /etc/mail/mimedefang.conf -a ! -f /etc/default/mimedefang ]
	then
	    echo "Copying /etc/mail/mimedefang.conf to /etc/default/mimedefang"
	    cp -p /etc/mail/mimedefang.conf /etc/default/mimedefang
	fi
    ;;

    abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac



exit 0
