#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/globus-scheduler-event-generator" ]; then
	invoke-rc.d globus-scheduler-event-generator stop || exit $?
fi
# End automatically added section
