#!/bin/sh

set -e

case $1 in
	configure)
		if [ "$2" ] && dpkg --compare-versions "$2" lt "1:09.00.0310-2" && \
			grep -q /usr/lib/odbc/psqlodbc..so /etc/odbcinst.ini ; then
			echo "Updating /etc/odbcinst.ini for multiarch support"
			odbcinst -u -d -n 'PostgreSQL ANSI'
			odbcinst -u -d -n 'PostgreSQL Unicode'
		fi
		if ! grep -q PostgreSQL /etc/odbcinst.ini ; then
			odbcinst -i -d -f /usr/share/psqlodbc/odbcinst.ini.template
		fi ;;
esac


