#!/usr/bin/perl

use warnings;
use strict;
use Debconf::Client::ConfModule ":all";

our $pkg="rocksndiamonds";


if ((defined $ARGV[0] and $ARGV[0] =~/reconfigure/) or
  (exists $ENV{DEBCONF_RECONFIGURE} and $ENV{DEBCONF_RECONFIGURE} == 1))
{
    fset "$pkg/begin", "seen", "false";
    fset "$pkg/select_games", "seen", "false";
}

input "high", "$pkg/begin";
go;
get("$pkg/begin") eq 'true' or exit 0;

input "high", "$pkg/select_games";
go;
