#!/bin/sh

set -e

case $1 in
    configure)
        # Add the "orthanc" user
        if ! getent passwd orthanc > /dev/null; then
            adduser --system --quiet \
                    --home /var/lib/orthanc --no-create-home \
                    --shell /bin/bash --group --gecos "Orthanc Administrator" orthanc
        fi
        if test "`id -u orthanc`" -eq 0; then
            echo "The orthanc administrative user must not be root." >&2
            false
        fi
        if test "`id -g orthanc`" -eq 0; then
            echo "The orthanc administrative group must not be root." >&2
            false
        fi

        # Configure the permissions of the required directories
        chown -R orthanc:orthanc /etc/orthanc
        chown -R orthanc:orthanc /var/lib/orthanc

        chmod 0775 /etc/orthanc
        chmod 0664 /etc/orthanc/orthanc.json
        chmod 0664 /etc/orthanc/serve-folders.json
	chmod 0775 /var/lib/orthanc

	# Start the Orthanc service after installation
        # https://www.debian.org/doc/debian-policy/ch-opersys.html#s9.3.3.2
	if [ -x /etc/init.d/orthanc ]; then
           if which invoke-rc.d >/dev/null 2>&1; then
               invoke-rc.d orthanc start
           else
               /etc/init.d/orthanc start
           fi
        fi
	;;

    abort-upgrade|abort-remove|abort-deconfigure)
	;;

    *)
	echo "postinst called with unknown argument \`$1'" >&2
	exit 1
	;;
esac

# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/orthanc" ]; then
		update-rc.d orthanc defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d orthanc $_dh_action || exit $?
	fi
fi
# End automatically added section

