#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ast/bing.xml 45.0esr-2~ iceweasel-l10n-ast -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ast/ddg.xml 45.0esr-2~ iceweasel-l10n-ast -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ast/diccionariu-alla.xml 45.0esr-2~ iceweasel-l10n-ast -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ast/eBay-es.xml 45.0esr-2~ iceweasel-l10n-ast -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ast/google.xml 45.0esr-2~ iceweasel-l10n-ast -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ast/wikipedia-ast.xml 45.0esr-2~ iceweasel-l10n-ast -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ast/yahoo-es.xml 45.0esr-2~ iceweasel-l10n-ast -- "$@"
# End automatically added section
