#!/bin/sh
set -e
# Automatically added by dh_installinit/11
if [ -x "/etc/init.d/hyperv-daemons.hv-vss-daemon" ]; then
	invoke-rc.d hyperv-daemons.hv-vss-daemon stop || exit $?
fi
# End automatically added section
# Automatically added by dh_installinit/11
if [ -x "/etc/init.d/hyperv-daemons.hv-kvp-daemon" ]; then
	invoke-rc.d hyperv-daemons.hv-kvp-daemon stop || exit $?
fi
# End automatically added section
# Automatically added by dh_installinit/11
if [ -x "/etc/init.d/hyperv-daemons.hv-fcopy-daemon" ]; then
	invoke-rc.d hyperv-daemons.hv-fcopy-daemon stop || exit $?
fi
# End automatically added section
