#!/bin/sh

set -e

case "$1" in
configure)
    if which udevadm >/dev/null; then
        udevadm control --reload || true
    fi
    # load the kernel module (as opposed to letting the init script do it)
    if [ -d /run/systemd/system ] ; then
        /lib/systemd/systemd-modules-load aoetools.conf
    fi
    ;;
abort-upgrade|abort-remove|abort-deconfigure)
    ;;
*)
    echo "postinst called with unknown argument '$1'"
    exit 1
    ;;
esac

# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/aoetools" ]; then
		update-rc.d aoetools start 41 S . start 34 0 6 . >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d aoetools $_dh_action || exit $?
	fi
fi
# End automatically added section
# Automatically added by dh_systemd_start
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
	if [ -n "$2" ]; then
		_dh_action=try-restart
	else
		_dh_action=start
	fi
	deb-systemd-invoke $_dh_action aoe-discover.service >/dev/null || true
fi
# End automatically added section

exit 0
