#!/bin/sh
set -e
# Automatically added by dh_icons
if which update-icon-caches >/dev/null 2>&1 ; then
	update-icon-caches /usr/share/icons/expeyes-progman-jr-doc.png /usr/share/icons/expeyes-progman-jr-doc.svg /usr/share/icons/eyes-doc.png /usr/share/icons/eyesj-doc.png
fi
# End automatically added section
