#!/bin/sh
set -e

# Automatically added by dh_moduleupdate
ejabberdctl="/usr/sbin/ejabberdctl"
mods="mod_rest"

if [ "$1" = "configure" ]; then
	# check if ejabberd is running
	$ejabberdctl status > /dev/null || exit 0

	# source /etc/default/ejabberd
	[ -f "/etc/default/ejabberd" ] && . /etc/default/ejabberd

	for mod in $mods; do
		if [ "$($ejabberdctl update_list | grep -c $mod)" -eq "1" ]; then
			echo -n "Upgrading ejabberd module $mod... "
			$ejabberdctl update $mod > /dev/null || { echo "failed"; continue; }
			echo "ok"
		else
			echo "$mod is not enabled or has no update."
		fi
	done
fi
# End automatically added section

