#! /bin/sh -e

del_override() {
    if dpkg-statoverride --list $4 >/dev/null; then
	dpkg-statoverride --force --remove $4
    fi
}

if [ "$1" = "purge" ]; then
    rm -f /etc/courier/imapd.pem
    rm -f /etc/courier/imapaccess.dat
    del_override root courier 0640 /etc/courier/imapd.cnf
fi

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d courier-imap-ssl remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d courier-imap remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask courier-imap.service >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge courier-imap.service >/dev/null
		deb-systemd-helper unmask courier-imap.service >/dev/null
	fi
fi
# End automatically added section


exit 0
