#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/mysqmail-postfix-logger" ]; then
	invoke-rc.d mysqmail-postfix-logger stop || exit $?
fi
# End automatically added section
