#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.2.1
dpkg-maintscript-helper dir_to_symlink /usr/lib/GNUstep/Applications/EdenMath.app/Resources /usr/share/GNUstep/EdenMath.app 1.1.1a-8\~ edenmath.app -- "$@"
# End automatically added section
