#!/bin/sh
set -e
# Automatically added by dh_systemd_start/10.10.9
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'virtlockd.service' 'virtlockd.socket' >/dev/null
fi
# End automatically added section
# Automatically added by dh_systemd_start/10.10.9
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'virtlockd.socket' >/dev/null
fi
# End automatically added section
# Automatically added by dh_installinit/10.10.9
if [ -x "/etc/init.d/libvirt-guests" ] && [ "$1" = remove ]; then
	invoke-rc.d libvirt-guests stop || exit $?
fi
# End automatically added section
# Automatically added by dh_installinit/10.10.9
if [ -x "/etc/init.d/libvirtd" ] && [ "$1" = remove ]; then
	invoke-rc.d libvirtd stop || exit $?
fi
# End automatically added section
# Automatically added by dh_installinit/10.10.9
if [ -x "/etc/init.d/virtlogd" ] && [ "$1" = remove ]; then
	invoke-rc.d virtlogd stop || exit $?
fi
# End automatically added section
