#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/kea-dhcp4-server" ]; then
		update-rc.d kea-dhcp4-server defaults >/dev/null
		invoke-rc.d kea-dhcp4-server start || exit $?
	fi
fi
# End automatically added section
