#!/bin/sh
set -e
# Automatically added by dh_installdeb
dpkg-maintscript-helper mv_conffile /etc/simpleid/apache.conf /etc/apache2/conf-available/simpleid.conf 0.8.3-1~ -- "$@"
# End automatically added section
