#!/bin/sh
#
# Delete dhcpy6d's log files upon package purge.
#

set -e

case "$1" in
    purge)
        rm -f /var/log/dhcpy6d.log* /var/lib/dhcpy6d/volatile.sqlite
        # Taken from ucf's postrm example
        for ext in '' '~' '%' .bak .ucf-new .ucf-old .ucf-dist; do
            rm -f "/etc/default/dhcpy6d$ext"
        done
        if which ucf >/dev/null; then
            ucf --purge /etc/default/dhcpy6d
        fi
        if which ucfr >/dev/null; then
            ucfr --purge dhcpy6d /etc/default/dhcpy6d
        fi
        ;;
esac

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d dhcpy6d remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section

