#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/dhcpy6d" ]; then
	invoke-rc.d dhcpy6d stop || exit $?
fi
# End automatically added section

# Automatically added by dhpython:
if which pyclean >/dev/null 2>&1; then
	pyclean -p dhcpy6d 
else
	dpkg -L dhcpy6d | grep \.py$ | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section
