#!/bin/sh
set -e
# Automatically added by dh_systemd_start/10.10.9
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'tangd-keygen.service' 'tangd-update.path' 'tangd-update.service' 'tangd.socket' >/dev/null
fi
# End automatically added section
