#!/bin/sh
set -e

# Automatically added by dh_installmenu
if [ "$1" = "configure" ] && [ -x "`which update-menus 2>/dev/null`" ]; then
	update-menus
fi
# End automatically added section


# Install alternative
update-alternatives --install /usr/bin/infobrowser \
	infobrowser /usr/bin/pinfo 50 \
	--slave /usr/share/man/man1/infobrowser.1.gz \
	infobrowser.1.gz /usr/share/man/man1/pinfo.1.gz

exit 0
