#!/bin/bash -e

. /usr/share/debconf/confmodule

case "$1" in
    abort-upgrade|abort-remove|abort-deconfigure)  exit 0 ;;
    configure) ;;  # continue below
    *)  exit 0 ;;
esac

ODICT=/usr/share/dict/gene.dic
EDICT=/usr/share/dict/gene.sdic
JDICT=/usr/share/dict/jgene.sdic
MKARY=/usr/bin/mkary

ESCRIPT=/usr/share/sdic/gene.pl
JSCRIPT=/usr/share/sdic/jgene.pl

download_archive ()
{
    db_get sdic-gene95/tmpdir
    SDICTMP=$RET
    LZH=$SDICTMP/gene95.lzh
    TGZ=$SDICTMP/gene95.tar.gz
    TG2=$SDICTMP/gene95.tar.bz2
    TG2ARCH=http://www.namazu.org/~tsuchiya/sdic/data/gene95.tar.bz2

    test -O $LZH && return 0
    test -O $TGZ && return 0
    test -O $TG2 && return 0

    nc -w 3 -z www.namazu.org 80 && \
        wget -q $TG2ARCH -O $TG2 && \
        return 0

    echo "Cannot download gene95 archive: $TG2ARCH"
    exit 1
}

function find_archive ()
{
    [ ! -r $1 ] && return 0
    if [ ! -O $1 ]; then
        echo "$1 is not owned by root." 1>&2
        exit 1
    elif [ ! -x $2 ]; then
        echo "You need $2." 1>&2
        exit 1
    fi
    ARC=$1
    IGNORELINES=$3
    COMMAND=$4
    return 0
}

function install_from_archive ()
{
    db_get sdic-gene95/tmpdir
    SDICTMP=$RET
    ARC=""
    LZH=$SDICTMP/gene95.lzh
    TGZ=$SDICTMP/gene95.tar.gz
    TG2=$SDICTMP/gene95.tar.bz2
    find_archive  $LZH /usr/bin/lha 5 'lha p $ARC gene.txt'
    [ "$ARC" = "" ] && find_archive $TGZ /bin/gunzip 2 'tar zxOf $ARC gene.txt'
    [ "$ARC" = "" ] && find_archive $TG2 /bin/bunzip2 2 'bunzip2 -c $ARC|tar xOf - gene.txt'
    if [ "$ARC" = "" ]; then
        echo "Prepare $LZH or $TGZ or $TG2 first." 1>&2
        exit 1
    fi
    echo -n "Extract $ODICT from $ARC ... " 1>&2
    eval $COMMAND > $ODICT
    chmod 644 $ODICT
    echo "done." 1>&2
}

make_array ()
{
    test -s $1.ary && return 0
    test -x $MKARY || return 0
    echo -n "Building suffix array (This will take for a minute) ... "
    $MKARY -q -b 10 $1 && chmod 644 $1 && echo done.
}

# check and download original archive
download_archive

# extract original dictionary
test -s $EDICT || test -s $ODICT || install_from_archive

# create eiwa dictionary
if [ ! -s $EDICT -o "`nkf -g $EDICT 2>/dev/null`" != "EUC-JP" ]; then
    echo -n "Building $EDICT from $ODICT ... " 1>&2
    nkf -S -e $ODICT | $ESCRIPT > $EDICT
    chmod 644 $EDICT
    echo "done." 1>&2
fi
db_get sdic-gene95/en_array
if [ "$RET" = "true" ]; then
    make_array $EDICT
fi

# create waei dictionary
db_get sdic-gene95/make_jp
if [ "$RET" = "true" ]; then
    if [ ! -s $JDICT ]; then
        echo -n "Building $JDICT  ... " 1>&2
        $JSCRIPT $EDICT >$JDICT 2>/dev/null
        chmod 644 $JDICT
        echo "done." 1>&2
    fi
    db_get sdic-gene95/jp_array
    if [ "$RET" = "true" ]; then
        make_array $JDICT waei
    fi
fi


