#!/bin/sh
set -e
# Automatically added by dh_installinit/11.5.3
if [ -x "/etc/init.d/globus-scheduler-event-generator" ]; then
	invoke-rc.d globus-scheduler-event-generator stop || exit 1
fi
# End automatically added section
