#!/bin/sh

set -e

WMentry="/usr/bin/qtile"

 

update-alternatives --install /usr/bin/x-window-manager \
  x-window-manager $WMentry 50 --slave \
  /usr/share/man/man1/x-window-manager.1.gz \
  x-window-manager.1.gz /usr/share/man/man1/qtile.1.gz
