#!/bin/sh

set -e

if [ "${1}" = "remove" ] && [ -r /usr/share/debconf/confmodule ] && [ -r /usr/share/dbconfig-common/dpkg/prerm ] ; then
	. /usr/share/debconf/confmodule

	db_get aodh/configure_db
	if [ "$RET" = "true" ]; then
		. /usr/share/dbconfig-common/dpkg/prerm
		dbc_go aodh-common $@
	fi
fi



exit 0
