#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/rotter" ]; then
		update-rc.d rotter start 95 2 3 4 5 . stop 13 0 1 6 . >/dev/null
		invoke-rc.d rotter start || exit $?
	fi
fi
# End automatically added section
# Automatically added by dh_installmenu
if [ "$1" = "configure" ] && [ -x "`which update-menus 2>/dev/null`" ]; then
	update-menus
fi
# End automatically added section
