#! /bin/sh

set -e

. /usr/share/debconf/confmodule

if [ "$1" = "configure" ] || [ "$1" = "reconfigure" ]; then
	# Double guess the cobbler server: in /etc/cobbler/settings
	if [ -r /etc/cobbler/settings ] ; then
		# The authoritative value is always the one in the config file
		CONFIG_SERVER_HOSTNAME=`cat /etc/cobbler/settings | grep -e "^server:" | awk '{print $2}'`
		db_set cobbler/server ${CONFIG_SERVER_HOSTNAME}
	else
		# Otherwise use what's in debconf db (ie: preseed)
		db_get cobbler/server || true
		if [ -z "${RET}" ] ; then
			# But if it's empty, we can double-guess
			CALC_HOSTNAME=$(hostname --fqdn)
			if [ -n "${CALC_HOSTNAME}" ] ; then
				db_set cobbler/server ${CALC_HOSTNAME}
			fi
		fi
	fi

	# Double guess the next-server IP
	if [ -r /etc/cobbler/settings ] ; then
		CONFIG_NEXT_SERVER=`cat /etc/cobbler/settings | grep -e "^next_server:" | awk '{print $2}'`
		db_set cobbler/next_server ${CONFIG_NEXT_SERVER}
	else
		db_get cobbler/next_server || true
		if [ -z "${RET}" ] ; then
			# Sanitize some ip settings, so as to make cobbler more useful out of the box
			while read Iface Destination Gateway Flags RefCnt Use Metric Mask MTU Window IRTT; do
				[ "$Mask" = "00000000" ] && \
				interface="$Iface" && \
				ipaddr=$(LC_ALL=C /sbin/ip -4 addr list dev "$interface" scope global) && \
				ipaddr=${ipaddr#* inet } && \
				ipaddr=${ipaddr%%/*} && \
				break
			done < /proc/net/route


			db_get cobbler/next_server || true
			if ([ -n "$RET" ] && [ "$RET" != "127.0.0.1" ]); then
				db_set cobbler/next_server "$RET"
			elif [ -n "$ipaddr" ]; then
				db_set cobbler/next_server "$ipaddr"
			fi
		fi
	fi

	# If there's no password file, ask for a password
	if ! [ -e /etc/cobbler/users.digest ] ; then
		db_input high cobbler/password || true
	fi
	db_input low cobbler/server || true
	db_input low cobbler/next_server || true
	db_go
fi

exit 0
