#! /bin/sh -e

if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ]; then
    update-alternatives --quiet --remove java /usr/bin/gij-6
    update-alternatives --quiet --remove rmiregistry /usr/bin/grmiregistry-6
    update-alternatives --quiet --remove keytool /usr/bin/gkeytool-6
    update-alternatives --quiet --remove orbd /usr/bin/gorbd-6
    update-alternatives --quiet --remove rmid /usr/bin/grmid-6
fi



exit 0
