#!/bin/sh
set -e

if [ -x "/etc/init.d/dpm" ]; then
	if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
		invoke-rc.d dpm stop || exit $?
	else
		/etc/init.d/dpm stop || exit $?
	fi
fi

if [ "$1" = "remove" ] ; then
	update-alternatives --remove dpm /usr/lib/dpm-mysql/dpm
fi


