#!/bin/sh

set -e

case "${1}" in
	configure)
		chown root:doodle /usr/bin/doodled
		chmod g+s /usr/bin/doodled
		;;

	abort-upgrade|abort-remove|abort-deconfigure)

		;;

	*)
		echo "postinst called with unknown argument \`${1}'" >&2
		exit 1
		;;
esac

# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/doodled" ]; then
		update-rc.d doodled defaults 22 >/dev/null
		invoke-rc.d doodled start || exit $?
	fi
fi
# End automatically added section


exit 0
