#!/bin/sh

set -e

if [ "$1" = purge ]; then
    rm -rf /etc/corosync/qnetd/nssdb
fi

# Automatically added by dh_installinit/11.2.1
if [ "$1" = "purge" ] ; then
	update-rc.d corosync-qnetd remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.2.1
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'corosync-qnetd.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'corosync-qnetd.service' >/dev/null || true
		deb-systemd-helper unmask 'corosync-qnetd.service' >/dev/null || true
	fi
fi
# End automatically added section

