#!/bin/sh
set -e
# Automatically added by dh_installinit/10.10.2
if [ "$1" = "purge" ] ; then
	update-rc.d kopano-dagent remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_apparmor/2.11.0-11
if [ "$1" = "purge" ] && ! [ -e "/etc/apparmor.d/usr.sbin.kopano-dagent" ] ; then
    rm -f "/etc/apparmor.d/disable/usr.sbin.kopano-dagent" || true
    rm -f "/etc/apparmor.d/force-complain/usr.sbin.kopano-dagent" || true
    rm -f "/etc/apparmor.d/local/usr.sbin.kopano-dagent" || true
    rmdir /etc/apparmor.d/disable 2>/dev/null || true
    rmdir /etc/apparmor.d/local   2>/dev/null || true
    rmdir /etc/apparmor.d         2>/dev/null || true
fi
# End automatically added section
