#! /bin/sh 
set -e

if [ "$1" = purge ]; then
	rm -f /etc/calamaris/cron.conf
	rm -f /etc/cron.daily/calamaris
	rm -f /var/log/calamaris/*
fi

# Automatically added by dh_installdebconf
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

