#!/bin/sh
set -e
# Automatically added by dh_installcligac/UNDECLARED
if [ "$1" = "configure" ] && [ -x /usr/share/cli-common/gac-package-install ]; then
	/usr/share/cli-common/gac-package-install libvirtuoso5.5-cil
fi
# End automatically added section
