#!/bin/sh

set -e

DIRS="/var/log/graphite-api /var/lib/graphite-api"

if [ "$1" = "configure" ]; then
    # This use is shared with graphite-web
    adduser --system --quiet --home /var/lib/graphite --no-create-home \
	    --shell /bin/false --force-badname --group --gecos "Graphite User" _graphite

    for i in $DIRS; do
	mkdir -m 0755 -p $i
	if ! dpkg-statoverride --list $i >/dev/null 2>&1; then
	    dpkg-statoverride --update --add _graphite _graphite 0755 $i
	fi
    done
fi


# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p graphite-api 
fi
if which pypy3compile >/dev/null 2>&1; then
	pypy3compile -p graphite-api  || true
fi

# End automatically added section
# Automatically added by dh_installinit/11.4.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/graphite-api" ]; then
		update-rc.d graphite-api defaults >/dev/null
		invoke-rc.d graphite-api start || exit 1
	fi
fi
# End automatically added section

