#!/bin/sh
set -e
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper symlink_to_dir /usr/share/doc/libplplot-dev libplplot12 5.13.0+dfsg-5~ -- "$@"
# End automatically added section
