#!/bin/sh
set -e

# Automatically added by dh_installmenu/11.5.1
if [ "$1" = "configure" ] && [ -x "`which update-menus 2>/dev/null`" ]; then
	update-menus
fi
# End automatically added section


if [ "$1" = "configure" ]; then
	if dpkg --compare-versions "$2" lt-nl "2.2.2-3"; then
		rm -f /etc/X11/Xresources/XCircuit
	fi
fi
