#!/bin/sh
set -e



# Move the app-defaults conffile.
if [ "$1" = "install" -o "$1" = "upgrade" ]; then
	if dpkg --compare-versions "$2" lt-nl "2.2.2-3"; then
		if [ -f /etc/X11/Xresources/XCircuit ]; then
			mv /etc/X11/Xresources/XCircuit /etc/X11/app-defaults/XCircuit
		fi
	fi
fi
