#!/bin/sh
# preinst script for levee
set -e

case "$1" in
    install|upgrade)
    	if [ "$2" = "3.4o-7" ]; then
		update-alternatives --remove editor /usr/bin/lev
		update-alternatives --remove vi /usr/bin/lev
	fi
	;;

    abort-upgrade)
	;;

    *)
        echo "preinst called with unknown argument: $1" >&2
        exit 1
	;;
esac



exit 0
