#!/bin/sh
set -e
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/texmf/hyphen.d/10texlive-lang-german.cnf 2015.20150524-1~ -- "$@"
# End automatically added section
