#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.1.5
dpkg-maintscript-helper rm_conffile /etc/init/friendly-recovery.conf 0.2.36\~ -- "$@"
# End automatically added section
# Automatically added by dh_systemd_start/11.1.5
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'friendly-recovery.service' >/dev/null || true
fi
# End automatically added section
