#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.3.5
dpkg-maintscript-helper rm_conffile /etc/akonadi/mysql-global-mobile.conf 4:17.08.3-2\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/akonadi/mysql-global.conf 4:17.08.3-2\~ -- "$@"
# End automatically added section
