#!/bin/sh
set -e
# Automatically added by dh_systemd_start/11.5.3
if [ -d /run/systemd/system ]; then
	deb-systemd-invoke stop 'zfs-import-cache.service' 'zfs-import-scan.service' 'zfs.target' >/dev/null || true
fi
# End automatically added section
