#!/bin/sh


case "$1" in
    purge)
        # remove the configuration files in /etc/mgetty
        for file in voice.conf; do
	    if [ -f /etc/mgetty/$file ] ; then
	    	rm -f /etc/mgetty/$file
	    fi
	    if [ -f /etc/mgetty/$file.dpkg-old ] ; then
	    	rm -f /etc/mgetty/$file.dpkg-old
	    fi
	    if [ -f /etc/mgetty/$file.dpkg-new ] ; then
	    	rm -f /etc/mgetty/$file.dpkg-new
	    fi
	done
	rmdir /etc/mgetty || true;
	;;
    *)
	;;
esac


