#!/bin/sh
set -e
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/texmf/fmt.d/10texlive-formats-extra.cnf 2015.20150524-1~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/texmf/fmt.d/10texlive-omega.cnf 2015.20150524-1~ -- "$@"
# End automatically added section
