#!/bin/sh
set -e



if [ "$1" = "remove" ] ; then
  update-alternatives --remove voms-proxy-init /usr/bin/voms-proxy-init3
  update-alternatives --remove voms-proxy-info /usr/bin/voms-proxy-info3
  update-alternatives --remove voms-proxy-destroy /usr/bin/voms-proxy-destroy3
fi
