#!/bin/sh
set -e
# Automatically added by dh_installsystemd/10.10.9
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/10.10.9
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'dm-event.socket' >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'dm-event.socket' >/dev/null
		deb-systemd-helper unmask 'dm-event.socket' >/dev/null
	fi
fi
# End automatically added section
