#!/bin/sh
set -e
# Automatically added by dh_installsystemd/10.10.9
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'dm-event.service' 'dm-event.socket' >/dev/null
fi
# End automatically added section
