#!/bin/sh
set -e
# Automatically added by dh_icons/11.5.4
if which update-icon-caches >/dev/null 2>&1 ; then
	update-icon-caches /usr/share/icons/debian-installer-launcher.png
fi
# End automatically added section
# Automatically added by dh_installmenu/11.5.4
if [ -x "`which update-menus 2>/dev/null`" ]; then update-menus ; fi
# End automatically added section
# Automatically added by dh_installdebconf/11.5.4
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section
