#!/bin/sh

set -e

if [ "${1}" = "configure" ] ; then
	update-alternatives --install /usr/share/puppet/modules/openssl puppet-module-openssl /usr/share/puppet/modules.available/camptocamp-openssl 500
fi



exit 0
