#!/bin/sh

set -e

case $1 in
    purge|remove|upgrade)
        # Restart the Orthanc service
        # https://www.debian.org/doc/debian-policy/ch-opersys.html#s9.3.3.2
        if [ -x /etc/init.d/orthanc ]; then
            if which invoke-rc.d >/dev/null 2>&1; then
                invoke-rc.d orthanc restart
            else
                /etc/init.d/orthanc restart
            fi
        fi
        ;;

    failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac


