#!/bin/sh
set -e

if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi

# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/default/knot-resolver 1.1.0-3~ knot-resolver -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/init.d/knot-resolver 1.1.0-3~ knot-resolver -- "$@"
# End automatically added section
# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d kresd remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section


if [ -x "/usr/bin/deb-systemd-helper" ]; then
	for service in kresd.socket kresd-control.socket kresd-tls.socket kresd.service; do
		if [ "$1" = "remove" ]; then
			deb-systemd-helper mask $service >/dev/null
		fi

		if [ "$1" = "purge" ]; then
			deb-systemd-helper purge $service >/dev/null
			deb-systemd-helper unmask $service >/dev/null
		fi
	done
fi

exit 0
