#!/bin/sh
set -e
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/default/knot-resolver 1.1.0-3~ knot-resolver -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/init.d/knot-resolver 1.1.0-3~ knot-resolver -- "$@"
# End automatically added section
