#!/bin/sh
set -e
# Automatically added by dh_installinit/11.5.3
if [ -x "/etc/init.d/ovn-central" ] && [ "$1" = remove ]; then
	invoke-rc.d ovn-central stop || exit 1
fi
# End automatically added section
