#!/bin/sh

set -e


if [ upgrade != "$1" ] || dpkg --compare-versions "$2" lt 1:4.3.0~beta1-1; then
	dpkg-divert --add --rename \
		--divert /usr/lib/libreoffice/share/basic/dialog.xlc.noaccess \
			/usr/lib/libreoffice/share/basic/dialog.xlc
	dpkg-divert --add --rename \
		--divert /usr/lib/libreoffice/share/basic/script.xlc.noaccess \
			/usr/lib/libreoffice/share/basic/script.xlc
fi



exit 0
