#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.5.4
dpkg-maintscript-helper dir_to_symlink /usr/share/doc/t-code t-code-common 2:2.3.1-3.4 -- "$@"
# End automatically added section
# Automatically added by dh_installemacsen/11.5.4
if [ -e /var/lib/emacsen-common/state/package/installed/emacsen-common -a -x /usr/lib/emacsen-common/emacs-package-remove ] ; then
	/usr/lib/emacsen-common/emacs-package-remove --prerm t-code
fi
# End automatically added section
