#!/bin/sh
set -e
# Automatically added by dh_icons
if which update-icon-caches >/dev/null 2>&1 ; then
	update-icon-caches /usr/share/icons/wm-icons
fi
# End automatically added section
# Automatically added by dh_installmenu
inst=/etc/menu-methods/wm-icons
if [ "$1" = "remove" ] && [ -f "$inst" ]; then chmod a-x $inst ; fi
if [ -x "`which update-menus 2>/dev/null`" ]; then update-menus ; fi
# End automatically added section
