#!/bin/sh
set -e
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/ganeti/instance-debootstrap/hooks/xen-hvc0 0.14-1~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/ganeti/instance-debootstrap/hooks/clear-root-password 0.14-1~ -- "$@"
# End automatically added section
