#!/bin/sh

set -e

if [ "$1" = "remove" -o "$1" = "purge" ]; then
    update-alternatives --remove php-config /usr/bin/php-config7.1
    update-alternatives --remove phpize /usr/bin/phpize7.1
fi



exit 0
