#!/bin/sh

set -e

# Remove /etc/mcelog-disabled on purge
if [ "$1" = "purge" ]; then
    if [ -d /var/lib/mcelog ]; then
	rm -f /var/lib/mcelog/memory-errors
	rmdir --ignore-fail-on-non-empty /var/lib/mcelog
    fi

    # Remove files and logs created by versions prior to 0.9~pre1-2.
    rm -f /etc/mcelog-disabled
    rm -f /var/log/mcelog /var/log/mcelog.*

    # Purge debconf templates; debconf removed starting with 0.9~pre1-2.
    if [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
    fi
fi

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d mcelog remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section

