#!/bin/sh -e

case "$1" in
  purge)
	rm -f /etc/sudo-ldap.conf
	rm -rf /var/lib/sudo
	rm -rf /run/sudo
  ;;

  remove|upgrade|deconfigure)
  ;;

  abort-upgrade|failed-upgrade)
    if [ -e "/etc/sudoers.pre-conffile" ]; then
        mv /etc/sudoers.pre-conffile /etc/sudoers
    fi
  ;;


  *)
        echo "unknown argument --> $1" >&2
        exit 0
  ;;
esac

# remove sudoers entries, if any, from nsswitch.conf
if [ -w /etc/nsswitch.conf ] ; then
	sed -i /^sudoers:/d /etc/nsswitch.conf
fi

# Automatically added by dh_installinit/11.5.3
if [ "$1" = "purge" ] ; then
	update-rc.d sudo-ldap remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdeb/11.5.3
dpkg-maintscript-helper rm_conffile /etc/init.d/sudo 1.8.21p2-2\~ -- "$@"
# End automatically added section

