#!/bin/sh
set -e
refresh_libvariant_alternative () {
	local libvariant=$1
	local libpriority=$2
	update-alternatives --quiet \
		--install \
			/usr/lib/x86_64-linux-gnu/libtachyon.so.0 \
			libtachyon.so.0 \
			/usr/lib/x86_64-linux-gnu/libtachyon-${libvariant}.so.0 $libpriority \
		--slave /usr/lib/x86_64-linux-gnu/libtachyon.so.0.0.0 \
			libtachyon.so.0.0.0 \
			/usr/lib/x86_64-linux-gnu/libtachyon-${libvariant}.so.0.0.0
	return 0
	}
case $1 in
	remove|deconfigure)
		for LIBVARIANT in mt-openmp mt-thr; do
			case $LIBVARIANT in
			serial)         LIBPRIORITY=10 ;;
			mt-openmp)      LIBPRIORITY=110 ;;
			mt-thr)         LIBPRIORITY=150 ;;
			mpich-openmp)   LIBPRIORITY=210 ;;
			mpich-thr)      LIBPRIORITY=250 ;;
			mpich)          LIBPRIORITY=290 ;;
			openmpi-openmp) LIBPRIORITY=310 ;;
			openmpi-thr)    LIBPRIORITY=350 ;;
			openmpi)        LIBPRIORITY=390 ;;
				*) echo "unknown library variant \'${LIBVARIANT}': skip" >&2 ;;
			esac
			refresh_libvariant_alternative $LIBVARIANT $LIBPRIORITY
		done
		;;
	upgrade|failed-upgrade) ;;
	*) echo "prerm called with unknown argument \`$1'" >&2 ; exit 0 ;;
esac
# Automatically added by dh_installdeb/11.2.1
dpkg-maintscript-helper symlink_to_dir /usr/share/doc/libtachyon-mt-0-dev /usr/share/doc/libtachyon-dev-common 0.99~b6+dsx-8~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.2.1
dpkg-maintscript-helper dir_to_symlink /usr/share/doc/libtachyon-mt-0-dev /usr/share/doc/libtachyon-dev-common 0.99~b6+dsx-5~ -- "$@"
# End automatically added section

exit 0
