#!/bin/sh

set -e

# Recover from incorrect init.d script runlevel settings in
# version 2.1.2-2 and earlier
if [ "$1" = "configure" ] && dpkg --compare-versions "$2" le "2.1.2-2" ; then
    update-rc.d -f qtsmbstatusd remove
fi

# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/qtsmbstatusd" ]; then
		update-rc.d qtsmbstatusd defaults >/dev/null
		invoke-rc.d qtsmbstatusd start || exit $?
	fi
fi
# End automatically added section

