#!/bin/sh

set -e

if [ "$1" = purge ]
then
  rm -f /etc/slay_mode
fi

# Automatically added by dh_installdebconf/11.4.1
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

