#!/bin/sh

set -e

dpkg-maintscript-helper dir_to_symlink \
	/usr/share/openstack-dashboard/static /var/lib/openstack-dashboard/static 2:9.0.0~rc1-2 openstack-dashboard-apache -- "$@"


if [ "${1}" = "purge" ] ; then
	if [ -f /etc/default/openstack-dashboard-apache ] ; then
		rm -rf /etc/default/openstack-dashboard-apache
	fi
fi

# Automatically added by dh_installdebconf/11.5
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

