#!/bin/sh
set -e
# Automatically added by dh_installinit/10.8
if [ "$1" = "purge" ] ; then
	update-rc.d lizardfs-cgiserv remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/10.8
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask lizardfs-cgiserv.service >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge lizardfs-cgiserv.service >/dev/null
		deb-systemd-helper unmask lizardfs-cgiserv.service >/dev/null
	fi
fi
# End automatically added section
