#!/bin/sh

set -e

dpkg-maintscript-helper rm_conffile \
	/etc/bash_completion.d/rpmlint \
	1.7-2 rpmlint -- "$@"


# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p rpmlint /usr/share/rpmlint
fi

# End automatically added section

