#!/bin/sh

set -e

if [ "$1" = "configure" ] ; then
	update-alternatives --install /usr/sbin/exabgp exabgp /usr/sbin/python2-exabgp 100
fi


# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p python-exabgp 
fi

# End automatically added section


exit 0
