#!/bin/sh
set -e
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/rm/yahoo-ch.xml 45.0esr-2~ iceweasel-l10n-rm -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/rm/wikipedia-rm.xml 45.0esr-2~ iceweasel-l10n-rm -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/rm/pledarigrond.xml 45.0esr-2~ iceweasel-l10n-rm -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/rm/leo_ende_de.xml 45.0esr-2~ iceweasel-l10n-rm -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/rm/google.xml 45.0esr-2~ iceweasel-l10n-rm -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/rm/ddg.xml 45.0esr-2~ iceweasel-l10n-rm -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/rm/bing.xml 45.0esr-2~ iceweasel-l10n-rm -- "$@"
# End automatically added section
