#!/bin/sh
set -e
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/default/argus-server 2:3.0.8.1-1~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/init.d/argus-server 2:3.0.8.1-1~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/ppp/ip-down.d/argus-server 2:3.0.8.1-1~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/ppp/ip-up.d/argus-server 2:3.0.8.1-1~ -- "$@"
# End automatically added section
