#!/bin/sh
set -e
# Automatically added by dh_icons/11.1.6
if which update-icon-caches >/dev/null 2>&1 ; then
	update-icon-caches /usr/share/icons/virtaal.png /usr/share/icons/virtaal.xpm
fi
# End automatically added section
