#!/bin/sh
set -e
# Automatically added by dh_installdeb
dpkg-maintscript-helper symlink_to_dir /usr/share/doc/librubberband-dev /usr/share/doc/librubberband2 1.8.1-6\~ -- "$@"
# End automatically added section
