#!/bin/sh
set -e
# Automatically added by dh_installinit/10.10.5
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/inetutils-syslogd" ]; then
		update-rc.d inetutils-syslogd defaults 10 90 >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d inetutils-syslogd $_dh_action || exit $?
	fi
fi
# End automatically added section
