#!/bin/sh
set -e
# Automatically added by dh_installinit/11.1.3
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/cachefilesd" ]; then
		update-rc.d cachefilesd defaults >/dev/null
		invoke-rc.d cachefilesd start || exit 1
	fi
fi
# End automatically added section
