#!/bin/sh
set -e
# Automatically added by dh_installinit/11.5.3
if [ -x "/etc/init.d/lxcfs" ] && [ "$1" = remove ]; then
	invoke-rc.d lxcfs stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installdeb/11.5.3
dpkg-maintscript-helper rm_conffile /etc/init/lxcfs.conf 3.0.3-2\~ lxcfs -- "$@"
# End automatically added section
