#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.3.5
dpkg-maintscript-helper symlink_to_dir /usr/share/doc/libgnustep-gui0.26 /usr/share/doc/gnustep-gui-common 0.25.0-3\~ -- "$@"
# End automatically added section
