#!/bin/sh

set -e

dante_service_error()
{
	exit "$?"
}

# Automatically added by dh_installinit/11.3.5
if [ -x "/etc/init.d/danted" ] && [ "$1" = remove ]; then
	invoke-rc.d danted stop || dante_service_error
fi
# End automatically added section

