#!/bin/sh
set -e

# Automatically added by dhpython:
if which py3compile >/dev/null 2>&1; then
	py3compile -p python3-flask-silk 
fi

# End automatically added section
# Automatically added by dh_icons
if which update-icon-caches >/dev/null 2>&1 ; then
	update-icon-caches /usr/share/icons/python3-flask-silk
fi
# End automatically added section
