#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/neutron-openvswitch-agent" ] && [ "$1" = remove ]; then
	invoke-rc.d neutron-openvswitch-agent stop || true
fi
# End automatically added section
