#!/bin/sh
set -e

# Automatically added by dhpython:
if which pycompile >/dev/null 2>&1; then
	pycompile -p rapid-photo-downloader /usr/share/rapid-photo-downloader -V 2.7
fi

# End automatically added section
