#!/bin/sh
set -e

. /usr/share/debconf/confmodule

if [ -f /usr/share/dbconfig-common/dpkg/postrm ]; then
	. /usr/share/dbconfig-common/dpkg/postrm
	dbc_go glewlwyd "$@"
fi

if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask glewlwyd.service >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	 if [ -x "$(command -v deluser)" ]; then
		 deluser --quiet --system glewlwyd > /dev/null || true
	else
		 echo >&2 "not removing glewlwyd system account because deluser command was not found"
	fi
	
	db_purge
fi

# Automatically added by dh_installsystemd/11.3.5
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.3.5
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'glewlwyd.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'glewlwyd.service' >/dev/null || true
		deb-systemd-helper unmask 'glewlwyd.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installdebconf/11.3.5
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

