#!/bin/sh
set -e
# Automatically added by dh_installdeb/11
dpkg-maintscript-helper symlink_to_dir /usr/share/doc/python-regex-dbg python-regex-dbg 0.1.20171212-1 -- "$@"
# End automatically added section
