#!/bin/sh
set -e


if [ "$1" = purge ]; then
    rm -f /etc/pki/default.cfg
    rm -f /var/log/pki/pki-server*.log
    rm -rf /var/log/pki/server

    # these are created by pkispawn
    rm -f /etc/default/pki-tomcat
    rm -rf /etc/dogtag/tomcat/pki-tomcat
    rm -rf /etc/pki/pki-tomcat
    rm -f /etc/systemd/system/pki-tomcatd.target.wants/*
    rm -f /etc/systemd/system/pki-tomcatd-nuxwdog.target.wants/*
    rm -rf /var/lib/pki/pki-tomcat
    rm -rf /var/log/pki/pki-tomcat
fi

# Automatically added by dh_installinit/11.5.3
if [ "$1" = "purge" ] ; then
	update-rc.d pki-tomcatd remove >/dev/null
fi
# End automatically added section

