#!/bin/sh
set -e

LOGFILE='/var/log/i2pd/i2pd.log'
I2PDHOME='/var/lib/i2pd'
I2PDUSER='i2pd'

case "$1" in
  configure|reconfigure)
    if getent passwd $I2PDUSER > /dev/null 2>&1; then
      groupadd -f $I2PDUSER || true
    else
      adduser --system --quiet --group --home $I2PDHOME $I2PDUSER
    fi

    mkdir -p -m0750 /var/log/i2pd
    chown -f ${I2PDUSER}:adm /var/log/i2pd
    touch $LOGFILE
    chmod 640 $LOGFILE
    chown -f ${I2PDUSER}:adm $LOGFILE
    mkdir -p -m0750 $I2PDHOME
    chown -f -P ${I2PDUSER}:${I2PDUSER} ${I2PDHOME}
  ;;
  abort-upgrade|abort-remove|abort-deconfigure)
    echo "Aborting upgrade"
    exit 0
  ;;
  *)
    echo "postinst called with unknown argument '$1'" >&2
    exit 0
  ;;
esac

# Automatically added by dh_installsystemd/11.5.3
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# In case this system is running systemd, we need to ensure that all
	# necessary tmpfiles (if any) are created before starting.
	if [ -d /run/systemd/system ] ; then
		systemd-tmpfiles --create i2pd.conf >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installinit/11.5.3
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/i2pd" ]; then
		update-rc.d i2pd defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d i2pd $_dh_action || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.5.3
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# This will only remove masks created by d-s-h on package removal.
	deb-systemd-helper unmask 'i2pd.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'i2pd.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'i2pd.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'i2pd.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
