#!/bin/sh
set -e

# Automatically added by dh_python2:
# make sure python-central files are removed before new package is installed
if [ "$1" = upgrade ] && [ -f /var/lib/pycentral/python-galleryremote.pkgremove ]
then
	pycentral pkgremove python-galleryremote
	rm -f /var/lib/pycentral/python-galleryremote.pkgremove
fi

# End automatically added section
