#!/bin/sh
set -e

# Automatically added by dh_installinit/11.4.1
if [ "$1" = "purge" ] ; then
	update-rc.d nsd remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.4.1
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'nsd.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'nsd.service' >/dev/null || true
		deb-systemd-helper unmask 'nsd.service' >/dev/null || true
	fi
fi
# End automatically added section


if test "$1" = "purge"; then
    spool=/var/lib/nsd
    rm -f $spool/nsd.db $spool/ixfr.db $spool/xfrd.state
    rmdir $spool 2>/dev/null || true

    dpkg-statoverride --remove $spool >/dev/null 2>/dev/null || true

    # remove server/control keys on purge
    for f in nsd_control.key nsd_control.pem nsd_server.key nsd_server.pem; do
	rm -f "/etc/nsd/$f"
    done
fi

exit 0
