#!/bin/sh

set -e

if [ "$1" = "purge" ] ; then
  for dir in /etc/dkim-milter-python/ /var/log/dkim-milter-python; do
    if [ -d "$dir" ]; then
      rmdir "$dir" --ignore-fail-on-non-empty || true
    fi
  done
fi


# Automatically added by dh_installinit/11.5.4
if [ "$1" = "purge" ] ; then
	update-rc.d dkim-milter-python remove >/dev/null
fi
# End automatically added section


exit 0

