#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/ryu" ]; then
		update-rc.d ryu defaults >/dev/null || exit $?
	fi
fi
# End automatically added section
