#!/bin/sh

set -e

# Automatically added by dh_installdebconf
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


if [ "$1" = "purge" ]; then
	rm -f /etc/gosa/desktoprc
	rmdir --ignore-fail-on-non-empty /etc/gosa/
fi
