#!/bin/sh
set -e

run_vlc_cache_gen() {
    if ! /usr/lib/x86_64-linux-gnu/vlc/vlc-cache-gen -f /usr/lib/x86_64-linux-gnu/vlc/plugins ; then
        echo "WARNING: Regenerating VLC plugin cache failed."
        echo "Please run '/usr/lib/x86_64-linux-gnu/vlc/vlc-cache-gen -f /usr/lib/x86_64-linux-gnu/vlc/plugins' manually."
    fi
}

case "$1" in
    triggered)
        run_vlc_cache_gen
        exit 0
        ;;
    configure)
        dpkg-trigger /usr/lib/x86_64-linux-gnu/vlc/plugins
        ;;
esac


