#!/bin/sh
set -e
# Automatically added by dh_installinit/11.3.5
if [ -x "/etc/init.d/gobgpd" ]; then
	invoke-rc.d gobgpd stop || exit 1
fi
# End automatically added section
# Automatically added by dh_systemd_start/11.3.5
if [ -d /run/systemd/system ]; then
	deb-systemd-invoke stop 'gobgpd.service' >/dev/null || true
fi
# End automatically added section
