#!/bin/sh

set -e

. /usr/share/debconf/confmodule
. /usr/share/dbconfig-common/dpkg/prerm.pgsql

dbc_go mailman3-suite "$@"

if which pyclean >/dev/null 2>&1; then
    pyclean -p mailman3-suite
else
    dpkg -L mailman3-suite | grep \.py$ | while read file
    do
        rm -f "${file}"[co] >/dev/null
    done
fi

case "$1" in
    remove|upgrade|deconfigure)
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# Automatically added by dh_installinit/11
if [ -x "/etc/init.d/mailman3-suite" ] && [ "$1" = remove ]; then
	invoke-rc.d mailman3-suite stop || exit $?
fi
# End automatically added section


exit 0
