#!/bin/sh
set -e
# Get tasksel's templates loaded up.
. /usr/share/debconf/confmodule
# Automatically added by dh_installmenu/10.10.5
if [ "$1" = "configure" ] && [ -x "`which update-menus 2>/dev/null`" ]; then
	update-menus
fi
# End automatically added section

