#!/bin/sh
# postinst script for gap-scscp
set -e
DAEMONUSER=_gapd
case "${1}" in
	configure)
		if ! getent passwd | grep -q "^${DAEMONUSER}:" ; then
			echo -n "Adding ${DAEMONUSER} system account..."
			adduser --quiet --system --group --force-badname --shell /bin/sh --home /var/lib/${DAEMONUSER#_} --gecos "GAP SCSCP server daemon" ${DAEMONUSER}
			echo " done"
		fi
		;;
	*)
		;;
esac
# Automatically added by dh_installinit/12
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/gapd" ]; then
		update-rc.d gapd defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d gapd $_dh_action || exit 1
	fi
fi
# End automatically added section

