#!/bin/sh
set -e

# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p nemo-owncloud /usr/share/nemo-python/extensions
fi
if which pypy3compile >/dev/null 2>&1; then
	pypy3compile -p nemo-owncloud /usr/share/nemo-python/extensions || true
fi

# End automatically added section
