#!/bin/sh
set -e

if [ "$1" = "purge" ] && [ -d "/var/lib/gnats/gnats-db" ]; then
	rmdir --ignore-fail-on-non-empty "/var/lib/gnats/gnats-db"
fi

# Automatically added by dh_installdebconf/10.7.2
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

