#!/bin/sh
set -e
# Automatically added by dh_php/UNDECLARED
# Hey emacs, this is -*- shell-script -*-

for name in wikidiff2 ; do
    find /etc/php -mindepth 3 -maxdepth 3 -name "${name}.ini*" | \
    sed -Ee "s,.dpkg-(remove|bak|backup)$,," | \
    grep "/etc/php/[.0-9]*/mods-available/${name}.ini" | \
    fgrep -v "$(for version in 7.3 ; do echo "/etc/php/${version}/mods-available/${name}.ini"; done)" | \
    while read conffile; do
	dpkg-maintscript-helper rm_conffile "${conffile}" -- "$@"
	for dir in \
	    "$(dirname $(dirname "${conffile}"))"/mods-available \
	    "$(dirname $(dirname "${conffile}"))" \
	    /etc/php;
	do
	    if [ -d $dir ]; then
		rmdir --ignore-fail-on-non-empty $dir
	    fi
	done
    done
done
    
if [ -e /usr/lib/php/php-maintscript-helper ] ; then
    . /usr/lib/php/php-maintscript-helper
    
    for version in 7.3 ; do
        for name in wikidiff2 ; do
            php_invoke enmod "$version" ALL "$name" || exit 1
	done
    done
else
    for name in wikidiff2 ; do
        phpenmod "$name"
    done
fi
# End automatically added section
# Automatically added by dh_installdeb/11.5.1
dpkg-maintscript-helper rm_conffile /etc/mediawiki-extensions/extensions-enabled/wikidiff2.php 1.4.1-1 -- "$@"
dpkg-maintscript-helper rm_conffile /etc/mediawiki-extensions/extensions-available/wikidiff2.php 1.4.1-1 -- "$@"
# End automatically added section
