#! /bin/sh
# postrm script for gtkballs 

set -e

case "$1" in
       purge)
	      # Delete high score file
	   	rm -f /var/games/gtkballs-scores;

		;;
       remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)


        ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1

esac

# Automatically added by dh_installmenu
if [ -x "`which update-menus 2>/dev/null`" ]; then update-menus ; fi
# End automatically added section


exit 0
