#! /bin/sh
# postinst script for Gtkballs

set -e

case "$1" in
    configure)
		# create a high score file
		SCOREFILE=/var/games/gtkballs-scores;
		if [ ! -f $SCOREFILE ]; then 
			touch $SCOREFILE; 
			chgrp games $SCOREFILE;
			chmod 0664 $SCOREFILE;
		fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)

    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# Automatically added by dh_installmenu
if [ "$1" = "configure" ] && [ -x "`which update-menus 2>/dev/null`" ]; then
	update-menus
fi
# End automatically added section


exit 0


