#!/bin/sh

set -e

. /usr/share/debconf/confmodule
db_version 2.0

unpriv_userns=-1
if [ -r /proc/sys/kernel/unprivileged_userns_clone ]; then
	unpriv_userns=$(cat /proc/sys/kernel/unprivileged_userns_clone)
fi

# Display warning if unprivileged user namespaces are disabled in the running kernel
if [ "$unpriv_userns" -eq 0 ]; then
	db_input high charliecloud/unpriv_userns_warning || true
	db_go || true
fi
