#!/bin/sh 
set -e

dpkg-maintscript-helper rm_conffile \
  /etc/emacs/site-start.d/50wl.el 2.6.1-4~ -- "$@"

# Automatically added by dh_installemacsen/11.3.5
if ( [ "$1" = "install" ] || [ "$1" = "upgrade" ] ) \
	&& [ -e /var/lib/emacsen-common/state/package/installed/emacsen-common -a -x /usr/lib/emacsen-common/emacs-package-install ]
then
	/usr/lib/emacsen-common/emacs-package-install --preinst wl
fi
# End automatically added section

