#!/bin/sh

set -e

if [ "${1}" = "purge" ] ; then
	if [ -f /usr/share/debconf/confmodule ] && [ -f /usr/share/dbconfig-common/dpkg/postrm ] ; then
		. /usr/share/debconf/confmodule

		db_get keystone/configure_db
		if [ "$RET" = "true" ] ; then
			. /usr/share/dbconfig-common/dpkg/postrm
			dbc_go keystone $@
		fi
	fi
	rm -rf /var/log/keystone /var/lib/keystone /etc/keystone
	if [ -x `which a2dissite`"" ] ; then
		a2dissite wsgi-keystone.conf || true
	fi
fi

# Automatically added by dh_installdebconf/11.4.1
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section
# Automatically added by dh_apparmor/2.13-8
if [ "$1" = "purge" ] && ! [ -e "/etc/apparmor.d/usr.bin.keystone-all" ] ; then
    rm -f "/etc/apparmor.d/disable/usr.bin.keystone-all" || true
    rm -f "/etc/apparmor.d/force-complain/usr.bin.keystone-all" || true
    rm -f "/etc/apparmor.d/local/usr.bin.keystone-all" || true
    rmdir /etc/apparmor.d/disable 2>/dev/null || true
    rmdir /etc/apparmor.d/local   2>/dev/null || true
    rmdir /etc/apparmor.d         2>/dev/null || true
fi
# End automatically added section

