#!/bin/sh

set -e

if [ "$1" = "upgrade" ] || [ "$1" = "configure" ]; then
    update-alternatives --quiet --remove mips64el-linux-gnuabi64-gfortran /usr/bin/mips64el-linux-gnuabi64-gfortran-6
fi



exit 0
