#!/bin/sh

set -e

if [ "${1}" = purge ] ; then
	rm -f /var/log/ceilometer/ceilometer-agent-compute.log*
	[ -d /var/log/ceilometer ] && rmdir --ignore-fail-on-non-empty /var/log/ceilometer
fi

# Automatically added by dh_installinit/11.3.5
if [ "$1" = "purge" ] ; then
	update-rc.d ceilometer-agent-compute remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/11.3.5
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'ceilometer-agent-compute.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'ceilometer-agent-compute.service' >/dev/null || true
		deb-systemd-helper unmask 'ceilometer-agent-compute.service' >/dev/null || true
	fi
fi
# End automatically added section

