#!/bin/sh
set -e
# Automatically added by dh_installinit/10.7.2
if [ -x "/etc/init.d/ovirt-guest-agent" ] && [ "$1" = remove ]; then
	invoke-rc.d ovirt-guest-agent stop || exit $?
fi
# End automatically added section

# Automatically added by dh_python2:
if which pyclean >/dev/null 2>&1; then
	pyclean -p ovirt-guest-agent 
else
	dpkg -L ovirt-guest-agent | grep \.py$ | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section
