#!/bin/sh

set -e

ONEHOME=/var/lib/one

if [ "$1" = "purge" ]; then
    rm -rf $ONEHOME/sunstone_vnc_tokens
fi

# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/one/sunstone-plugins.yaml 4.12.3+dfsg-1 -- "$@"
# End automatically added section
# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d opennebula-sunstone remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d opennebula-novnc remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask opennebula-sunstone.service >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge opennebula-sunstone.service >/dev/null
		deb-systemd-helper unmask opennebula-sunstone.service >/dev/null
	fi
fi
# End automatically added section

