#!/bin/sh
set -e
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/one/sunstone-plugins.yaml 4.12.3+dfsg-1 -- "$@"
# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/opennebula-sunstone" ]; then
	invoke-rc.d opennebula-sunstone stop || exit $?
fi
# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/opennebula-novnc" ]; then
	invoke-rc.d opennebula-novnc stop || exit $?
fi
# End automatically added section
