#!/bin/sh
set -e
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/mk/amazondotcom.xml 45.0esr-2~ iceweasel-l10n-mk -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/mk/answers.xml 45.0esr-2~ iceweasel-l10n-mk -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/mk/bing.xml 45.0esr-2~ iceweasel-l10n-mk -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/mk/creativecommons.xml 45.0esr-2~ iceweasel-l10n-mk -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/mk/ddg.xml 45.0esr-2~ iceweasel-l10n-mk -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/mk/eBay.xml 45.0esr-2~ iceweasel-l10n-mk -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/mk/google.xml 45.0esr-2~ iceweasel-l10n-mk -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/mk/wikipedia-mk.xml 45.0esr-2~ iceweasel-l10n-mk -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/mk/yahoo.xml 45.0esr-2~ iceweasel-l10n-mk -- "$@"
# End automatically added section
