#! /bin/sh
# postrm script for racoon 
#
# see: dh_installdeb(1)

set -e

if [ "$1" = purge ]; then
	rm -f /etc/default/racoon
	if which deluser >/dev/null 2>&1; then
		deluser --quiet --system racoon > /dev/null || true
	fi
	if which delgroup >/dev/null 2>&1; then
		delgroup --quiet --system racoon > /dev/null || true
	fi
fi

# Automatically added by dh_systemd_enable/10.7.2
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask racoon.service >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge racoon.service >/dev/null
		deb-systemd-helper unmask racoon.service >/dev/null
	fi
fi
# End automatically added section
# Automatically added by dh_installinit/10.7.2
if [ "$1" = "purge" ] ; then
	update-rc.d racoon remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/10.7.2
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask racoon.service >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge racoon.service >/dev/null
		deb-systemd-helper unmask racoon.service >/dev/null
	fi
fi
# End automatically added section
# Automatically added by dh_installdebconf/10.7.2
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


exit 0
