#!/bin/sh -e

case "$1" in
    purge)
	if [ -d /etc/apticron ] ; then
		rm -rf /etc/apticron || true
	fi
	rm -rf /var/lib/apticron
    ;;
esac

# Automatically added by dh_systemd_start/11.3.5
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/11.3.5
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'apticron.timer' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'apticron.timer' >/dev/null || true
		deb-systemd-helper unmask 'apticron.timer' >/dev/null || true
	fi
fi
# End automatically added section

