#!/bin/sh
set -e

CONFFILE=/etc/dibbler/client.conf
TMP=${CONFFILE}-dpkg-new

if [ "$1" = "purge" ] ; then
    if [ -e ${CONFFILE} ]; then
	rm -f ${CONFFILE}
    fi
    if [ -e ${TMP} ]; then
	rm -f ${TMP}
    fi
    test -f /usr/bin/ucf && ucf --debconf-ok --purge ${CONFFILE}
fi

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d dibbler-client remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installdebconf
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

