#!/bin/sh

set -e

MCOLLECTIVE_SERVER_CFG="/etc/mcollective/server.cfg"

case "$1" in
	purge)
		if [ -e "$MCOLLECTIVE_SERVER_CFG" ]; then
			rm -rf $MCOLLECTIVE_SERVER_CFG
			rmdir --ignore-fail-on-non-empty /etc/mcollective
		fi

	;;
	upgrade|failed-upgrade|abort-install|abort-upgrade|disappear|remove)
	;;
	*)
		echo "postrm called with unknown argument \`${1}'" >&2
		exit 1
	;;
esac

# Automatically added by dh_installsystemd/11.2.1
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.2.1
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'mcollective.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'mcollective.service' >/dev/null || true
		deb-systemd-helper unmask 'mcollective.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
