#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/prayer-accountd" ]; then
		update-rc.d prayer-accountd defaults >/dev/null
		invoke-rc.d prayer-accountd start || exit $?
	fi
fi
# End automatically added section
