#!/bin/sh
set -e

# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p accerciser 
fi
if which pypy3compile >/dev/null 2>&1; then
	pypy3compile -p accerciser  || true
fi

if which py3compile >/dev/null 2>&1; then
	py3compile -p accerciser /usr/share/accerciser
fi
if which pypy3compile >/dev/null 2>&1; then
	pypy3compile -p accerciser /usr/share/accerciser || true
fi

# End automatically added section
