#!/bin/sh

set -e

case "$1" in
    purge)
	# remove /var/lib/spamass-milter if it exists
	if [ -e /var/lib/spamass-milter ]; then
	    rmdir --ignore-fail-on-non-empty /var/lib/spamass-milter
	fi;
	# remove /var/spool/postfix/spamass if it exists
	if [ -e /var/spool/postfix/spamass ]; then
	    rmdir --ignore-fail-on-non-empty /var/spool/postfix/spamass
	fi;
	;;
    *) 
	# do nothing
	;;
esac

### Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d spamass-milter remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
##

exit 0;
