#!/bin/sh
set -e
# Automatically added by dh_installinit/10.10.9
if [ -x "/etc/init.d/nordugrid-arc-egiis" ]; then
	invoke-rc.d nordugrid-arc-egiis stop || exit $?
fi
# End automatically added section
