#! /bin/sh
# postrm script for plptools
#     
# see: dh_installdeb(1)

set -e

case "$1" in
		remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	;;

	purge)
		rm -f /etc/plptools.conf /etc/default/plptools
	;;

	*)
		echo "postrm called with unknown argument \`$1'" >&2
		exit 0
	;;

esac   

# Automatically added by dh_installinit/11.2.1
if [ "$1" = "purge" ] ; then
	update-rc.d plptools remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installmenu/11.2.1
if [ -x "`which update-menus 2>/dev/null`" ]; then update-menus ; fi
# End automatically added section
# Automatically added by dh_installdebconf/11.2.1
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


exit 0
