#!/bin/sh

set -e


ipmievd_initd_failed() {
	echo "Unable to start ipmievd during installation.  Trying to disable."
	if [ -f /etc/default/ipmievd ] && \
           grep -q ^ENABLED=\"false\" /etc/default/ipmievd ; then
	    :
	else
	    touch /etc/default/ipmievd
	    echo "ENABLED=\"false\"" >> /etc/default/ipmievd
	fi
}

# Automatically added by dh_systemd_enable/10.10.7
if deb-systemd-helper debian-installed 'ipmievd.service'; then
	# This will only remove masks created by d-s-h on package removal.
	deb-systemd-helper unmask 'ipmievd.service' >/dev/null || true

	if deb-systemd-helper --quiet was-enabled 'ipmievd.service'; then
		# Create new symlinks, if any.
		deb-systemd-helper enable 'ipmievd.service' >/dev/null || true
	fi
fi

# Update the statefile to add new symlinks (if any), which need to be cleaned
# up on purge. Also remove old symlinks.
deb-systemd-helper update-state 'ipmievd.service' >/dev/null || true
# End automatically added section
# Automatically added by dh_installinit/10.10.7
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/ipmievd" ]; then
		update-rc.d ipmievd defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d ipmievd $_dh_action || ipmievd_initd_failed
	fi
fi
# End automatically added section

