#!/bin/sh

set -e

case "$1" in
    purge)
	rm -rf /var/lib/puppet
	;;
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1

esac

# Automatically added by dh_installinit/11.5.1
if [ "$1" = "purge" ] ; then
	update-rc.d puppet remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.5.1
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'puppet.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'puppet.service' >/dev/null || true
		deb-systemd-helper unmask 'puppet.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
