#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/tryton-server" ] && [ "$1" = remove ]; then
	invoke-rc.d tryton-server stop || exit $?
fi
# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/tryton-server-cron" ] && [ "$1" = remove ]; then
	invoke-rc.d tryton-server-cron stop || exit $?
fi
# End automatically added section

# Automatically added by dh_python2:
if which pyclean >/dev/null 2>&1; then
	pyclean -p tryton-server 
else
	dpkg -L tryton-server | grep \.py$ | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section
