#!/bin/sh
set -e
# Automatically added by dh_installdeb/10.10.5
dpkg-maintscript-helper rm_conffile /etc/icmake/YEARS 7.14.1-1 -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10.5
dpkg-maintscript-helper rm_conffile /etc/icmake/VERSION 7.14.1-1 -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10.5
dpkg-maintscript-helper rm_conffile /etc/icmake/AUTHOR 7.14.1-1 -- "$@"
# End automatically added section
