#!/bin/sh
set -e
# Automatically added by dh_installinit/11.1.2
if [ -x "/etc/init.d/arpwatch" ] && [ "$1" = remove ]; then
	invoke-rc.d arpwatch stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installdeb/11.1.2
dpkg-maintscript-helper rm_conffile /etc/arpwatch.conf 2.1a15-3\~ arpwatch -- "$@"
# End automatically added section
