#!/bin/sh

set -e

case "$1" in
    configure)
        dpkg-maintscript-helper rm_conffile /etc/rsyslog.d/asunder.conf 2.5-2 -- "$@"
        dpkg-maintscript-helper rm_conffile /etc/logrotate.d/asunder 2.8-3 -- "$@"
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# Automatically added by dh_icons
if which update-icon-caches >/dev/null 2>&1 ; then
	update-icon-caches /usr/share/icons/asunder.png
fi
# End automatically added section


exit 0
