#!/bin/sh
set -e
# Automatically added by dh_installinit/11.3.5
if [ -x "/etc/init.d/senlin-engine" ] && [ "$1" = remove ]; then
	invoke-rc.d senlin-engine stop || true
fi
# End automatically added section
