#!/bin/sh -e

# remove old highscore directory, if user wishes it.
if [ -d /var/lib/games/mirrormagic ]; then
    . /usr/share/debconf/confmodule
    db_get mirrormagic/remove_old_highscores
    if [ "$RET" = "true" ]; then
	rm -rf /var/lib/games/mirrormagic/*
	rmdir -p --ignore-fail-on-non-empty /var/lib/games/mirrormagic || true
    fi
fi                                                                          

# fix permissions in highscore directories
if [ "$1" = "configure" ]; then
    if dpkg --compare-versions "$2" lt-nl 2.0.0-12; then
	echo "Fixing mirrormagic's high-score files permissions..."
	chmod -R o-w,g+w /var/games/mirrormagic
    fi
fi




