#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/sleepd" ]; then
		update-rc.d sleepd defaults >/dev/null
		invoke-rc.d sleepd start || exit $?
	fi
fi
# End automatically added section
