#!/bin/sh
set -e

# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p smbios-utils /usr/share/smbios-utils
fi

# End automatically added section

dpkg-maintscript-helper rm_conffile \
	/etc/yum/pluginconf.d/dellsysid.conf 2.4.0-2~ smbios-utils -- "$@"

