#!/bin/sh

set -e

if [ "${1}" = "configure" ] ; then
	update-alternatives --install /usr/share/puppet/modules/congress puppet-module-congress /usr/share/puppet/modules.available/congress 500
fi



exit 0
