#!/bin/sh
set -e
# Automatically added by dh_installinit/11.3.5
if [ -x "/etc/init.d/kea-dhcp-ddns-server" ]; then
	invoke-rc.d kea-dhcp-ddns-server stop || exit 1
fi
# End automatically added section
