#!/bin/sh

set -e

if [ "$1" = "configure" ]; then
	adduser --system --quiet --group --home /var/lib/4store fourstore || :
fi

installinit_error() {
	exit $?
}

# Automatically added by dh_installinit/11.2.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/4store" ]; then
		update-rc.d 4store defaults >/dev/null || installinit_error
	fi
fi
# End automatically added section

