#!/bin/sh

set -e

# Source debconf library
. /usr/share/debconf/confmodule

[ ! -f /var/lib/fookebox/fookebox.sqlite ] && exit 0

db_input high fookebox/remove_database || true
db_go

# Check the answer
db_get fookebox/remove_database
if [ "$RET" = "true" ] ; then
	rm -f /var/lib/fookebox/fookebox.sqlite
	rmdir /var/lib/fookebox/
fi
