#! /bin/sh
# postinst script for capiutils

set -e

case "$1" in
    configure)
        if [ ! -c /dev/capi ] ; then
            if [ ! -d /dev/.udev/ ] && [ ! -d /run/udev/ ] ; then
                cd /dev
                echo "Note: running MAKEDEV to create CAPI devices in /dev..."
                /sbin/MAKEDEV capi
            fi
        fi
        ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac

# Automatically added by dh_installinit/11.2.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/capiutils" ]; then
		update-rc.d capiutils defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d capiutils $_dh_action || exit 1
	fi
fi
# End automatically added section

exit 0
