#!/bin/sh
set -e
# Automatically added by dh_installemacsen/11.5.4
if [ -e /var/lib/emacsen-common/state/package/installed/emacsen-common -a -x /usr/lib/emacsen-common/emacs-package-remove ] ; then
	/usr/lib/emacsen-common/emacs-package-remove --prerm why3
fi
# End automatically added section
