#!/bin/sh
# postrm script for dnssec-trigger
#
# see: dh_installdeb(1)

set -e

dpkg-maintscript-helper mv_conffile /etc/init.d/dnssec-trigger /etc/init.d/dnssec-triggerd 0.12-1~ dnssec-trigger -- "$@"
dpkg-maintscript-helper mv_conffile /etc/dnssec.conf /etc/dnssec-trigger/dnssec.conf 0.12-3~ dnssec-trigger -- "$@"

case "$1" in
    purge)
	rm -f /etc/dnssec-trigger/dnssec_trigger_control.key \
	      /etc/dnssec-trigger/dnssec_trigger_control.pem \
	      /etc/dnssec-trigger/dnssec_trigger_server.key \
	      /etc/dnssec-trigger/dnssec_trigger_server.pem
    ;;

    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# Automatically added by dh_installsystemd/11.2.1
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/11.2.1
if [ "$1" = "purge" ] ; then
	update-rc.d dnssec-triggerd remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.2.1
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'dnssec-triggerd.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'dnssec-triggerd.service' >/dev/null || true
		deb-systemd-helper unmask 'dnssec-triggerd.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
