#!/bin/sh -e

# Debian Postfix prerm
# LaMont Jones <lamont@debian.org>

. /usr/share/postfix/postinst.functions

case "$1" in
    upgrade)
	;;

    deconfigure)
	;;

    remove)
	[ -x /usr/sbin/invoke-rc.d ] && \
		INIT="invoke-rc.d postfix" || \
		INIT="/etc/init.d/postfix"
	${INIT} stop
	rm -rf /var/spool/postfix/lib
	rm -rf /var/spool/postfix/etc
    	;;

    failed-upgrade)
	;;

    *)
	echo "prerm called with unknown argument \`$1'" >&2
	exit 1
	;;
esac
# Automatically added by dh_installinit/10.10.9
if [ -x "/etc/init.d/postfix" ]; then
	invoke-rc.d postfix stop || exit $?
fi
# End automatically added section

exit 0
