#!/bin/sh
#
# prerm script for the Debian GNU/Linux python-rpy package
#
# Copyright 2006 by Dirk Eddelbuettel <edd@debian.org>

set -e


# Automatically added by dh_python2:
if which pyclean >/dev/null 2>&1; then
	pyclean -p python-rpy 
else
	dpkg -L python-rpy | grep \.py$ | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section


case "$1" in
    remove|purge)
	;;

    upgrade)
	;;

    failed-upgrade|abort-install|abort-upgrade|disappear)
	;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac                 
