#!/bin/sh

set -e

case "$1" in
    purge)
        rm -f  /etc/zabbix/zabbix_java_gateway.conf \
               /etc/zabbix/logback-console.xml      \
               /etc/zabbix/logback.xml
        rm -fr /var/log/zabbix-java-gateway
        rm -f  /var/run/zabbix/zabbix_gateway_java.pid
    ;;
esac

# Automatically added by dh_installinit/11.5.4
if [ "$1" = "purge" ] ; then
	update-rc.d zabbix-java-gateway remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.5.4
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'zabbix-java-gateway.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'zabbix-java-gateway.service' >/dev/null || true
		deb-systemd-helper unmask 'zabbix-java-gateway.service' >/dev/null || true
	fi
fi
# End automatically added section

