#!/bin/sh

set -e

CONFFILE=/etc/default/durep-rolling
STORAGE=/usr/share/durep/www

if test "$1" = "remove" && test -f $CONFFILE ; then
    . $CONFFILE
	if test -d $HTTPFILEROOT/durep ; then
        rm -R $HTTPFILEROOT/durep
    fi
fi

# Automatically added by dh_installdebconf
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

