#!/bin/sh
set -e

# Automatically added by dh_pypy:
if which pypycompile >/dev/null 2>&1; then
	pypycompile -p pypy-scandir 
elif pypy -m py_compile >/dev/null 2>&1; then
	dpkg -L pypy-scandir | grep '\.py$' | pypy -m py_compile - >/dev/null
fi

# End automatically added section
