#!/bin/sh
set -e
update-alternatives --install /usr/bin/x-www-browser x-www-browser /usr/bin/qutebrowser 40

# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p qutebrowser 
fi

# End automatically added section
# Automatically added by dh_installmenu/11.3.5
if [ "$1" = "configure" ] && [ -x "`which update-menus 2>/dev/null`" ]; then
	update-menus
fi
# End automatically added section

