#!/bin/sh

set -e

CONF=/etc/openstack-dashboard/local_settings.py

. /usr/share/debconf/confmodule

if [ -r $CONF ] ; then
	VALS=$(grep '^[# \t]*ALLOWED_HOSTS[\t ]*=[ \t]*' $CONF | cut -d= -f2 | sed -e 's/ //g' -e 's|\[||g' -e 's|\]||g' -e "s|'||g" -e 's|"||g' -e 's|#||g')
	if echo x"${VALS}" | grep -q '*' ; then
		db_set horizon/allowed-hosts '*'
	else
		db_set horizon/allowed-hosts $VALS
	fi
else
	db_get horizon/allowed-hosts
	if [ -z "${RET}" ] ; then
		db_set horizon/allowed-hosts $(hostname --fqdn),localhost
	fi
fi

db_input high horizon/allowed-hosts || true
db_go



exit 0
