#! /bin/sh

set -e

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d snmptrapd remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask snmptrapd.service >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge snmptrapd.service >/dev/null
		deb-systemd-helper unmask snmptrapd.service >/dev/null
	fi
fi
# End automatically added section


if [ $1 = purge ]; then
    rm -f /var/lib/snmp/snmptrapd.conf*
    rm -f /var/run/snmptrapd.pid
fi

exit 0
