#!/bin/sh
set -e
# Automatically added by dh_installmenu/11.1.4
if [ "$1" = "configure" ] && [ -x "`which update-menus 2>/dev/null`" ]; then
	update-menus
fi
# End automatically added section
# Automatically added by dh_installwm/11.1.4
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ]; then
	update-alternatives --install /usr/bin/x-window-manager \
		x-window-manager /usr/bin/amiwm 20 \
		--slave /usr/share/man/man1/x-window-manager.1.gz \
		x-window-manager.1.gz /usr/share/man/man1/amiwm.1.gz
fi
# End automatically added section
