#!/bin/sh
set -e

case "$1" in
	remove)
		update-alternatives --remove cwl-runner /usr/bin/cwltool
		;;

	upgrade|failed-upgrade|deconfigure)
		;;

esac


# Automatically added by dh_python2:
if which pyclean >/dev/null 2>&1; then
	pyclean -p cwltool 
else
	dpkg -L cwltool | grep '\.py$' | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section

