#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/bopm" ]; then
		update-rc.d bopm start 60 2 3 4 5 . stop 60 0 1 6 . >/dev/null
		invoke-rc.d bopm start || exit $?
	fi
fi
# End automatically added section
