#! /bin/sh
set -e

# Automatically added by dh_icons/11.3.5
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if which update-icon-caches >/dev/null 2>&1 ; then
		update-icon-caches /usr/share/icons/ContrastHigh
	fi
fi
# End automatically added section


update-alternatives --install /usr/share/icons/default/index.theme \
        x-cursor-theme /usr/share/icons/mate/cursor.theme 100
update-alternatives --install /usr/share/icons/default/index.theme \
        x-cursor-theme /usr/share/icons/mate-black/cursor.theme 30
