#!/bin/sh

set -e

if [ $1 != "configure" ] ; then
  exit 0
fi

running() {
  invoke-rc.d $1 status >/dev/null 2>&1
}

if [ -x /etc/init.d/unicorn ]; then
  if running unicorn; then
    invoke-rc.d unicorn upgrade
  fi
fi

# Automatically added by dh_systemd_enable/10.9
if deb-systemd-helper debian-installed unicorn.service; then
	# This will only remove masks created by d-s-h on package removal.
	deb-systemd-helper unmask unicorn.service >/dev/null || true

	if deb-systemd-helper --quiet was-enabled unicorn.service; then
		# Create new symlinks, if any.
		deb-systemd-helper enable unicorn.service >/dev/null || true
	fi
fi

# Update the statefile to add new symlinks (if any), which need to be cleaned
# up on purge. Also remove old symlinks.
deb-systemd-helper update-state unicorn.service >/dev/null || true
# End automatically added section
# Automatically added by dh_installinit/10.9
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/unicorn" ]; then
		update-rc.d unicorn defaults >/dev/null || exit $?
	fi
fi
# End automatically added section


exit 0
