#!/bin/sh
set -e

if [ "$1" = purge ] && [ -d /var/cache/xfstt ]; then
	echo " Removing xfstt cache files."
	rm -rf /var/cache/xfstt 2>/dev/null || true
fi

if [ "$1" = purge ] && [ -e /etc/default/xfstt ]; then
	echo " Removing xfstt config files."
	rm -f /etc/default/xfstt 2>/dev/null || true
fi

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d xfstt remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installdebconf
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


exit 0
