#!/bin/sh
set -e

# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p python-visionegg 
fi

if which pycompile >/dev/null 2>&1; then
	pycompile -p python-visionegg /usr/share/python-visionegg
fi

# End automatically added section
