#!/bin/sh
set -e
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/icecast2/web/status2.xsl 2.4.0-1~ icecast2 -- "$@"
# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/icecast2" ]; then
	invoke-rc.d icecast2 stop || exit $?
fi
# End automatically added section
