#!/bin/sh
set -e
# Automatically added by dh_installinit/10.10.9
if [ -x "/etc/init.d/heat-api-cloudwatch" ] && [ "$1" = remove ]; then
	invoke-rc.d heat-api-cloudwatch stop || true
fi
# End automatically added section
