#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.3.5
dpkg-maintscript-helper symlink_to_dir /usr/share/doc/libplplot-java libplplot12 5.13.0+dfsg-4~ -- "$@"
# End automatically added section
