#!/bin/sh

set -e

if [ "${1}" = "configure" ] ; then
	update-alternatives --install /usr/share/puppet/modules/neutron puppet-module-neutron /usr/share/puppet/modules.available/neutron 500
fi



exit 0
