#!/bin/sh

set -e

dpkg-maintscript-helper mv_conffile /etc/memcachedb.conf /etc/memcachedb.d/default.conf 1.2.0-11 memcachedb -- "$@"

if [ "$1" = "purge" ]; then
	dpkg-statoverride --remove /var/lib/memcachedb || test $? -eq 2
	rm -rf /var/lib/memcachedb
	userdel memcachedb
fi

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d memcachedb remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section

