#!/bin/sh

set -e

if [ "${1}" = "configure" ] ; then
	update-alternatives --install /usr/share/puppet/modules/octavia puppet-module-octavia /usr/share/puppet/modules.available/octavia 500
fi



exit 0
