#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.4.1
dpkg-maintscript-helper rm_conffile /etc/init.d/ipmi_port 3.0.0-3\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/init.d/ipmiutil_asy 3.0.0-3\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/init.d/ipmiutil_evt 3.0.0-3\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/init.d/ipmiutil_wdt 3.0.0-3\~ -- "$@"
# End automatically added section
