#!/bin/sh
set -e

# Automatically added by dh_python2:
if which pyclean >/dev/null 2>&1; then
	pyclean -p tryton-modules-account-stock-landed-cost-weight 
else
	dpkg -L tryton-modules-account-stock-landed-cost-weight | grep \.py$ | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section
