#!/bin/sh

set -e

if [ "$1" = "configure" ] ; then
    update-alternatives \
        --install /usr/bin/tldr tldr /usr/bin/tldr-py 10 \
        --slave /usr/share/man/man1/tldr.1.gz tldr.1.gz /usr/share/man/man1/tldr-py.1.gz
fi


# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p tldr-py 
fi
if which pypy3compile >/dev/null 2>&1; then
	pypy3compile -p tldr-py  || true
fi

# End automatically added section

