#!/bin/sh
set -e

rm -f /var/cache/ferm/*.sh /var/cache/ferm/*.tmp

if [ "$1" = "purge" ]; then
	rm -f /etc/default/ferm
fi

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d ferm remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask ferm.service >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge ferm.service >/dev/null
		deb-systemd-helper unmask ferm.service >/dev/null
	fi
fi
# End automatically added section
# Automatically added by dh_installdebconf
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

