#!/bin/sh

set -e

# Prepare to move a conffile without triggering a dpkg question
prep_mv_conffile() {
    local PKGNAME="$1"
    local CONFFILE="$2"

    [ -e "$CONFFILE" ] || return 0

    local md5sum="$(md5sum $CONFFILE | sed -e 's/ .*//')"
    local old_md5sum="$(dpkg-query -W -f='${Conffiles}' $PKGNAME | \
            sed -n -e "\' $CONFFILE ' { s/ obsolete$//; s/.* //; p }")"
    if [ "$md5sum" = "$old_md5sum" ]; then
        rm -f "$CONFFILE"
    fi
}

case "$1" in
install|upgrade)
    if dpkg --compare-versions "$2" le "1.1+dfsg-2"; then
        prep_mv_conffile namebench "/etc/namebench.cfg"
    fi
    ;;
*)
    echo "preinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac



exit 0
