#!/bin/sh -e

CONFIG=/etc/iog.cfg
PKGCONFIG=/usr/share/iog/iog.cfg

if [ $1 = purge ]
then
	test -x /usr/bin/ucfr && ucfr --purge iog $CONFIG
	test -x /usr/bin/ucf && ucf --purge $CONFIG
	rm -f $CONFIG
fi

# Automatically added by dh_installdebconf/11.5.3
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


exit 0
