#!/bin/sh

set -e

# Automatically added by dh_installmenu
inst=/etc/menu-methods/olwm
if [ -f $inst ]; then
	chmod a+x $inst
	if [ -x "`which update-menus 2>/dev/null`" ]; then
		update-menus
	fi
fi
# End automatically added section


if [ "$1" = configure ]; then
  # Remove old alternative (if it's still there)
  update-alternatives --remove x-window-manager /usr/bin/X11/olwm > /dev/null 2>&1 || true
  # ...and install new one that now points to the wrapper
  update-alternatives --install /usr/bin/x-window-manager x-window-manager /usr/bin/olwm-x-window-manager 44 \
     --slave /usr/share/man/man1/x-window-manager.1.gz x-window-manager.1.gz /usr/share/man/man1/olwm.1.gz
fi
