#!/bin/sh

set -e

CONFFILE="/etc/default/container-tools"

. /usr/share/debconf/confmodule

db_settitle open-infrastructure-container-tools/title
db_input low open-infrastructure-container-tools/machines || true
db_go

db_settitle open-infrastructure-container-tools/title
db_input low open-infrastructure-container-tools/config || true
db_go

db_settitle open-infrastructure-container-tools/title
db_input low open-infrastructure-container-tools/debconf || true
db_go

db_settitle open-infrastructure-container-tools/title
db_input low open-infrastructure-container-tools/hooks || true
db_go

db_settitle open-infrastructure-container-tools/title
db_input low open-infrastructure-container-tools/keys || true
db_go

db_settitle open-infrastructure-container-tools/title
db_input low open-infrastructure-container-tools/cache || true
db_go

if [ -e /usr/share/container-tools/scripts ]
then
	SCRIPT_CHOICES="$(cd /usr/share/container-tools/scripts && find -maxdepth 1 -not -type d -and -not -name 'default' -and -not -name 'debconf' -and -not -name '*.d' -printf '%P\n' | sort)"
	db_subst open-infrastructure-container-tools/script SCRIPT_CHOICES "$(echo ${SCRIPT_CHOICES} | sed -e 's| |, |g')"

	if [ -x /usr/bin/lsb_release ]
	then
		DISTRIBUTOR="$(lsb_release -is 2>/dev/null)"
	fi

	DISTRIBUTOR="${DISTRIBUTOR:-Debian}"

	case "${DISTRIBUTOR}" in
		Progress*)
			SCRIPT_DEFAULT="progress-linux"
			;;

		*)
			SCRIPT_DEFAULT="debian"
			;;
	esac

	db_subst open-infrastructure-container-tools/script SCRIPT_DEFAULT "${SCRIPT_DEFAULT}"

	db_settitle open-infrastructure-container-tools/title
	db_input low open-infrastructure-container-tools/script || true
	db_go
fi

if [ -e "${CONFFILE}" ]
then
	. ${CONFFILE} || true

	db_set open-infrastructure-container-tools/irc "${IRK_TARGETS}"
fi

db_settitle open-infrastructure-container-tools/title
db_input low open-infrastructure-container-tools/irc || true
db_go

db_stop
