#!/bin/sh

set -e

Remove ()
{
	DEFAULT="${1}"

	if [ -h "${DEFAULT}" ]
	then
		TARGET="$(readlink -f ${DEFAULT})"
	else
		TARGET=""
	fi

	for ITEM in ${DEFAULT} ${TARGET}
	do
		if dpkg-statoverride --list "${ITEM}" > /dev/null 2>&1
		then
			dpkg-statoverride --quiet --remove "${ITEM}"
		fi

		rmdir --ignore-fail-on-non-empty --parents ${ITEM} > /dev/null 2>&1 || true

		rm -f ${ITEM} > /dev/null 2>&1 || true
		rmdir --ignore-fail-on-non-empty --parents $(dirname ${ITEM}) > /dev/null 2>&1 || true
	done
}

case "${1}" in
	remove)
		Remove /var/cache/container-tools
		Remove /etc/container-tools/debconf
		Remove /etc/container-tools/config
		Remove /etc/container-tools/hooks
		Remove /etc/container-tools/keys
		Remove /var/lib/machines
		;;

	purge)
		rm -f /etc/default/container-tools
		;;

	upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

		;;

	*)
		echo "postrm called with unknown argument \`${1}'" >&2
		exit 1
		;;
esac

# Automatically added by dh_installsystemd/11.3.5
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.3.5
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'container-auto.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'container-auto.service' >/dev/null || true
		deb-systemd-helper unmask 'container-auto.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installdebconf/11.3.5
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


exit 0
