#!/bin/sh

set -e

case "${1}" in
	remove|upgrade|deconfigure)
		update-alternatives --quiet --remove container-tools_script /usr/share/container-tools/scripts/debootstrap
		update-alternatives --quiet --remove container-tools_script /usr/share/container-tools/scripts/curl
		update-alternatives --quiet --remove container-tools_script /usr/share/container-tools/scripts/progress-linux
		update-alternatives --quiet --remove container-tools_script /usr/share/container-tools/scripts/debian
		;;

	failed-upgrade)

		;;

	*)
		echo "prerm called with unknown argument \`${1}'" >&2
		exit 1
		;;
esac

# Automatically added by dh_installsystemd/11.3.5
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'container-auto.service' >/dev/null || true
fi
# End automatically added section


exit 0
