#!/bin/sh
set -e
# Automatically added by dh_installinit/12
if [ "$1" = "purge" ] ; then
	update-rc.d krb5-kpropd remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_systemd_enable/12
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'krb5-kpropd.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'krb5-kpropd.service' >/dev/null || true
		deb-systemd-helper unmask 'krb5-kpropd.service' >/dev/null || true
	fi
fi
# End automatically added section
