#! /bin/sh

set -e

if test "remove" = "$1"; then
    if which update-inetd >/dev/null 2>&1 ; then
	update-inetd --remove '#?krb5_prop.*/usr/sbin/kpropd'
    fi
fi

# Automatically added by dh_installinit/12
if [ -x "/etc/init.d/krb5-kpropd" ]; then
	invoke-rc.d krb5-kpropd stop || exit 1
fi
# End automatically added section


exit 0
