#!/bin/sh
set -e
# Automatically added by dh_installdeb
dpkg-maintscript-helper mv_conffile /etc/apache2/conf.d/horde.conf /etc/apache2/conf-available/php-horde.conf 5.1.0+debian0-1~ -- "$@"
# End automatically added section
