#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.3.2
dpkg-maintscript-helper rm_conffile /etc/dput.d/profiles/backports.json 1.9\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/dput-ng 1.19\~ -- "$@"
# End automatically added section
