#!/bin/sh
set -e

# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p spades /usr/share/spades
fi

if which pycompile >/dev/null 2>&1; then
	pycompile -p spades /usr/lib/spades
fi

# End automatically added section
