#!/bin/sh
set -e
# Automatically added by dh_installinit/10.10.8
if [ -x "/etc/init.d/gridengine-exec" ] && [ "$1" = remove ]; then
	invoke-rc.d gridengine-exec stop || exit $?
fi
# End automatically added section
