#!/bin/sh
set -e

case "$1" in
    install|upgrade)
        DOCDIR=/usr/share/doc/python-gpgme-dbg
        if [ -L $DOCDIR ]; then rm $DOCDIR; fi
    ;;

    abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac



exit 0
