#!/bin/sh
set -e

# Automatically added by dhpython:
if which pycompile >/dev/null 2>&1; then
	pycompile -p babiloo /usr/share/babiloo -V 2.5-
fi

# End automatically added section
# Automatically added by dh_installmenu
if [ "$1" = "configure" ] && [ -x "`which update-menus 2>/dev/null`" ]; then
	update-menus
fi
# End automatically added section
