#!/bin/sh
set -e
# Automatically added by dh_systemd_start/11.3.5
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'sssd-kcm.service' 'sssd-kcm.socket' >/dev/null || true
fi
# End automatically added section
