#!/bin/sh
set -e
# Automatically added by dh_installdeb/12
dpkg-maintscript-helper mv_conffile /etc/ownCloud/sync-exclude.lst /etc/owncloud-client/sync-exclude.lst 1.8.0\+dfsg-1\~ -- "$@"
# End automatically added section
