#!/bin/sh

set -e

dpkg-maintscript-helper mv_conffile /etc/memcachedb.conf /etc/memcachedb.d/default.conf 1.2.0-11 memcachedb -- "$@"

if [ "$1" = "configure" ]; then
    if ! getent passwd memcachedb >/dev/null; then
        adduser \
	    --quiet \
            --system \
            --disabled-login \
            --group \
            --home /var/lib/memcachedb \
	    --no-create-home \
            --gecos "Memcached Server" \
            --shell /bin/false \
            memcachedb
    fi

    if ! dpkg-statoverride --list /var/lib/memcachedb > /dev/null ; then
	dpkg-statoverride --update --add memcachedb memcachedb 755 /var/lib/memcachedb
    fi
fi

# Automatically added by dh_installinit/10.7.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/memcachedb" ]; then
		update-rc.d memcachedb defaults >/dev/null
		invoke-rc.d memcachedb start || exit $?
	fi
fi
# End automatically added section

