#!/bin/sh
set -e
# Automatically added by dh_installinit/11.1.5
if [ -x "/etc/init.d/gangliarc" ]; then
	invoke-rc.d gangliarc stop || exit 1
fi
# End automatically added section

# Automatically added by dh_python2:
if which pyclean >/dev/null 2>&1; then
	pyclean -p nordugrid-arc-gangliarc 
else
	dpkg -L nordugrid-arc-gangliarc | grep '\.py$' | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section
