#!/bin/sh
set -e
# $Id: rwhod.postinst,v 1.2 1999/11/12 22:13:05 herbert Exp $

if ! id -u rwhod >/dev/null 2>&1; then
	adduser --quiet --system --home /var/spool/rwho rwhod
fi
mkdir -p -m 755 /var/spool/rwho
chown -R rwhod /var/spool/rwho

# Automatically added by dh_installinit/11.5.3
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/rwhod" ]; then
		update-rc.d rwhod defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d rwhod $_dh_action || exit 1
	fi
fi
# End automatically added section

