#!/bin/sh
set -e
# $Id: rwhod.postrm,v 1.2 1999/11/12 04:58:48 herbert Exp $

if [ "$1" = purge ]; then
	if command -v userdel >/dev/null 2>&1; then
		userdel -r rwhod
	fi
fi

# Automatically added by dh_installinit/11.5.3
if [ "$1" = "purge" ] ; then
	update-rc.d rwhod remove >/dev/null
fi
# End automatically added section

