#!/bin/sh

set -e

VERSION=%VERSION%

case $1 in
    upgrade|remove|deconfigure)
	# Stop the Orthanc service before removal/upgrade
        # https://www.debian.org/doc/debian-policy/ch-opersys.html#s9.3.3.2
	if [ -x /etc/init.d/orthanc ]; then
            if which invoke-rc.d >/dev/null 2>&1; then
		invoke-rc.d orthanc stop
            else
		/etc/init.d/orthanc stop
            fi
        fi
	;;
    
    failed-upgrade)
	;;

    *)
	echo "prerm called with unknown argument \`$1'" >&2
	exit 1
	;;
esac

# Automatically added by dh_installinit/11.5.4
if [ -x "/etc/init.d/orthanc" ] && [ "$1" = remove ]; then
	invoke-rc.d orthanc stop || exit 1
fi
# End automatically added section

