#!/bin/sh

set -e

if [ "$1" = "purge" ] ; then
    rm -f /var/log/nova/nova-scheduler.log*
fi


# Automatically added by dh_installinit/10.10.9
if [ "$1" = "purge" ] ; then
	update-rc.d nova-scheduler remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/10.10.9
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'nova-scheduler.service' >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'nova-scheduler.service' >/dev/null
		deb-systemd-helper unmask 'nova-scheduler.service' >/dev/null
	fi
fi
# End automatically added section

