#!/bin/sh

set -e

# Remove configuration if package is being purged
if [ "$1" = "purge" ]; then
	rm -f /etc/miniupnpd/miniupnpd.conf
	rm -f /etc/default/miniupnpd
	if [ -e /etc/miniupnpd ] ; then
		rmdir --ignore-fail-on-non-empty /etc/miniupnpd || true
	fi
fi

# Automatically added by dh_installinit/10.9
if [ "$1" = "purge" ] ; then
	update-rc.d miniupnpd remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installdebconf/10.9
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


exit 0
