#!/bin/sh 

set -e

## The version in Woody had a now obsolete question about a defaults
## file.  We do not need that question anymore.
if dpkg --compare-versions 3.7-3 le-nl "$2"; then

    # Source debconf library, if present.
    if [ -e /usr/share/debconf/confmodule ]; then
        . /usr/share/debconf/confmodule    
        ## Remove all questions in the debconf database.
        db_purge
    fi

fi



exit 0
