#!/bin/sh
set -e

# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p totalopenstation 
fi

if which pycompile >/dev/null 2>&1; then
	pycompile -p totalopenstation /usr/share/totalopenstation
fi

# End automatically added section
