#!/bin/sh

set -e

if [ "$1" = "configure" ] ; then
	update-alternatives --install /usr/bin/reno reno /usr/bin/python2-reno 300
fi


# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p python-reno 
fi

# End automatically added section


exit 0
