#! /bin/sh
# postinst script for mailgraph
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package
#

. /usr/share/debconf/confmodule

DEFAULT="/usr/share/mailgraph/default.conf"

case "$1" in
    configure)

        tempfile=`mktemp`
        cp -p /usr/share/mailgraph/default.conf ${tempfile}

        # Merge debconf values into the configuration
        for foo in BOOT_START=start_on_boot MAIL_LOG=mail_log IGNORE_LOCALHOST=ignore_localhost; do
                db_get mailgraph/${foo#*=}
                sed -i -re "s@^(${foo%=*}=).*@\1\"${RET}\"@" "$tempfile"
        done

        ucf --debconf-ok ${tempfile} /etc/default/mailgraph
        ucfr mailgraph /etc/default/mailgraph
        rm -f ${tempfile}
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;

esac

# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/mailgraph" ]; then
		update-rc.d mailgraph defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d mailgraph $_dh_action || exit $?
	fi
fi
# End automatically added section


exit 0
