#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/guidedog" ]; then
		update-rc.d guidedog defaults >/dev/null
		invoke-rc.d guidedog start || exit $?
	fi
fi
# End automatically added section
# Automatically added by dh_icons
if which update-icon-caches >/dev/null 2>&1 ; then
	update-icon-caches /usr/share/icons/locolor
fi
# End automatically added section
