#!/bin/sh
set -e
# Automatically added by dh_installinit/11.1.4
if [ -x "/etc/init.d/prometheus-varnish-exporter" ]; then
	invoke-rc.d prometheus-varnish-exporter stop || exit 1
fi
# End automatically added section
