#!/bin/sh

set -e

if [ "$1" = "configure" ]; then
  if [ ! -h /opt/alljoyn ]; then
    # until all issues are resolved, this package needs
    # a link from /opt to the correct directory
    ln -s /usr/lib/alljoyn/opt/alljoyn /opt/alljoyn
  fi
fi

# Automatically added by dh_installinit/11.1.4
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/alljoyn-gateway-1504" ]; then
		update-rc.d alljoyn-gateway-1504 defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d alljoyn-gateway-1504 $_dh_action || exit 1
	fi
fi
# End automatically added section


exit 0
