#!/bin/sh

set -eu

rm -f /usr/lib/distcc/* 2>/dev/null || true

# Automatically added by dh_installinit/10.9.2
if [ -x "/etc/init.d/distcc" ]; then
	invoke-rc.d distcc stop || exit $?
fi
# End automatically added section

