#!/bin/sh

set -e

if [ "$1" = "purge" -a -e /usr/share/debconf/confmodule ]; then
    # Source debconf library.
    . /usr/share/debconf/confmodule
    # Remove my changes to the db.
    db_purge
    
    # Remove files in /etc/codeaster
    rm -f /etc/codeaster/asrun
    rm -f /etc/codeaster/aster    
    find /etc/codeaster  -type d -empty | xargs -r rmdir

fi

# Automatically added by dh_installdebconf/11.2.1
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

