#!/bin/sh
set -e
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/mediawiki-extensions/extensions-enabled/wikidiff2.php 1.4.1-1 -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/mediawiki-extensions/extensions-available/wikidiff2.php 1.4.1-1 -- "$@"
# End automatically added section
