#!/bin/sh
set -e
# Automatically added by dh_systemd_enable/10.8
if deb-systemd-helper debian-installed systemd-bootchart.service; then
	# This will only remove masks created by d-s-h on package removal.
	deb-systemd-helper unmask systemd-bootchart.service >/dev/null || true

	if deb-systemd-helper --quiet was-enabled systemd-bootchart.service; then
		# Create new symlinks, if any.
		deb-systemd-helper enable systemd-bootchart.service >/dev/null || true
	fi
fi

# Update the statefile to add new symlinks (if any), which need to be cleaned
# up on purge. Also remove old symlinks.
deb-systemd-helper update-state systemd-bootchart.service >/dev/null || true
# End automatically added section
# Automatically added by dh_systemd_start/10.8
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
	if [ -n "$2" ]; then
		_dh_action=try-restart
	else
		_dh_action=start
	fi
	deb-systemd-invoke $_dh_action systemd-bootchart.service >/dev/null || true
fi
# End automatically added section
