#!/bin/sh
set -e
# Automatically added by dh_systemd_start/10.8
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop systemd-bootchart.service >/dev/null
fi
# End automatically added section
