#!/bin/sh
set -e

# Automatically added by dh_systemd_enable
if deb-systemd-helper debian-installed docker-swarm.service; then
	# This will only remove masks created by d-s-h on package removal.
	deb-systemd-helper unmask docker-swarm.service >/dev/null || true

	if deb-systemd-helper --quiet was-enabled docker-swarm.service; then
		# Create new symlinks, if any.
		deb-systemd-helper enable docker-swarm.service >/dev/null || true
	fi
fi

# Update the statefile to add new symlinks (if any), which need to be cleaned
# up on purge. Also remove old symlinks.
deb-systemd-helper update-state docker-swarm.service >/dev/null || true
# End automatically added section
# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/docker-swarm" ]; then
		update-rc.d docker-swarm defaults >/dev/null || exit $?
	fi
fi
# End automatically added section


case "$1" in
    configure*)
        if [ -z "$2" ]; then
            ## First install; init script should be disabled by default.
            if [ -x "/etc/init.d/docker-swarm" ]; then
                update-rc.d docker-swarm disable >/dev/null || exit $?
            fi
        fi
    ;;
esac
