#!/bin/sh
# -*- shell-script -*-
set -e

if [ "$1" = "purge" -a -r /etc/printcap ]; then
  FILTERS=`awk -F[:=] '/[[:space:]]*:if=.*/ { print $3 }' /etc/printcap`

  if [ -n "$FILTERS" ]; then
    cat 1>&2 <<-EOI
	The following input filters are installed at the moment:
EOI
    echo $FILTERS|tr ' ' '\n' 1>&2
    cat 1>&2 <<-EOI

	If any of these filters were input filters from the magicfilter
	package, you have now inoperable input filters and cannot print
	on some or all printer queues.
EOI
  fi
fi

if test -x /usr/bin/update-menus; then
  update-menus
fi

if [ "$1" = purge -a -e /usr/share/debconf/confmodule ]; then
        . /usr/share/debconf/confmodule
        db_purge
fi

exit 0
