#!/bin/sh -e

# Initialize debconf if not yet done
if [ _"$DEBCONF_REDIR" = _"" ]; then
    . /usr/share/debconf/confmodule
    db_version 2.0
    db_capb backup
fi

db_input "medium" "shared/med-config/useusermenus" || true
db_go
db_get shared/med-config/useusermenus
if [ $RET ] ; then
    db_input "medium" "shared/med-config/usermenus" || true
    db_go
fi

# if blends.config package is not yet installed we have to stop here
if [ ! -f /etc/blends/blends.conf ] ; then
   db_stop
   exit 0
fi

[ -s /etc/blends/blends.conf ]         && . /etc/blends/blends.conf
[ -s /etc/blends/med/med.conf ] && . /etc/blends/med/med.conf

# Add at least one default role for each Blend
addRole med med

# Login names of all users of the system as comma separated list 
USERS=`getAllUsers 0 ,`

# "login (Real Name)" of users registered to the Debian Pure Blend med
BLENDUSERS=`getUsersInRole med med 0 ,`

db_set med-config/group "$BLENDUSERS"
db_subst med-config/group users "$USERS"
db_get med-config/group

db_input high med-config/group || true
db_go

db_stop

if [ -d /etc/blends/med/ ] ; then 
    if [ ! -f /etc/blends/med/med.conf ] ; then 
        # Due to a bug in blends-common the real Blend config file was moved to med.conf~.  This is fixed here
        if [ -f /etc/blends/med/med.conf~ ] ; then
            cp -a /etc/blends/med/med.conf~ /etc/blends/med/med.conf
        fi
    fi
fi
                
exit 0
