#!/bin/sh

set -e

# Automatically added by dh_installinit/11.3.5
if [ "$1" = "purge" ] ; then
	update-rc.d nordugrid-arc-egiis remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section


if [ "$1" = "purge" ] ; then
    APP_PROFILE=/etc/apparmor.d/usr.sbin.slapd
    LOCAL_APP_PROFILE=/etc/apparmor.d/local/usr.sbin.slapd

    if [ -r "$LOCAL_APP_PROFILE" ] ; then
	sed '/# AppArmor profile for NorduGrid ARC EGIIS START/,/# AppArmor profile for NorduGrid ARC EGIIS END/d' -i "$LOCAL_APP_PROFILE"
    fi

    if [ ! -r "$APP_PROFILE" ] ; then
	if [ -r "$LOCAL_APP_PROFILE" ] ; then
	    if [ -z "`sed '/^#/d' $LOCAL_APP_PROFILE`" ] ; then
		rm -f "$LOCAL_APP_PROFILE" || true
	    fi
	fi
	rmdir /etc/apparmor.d/local 2>/dev/null || true
	rmdir /etc/apparmor.d 2>/dev/null || true
    fi

    if [ -r "$APP_PROFILE" ] ; then
	# Reload the profile
	if aa-status --enabled 2>/dev/null ; then
            apparmor_parser -r -T -W "$APP_PROFILE" || true
	fi
    fi
fi

dpkg-maintscript-helper rm_conffile /etc/default/nordugrid-arc-egiis 5.4.2-2 -- "$@"
