#!/bin/sh

set -e

if [ "${1}" = "remove" ] || [ "${1}" = "upgrade" ] || [ "${1}" = "deconfigure" ] ; then
	update-alternatives --remove puppet-module-designate /usr/share/puppet/modules.available/designate
fi



exit 0
