#!/bin/sh
set -e
# Automatically added by dh_installinit/11.5.4
if [ "$1" = "purge" ] ; then
	update-rc.d corosync-notifyd remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdeb/11.5.4
dpkg-maintscript-helper rm_conffile /etc/init/corosync-notifyd.conf 2.4.3-1\~ -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/11.5.4
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'corosync-notifyd.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'corosync-notifyd.service' >/dev/null || true
		deb-systemd-helper unmask 'corosync-notifyd.service' >/dev/null || true
	fi
fi
# End automatically added section
