#!/bin/sh
set -e
# Automatically added by dh_systemd_start/11.3.2
if [ -d /run/systemd/system ]; then
	deb-systemd-invoke stop 'zfs-zed.service' >/dev/null || true
fi
# End automatically added section
