#!/bin/sh

set -e

case "$1" in
 purge)
   rm -f /var/games/xjump/record
 ;;
esac

# Automatically added by dh_installmenu
if [ -x "`which update-menus 2>/dev/null`" ]; then update-menus ; fi
# End automatically added section

