#!/bin/sh

set -e

if [ "$1" = "remove" ] || [ "$1" = "disappear" ] ; then
	update-alternatives --remove pecan /usr/bin/python2-pecan
	update-alternatives --remove gunicorn_pecan /usr/bin/python2-gunicorn_pecan
fi



exit 0
