#!/bin/sh
set -e
# Automatically added by dh_installinit/10.9
if [ -x "/etc/init.d/kexec-load" ] && [ "$1" = remove ]; then
	invoke-rc.d kexec-load stop || exit $?
fi
# End automatically added section
# Automatically added by dh_installinit/10.9
if [ -x "/etc/init.d/kexec" ] && [ "$1" = remove ]; then
	invoke-rc.d kexec stop || exit $?
fi
# End automatically added section
