#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ru/ddg.xml 45.0esr-2~ iceweasel-l10n-ru -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ru/google.xml 45.0esr-2~ iceweasel-l10n-ru -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ru/mailru.xml 45.0esr-2~ iceweasel-l10n-ru -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ru/ozonru.xml 45.0esr-2~ iceweasel-l10n-ru -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ru/priceru.xml 45.0esr-2~ iceweasel-l10n-ru -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ru/wikipedia-ru.xml 45.0esr-2~ iceweasel-l10n-ru -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ru/yandex-slovari.xml 45.0esr-2~ iceweasel-l10n-ru -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ru/yandex.xml 45.0esr-2~ iceweasel-l10n-ru -- "$@"
# End automatically added section
