#!/bin/sh
set -e
# Automatically added by dh_apparmor
if [ "$1" = "purge" ] && ! [ -e "/etc/apparmor.d/usr.sbin.fwknopd" ] ; then
    rm -f "/etc/apparmor.d/disable/usr.sbin.fwknopd" || true
    rm -f "/etc/apparmor.d/force-complain/usr.sbin.fwknopd" || true
    rm -f "/etc/apparmor.d/local/usr.sbin.fwknopd" || true
    rmdir /etc/apparmor.d/disable 2>/dev/null || true
    rmdir /etc/apparmor.d/local   2>/dev/null || true
    rmdir /etc/apparmor.d         2>/dev/null || true
fi
# End automatically added section
