#! /bin/sh

set -e

if [ "$1" = purge ]; then
    rm -rf /etc/X11/sawfish 2>/dev/null || true
    rm -rf /var/lib/sawfish 2>/dev/null || true
fi

# Automatically added by dh_installdeb/11.1.2
dpkg-maintscript-helper symlink_to_dir /usr/share/doc/sawfish /usr/share/doc/sawfish-data 1:1.11-1~ -- "$@"
# End automatically added section
# Automatically added by dh_installmenu/11.1.2
inst=/etc/menu-methods/sawfish
if [ "$1" = "remove" ] && [ -f "$inst" ]; then chmod a-x $inst ; fi
if [ -x "`which update-menus 2>/dev/null`" ]; then update-menus ; fi
# End automatically added section


exit 0
