#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.4
dpkg-maintscript-helper mv_conffile /etc/apache2/sites-available/default-tls /etc/apache2/sites-available/default-tls.conf -- "$@"
# End automatically added section
# Automatically added by dh_apache2/UNDECLARED
if [ "$1" = "purge" ] ; then
	if true; then
		if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
			. /usr/share/apache2/apache2-maintscript-helper

			for conf in gnutls  ; do
				apache2_invoke dismod $conf  || exit 1
			done
		fi
	fi
fi
# End automatically added section
