#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.5
dpkg-maintscript-helper rm_conffile /etc/init.d/cloudprintd 0.12-3\~ -- "$@"
# End automatically added section
# Automatically added by dh_systemd_start/11.5
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'cloudprintd.service' >/dev/null || true
fi
# End automatically added section
