#!/bin/sh

set -e

if [ "$1" = "remove" ] ; then
	update-alternatives --remove gnocchi /usr/bin/python2-gnocchi
fi


# Automatically added by dh_python2:
if which pyclean >/dev/null 2>&1; then
	pyclean -p python-gnocchiclient 
else
	dpkg -L python-gnocchiclient | grep '\.py$' | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section


exit 0
