#!/bin/sh

set -e

case "$1" in
    purge)
        rm -fr /var/log/zabbix-server
        rm -fr /var/run/zabbix
        rm -fr /etc/zabbix/alert.d
    ;;
esac

# Automatically added by dh_installinit/11.5.4
if [ "$1" = "purge" ] ; then
	update-rc.d zabbix-server remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdeb/11.5.4
dpkg-maintscript-helper rm_conffile /etc/default/zabbix-server 1:2.2.7\+dfsg-2\~ -- "$@"
# End automatically added section
# Automatically added by dh_ucf/11.5.4
if [ "$1" = "purge" ]; then
	for ext in .ucf-new .ucf-old .ucf-dist ""; do
		rm -f "/etc/sudoers.d/zabbix$ext"
	done
	
	if [ -x "`which ucf 2>/dev/null`" ]; then
		ucf --purge "/etc/sudoers.d/zabbix"
	fi
	if [ -x "`which ucfr 2>/dev/null`" ]; then
		ucfr --purge zabbix-server-pgsql "/etc/sudoers.d/zabbix"
	fi
fi
# End automatically added section
# Automatically added by dh_ucf/11.5.4
if [ "$1" = "purge" ]; then
	for ext in .ucf-new .ucf-old .ucf-dist ""; do
		rm -f "/etc/zabbix/zabbix_server.conf$ext"
	done
	
	if [ -x "`which ucf 2>/dev/null`" ]; then
		ucf --purge "/etc/zabbix/zabbix_server.conf"
	fi
	if [ -x "`which ucfr 2>/dev/null`" ]; then
		ucfr --purge zabbix-server-pgsql "/etc/zabbix/zabbix_server.conf"
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.5.4
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'zabbix-server.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'zabbix-server.service' >/dev/null || true
		deb-systemd-helper unmask 'zabbix-server.service' >/dev/null || true
	fi
fi
# End automatically added section

