#!/bin/sh
# See /usr/share/debhelper/dh_make/debian/postinst.ex
set -e

ike_error() {
	true
}

# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/ike" ]; then
		update-rc.d ike defaults >/dev/null
		invoke-rc.d ike start || ike_error
	fi
fi
# End automatically added section


exit 0
