#!/bin/sh

set -e

if [ "${1}" = "remove" ] || [ "${1}" = "upgrade" ] ; then
	# Remove traces of plugins
	rm -rf /var/lib/rabbitmq/plugins-scratch
fi

if [ "${1}" = "purge" ] ; then
	rm -f /etc/default/rabbitmq
	if [ -d /var/lib/rabbitmq ]; then
		rm -rf /var/lib/rabbitmq
	fi
	if [ -d /var/log/rabbitmq ]; then
		rm -rf /var/log/rabbitmq
	fi
	if [ -d /etc/rabbitmq ]; then
		rm -rf /etc/rabbitmq
	fi

	if getent passwd rabbitmq >/dev/null; then
		# Stop epmd if run by the rabbitmq user
		pkill -u rabbitmq epmd || :
	fi
fi

# Automatically added by dh_installinit/11.5
if [ "$1" = "purge" ] ; then
	update-rc.d rabbitmq-server remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_systemd_enable/11.5
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'rabbitmq-server.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'rabbitmq-server.service' >/dev/null || true
		deb-systemd-helper unmask 'rabbitmq-server.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
