#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/farpd" ]; then
		update-rc.d farpd stop 20 0 6 . >/dev/null || exit $?
	fi
fi
# End automatically added section
