#!/bin/sh

set -e

if [ "$1" = "purge" ] ; then
	if [ -r /usr/share/debconf/confmodule ] ; then
		. /usr/share/debconf/confmodule
		db_get nova/configure_db || true
		if [ "$RET" = "true" ] ; then
			if [ -f /usr/share/dbconfig-common/dpkg/postrm ] ; then
				. /usr/share/dbconfig-common/dpkg/postrm
				dbc_go nova-api $@
			else
				rm -f /etc/dbconfig-common/nova-api.conf
				if which ucf >/dev/null 2>&1; then
					ucf --purge /etc/dbconfig-common/nova-api.conf
					ucfr --purge nova-api /etc/dbconfig-common/nova-api.conf
				fi
			fi
		fi
	fi

	rm -f /var/log/nova/nova-api.log*
fi


# Automatically added by dh_installinit/11.3.5
if [ "$1" = "purge" ] ; then
	update-rc.d nova-api remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/11.3.5
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'nova-api.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'nova-api.service' >/dev/null || true
		deb-systemd-helper unmask 'nova-api.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installdebconf/11.3.5
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

