#!/bin/bash

set -e

dpkg-maintscript-helper rm_conffile \
	/etc/nftables/bridge-filter \
	0.5+snapshot20151106-1 nftables -- "$@"

dpkg-maintscript-helper rm_conffile \
	/etc/nftables/inet-filter \
	0.5+snapshot20151106-1 nftables -- "$@"

dpkg-maintscript-helper rm_conffile \
	/etc/nftables/ipv4-filter \
	0.5+snapshot20151106-1 nftables -- "$@"

dpkg-maintscript-helper rm_conffile \
	/etc/nftables/ipv4-mangle \
	0.5+snapshot20151106-1 nftables -- "$@"

dpkg-maintscript-helper rm_conffile \
	/etc/nftables/ipv4-nat \
	0.5+snapshot20151106-1 nftables -- "$@"

dpkg-maintscript-helper rm_conffile \
	/etc/nftables/ipv6-filter \
	0.5+snapshot20151106-1 nftables -- "$@"

dpkg-maintscript-helper rm_conffile \
	/etc/nftables/ipv6-mangle \
	0.5+snapshot20151106-1 nftables -- "$@"

dpkg-maintscript-helper rm_conffile \
	/etc/nftables/ipv6-nat \
	0.5+snapshot20151106-1 nftables -- "$@"

dpkg-maintscript-helper rm_conffile \
	/etc/init.d/nftables \
	0.6-1~ nftables -- "$@"

# Automatically added by dh_systemd_start/10.10.9
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/10.10.9
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'nftables.service' >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'nftables.service' >/dev/null
		deb-systemd-helper unmask 'nftables.service' >/dev/null
	fi
fi
# End automatically added section

