#!/bin/sh
set -e

if [ "$1" != "upgrade" ]; then
  update-alternatives --remove breathe-apidoc /usr/bin/python2-breathe-apidoc
fi

# Automatically added by dh_python2:
if which pyclean >/dev/null 2>&1; then
	pyclean -p python-breathe 
else
	dpkg -L python-breathe | grep '\.py$' | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section

