#!/bin/sh

set -e

if [ -f /usr/share/debconf/confmodule ]; then
        . /usr/share/debconf/confmodule
fi
if [ -f /usr/share/dbconfig-common/dpkg/postrm ]; then
        . /usr/share/dbconfig-common/dpkg/postrm
        dbc_go pnopaste $@
fi

case "$1" in
        purge)
                rm -f /etc/pnopaste/debiandb.pm
				if [ -x /usr/bin/ucf ]; then
	                ucf --debconf-ok --purge /etc/pnopaste/debiandb.pm
				fi
				if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
					. /usr/share/apache2/apache2-maintscript-helper
					apache2_invoke disconf pnopaste.conf
				fi
        ;;
        remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;
        *)
                echo "postrm called with unknown argument \`$1'" >&2
                exit 1
esac

# Automatically added by dh_installdebconf
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


exit 0
