#! /bin/sh

set -e

# Remove /var/lib/webkdc/keyring on purge and try to remove the directory.
if [ "$1" = purge ] ; then
    rm -f /var/lib/webkdc/keyring
    rmdir --ignore-fail-on-non-empty /var/lib/webkdc
fi

# Automatically added by dh_apache2
if [ "$1" = "purge" ] ; then
	if true; then
		if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
			. /usr/share/apache2/apache2-maintscript-helper

			for conf in webkdc  ; do
				apache2_invoke dismod $conf  || exit $?
			done
		fi
	fi
fi
# End automatically added section


exit 0
