#!/bin/sh -e 

. /usr/share/debconf/confmodule

# set -x

if [ "$1" = "configure" ]; then

  db_get inorwegian/whichvariant || true
  if [ "$RET" ]; then
    cd /usr/lib/ispell
    ln -f -s "$RET.hash" norsk.hash
    ln -f -s "$RET.aff" norsk.aff
  fi
fi

# Automatically added by installdeb-ispell/UNDECLARED
. /usr/share/debconf/confmodule
SCRIPT="update-default-ispell"

if [ "$1" = "configure" ] ; then
    if which $SCRIPT > /dev/null 2>&1; then
	$SCRIPT  --rebuild
    else
	echo "Error: $SCRIPT not present or executable. Missing dependency on dictionaries-common?" >&2
	exit 1
    fi
fi
# End automatically added section

