#!/bin/sh
# postinst script for jclic
#

set -e
case "$1" in
    configure)
	# Initializing edu.xtec.jclic node in Java system preferences
	jclic-libmanager -list -silent
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac



exit 0

