#!/bin/sh
set -e
# Automatically added by dh_installwm
if [ "$1" = "remove" ]; then
	update-alternatives --remove x-window-manager /usr/bin/wmii
fi
# End automatically added section

# Automatically added by dh_python2:
if which pyclean >/dev/null 2>&1; then
	pyclean -p wmii 
else
	dpkg -L wmii | grep \.py$ | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section
