#!/bin/sh
set -e
# Automatically added by dh_systemd_enable
# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask ptp4l.service >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled ptp4l.service; then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable ptp4l.service >/dev/null || true
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state ptp4l.service >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable
if deb-systemd-helper debian-installed phc2sys.service; then
	# This will only remove masks created by d-s-h on package removal.
	deb-systemd-helper unmask phc2sys.service >/dev/null || true

	if deb-systemd-helper --quiet was-enabled phc2sys.service; then
		# Create new symlinks, if any.
		deb-systemd-helper enable phc2sys.service >/dev/null || true
	fi
fi

# Update the statefile to add new symlinks (if any), which need to be cleaned
# up on purge. Also remove old symlinks.
deb-systemd-helper update-state phc2sys.service >/dev/null || true
# End automatically added section
# Automatically added by dh_systemd_enable
if deb-systemd-helper debian-installed timemaster.service; then
	# This will only remove masks created by d-s-h on package removal.
	deb-systemd-helper unmask timemaster.service >/dev/null || true

	if deb-systemd-helper --quiet was-enabled timemaster.service; then
		# Create new symlinks, if any.
		deb-systemd-helper enable timemaster.service >/dev/null || true
	fi
fi

# Update the statefile to add new symlinks (if any), which need to be cleaned
# up on purge. Also remove old symlinks.
deb-systemd-helper update-state timemaster.service >/dev/null || true
# End automatically added section
# Automatically added by dh_systemd_start
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
	deb-systemd-invoke start ptp4l.service >/dev/null || true
fi
# End automatically added section
