#!/bin/sh

set -e

case "$1" in
    remove|deconfigure)
	rm -rf /var/lib/casacore/data/geodetic/TAI_UTC
	rmdir -p --ignore-fail-on-non-empty /var/lib/casacore/data/geodetic/
	;;
    failed-upgrade|upgrade)
	;;
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac


