#!/bin/sh -e
# 
# Postinst file for ccal



set -e

case "$1" in
    configure)
    # Move a conffile without triggering a dpkg question
        if [ -e /etc/calcol ] && dpkg-maintscript-helper supports mv_conffile; then
            dpkg-maintscript-helper mv_conffile \
                /etc/calcol /etc/cal.col 3.5-7 ccal -- "$@"
        fi
         ;;
     abort-upgrade|abort-remove|abort-deconfigure)
         ;;
     *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

# Automatically added by dh_installmenu/11.5.3
if [ "$1" = "configure" ] && [ -x "`which update-menus 2>/dev/null`" ]; then
	update-menus
fi
# End automatically added section



exit 0
