#!/bin/sh
set -e
# Automatically added by dh_installxmlcatalogs
if [ "$1" = "configure" ]; then
	update-xmlcatalog --add --type system --id "http://www.oasis-open.org/docbook/xml/mathml/" --package docbook-mathml --local /usr/share/xml/docbook/custom/mathml/catalog.xml
	update-xmlcatalog --add --type public --id "-//OASIS//DTD DocBook MathML//EN" --package docbook-mathml --local /usr/share/xml/docbook/custom/mathml/catalog.xml
	update-xmlcatalog --add --type system --id "http://www.oasis-open.org/docbook/xml/mathml/1.0/dbmathml.dtd" --package docbook-mathml --local /usr/share/xml/docbook/custom/mathml/1.0/catalog.xml
	update-xmlcatalog --add --type public --id "-//OASIS//DTD DocBook MathML Module V1.0//EN" --package docbook-mathml --local /usr/share/xml/docbook/custom/mathml/1.0/catalog.xml
	update-xmlcatalog --add --type system --id "http://www.oasis-open.org/docbook/xml/mathml/1.1b1/dbmathml.dtd" --package docbook-mathml --local /usr/share/xml/docbook/custom/mathml/1.1b1/catalog.xml
	update-xmlcatalog --add --type public --id "-//OASIS//DTD DocBook MathML Module V1.1b1//EN" --package docbook-mathml --local /usr/share/xml/docbook/custom/mathml/1.1b1/catalog.xml
	update-xmlcatalog --add --type system --id "http://www.oasis-open.org/docbook/xml/mathml/1.1CR1/dbmathml.dtd" --package docbook-mathml --local /usr/share/xml/docbook/custom/mathml/1.1CR1/catalog.xml
	update-xmlcatalog --add --type public --id "-//OASIS//DTD DocBook MathML Module V1.1CR1//EN" --package docbook-mathml --local /usr/share/xml/docbook/custom/mathml/1.1CR1/catalog.xml

	update-xmlcatalog --add --type system --id "http://www.oasis-open.org/docbook/xml/mathml/" --package docbook-mathml --root
	update-xmlcatalog --add --type public --id "-//OASIS//DTD DocBook MathML" --package docbook-mathml --root

fi
# End automatically added section
