#!/bin/sh -e

DAEMON_USER="prelude-correlator"

if [ "$1" = "purge" ]
then
    deluser $DAEMON_USER || true
fi

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d prelude-correlator remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section


exit 0

