#!/bin/sh
set -e

# Automatically added by dhpython:
if which pyclean >/dev/null 2>&1; then
	pyclean -p prelude-correlator 
else
	dpkg -L prelude-correlator | grep \.py$ | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/prelude-correlator" ]; then
	invoke-rc.d prelude-correlator stop || exit $?
fi
# End automatically added section
