#!/bin/sh
set -e

if [ "$1" = "remove" ]; then
	update-alternatives --remove x-www-browser /usr/bin/uzbl-browser
fi


# Automatically added by dhpython:
if which pyclean >/dev/null 2>&1; then
	pyclean -p uzbl 
else
	dpkg -L uzbl | grep \.py$ | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section

