#!/bin/sh
set -e

if [ "$1" = "configure" ]; then
    update-alternatives \
    --install /usr/bin/php php /usr/bin/hhvm 40 \
    --slave /usr/share/man/man1/php.1.gz php.1.gz /usr/share/man/man1/hhvm.1.gz
fi

# Automatically added by dh_installinit/10.9
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/hhvm" ]; then
		update-rc.d hhvm defaults >/dev/null
		invoke-rc.d hhvm start || exit $?
	fi
fi
# End automatically added section

