#!/bin/sh
# postinst script for denyhosts

set -e

libdir=/var/lib/denyhosts/

touch /var/log/denyhosts
chmod 640 /var/log/denyhosts
chmod 640 /etc/denyhosts.conf
test -d $libdir || mkdir $libdir
chmod 750 $libdir


# Automatically added by dhpython:
if which pycompile >/dev/null 2>&1; then
	pycompile -p denyhosts /usr/share/denyhosts
fi

# End automatically added section
# Automatically added by dh_systemd_enable
# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask denyhosts.service >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled denyhosts.service; then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable denyhosts.service >/dev/null || true
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state denyhosts.service >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/denyhosts" ]; then
	update-rc.d denyhosts defaults >/dev/null
	invoke-rc.d denyhosts start || exit $?
fi
# End automatically added section


exit 0
