#!/bin/sh

set -e

case "$1" in
	purge)
		if getent passwd|grep -q ^muroard: ; then
			userdel muroard > /dev/null 2>&1 || true
		fi
		rm -rf /var/lib/muroard
	;;
	remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	;;
	*)
		echo "postrm called with unknown argument \`$1'" >&2
		exit 1
esac

# Automatically added by dh_installinit/11.4.1
if [ "$1" = "purge" ] ; then
	update-rc.d muroard remove >/dev/null
fi
# End automatically added section


exit 0
