#!/bin/sh -e

DEB_HOST_MULTIARCH=x86_64-linux-gnu
SLEPC_VERSION=3.8.3
SONAME=3.8

# Remove alternatives links
if [ "$1" = "remove" ]; then
  update-alternatives --remove libslepc.so.${SONAME} /usr/lib/${DEB_HOST_MULTIARCH}/libslepc_complex.so.${SLEPC_VERSION}
fi


