#! /bin/sh
set -e

if [ x != x"`command -v dpkg-statoverride`" ]; then
  if dpkg-statoverride --list /usr/bin/imget >/dev/null ; then
    dpkg-statoverride --remove /usr/bin/imget
  fi
fi

if [ "$1" = "purge" ]; then
  rm -f /etc/im/SiteConfig*
  if [ -d /etc/im ]; then
    rmdir --ignore-fail-on-non-empty /etc/im
  fi
fi

# Automatically added by dh_installdebconf/11.3.2
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

