#!/bin/sh

set -e

MCOLLECTIVE_SERVER_CFG="/etc/mcollective/server.cfg"

case "$1" in
	purge)
		if [ -e "$MCOLLECTIVE_SERVER_CFG" ]; then
			rm -rf $MCOLLECTIVE_SERVER_CFG
			rmdir --ignore-fail-on-non-empty /etc/mcollective
		fi

	;;
	upgrade|failed-upgrade|abort-install|abort-upgrade|disappear|remove)
	;;
	*)
		echo "postrm called with unknown argument \`${1}'" >&2
		exit 1
	;;
esac

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d mcollective remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask mcollective.service >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge mcollective.service >/dev/null
		deb-systemd-helper unmask mcollective.service >/dev/null
	fi
fi
# End automatically added section


exit 0
