#!/bin/sh

set -e

if [ "${1}" = "remove" ] || [ "${1}" = "upgrade" ] || [ "${1}" = "deconfigure" ] ; then
	update-alternatives --remove puppet-module-rsync /usr/share/puppet/modules.available/puppetlabs-rsync
fi



exit 0
