#!/bin/sh
set -e
# Automatically added by dh_installinit/11.3.5
if [ -x "/etc/init.d/nova-placement-api" ] && [ "$1" = remove ]; then
	invoke-rc.d nova-placement-api stop || true
fi
# End automatically added section
