#!/bin/sh

set -e

# If /tmp/ZABBIX_PACKAGE_DEBUG file exists then enable debugging of this script.
#if [ -e /tmp/ZABBIX_PACKAGE_DEBUG ]; then
#    set -x
#fi

if [ "$1" = "configure" ]; then
    # Does the user 'zabbix' exist?
    if ! getent passwd zabbix > /dev/null 2>&1 ; then
        # Not yet. Create it.
        adduser --quiet --system --group --disabled-login --no-create-home --home /nonexistent zabbix
    fi

    chown zabbix:zabbix /var/log/zabbix-proxy -R
fi

# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	# In case this system is running systemd, we need to ensure that all
	# necessary tmpfiles (if any) are created before starting.
	if [ -d /run/systemd/system ] ; then
		systemd-tmpfiles --create /usr/lib/tmpfiles.d/zabbix-proxy.conf >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/zabbix-proxy" ]; then
		update-rc.d zabbix-proxy defaults >/dev/null || exit $?
	fi
fi
# End automatically added section
# Automatically added by dh_ucf
if [ "$1" = "configure" ]; then
	ucf "/usr/share/zabbix-proxy-mysql/zabbix_proxy.conf" "/etc/zabbix/zabbix_proxy.conf"
	ucfr zabbix-proxy-mysql "/etc/zabbix/zabbix_proxy.conf"
fi
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/default/zabbix-proxy 1:2.2.7+dfsg-2~ -- "$@"
# End automatically added section

