#!/bin/sh
set -e
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/guestfish 1:1.20.6-2\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/guestfish-bash-completion.sh 1.21.31-1\~ -- "$@"
# End automatically added section
