#! /bin/sh -e

init_failed ()
{
        echo "WARNING: Stopping dansguardian failed! Upgrade or removal may be incomplete!" 
}

# Automatically added by dh_installinit
if [ -x "/etc/init.d/dansguardian" ]; then
	invoke-rc.d dansguardian stop || init_failed
fi
# End automatically added section

