#!/bin/sh
set -e
# Automatically added by dh_installdeb
dpkg-maintscript-helper symlink_to_dir /usr/share/doc/libmongo-client-doc /usr/share/doc/libmongo-client0 0.1.8-2.1~ -- "$@"
# End automatically added section
