#!/bin/sh
# prerm script for koules
#
# see: dh_installdeb(1)

set -e

case "$1" in
    remove|upgrade|deconfigure)
    if [ -L /usr/doc/koules ]; then
        rm -f /usr/doc/koules
    fi

        ;;
    failed-upgrade)
        ;;
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac



exit 0


