#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.3.2
dpkg-maintscript-helper symlink_to_dir /usr/share/doc/lemonldap-ng-doc/pages/documentation/current 1.3 1.9.7-3\~ -- "$@"
# End automatically added section
