#! /bin/sh
# postrm script for hobbit
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postrm> `remove'
#        * <postrm> `purge'
#        * <old-postrm> `upgrade' <new-version>
#        * <new-postrm> `failed-upgrade' <old-version>
#        * <new-postrm> `abort-install'
#        * <new-postrm> `abort-install' <old-version>
#        * <new-postrm> `abort-upgrade' <old-version>
#        * <disappearer's-postrm> `disappear' <r>overwrit>r> <new-version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

# Workaround for http://bugs.debian.org/560317 in case debconf is too old like on Squeeze
export DPKG_MAINTSCRIPT_PACKAGE=${DPKG_MAINTSCRIPT_PACKAGE:-xymon-client}
export DPKG_MAINTSCRIPT_NAME=${DPKG_MAINTSCRIPT_NAME:-postrm}

# Before deluser so debconf still works
# Automatically added by dh_installinit/11.1.2
if [ "$1" = "purge" ] ; then
	update-rc.d xymon-client remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installdeb/11.1.2
dpkg-maintscript-helper mv_conffile /etc/init.d/hobbit-client /etc/init.d/xymon-client 4.3.7-1\~\~ xymon-client -- "$@"
dpkg-maintscript-helper mv_conffile /etc/logrotate.d/hobbit-client /etc/logrotate.d/xymon-client 4.3.7-1\~\~ xymon-client -- "$@"
dpkg-maintscript-helper mv_conffile /etc/hobbit/localclient.cfg /etc/xymon/localclient.cfg 4.3.7-1\~\~ xymon-client -- "$@"
dpkg-maintscript-helper mv_conffile /etc/hobbit/hobbitclient.cfg /etc/xymon/xymonclient.cfg 4.3.7-1\~\~ xymon-client -- "$@"
dpkg-maintscript-helper mv_conffile /etc/hobbit/clientlaunch.cfg /etc/xymon/clientlaunch.cfg 4.3.7-1\~\~ xymon-client -- "$@"
# End automatically added section
# Automatically added by dh_installdebconf/11.1.2
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


case "$1" in
	purge|disappear)
	rm -rf /var/lib/hobbit /var/log/hobbit /var/run/hobbit /etc/hobbit \
		/etc/default/hobbit-client /var/lib/xymon /var/log/xymon \
		/var/run/xymon /etc/xymon /etc/default/xymon-client
	if test -x /usr/sbin/deluser ; then
		deluser hobbit || true
		deluser xymon || true
	fi
	if test -x /usr/sbin/delgroup ; then
		delgroup --only-if-empty hobbit || true
		delgroup --only-if-empty xymon || true
	fi
	;;

	remove|upgrade|failed-upgrade|abort-install|abort-upgrade)
	;;

	*)
	echo "postrm called with unknown argument \`$1'" >&2
	exit 1
	;;
esac

exit 0
