#!/bin/sh
set -e

# Automatically added by dh_python2:
# make sure python-central files are removed before new package is installed
if [ "$1" = upgrade ] && [ -f /var/lib/pycentral/keymapper.pkgremove ]
then
	pycentral pkgremove keymapper
	rm -f /var/lib/pycentral/keymapper.pkgremove
fi

# End automatically added section
