#!/bin/sh
set -e
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/apt/trusted.gpg.d/debian-ports-archive-2015.gpg 2016.01.25~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/apt/trusted.gpg.d/debian-ports-archive-2014.gpg 2016.01.25~ -- "$@"
# End automatically added section
