#!/bin/sh
set -e
# Automatically added by dh_dkms/UNDECLARED
DKMS_NAME=v4l2loopback
DKMS_VERSION=0.12.0

case "$1" in
    remove|upgrade|deconfigure)
      if [  "$(dkms status -m $DKMS_NAME -v $DKMS_VERSION)" ]; then
         dkms remove -m $DKMS_NAME -v $DKMS_VERSION --all
      fi
    ;;
esac
# End automatically added section
