#!/bin/sh
set -e
# Automatically added by dh_sysuser/UNDECLARED
# -*- sh -*-
# -*- sh -*-
export CONF_HOME=/var/spool/cron
export CONF_PACKAGE=bcron-run
export CONF_USERNAME=cron

/lib/sysuser-helper/sysuser-helper postinst "$@"
# End automatically added section
# Automatically added by dh_runit/UNDECLARED
# -*- shell-script -*-
export NAME='bcron-sched'
export ENABLE='yes'

# Unlike postrm, I can be sure, that runit-helper is present on
# postinst.
/lib/runit-helper/runit-helper postinst "$@"

# Local Variables:
# eval: (sh-set-shell "sh" t nil)
# End:
# vim: ft=sh:sw=4
# End automatically added section
# Automatically added by dh_sysuser/UNDECLARED
# -*- sh -*-
# -*- sh -*-
export CONF_HOME=/nonexistent
export CONF_PACKAGE=bcron-run
export CONF_USERNAME=_log-bcron-sched

/lib/sysuser-helper/sysuser-helper postinst "$@"
# End automatically added section
# Automatically added by dh_runit/UNDECLARED
# -*- shell-script -*-
export NAME='bcron-spool'
export ENABLE='yes'

# Unlike postrm, I can be sure, that runit-helper is present on
# postinst.
/lib/runit-helper/runit-helper postinst "$@"

# Local Variables:
# eval: (sh-set-shell "sh" t nil)
# End:
# vim: ft=sh:sw=4
# End automatically added section
# Automatically added by dh_sysuser/UNDECLARED
# -*- sh -*-
# -*- sh -*-
export CONF_HOME=/nonexistent
export CONF_PACKAGE=bcron-run
export CONF_USERNAME=_log-bcron-spool

/lib/sysuser-helper/sysuser-helper postinst "$@"
# End automatically added section
# Automatically added by dh_runit/UNDECLARED
# -*- shell-script -*-
export NAME='bcron-update'
export ENABLE='yes'

# Unlike postrm, I can be sure, that runit-helper is present on
# postinst.
/lib/runit-helper/runit-helper postinst "$@"

# Local Variables:
# eval: (sh-set-shell "sh" t nil)
# End:
# vim: ft=sh:sw=4
# End automatically added section
# Automatically added by dh_sysuser/UNDECLARED
# -*- sh -*-
# -*- sh -*-
export CONF_HOME=/nonexistent
export CONF_PACKAGE=bcron-run
export CONF_USERNAME=_log-bcron-update

/lib/sysuser-helper/sysuser-helper postinst "$@"
# End automatically added section
