#!/bin/sh

set -e


# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p nordugrid-arc-acix-cache 
fi

# End automatically added section
# Automatically added by dh_installinit/11.5.3
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/acix-cache" ]; then
		update-rc.d acix-cache defaults-disabled >/dev/null
		invoke-rc.d acix-cache start || exit 1
	fi
fi
# End automatically added section


dpkg-maintscript-helper rm_conffile /etc/default/acix-cache 5.4.2-2 -- "$@"
