#!/bin/sh 

set -e

if [ "$1" = "configure" ]; then
  if ! getent passwd ladvd > /dev/null; then
    adduser --system --quiet --group --no-create-home --home /var/empty/ \
      --disabled-password --disabled-login ladvd
  fi
fi

dpkg-maintscript-helper rm_conffile /etc/default/ladvd 1.0.4~ ladvd -- "$@"

# Automatically added by dh_systemd_enable/10.7.2
# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask ladvd.service >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled ladvd.service; then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable ladvd.service >/dev/null || true
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state ladvd.service >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/10.7.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/ladvd" ]; then
		update-rc.d ladvd defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d ladvd $_dh_action || exit $?
	fi
fi
# End automatically added section

