#!/bin/sh
set -e
# Automatically added by dh_installinit/10.10.5
if [ -x "/etc/init.d/zabbix-java-gateway" ] && [ "$1" = remove ]; then
	invoke-rc.d zabbix-java-gateway stop || exit $?
fi
# End automatically added section
