#!/bin/sh
set -e

if [ "$1" = "purge" ] ; then
    if dpkg-statoverride --list /var/log/balboa.log >/dev/null 2>&1 ; then
        dpkg-statoverride --remove /var/log/balboa.log
    fi
    echo "Removing log file (/var/log/balboa.log)"
    rm -rf /var/log/balboa.log

    rm -rf /var/lib/balboa
    deluser  --system balboa || echo "Could not remove balboa user."
fi

# Automatically added by dh_installsystemd/12
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/12
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'balboa.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'balboa.service' >/dev/null || true
		deb-systemd-helper unmask 'balboa.service' >/dev/null || true
	fi
fi
# End automatically added section

