#!/bin/sh
set -e
# Automatically added by dh_installemacsen/10.6.3
if [ -e /var/lib/emacsen-common/state/package/installed/emacsen-common -a -x /usr/lib/emacsen-common/emacs-package-remove ] ; then
	/usr/lib/emacsen-common/emacs-package-remove --prerm mu4e
fi
# End automatically added section
