#!/bin/sh
set -e
# Automatically added by dh_fortran_mod/UNDECLARED
multiarch="x86_64-linux-gnu"
base="gfortran-mod-15"
cmplr="gfortran-8"

mkdir -p /usr/lib/$multiarch/fortran/$base
ln -sf /usr/lib/$multiarch/fortran/$base /usr/lib/$multiarch/fortran/$cmplr


# End automatically added section
