#!/bin/sh
set -e
# Automatically added by dh_installinit/11.2.1
if [ -x "/etc/init.d/zaqar-server" ] && [ "$1" = remove ]; then
	invoke-rc.d zaqar-server stop || true
fi
# End automatically added section
