#!/bin/sh

set -e

LOGDIR=/var/log/solarpowerlog

if [ "$1" = "purge" ]
then
    rm -rf $LOGDIR || true
fi

# Automatically added by dh_installinit/11.5.3
if [ "$1" = "purge" ] ; then
	update-rc.d solarpowerlog remove >/dev/null
fi
# End automatically added section


exit 0
