#!/bin/sh
set -e

case "$1" in
	configure)
		# Very ugly hack to set timestamps same as /usr/lib/go-1.9/bin/go
		find /usr/lib/go-1.9/pkg -exec touch -r /usr/lib/go-1.9/bin/go {} \;
		;;
	*)
		;;
esac


