#!/bin/sh
set -e
# Automatically added by dh_installdeb
dpkg-maintscript-helper dir_to_symlink /usr/share/doc/libtachyon-mt-0-dev /usr/share/doc/libtachyon-dev-common 0.99~b6+dsx-5~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper symlink_to_dir /usr/share/doc/libtachyon-mt-0-dev /usr/share/doc/libtachyon-dev-common 0.99~b6+dsx-8~ -- "$@"
# End automatically added section
