#!/bin/sh
set -e

case "$1" in
    (upgrade|deconfigure|failed-upgrade)
	;;
    (remove)
        update-alternatives --remove quake-engine /usr/games/darkplaces
        ;;
    (*)
        echo "Unknown prerm action: $1" >&2
        exit 1
        ;;
esac



#vim:set sw=4 sts=4 et:
