#!/bin/sh -e
set -e

# Automatically added by dh_systemd_start
if [ -d /run/systemd/system ]; then
	deb-systemd-invoke stop dirsrv-snmp.service dirsrv.target >/dev/null
fi
# End automatically added section


if [ "$1" = "purge" ]; then
    # remove all installed instances
    for FILE in `ls -d $CONFDIR/slapd-* 2>/dev/null | sed -n '/\.removed$/!$'`
    do
        if [ -d "$FILE" ] ; then
            remove-ds -f -i $FILE
        fi
    done
fi
