#!/bin/sh
#
# stolen from ttf-dzongkha/debian/ttf-dzongkha.preinst :)
# 

set -e

VERSION=00103-13
PKG=ttf-ipafont-jisx0208
FILE=/etc/defoma/hints/${PKG}.hints

# Remove a no-longer used conffile
rm_conffile() {
    local PKGNAME="$1"
    local CONFFILE="$2"
    [ -e "$CONFFILE" ] || return 0

    local md5sum="$(md5sum $CONFFILE | sed -e 's/ .*//')"
    local old_md5sum="$(dpkg-query -W -f='${Conffiles}' $PKGNAME | \
            sed -n -e "\' $CONFFILE ' { s/ obsolete$//; s/.* //; p }")"
    if [ "$md5sum" != "$old_md5sum" ]; then
        echo "Obsolete conffile $CONFFILE has been modified by you."
        echo "Saving as $CONFFILE.dpkg-bak ..."
        mv -f "$CONFFILE" "$CONFFILE".dpkg-bak
    else
        echo "Removing obsolete conffile $CONFFILE ..."
        rm -f "$CONFFILE"
    fi
}

pathfind() {
    OLDIFS="$IFS"
    IFS=:
    for p in $PATH; do
        if [ -x "$p/$*" ]; then
            IFS="$OLDIFS"
            return 0
        fi
    done
    IFS="$OLDIFS"
    return 1
}


case "$1" in
install|upgrade)

    # cleanup obsolete alternatives from ttf-ipafont-jisx0208
    update-alternatives --remove ttf-japanese-gothic.ttf /usr/share/fonts/truetype/ipafont-jisx0208/ipag0208_for_legacy_compatibility.ttf
    update-alternatives --remove ttf-japanese-mincho.ttf /usr/share/fonts/truetype/ipafont-jisx0208/ipam0208_for_legacy_compatibility.ttf

    if dpkg --compare-versions "$2" lt-nl "$VERSION"; then
	if [ -f $FILE ]; then
        	if `pathfind defoma-font`; then
			defoma-font purge-all $FILE || true
		fi
	fi
	rm_conffile $PKG $FILE
    fi
esac



exit 0
