#!/bin/sh
set -e
# Automatically added by dh_installinit/11.3.5
if [ -x "/etc/init.d/yhsm-yubikey-ksm" ]; then
	invoke-rc.d yhsm-yubikey-ksm stop || exit 1
fi
# End automatically added section

# Automatically added by dh_python2:
if which pyclean >/dev/null 2>&1; then
	pyclean -p yhsm-yubikey-ksm 
else
	dpkg -L yhsm-yubikey-ksm | grep '\.py$' | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section
