#!/bin/sh

set -e

case "${1}" in
    purge|remove)
        if [ -x "$(which delgroup)" ]; then
            delgroup --quiet --system --only-if-empty xpra || true
        fi
    ;;
esac

# Automatically added by dh_installinit/11.5.3
if [ "$1" = "purge" ] ; then
	update-rc.d xpra remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_icons/11.5.3
if which update-icon-caches >/dev/null 2>&1 ; then
	update-icon-caches /usr/share/icons/xpra-mdns.png /usr/share/icons/xpra-shadow.png /usr/share/icons/xpra.png
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.5.3
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'xpra.service' 'xpra.socket' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'xpra.service' 'xpra.socket' >/dev/null || true
		deb-systemd-helper unmask 'xpra.service' 'xpra.socket' >/dev/null || true
	fi
fi
# End automatically added section

