#!/bin/sh
set -e
# Automatically added by dh_installdeb/10.10.5
dpkg-maintscript-helper dir_to_symlink /usr/share/doc/pike8.0-doc/html/manual/images /usr/share/doc/pike8.0-doc/html/reference/images 8.0.162-1~ pike8.0-doc -- "$@"
# End automatically added section
