#!/bin/sh
set -e
# Automatically added by dh_installinit/10.10.2
if [ -x "/etc/init.d/kopano-spooler" ] && [ "$1" = remove ]; then
	invoke-rc.d kopano-spooler stop || exit $?
fi
# End automatically added section
