#!/bin/sh
set -e
# Automatically added by dh_installinit/11.5.3
if [ -x "/etc/init.d/cinder-scheduler" ] && [ "$1" = remove ]; then
	invoke-rc.d cinder-scheduler stop || true
fi
# End automatically added section
