#!/bin/sh

set -e
set -u

if [ "$1" = "configure" ]; then
    adduser --system --quiet --group --home /dev/null --no-create-home \
        --disabled-login --gecos "KGB bot" --force-badname Debian-kgb

    if ! dpkg-statoverride --list /etc/kgb-bot/kgb.conf > /dev/null; then
        dpkg-statoverride --update --add root Debian-kgb 0640 /etc/kgb-bot/kgb.conf
    fi
fi

# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/kgb-bot" ]; then
		update-rc.d kgb-bot defaults >/dev/null
		invoke-rc.d kgb-bot start || exit $?
	fi
fi
# End automatically added section

