#!/bin/sh

set -e
set -u

LOG=/var/log/kgb-bot.log

if [ "$1" = "purge" ] ; then
	rm -f $LOG*
fi

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d kgb-bot remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section

