#!/bin/sh -e

update-alternatives --install /usr/bin/subvertpy-fast-export subvertpy-fast-export  /usr/bin/subvertpy2-fast-export 10


# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p python-subvertpy 
fi

# End automatically added section

