#!/bin/sh

set -e

if [ "$1" = "configure" ] ; then
	update-alternatives --quiet --remove alembic /usr/bin/python3-alembic
fi


# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p python3-alembic 
fi

# End automatically added section


exit 0
