#!/bin/sh

set -e

if [ "$1" = "remove" -o "$1" = "deconfigure" ]; then
    update-alternatives --remove phpdbg /usr/bin/phpdbg7.3
fi

php_enable() { return 0; }

if [ "$1" = "remove" ]; then
    if [ -e /usr/lib/php/php-maintscript-helper ]; then
	. /usr/lib/php/php-maintscript-helper

	mods=$(phpquery -M -v 7.3)
	for mod in $mods; do
	    php_invoke dismod 7.3 phpdbg $mod
	done
    else
	for mod in /etc/php/7.3/phpdbg/conf.d/*.ini; do 
	    rm -f $mod
	    for ext in '~' '%' .bak .ucf-new .ucf-old .ucf-dist;  do
		rm -f $mod$ext
	    done
	done
    fi
fi



exit 0
