#!/bin/sh
set -e
# Automatically added by dh_installinit/11.3.5
if [ -x "/etc/init.d/neutron-bgp-dragent" ] && [ "$1" = remove ]; then
	invoke-rc.d neutron-bgp-dragent stop || true
fi
# End automatically added section
