#!/bin/sh
set -e

# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p python3-dbus-tests /usr/lib/x86_64-linux-gnu/installed-tests/dbus-python/python3.7 -V 3.7
fi

# End automatically added section

# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p python3-dbus-tests /usr/lib/x86_64-linux-gnu/installed-tests/dbus-python/python3.6 -V 3.6
fi

# End automatically added section
