#!/bin/sh

set -e

if [ "$1" = configure ]; then
   update-alternatives \
       --install /usr/bin/scheme-r5rs scheme-r5rs /usr/bin/gsi 20 \
       --slave /usr/share/man/man1/scheme-r5rs.1 \
               scheme-r5rs.1 \
               /usr/share/man/man1/gsi.1.gz
fi


