#!/bin/sh
set -e
# Automatically added by dh_installinit/11.1.5
if [ -x "/etc/init.d/gridengine-master" ] && [ "$1" = remove ]; then
	invoke-rc.d gridengine-master stop || exit 1
fi
# End automatically added section
