#!/bin/sh
set -e
# Automatically added by dh_installinit/11.5.1
if [ -x "/etc/init.d/mistral-api" ] && [ "$1" = remove ]; then
	invoke-rc.d mistral-api stop || true
fi
# End automatically added section
