#!/bin/sh
set -e



case "$1" in
    purge|remove)

#
# remove obsolete directory
# new at release 2.4.4-1
#
	if [ -d /usr/lib/openvpn ]; then
	    rmdir --ignore-fail-on-non-empty /usr/lib/openvpn
	fi
    ;;

esac

# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/tmpfiles.d/openvpn.conf 2.4.3-3\~ openvpn -- "$@"
# End automatically added section
# Automatically added by dh_installinit/10.10.9
if [ "$1" = "purge" ] ; then
	update-rc.d openvpn remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/10.10.9
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'openvpn.service' >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'openvpn.service' >/dev/null
		deb-systemd-helper unmask 'openvpn.service' >/dev/null
	fi
fi
# End automatically added section
# Automatically added by dh_installdebconf/10.10.9
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


exit 0

