#!/bin/sh
set -e
# Automatically added by dh_installdeb/10.6.4
dpkg-maintscript-helper rm_conffile /etc/fonts/conf.avail/44-wqy-zenhei.conf 0.9.45-6\~ ttf-wqy-zenhei -- "$@"
dpkg-maintscript-helper rm_conffile /etc/fonts/conf.avail/43-wqy-zenhei-sharp.conf 0.9.45-6\~ ttf-wqy-zenhei -- "$@"
# End automatically added section
