#!/bin/sh
set -e

# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p mailman-api 
fi

# End automatically added section
# Automatically added by dh_installinit/10.7.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/mailman-api" ]; then
		update-rc.d mailman-api defaults >/dev/null
		invoke-rc.d mailman-api start || exit $?
	fi
fi
# End automatically added section
