#!/bin/sh
set -e
# Automatically added by dh_installinit/11.5.3
if [ -x "/etc/init.d/mailavenger" ] && [ "$1" = remove ]; then
	invoke-rc.d mailavenger stop || exit 1
fi
# End automatically added section
