#!/bin/sh
set -e
# Automatically added by dh_installinit/11.4.1
if [ "$1" = "purge" ] ; then
	update-rc.d pcscd remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.4.1
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'pcscd.service' 'pcscd.socket' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'pcscd.service' 'pcscd.socket' >/dev/null || true
		deb-systemd-helper unmask 'pcscd.service' 'pcscd.socket' >/dev/null || true
	fi
fi
# End automatically added section
