#!/bin/sh
set -e

reload_apache()
{
  if apache2ctl configtest 2>/dev/null; then
    invoke-rc.d apache2 restart || true
  else    
    echo "Your apache2 configuration is broken, so we're not restarting it for you."
  fi
}

# Automatically added by dh_installdeb
dpkg-maintscript-helper mv_conffile /etc/apache2/mods-available/mod-security.conf /etc/apache2/mods-available/security2.conf -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper mv_conffile /etc/apache2/mods-available/mod-security.load /etc/apache2/mods-available/security2.load -- "$@"
# End automatically added section


if [ -n "$2" ]; then
# remove dangling symlinks from previous versions
  if [ -n "$2" ] && dpkg --compare-versions "$2" lt 2.8.0-2 ; then
    for SYMLINK in mod-security.load mod-security.conf ; do
      if [ -L "/etc/apache2/mods-enabled/$SYMLINK" ] && [ ! -e "/etc/apache2/mods-enabled/$SYMLINK" ] ; then
        rm -f "/etc/apache2/mods-enabled/$SYMLINK"
      fi
    done
    reload_apache
  fi
fi

exit 0
