#!/bin/sh
set -e

# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p mgltools-vision 
fi

if which pycompile >/dev/null 2>&1; then
	pycompile -p mgltools-vision /usr/share/mgltools-vision -V 2.5-
fi

# End automatically added section
