#!/bin/sh
set -e
# Automatically added by dh_installzope
if which dzhandle >/dev/null; then
    case "$1" in install|upgrade)
	# install, upgrade
	#  - check, if product will be installed in an instance,
	#    where it already exists?

	dzhandle preinst-product -m "$*" zope-replacesupport /usr/share/zope/Products/ReplaceSupport ReplaceSupport
    esac
fi
# End automatically added section
