#!/bin/sh
set -e
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/debian-goodies.pkgnames 0.65\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/debmany 0.65\~ -- "$@"
# End automatically added section
