#! /bin/sh
# postinst script for gross

set -e

# lintian: postinst-does-not-load-confmodule
. /usr/share/debconf/confmodule

case "$1" in
    configure)
        DBDIR='/var/lib/gross'

        getent passwd gross > /dev/null || \
            adduser --system --home "$DBDIR" --no-create-home \
                    --disabled-password --group gross
        getent group gross > /dev/null || \
            addgroup --system gross 

        install -d -o gross -g gross -m 0700 "$DBDIR"
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)

    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/gross" ]; then
		update-rc.d gross defaults >/dev/null
		invoke-rc.d gross start || exit $?
	fi
fi
# End automatically added section


# without this, debconf hangs after end of postinst.
#db_stop

exit 0
