#!/bin/sh
set -e

# Automatically added by dhpython:
if which pycompile >/dev/null 2>&1; then
	pycompile -p koji-servers /usr/lib/koji-hub-plugins
fi

# End automatically added section

# Automatically added by dhpython:
if which pycompile >/dev/null 2>&1; then
	pycompile -p koji-servers /usr/share/koji-hub
fi

# End automatically added section

# Automatically added by dhpython:
if which pycompile >/dev/null 2>&1; then
	pycompile -p koji-servers /usr/share/koji-web
fi

# End automatically added section

# Automatically added by dhpython:
if which pycompile >/dev/null 2>&1; then
	pycompile -p koji-servers /usr/share/koji-web/lib/kojiweb
fi

# End automatically added section
