#!/bin/bash
#
# Gnats installation script -- written by Brian White <bcwhite@pobox.com>
# (This was my very first attempt at learning perl... please forgive me!)
#
# Forgiving -- rewritten to bash :-) by Milan Zamazal <pdm@debian.org>.
# ...and streamlined with SED by Chad Walstrom <chewie@debian.org>

set -e

###############################################################################
#
# Utility functions
#

# Call arguments and never return error
function protect () { "$@" || true; }

###############################################################################
#
# Remove the 'gnats' system configuration when purging
#

if [ "$1" = "purge" ] && [ -d "/var/lib/gnats/gnats-db" ]; then
	rmdir "/var/lib/gnats/gnats-db"
fi
###############################################################################
#
# Automatically added debhelper stuff
#
# Automatically added by dh_installdebconf
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

