#!/bin/sh -e

UFC_INCLUDE_DIR=/usr/lib/python2.7/dist-packages/ffc/backends/ufc

# Remove alternatives links
if [ "$1" = "remove" ]; then
  update-alternatives --remove ufc.h ${UFC_INCLUDE_DIR}/ufc.h
fi


# Automatically added by dh_python2:
if which pyclean >/dev/null 2>&1; then
	pyclean -p python-ffc 
else
	dpkg -L python-ffc | grep \.py$ | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section

