#!/bin/sh

set -e

if [ "$1" = "configure" ] ; then
	update-alternatives --install /usr/bin/gunicorn_pecan gunicorn_pecan /usr/bin/gunicorn_pecan-python3 300
	update-alternatives --install /usr/bin/pecan pecan /usr/bin/pecan-python3 300
fi


# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p python3-pecan 
fi

# End automatically added section


exit 0
