#!/bin/sh
set -e
# Automatically added by dh_systemd_enable
if deb-systemd-helper debian-installed lizardfs-metalogger.service; then
	# This will only remove masks created by d-s-h on package removal.
	deb-systemd-helper unmask lizardfs-metalogger.service >/dev/null || true

	if deb-systemd-helper --quiet was-enabled lizardfs-metalogger.service; then
		# Create new symlinks, if any.
		deb-systemd-helper enable lizardfs-metalogger.service >/dev/null || true
	fi
fi

# Update the statefile to add new symlinks (if any), which need to be cleaned
# up on purge. Also remove old symlinks.
deb-systemd-helper update-state lizardfs-metalogger.service >/dev/null || true
# End automatically added section
# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/lizardfs-metalogger" ]; then
		update-rc.d lizardfs-metalogger defaults >/dev/null || exit $?
	fi
fi
# End automatically added section
