#!/bin/sh
set -e
# Automatically added by dh_installdeb
dpkg-maintscript-helper symlink_to_dir /usr/share/doc/libnetfilter-queue1-dbg /usr/share/doc/libnetfilter-queue1 1.0.2-1~ libnetfilter-queue1-dbg -- "$@"
# End automatically added section
