#!/bin/sh

set -e

STENOTYPE=/usr/sbin/stenotype

if [ "$1" = "purge" ] ; then
    if dpkg-statoverride --list $STENOTYPE >/dev/null 2>&1 ; then
        dpkg-statoverride --remove $STENOTYPE
    fi
fi

# Automatically added by dh_systemd_start/10.9.2
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/10.9.2
if [ "$1" = "purge" ] ; then
	update-rc.d stenographer remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section

