#! /bin/sh

set -e

prevver="$2"

del_munin_async_user() {
	if getent passwd munin-async >/dev/null; then
		userdel -r munin-async
	fi
}

case "$1" in
	purge)
		del_munin_async_user
		;;
	*)
		;;
esac

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d munin-async remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask munin-async.service >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge munin-async.service >/dev/null
		deb-systemd-helper unmask munin-async.service >/dev/null
	fi
fi
# End automatically added section

