#!/bin/sh
set -e
# Automatically added by dh_systemd_start/10.10.7
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'pimd.service' >/dev/null
fi
# End automatically added section
