#!/bin/sh
set -e
# Automatically added by dh_installinit/11.3.5
if [ -x "/etc/init.d/dropbear" ] && [ "$1" = remove ]; then
	invoke-rc.d dropbear stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installdeb/11.3.5
dpkg-maintscript-helper symlink_to_dir /usr/share/doc/dropbear-run dropbear-bin 2016.72-1 -- "$@"
# End automatically added section
