#!/bin/sh
set -e
# Automatically added by dh_systemd_start/11.1.4
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'webhook.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_start/11.1.4
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'webhook.service' >/dev/null || true
fi
# End automatically added section
