#!/bin/sh

set -e

# Automatically added by dh_installinit/11.3.5
if [ "$1" = "purge" ] ; then
	update-rc.d haproxy remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installdeb/11.3.5
dpkg-maintscript-helper mv_conffile /etc/rsyslog.d/haproxy.conf /etc/rsyslog.d/49-haproxy.conf 1.5.3-2\~ -- "$@"
# End automatically added section
# Automatically added by dh_systemd_enable/11.3.5
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'haproxy.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'haproxy.service' >/dev/null || true
		deb-systemd-helper unmask 'haproxy.service' >/dev/null || true
	fi
fi
# End automatically added section


case "$1" in
    purge)
        deluser --system haproxy || true
        delgroup --system haproxy || true
    ;;
    *)
    ;;
esac

exit 0
