#!/bin/sh
# postinst script for python3-cymruwhois

set -e
if [ $1 = 'configure' ]; then
	update-alternatives --install /usr/bin/cymruwhois cymruwhois /usr/bin/python3-cymruwhois 200 --slave /usr/share/man/man1/cymruwhois.1.gz cymruwhois.1.gz /usr/share/man/man1/python3-cymruwhois.1.gz
fi


# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p python3-cymruwhois 
fi
if which pypy3compile >/dev/null 2>&1; then
	pypy3compile -p python3-cymruwhois  || true
fi

# End automatically added section


exit 0
