#!/bin/sh
set -e

if dpkg-maintscript-helper supports rm_conffile; then
    dpkg-maintscript-helper rm_conffile \
      /etc/emacs21/site-start.d/90ibulgarian.el 3.0-10 ibulgarian -- "$@"
fi

# Automatically added by dh_installdebconf/11.5.1
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section
# Automatically added by installdeb-ispell/UNDECLARED
rmscript="remove-default-ispell"

case "$1" in abort-install|remove)
	if which $rmscript > /dev/null 2>&1; then
	    $rmscript ibulgarian
	else
	    echo "Warning: $rmscript not present or executable." >&2
	fi

        # Remove shared question stuff on package removal, not only on purge
	if [ -e /usr/share/debconf/confmodule ]; then
	    . /usr/share/debconf/confmodule
	    db_purge
	fi
esac
# End automatically added section


exit 0
