#!/bin/sh
set -e

# Automatically added by dh_pypy:
if which pypyclean >/dev/null 2>&1; then
	pypyclean -p pypy-zodbpickle 
else
	dpkg -L pypy-zodbpickle | perl -ne 's,/([^/]*)\.py$,/__pycache__/\1.*, or next; unlink $_ or die $! foreach glob($_)'
	find /usr/lib/pypy/dist-packages/ -type d -name __pycache__ -empty -print0 | xargs --null --no-run-if-empty rmdir
fi

# End automatically added section
