#!/bin/sh

set -e

# Source debconf library.
. /usr/share/debconf/confmodule

# Automatically added by dh_php/UNDECLARED
for conf in geos; do
    dpkg-maintscript-helper rm_conffile /etc/php/mods-available/${conf}.ini -- "$@"
done

if [ -e /usr/lib/php/php-maintscript-helper ] ; then
    . /usr/lib/php/php-maintscript-helper

    for version in 7.2 ; do
        for conf in geos ; do
            php_invoke enmod $version ALL $conf || exit 1
	done
    done
else
    for conf in geos ; do
        phpenmod $conf
    done
fi
# End automatically added section


if [ "$1" = "configure" ]; then
	phpenmod geos
fi

exit 0
