#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.4.1
dpkg-maintscript-helper rm_conffile /etc/cron.daily/units 2.17-3\~ -- "$@"
# End automatically added section
# Automatically added by dh_installmenu/11.4.1
if [ -x "`which update-menus 2>/dev/null`" ]; then update-menus ; fi
# End automatically added section
