#! /bin/sh

set -e

DOCDIR="/usr/share/doc/amphetamine"

if [ -d "$DOCDIR" -a ! -L "$DOCDIR" ]; then
  rmdir --ignore-fail-on-non-empty "$DOCDIR"
  if [ ! -d "$DOCDIR" ]; then
    ln -s amphetamine-data "$DOCDIR"
  fi
fi



