#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.3.2
dpkg-maintscript-helper rm_conffile /etc/init.d/gfs2-tools 3.1.3-1.2\~ gfs2-tools -- \"\$\@\" 0 -- "$@"
# End automatically added section
