#!/bin/sh
set -e
# Automatically added by dh_installsystemd/11.4.1
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'teeworlds-server.service' >/dev/null || true
fi
# End automatically added section
