#!/bin/sh

set -e

if [ "$1" = "remove" ] ; then
	update-alternatives --remove sahara /usr/bin/python2-sahara
fi


# Automatically added by dh_python2:
if which pyclean >/dev/null 2>&1; then
	pyclean -p python-saharaclient 
else
	dpkg -L python-saharaclient | grep \.py$ | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section


exit 0
