#! /bin/sh
# postrm script for icecast2

set -e

case "$1" in
    purge)
	rm -rf /var/log/icecast2
	deluser --system --quiet icecast2 || true
	delgroup --system --quiet --only-if-empty icecast || true
	;;
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

	;;
    *)
	echo "postrm called with unknown argument \`$1'" >&2
	exit 1
esac

# Automatically added by dh_installinit/11.5.1
if [ "$1" = "purge" ] ; then
	update-rc.d icecast2 remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdeb/11.5.1
dpkg-maintscript-helper rm_conffile /etc/icecast2/web/status2.xsl 2.4.0-1\~ icecast2 -- "$@"
# End automatically added section
# Automatically added by dh_installdebconf/11.5.1
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


exit 0
