#! /bin/sh
# postrm script for bastet

set -e

if [ "$1" = purge ] ; then
  rm -f /var/games/bastet.scores2
fi

# Automatically added by dh_installdebconf/11.5.3
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


exit 0

