#!/bin/sh

set -e

if [ "${1}" = "configure" ] ; then
        update-alternatives --install /usr/share/puppet/modules/openstacklib puppet-module-openstacklib /usr/share/puppet/modules.available/openstacklib 500
fi



exit 0
