#!/bin/sh

set -e

if [ "$1" = "configure" ] ; then
	update-alternatives --install /usr/bin/murano-pkg-check murano-pkg-check /usr/bin/python2-murano-pkg-check 300
fi


# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p python-murano-pkg-check 
fi

# End automatically added section


exit 0
