#!/bin/sh

set -e

if [ -d /run/systemd/system ]; then
	deb-systemd-invoke stop dovecot.socket || true
fi

# Automatically added by dh_installdeb/10.10.7
dpkg-maintscript-helper rm_conffile /etc/dovecot/README 1:2.2.27-3\~ -- "$@"
# End automatically added section
# Automatically added by dh_installinit/10.10.7
if [ -x "/etc/init.d/dovecot" ] && [ "$1" = remove ]; then
	invoke-rc.d dovecot stop || exit $?
fi
# End automatically added section

