#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.3.5
dpkg-maintscript-helper dir_to_symlink /usr/share/gocode/src/github.com/appc/cni /usr/share/gocode/src/github.com/containernetworking/cni 0.3.0 -- "$@"
# End automatically added section
