#!/bin/sh
set -e

# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p apt-transport-spacewalk /usr/lib/apt-spacewalk
fi

# End automatically added section

# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p apt-transport-spacewalk /usr/share/rhn/actions
fi

# End automatically added section
