#!/bin/sh

set -e

if [ "${1}" = "configure" ] ; then
	update-alternatives --install /usr/share/puppet/modules/datacat puppet-module-datacat /usr/share/puppet/modules.available/richardc-datacat 500
fi



exit 0
