#!/bin/sh
set -e

# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p gpodder 
fi

if which pycompile >/dev/null 2>&1; then
	pycompile -p gpodder /usr/share/gpodder
fi

# End automatically added section
