#!/bin/sh
set -e
# Automatically added by dh_installmenu
if [ "$1" = "configure" ] && [ -x "`which update-menus 2>/dev/null`" ]; then
	update-menus
fi
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/logwatch/conf/logfiles/seaudit-report-group.conf 4.0.0-1~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/logwatch/conf/services/seaudit-report-service.conf 4.0.0-1~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/logwatch/scripts/services/seaudit-report-service 3.3.8+20151215-2~ -- "$@"
# End automatically added section
