#!/bin/sh
set -e
# Automatically added by dh_installinit/11.1.4
if [ -x "/etc/init.d/golang-redoctober" ]; then
	invoke-rc.d golang-redoctober stop || exit 1
fi
# End automatically added section
# Automatically added by dh_systemd_start/11.1.4
if [ -d /run/systemd/system ]; then
	deb-systemd-invoke stop 'golang-redoctober.service' >/dev/null || true
fi
# End automatically added section
