#!/bin/sh
# postrm script for sympow
set -e
SYMPOW_PKGCACHEDIR=/var/cache/sympow
SYMPOW_PKGCACHEDATADIR=$SYMPOW_PKGCACHEDIR/datafiles
# Automatically added by dh_installdeb
dpkg-maintscript-helper dir_to_symlink /usr/share/doc/sympow /usr/share/doc/sympow-data 1.023-6~ -- "$@"
# End automatically added section

case "${1}" in
	purge)
    if [ -d $SYMPOW_PKGCACHEDATADIR ]; then
			rmdir --ignore-fail-on-non-empty $SYMPOW_PKGCACHEDATADIR
		fi
    if [ -d $SYMPOW_PKGCACHEDIR ]; then
			rmdir --ignore-fail-on-non-empty $SYMPOW_PKGCACHEDIR
		fi
		;;
	*)
		;;
esac
exit 0
