#!/bin/sh -e

case $1 in
    remove|disappear)
	for f in londiste scriptmgr queue_mover queue_splitter; do
	    update-alternatives --remove $f /usr/bin/${f}3 || exit 1 ;
	done;;

    purge)
	rm -rf /var/log/skytools /var/run/skytools
	;;
esac

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d skytools3 remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section

