#!/bin/sh
set -e
# Automatically added by dh_installudev
if [ "$1" = configure ]; then
	if [ -e "/etc/udev/rules.d/z60_avarice.rules" ]; then
		echo "Preserving user changes to /etc/udev/rules.d/60-avarice.rules ..."
		if [ -e "/etc/udev/rules.d/60-avarice.rules" ]; then
			mv -f "/etc/udev/rules.d/60-avarice.rules" "/etc/udev/rules.d/60-avarice.rules.dpkg-new"
		fi
		mv -f "/etc/udev/rules.d/z60_avarice.rules" "/etc/udev/rules.d/60-avarice.rules"
	fi
fi
# End automatically added section
