#!/bin/sh

set -e

if [ "${1}" = "purge" ] ; then
	rm -rf /var/log/heat/heat-api-cfn*
	[ -d /var/log/heat ] && rmdir --ignore-fail-on-non-empty /var/log/heat
fi

# Automatically added by dh_installinit/11.5.3
if [ "$1" = "purge" ] ; then
	update-rc.d heat-api-cfn remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_systemd_enable/11.5.3
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'heat-api-cfn.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'heat-api-cfn.service' >/dev/null || true
		deb-systemd-helper unmask 'heat-api-cfn.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installdebconf/11.5.3
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


exit 0
