#!/bin/sh
set -e
# Automatically added by dh_installinit/11.5.3
if [ -x "/etc/init.d/heat-api-cfn" ] && [ "$1" = remove ]; then
	invoke-rc.d heat-api-cfn stop || true
fi
# End automatically added section
