#!/bin/sh
set -e

# Automatically added by dh_installinit/11.3.5
if [ "$1" = "purge" ] ; then
	update-rc.d cubemap remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/11.3.5
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'cubemap.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'cubemap.service' >/dev/null || true
		deb-systemd-helper unmask 'cubemap.service' >/dev/null || true
	fi
fi
# End automatically added section


if [ "$1" = "purge" ] ; then
        deluser --quiet --system cubemap > /dev/null || true
fi
