#!/bin/sh
set -e
# Automatically added by dh_installdeb
dpkg-maintscript-helper mv_conffile /etc/init.d/opencryptoki /etc/init.d/pkcsslotd -- "$@"
# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/pkcsslotd" ]; then
	invoke-rc.d pkcsslotd stop || exit $?
fi
# End automatically added section
