#!/bin/sh
# postinst script for sympow
set -e
SYMPOW=/usr/bin/sympow
ENDIANTUPLE=$($SYMPOW -dump-endiantuple)
SYMPOW_PKGCACHEDIR=/var/cache/sympow
SYMPOW_PKGCACHEDATADIR=$SYMPOW_PKGCACHEDIR/datafiles
SYMPOW_PKGCACHEDATABINDIR=$SYMPOW_PKGCACHEDATADIR/$ENDIANTUPLE
case "${1}" in
	configure)
    if [ ! -d $SYMPOW_PKGCACHEDIR ]; then
			mkdir -p $SYMPOW_PKGCACHEDIR
			chown 0:0 $SYMPOW_PKGCACHEDIR
			chmod ug+rwx $SYMPOW_PKGCACHEDIR
		fi
    if [ ! -d $SYMPOW_PKGCACHEDATADIR ]; then
			mkdir -p $SYMPOW_PKGCACHEDATADIR
			chown 0:0 $SYMPOW_PKGCACHEDATADIR
			chmod ug+rwx,o+rwt,ug+s $SYMPOW_PKGCACHEDATADIR
		fi
    if [ ! -d $SYMPOW_PKGCACHEDATABINDIR ]; then
			mkdir -p $SYMPOW_PKGCACHEDATABINDIR
			chown 0:0 $SYMPOW_PKGCACHEDATABINDIR
			chmod ug+rwx,o+rwt,ug+s $SYMPOW_PKGCACHEDATABINDIR
		fi
		;;
	*)
		;;
esac
# Automatically added by dh_installdeb/11.3.5
dpkg-maintscript-helper dir_to_symlink /usr/share/doc/sympow /usr/share/doc/sympow-data 1.023-6~ -- "$@"
# End automatically added section

exit 0
