#!/bin/sh
set -e
# Automatically added by dh_systemd_enable/10.7.2
# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask nagios-nrpe-server.service >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled nagios-nrpe-server.service; then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable nagios-nrpe-server.service >/dev/null || true
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state nagios-nrpe-server.service >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/10.7.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	# In case this system is running systemd, we need to ensure that all
	# necessary tmpfiles (if any) are created before starting.
	if [ -d /run/systemd/system ] ; then
		systemd-tmpfiles --create /usr/lib/tmpfiles.d/nagios-nrpe-server.conf >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installinit/10.7.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/nagios-nrpe-server" ]; then
		update-rc.d nagios-nrpe-server defaults >/dev/null
		invoke-rc.d nagios-nrpe-server start || exit $?
	fi
fi
# End automatically added section
