#!/bin/sh
# prerm script for prewikka
#
# see: dh_installdeb(1)

set -e

# source debconf stuff
. /usr/share/debconf/confmodule
# source dbconfig-common stuff
. /usr/share/dbconfig-common/dpkg/prerm
dbc_go prewikka $@


# Automatically added by dh_python3:
if which py3clean >/dev/null 2>&1; then
	py3clean -p prewikka 
else
	dpkg -L prewikka | perl -ne 's,/([^/]*)\.py$,/__pycache__/\1.*, or next; unlink $_ or die $! foreach glob($_)'
	find /usr/lib/python3/dist-packages/ -type d -name __pycache__ -empty -print0 | xargs --null --no-run-if-empty rmdir
fi

# End automatically added section


exit 0


