#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.2.1
dpkg-maintscript-helper dir_to_symlink /usr/share/doc/roundcube roundcube-core 1.1.2\+dfsg.1-3 -- "$@"
# End automatically added section
