#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.3.5
dpkg-maintscript-helper mv_conffile /etc/X11/WindowMaker/background.menu /usr/share/WindowMaker/background.menu 0.95.7-5\~ -- "$@"
dpkg-maintscript-helper mv_conffile /etc/X11/WindowMaker/wmmacros /usr/share/WindowMaker/wmmacros 0.95.7-5\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/X11/WindowMaker/appearance.menu 0.95.7-5\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/X11/WindowMaker/menu.posthook 0.95.7-5\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/X11/WindowMaker/menu.prehook 0.95.7-5\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/menu-methods/wmappearance 0.95.8-2\~ -- "$@"
# End automatically added section
