#!/bin/sh
set -e
# Automatically added by dh_installsystemd/11.5.4
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'kopano-ical.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/11.5.4
if [ -x "/etc/init.d/kopano-ical" ] && [ "$1" = remove ]; then
	invoke-rc.d --skip-systemd-native kopano-ical stop || exit 1
fi
# End automatically added section
