#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/tango-accesscontrol" ]; then
		update-rc.d tango-accesscontrol defaults 25 >/dev/null
		invoke-rc.d tango-accesscontrol start || exit $?
	fi
fi
# End automatically added section
