#!/bin/sh

set -e

case "${1}" in
	purge)
		rm -rf /var/log/gadmin-openvpn/server
		rmdir --ignore-fail-on-non-empty /var/log/gadmin-openvpn
		;;

	remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

		;;

	*)
		echo "postrm called with unknown argument \`${1}'" >&2
		exit 1
		;;
esac

# Automatically added by dh_icons
if which update-icon-caches >/dev/null 2>&1 ; then
	update-icon-caches /usr/share/icons/gadmin-openvpn-server.png
fi
# End automatically added section
# Automatically added by dh_installmenu
if [ -x "`which update-menus 2>/dev/null`" ]; then update-menus ; fi
# End automatically added section


exit 0
