#!/bin/sh

set -e

# Remove configuration if package is being purged
if [ "$1" = "purge" ]; then
	FILES="dtc-xen-firewall-custom-rules dtc-xen-firewall.sh dtc-xen-firewall-config"
	MY_CWD=`pwd`
	cd /etc/dtc-xen
	for i in ${FILES} ; do
		rm -f /etc/dtc-xen/${i}
	done
	cd ${MY_CWD}
fi

# Automatically added by dh_installdebconf
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section
# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d dtc-xen-firewall remove >/dev/null
fi
# End automatically added section


exit 0
