#!/bin/sh

if [ "$1" = "purge" ]
then
    find /etc/logtool -type l -exec rm -f {} \;
fi

# Automatically added by dh_installdebconf
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section
