#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.1.4
dpkg-maintscript-helper dir_to_symlink /usr/lib/GNUstep/Applications/TextEdit.app/Resources /usr/share/GNUstep/TextEdit.app 5.0-2\~ textedit.app -- "$@"
# End automatically added section
