#!/bin/sh
set -e
# Automatically added by dh_installinit/11.1.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/ipkungfu" ]; then
		update-rc.d ipkungfu defaults >/dev/null
		invoke-rc.d ipkungfu start || exit 1
	fi
fi
# End automatically added section
