#!/bin/sh
set -e

# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p python-pycsw 
fi

if which pycompile >/dev/null 2>&1; then
	pycompile -p python-pycsw /usr/lib/python-pycsw -V 2.5-
fi

# End automatically added section
