#!/bin/sh
# postinst script for fancontrol
#
# see: dh_installdeb(1)
set -e

case "$1" in
    configure)
        # Remove shutdown and reboot links; this init script does not need them.
        if dpkg --compare-versions "$2" lt "1:3.1.1-5"; then
	    rm -f /etc/rc0.d/K[0-9][0-9]fancontrol /etc/rc1.d/K[0-9][0-9]fancontrol /etc/rc6.d/K[0-9][0-9]fancontrol
        fi
    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
	exit 1
    ;;
esac

# Automatically added by dh_systemd_enable
# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask fancontrol.service >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled fancontrol.service; then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable fancontrol.service >/dev/null || true
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state fancontrol.service >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/fancontrol" ]; then
		update-rc.d fancontrol defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d fancontrol $_dh_action || exit $?
	fi
fi
# End automatically added section

