#!/bin/sh

set -e

case "$1" in

	configure)
		glib-compile-schemas /usr/share/glib-2.0/schemas
	;;

	abort-upgrade|abort-remove|abort-deconfigure)
	;;

	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
	;;

esac

# Automatically added by dh_icons/10.10.7
if which update-icon-caches >/dev/null 2>&1 ; then
	update-icon-caches /usr/share/icons/mate-window-applets
fi
# End automatically added section


exit 0
