#!/bin/sh
set -e

dpkg-maintscript-helper rm_conffile \
  /etc/emacs/site-start.d/50wl-beta.el 2.7.7+cvs.2001.12.12-1~ -- "$@"
dpkg-maintscript-helper rm_conffile \
  /etc/emacs/site-start.d/60wl-beta.el 2.7.7+cvs.2001.12.15-1~ -- "$@"

if [ ! -e /var/lib/emacsen-common/state/package/installed/emacsen-common ]; then
    # Fallback to emacsen-common 1.x
    if [ "$1" = "configure" ] && [ -x /usr/lib/emacsen-common/emacs-package-install ]; then
	/usr/lib/emacsen-common/emacs-package-install wl-beta
    fi
else
# Automatically added by dh_installemacsen
if [ "$1" = "configure" ] && [ -e /var/lib/emacsen-common/state/package/installed/emacsen-common -a -x /usr/lib/emacsen-common/emacs-package-install ]
then
	/usr/lib/emacsen-common/emacs-package-install --postinst wl-beta
fi
# End automatically added section

fi
