#!/bin/sh
set -e
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/de/yahoo-de.xml 45.0esr-2~ iceweasel-l10n-de -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/de/wikipedia-de.xml 45.0esr-2~ iceweasel-l10n-de -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/de/leo_ende_de.xml 45.0esr-2~ iceweasel-l10n-de -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/de/google.xml 45.0esr-2~ iceweasel-l10n-de -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/de/eBay-de.xml 45.0esr-2~ iceweasel-l10n-de -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/de/ddg.xml 45.0esr-2~ iceweasel-l10n-de -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/de/bing.xml 45.0esr-2~ iceweasel-l10n-de -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/de/amazondotcom-de.xml 45.0esr-2~ iceweasel-l10n-de -- "$@"
# End automatically added section
