#!/bin/sh

set -e

package=namazu2

. /usr/share/debconf/confmodule

CFG=/etc/namazu/cgidirs

if [ "$1" = "configure" ]; then

	db_get namazu2/install
	PLACE=$RET

	echo $PLACE > $CFG
	if [ ! -z "$PLACE" -a "x$PLACE" != "x" ]; then
		for d in $PLACE; do
			echo "copying to $d ..."
			if [ ! -d $d ]; then
				install -d $d
			fi
			cp -a /usr/lib/cgi-bin/namazu.cgi $d/
		done
	fi
fi	

# Automatically added by dh_installemacsen
if [ "$1" = "configure" ] && [ -e /var/lib/emacsen-common/state/package/installed/emacsen-common -a -x /usr/lib/emacsen-common/emacs-package-install ]
then
	/usr/lib/emacsen-common/emacs-package-install --postinst namazu2
fi
# End automatically added section

