#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/avr-evtd" ]; then
		update-rc.d avr-evtd start 12 2 3 4 5 . stop 95 0 1 6 . >/dev/null
		invoke-rc.d avr-evtd start || exit $?
	fi
fi
# End automatically added section
