#! /bin/sh

set -e

# Clean up after ourselves

if [ "$1" = remove ]; then rm -f /etc/X11/fvwm/system.fvwmrc; fi

# Automatically added by dh_installmenu
inst=/etc/menu-methods/fvwm1
if [ "$1" = "remove" ] && [ -f "$inst" ]; then chmod a-x $inst ; fi
if [ -x "`which update-menus 2>/dev/null`" ]; then update-menus ; fi
# End automatically added section


exit 0
