#!/bin/sh

set -e

case "$1" in
    remove)
        # remove **only** empty data dir
        rmdir -p --ignore-fail-on-non-empty /var/lib/elasticsearch || true
        ;;

    purge)
        rm -rf /var/log/elasticsearch /var/lib/elasticsearch

        dpkg-statoverride --list \
            | awk '$1 == "elasticsearch" || $2 == "elastcsearch" {print $4 }' \
            | xargs -n1 dpkg-statoverride --remove

        deluser elasticsearch || true
        delgroup elasticsearch || true
        ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;

    *)
        echo "$0 called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d elasticsearch remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section


exit 0
