#!/bin/sh
set -e

case "$1" in
    remove|upgrade|deconfigure)
        ;;

    failed-upgrade)
        ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

# NOT added by dh_installinit
if [ -x "/etc/init.d/elasticsearch" ]; then
	invoke-rc.d elasticsearch stop || exit $?
fi

# Automatically added by dh_installinit
if [ -x "/etc/init.d/elasticsearch" ]; then
	invoke-rc.d elasticsearch stop || exit $?
fi
# End automatically added section


exit 0
