#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/dns-flood-detector" ]; then
		update-rc.d dns-flood-detector defaults 40 >/dev/null
		invoke-rc.d dns-flood-detector start || exit $?
	fi
fi
# End automatically added section
