#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper symlink_to_dir /usr/share/doc/python-zope.interface-dbg /usr/share/doc/python-zope.interface 4.1.1-3.1~ -- "$@"
# End automatically added section
