#!/bin/sh
set -e

# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p game-data-packager /usr/share/games/game-data-packager
fi

# End automatically added section
# Automatically added by dh_installdeb/11.2.1
dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/game-data-packager 42\~ -- "$@"
# End automatically added section
