#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/amavisd-milter" ] && [ "$1" = remove ]; then
	invoke-rc.d amavisd-milter stop || exit $?
fi
# End automatically added section
