#!/bin/sh
set -e

# Automatically added by dh_installdebconf
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


if [ -L /usr/include/FL/Fl_Preferences.h ]; then
    (cd /usr/include/FL; for H in *.H; do rm -f `basename $H .H`.h; done)
    rmdir --ignore-fail-on-non-empty /usr/include/FL
fi
