#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/latd" ]; then
	update-rc.d latd defaults >/dev/null
	invoke-rc.d latd start || exit $?
fi
# End automatically added section
