#!/bin/sh
set -e
# Automatically added by dh_installinit/12
if [ -x "/etc/init.d/cloudkitty-api" ] && [ "$1" = remove ]; then
	invoke-rc.d cloudkitty-api stop || true
fi
# End automatically added section
