#!/bin/sh

if [ "$1" = "configure" ]; then
        if [ -d /usr/doc -a -h /usr/doc/python-imaging-doc-pdf -a -d /usr/share/doc/python-imaging-doc-pdf ]; then
                rm -f /usr/doc/python-imaging-doc-pdf
        fi
fi


