#!/bin/sh

set -e

action=$1
version=$2

if [ "$action" = "configure" ] ; then
  if dpkg --compare-versions "$version" le 3.5.7 ; then
    . /usr/share/debconf/confmodule
    db_input critical ifhp/filters_have_moved || true
    db_go || true
  fi
fi
