#!/bin/sh
set -e

# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p gedit-plugin-synctex /usr/lib/x86_64-linux-gnu/gedit/plugins
fi

# End automatically added section
