#!/bin/sh
set -e
# Automatically added by dh_installinit/10.10.9
if [ -x "/etc/init.d/cinder-volume" ] && [ "$1" = remove ]; then
	invoke-rc.d cinder-volume stop || true
fi
# End automatically added section
