#!/bin/sh
set -e
# Automatically added by dh_installdeb/12
dpkg-maintscript-helper rm_conffile /etc/default/udftools 2.0-1\~ udftools -- "$@"
dpkg-maintscript-helper rm_conffile /etc/init.d/udftools 2.0-1\~ udftools -- "$@"
# End automatically added section
