#!/bin/sh
set -e

# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p linux-grsec-support-4.9.0-4 /usr/share/linux-grsec-support-4.9.0-4
fi

# End automatically added section
