#!/bin/sh
set -e
# Automatically added by dh_installinit/10.10.9
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/acix-index" ]; then
		update-rc.d acix-index defaults >/dev/null
		invoke-rc.d acix-index start || exit $?
	fi
fi
# End automatically added section

# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p nordugrid-arc-acix-index 
fi

# End automatically added section
