#!/bin/sh
set -e

test "$1" = 'remove' || test "$1" = 'deconfigure' || \
  test "$1" = 'failed-upgrade' || exit 0

for i in twoftpd twoftpd-anon; do
  update-service --remove /etc/$i 2>/dev/null || :
done
