#!/bin/sh -e

TCPCRYPT_USER=debian-tcpcryptd

case $1 in
    purge)
	# add a debian-tcpcryptd user if one does not already exist
	if getent passwd "$TCPCRYPT_USER" >/dev/null ; then
            deluser "$TCPCRYPT_USER"
	fi
        ;;
esac

# Automatically added by dh_systemd_start
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask tcpcryptd.service >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge tcpcryptd.service >/dev/null
		deb-systemd-helper unmask tcpcryptd.service >/dev/null
	fi
fi
# End automatically added section

