#!/bin/sh

set -e

ARCH=`dpkg --print-architecture`

if [ "$1" = "configure" ]; then

        if [ "$ARCH" = "amd64" ]; then
            update-alternatives --force \
                --install /etc/ld.so.conf.d/x86_64-linux-gnu_GL.conf x86_64-linux-gnu_gl_conf /usr/lib/virtualbox/additions/00vboxvideo.conf 8605

            update-alternatives --force \
               --install /etc/ld.so.conf.d/x86_64-linux-gnu_EGL.conf x86_64-linux-gnu_egl_conf /usr/lib/virtualbox/additions/00vboxvideo.conf 8605
        else
            update-alternatives --force \
               --install /etc/ld.so.conf.d/i386-linux-gnu_GL.conf i386-linux-gnu_gl_conf /usr/lib/virtualbox/additions/00vboxvideo.conf 8605

            update-alternatives --force \
               --install /etc/ld.so.conf.d/i386-linux-gnu_EGL.conf i386-linux-gnu_egl_conf /usr/lib/virtualbox/additions/00vboxvideo.conf 8605
        fi

	ldconfig
fi

# Automatically added by dh_installdeb/11
dpkg-maintscript-helper rm_conffile /etc/init.d/virtualbox-guest-x11 5.0.12-dfsg-2\~ -- "$@"
# End automatically added section


# remove stale virtualbox-guest-x11 links
case "$1" in
  configure)
    if dpkg --compare-versions "$2" lt "5.0.12-dfsg-2~" ; then
      update-rc.d -f virtualbox-guest-x11 remove > /dev/null || true
    fi
  ;;
esac

