#!/bin/sh

set -e

# Source debconf library:
. /usr/share/debconf/confmodule

db_version 2.0
db_capb backup

# Get udev root path
if [ -f /etc/udev/udev.conf ]; then
    . /etc/udev/udev.conf
fi
udev_root="${udev_root%/}"
udev_root="${udev_root:-/dev}"


# Do you intend to install this package on a live system ?
# Ask it only once, please...
db_fget bilibop-rules/on-live-system seen
if [ "${RET}" != "true" ]; then
    db_input critical bilibop-rules/on-live-system || true
    db_go || true
fi

# If this package is intended to be installed on a Live System,
# then skip other questions.
db_get bilibop-rules/on-live-system
if [ "${RET}" = "true" ]; then
    db_stop
    exit 0
fi

# make_unpersistent_rules
# -----------------------

if [ -f "/etc/udev/rules.d/70-persistent-cd.rules" -o -f "/etc/udev/rules.d/70-persistent-net.rules" ]; then
    db_input high bilibop-rules/make_unpersistent_rules || true
    db_go || true
fi

# grub_device_map_manager
# -----------------------

if [ -d "/boot/grub" -a -x "/usr/sbin/grub-mkdevicemap" ]; then
    db_input high bilibop-rules/grub_device_map_manager || true
    db_go || true
fi

# Skip questions whose answer cannot be treaded by the postinst script:
if ! invoke-rc.d udev status 1>${udev_root}/null 2>&1; then
    db_stop
    exit 0
fi

# bilibop_rules_generator
# -----------------------

# Next questions (in the loop) should have the same priority:
prio="low"
STATE=1
while true; do
    case "${STATE}" in
        0)
            # Don't go back:
            STATE=1
            continue
            ;;
        1)
            if [ -f /etc/udev/rules.d/66-bilibop.rules ]; then
                db_input ${prio} bilibop-rules/bilibop_rules_generator/overwrite || true
            else
                db_input ${prio} bilibop-rules/bilibop_rules_generator/customize || true
            fi
            ;;
        2)
            CUSTOM_RULES="false"
            if [ -f /etc/udev/rules.d/66-bilibop.rules ]; then
                db_get bilibop-rules/bilibop_rules_generator/overwrite
                if [ "${RET}" = "rebuild" ]; then
                    CUSTOM_RULES="true"
                    db_input ${prio} bilibop-rules/bilibop_rules_generator/options || true
                fi
            else
                db_get bilibop-rules/bilibop_rules_generator/customize
                if [ "${RET}" = "true" ]; then
                    CUSTOM_RULES="true"
                    db_input ${prio} bilibop-rules/bilibop_rules_generator/options || true
                fi
            fi
            ;;
        3)
            if [ "${CUSTOM_RULES}" = "true" ]; then
                db_get bilibop-rules/bilibop_rules_generator/options
                # Check options only if the helper script if available:
                if [ -x /usr/share/bilibop/bilibop_rules_generator ]; then
                    /usr/share/bilibop/bilibop_rules_generator -o ${udev_root}/null ${RET} 2>${udev_root}/null ||
                    db_input ${prio} bilibop-rules/bilibop_rules_generator/bad_options
                fi
            fi
            ;;
        *)
            break
            ;;
    esac

    if db_go; then
        STATE=$((STATE+1))
    else
        STATE=$((STATE-1))
    fi
done

# physical_volumes_filter
# -----------------------

if [ -h /proc/mounts -a -d /sys/block ]; then
    for blk in $(ls /sys/block | grep -Ev '^(loop|dm-)'); do
        if lsblk ${udev_root}/${blk} --noheadings -o mountpoint | grep -q '^/$'; then
            SYSTEM_DISK="${udev_root}/${blk}"
            break
        fi
    done

    if lsblk ${SYSTEM_DISK} --noheadings -o type,fstype | grep -Eq '\<(lvm|LVM2_member)\>'; then
        db_input low bilibop-rules/physical_volumes_filter/system-only || true
        db_go || true
    fi
fi

db_stop


:
# vim: et ts=4 sts=4 sw=4
