#!/bin/sh
set -e
# Automatically added by dh_cligacpolicy
if [ "$1" = "remove" ] ||  [ "$1" = "upgrade" ] && [ -x /usr/share/cli-common/policy-remove ]; then
	/usr/share/cli-common/policy-remove nunit.core 2.6
fi
# End automatically added section
