#!/bin/sh

# Written by Petter Reinholdtsen <pere@hungry.com> see
# http://bugs.debian.org/542112

set -e

# Recover from incorrect init.d script headers in version 0.0.40-1 and earlier
if [ "$1" = "configure" ] && dpkg --compare-versions "$2" le "0.0.40-1" \
   && [ -f /etc/rc3.d/S[0-9][0-9]shishi-kdc ] \
   && [ -f /etc/rc2.d/K[0-9][0-9]shishi-kdc ] ; then
    update-rc.d -f shishi-kdc remove
fi

# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/shishi-kdc" ]; then
		update-rc.d shishi-kdc defaults >/dev/null
		invoke-rc.d shishi-kdc start || exit $?
	fi
fi
# End automatically added section

