#!/bin/sh -e

CONFIG=/etc/default/am-utils

# Automatically added by dh_installinit/11.1.4
if [ "$1" = "purge" ] ; then
	update-rc.d am-utils remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installdebconf/11.1.4
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


if [ "$1" = "purge" ] ; then
    test -x /usr/bin/ucf && ucf --purge $CONFIG
    rm -f /etc/default/am-utils
fi

if [ "$1" = remove ] && [ -f /etc/amd/config.disabled-by-am-utils ] && [ ! -f /etc/amd/config ]
then
    echo "Reenabling old amd package..."
    mv /etc/amd/config.disabled-by-am-utils /etc/amd/config
fi

exit 0
