#!/bin/sh
set -e
# Automatically added by dh_installdeb/11
dpkg-maintscript-helper rm_conffile /etc/plinth/modules-enabled/lib 0.4.3-1~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11
dpkg-maintscript-helper rm_conffile /etc/plinth/modules-enabled/expert_mode 0.4.3-1~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11
dpkg-maintscript-helper rm_conffile /etc/plinth/modules-enabled/packages 0.5-1~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11
dpkg-maintscript-helper rm_conffile /etc/plinth/modules-enabled/xmpp 0.13.0+ds-1~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11
dpkg-maintscript-helper rm_conffile /etc/plinth/modules-enabled/apps 0.15.1+ds-2~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11
dpkg-maintscript-helper rm_conffile /etc/plinth/modules-enabled/owncloud 0.15.1+ds-2~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11
dpkg-maintscript-helper rm_conffile /etc/plinth/modules-enabled/system 0.15.1+ds-2~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11
dpkg-maintscript-helper rm_conffile /etc/plinth/modules-enabled/disks 0.15.3+ds-1~ -- "$@"
# End automatically added section
