#!/bin/sh
set -e
# Automatically added by dh_installdeb/11
dpkg-maintscript-helper rm_conffile /etc/plinth/modules-enabled/disks 0.15.3+ds-1~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11
dpkg-maintscript-helper rm_conffile /etc/plinth/modules-enabled/system 0.15.1+ds-2~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11
dpkg-maintscript-helper rm_conffile /etc/plinth/modules-enabled/owncloud 0.15.1+ds-2~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11
dpkg-maintscript-helper rm_conffile /etc/plinth/modules-enabled/apps 0.15.1+ds-2~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11
dpkg-maintscript-helper rm_conffile /etc/plinth/modules-enabled/xmpp 0.13.0+ds-1~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11
dpkg-maintscript-helper rm_conffile /etc/plinth/modules-enabled/packages 0.5-1~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11
dpkg-maintscript-helper rm_conffile /etc/plinth/modules-enabled/expert_mode 0.4.3-1~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11
dpkg-maintscript-helper rm_conffile /etc/plinth/modules-enabled/lib 0.4.3-1~ -- "$@"
# End automatically added section
# Automatically added by dh_systemd_start/11
if [ -d /run/systemd/system ]; then
	deb-systemd-invoke stop 'plinth.service' >/dev/null
fi
# End automatically added section

# Automatically added by dh_python3:
if which py3clean >/dev/null 2>&1; then
	py3clean -p plinth 
else
	dpkg -L plinth | perl -ne 's,/([^/]*)\.py$,/__pycache__/\1.*, or next; unlink $_ or die $! foreach glob($_)'
	find /usr/lib/python3/dist-packages/ -type d -name __pycache__ -empty -print0 | xargs --null --no-run-if-empty rmdir
fi

# End automatically added section
