#!/bin/sh

set -e

case "${1}" in
	configure)
		mkdir -p /etc/live/boot

		if [ -x "$(which update-initramfs 2>/dev/null)" ] && [ -e /etc/initramfs-tools/initramfs.conf ]
		then
			update-initramfs -u
		fi
		;;

	abort-upgrade|abort-remove|abort-deconfigure)

		;;

	*)
		echo "postinst called with unknown argument \`${1}'" >&2
		exit 1
		;;
esac



exit 0
