#!/bin/sh

set -e

# Automatically added by dh_installsystemd/11.3.5
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.3.5
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'consul.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'consul.service' >/dev/null || true
		deb-systemd-helper unmask 'consul.service' >/dev/null || true
	fi
fi
# End automatically added section


if [ "$1" = "purge" ]; then
    deluser --system consul || true
    rm -rf /var/lib/consul || true
fi
