#!/bin/sh
set -e
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/son/amazon-france.xml 45.0esr-2~ iceweasel-l10n-son -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/son/bing.xml 45.0esr-2~ iceweasel-l10n-son -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/son/cnrtl-tlfi-fr.xml 45.0esr-2~ iceweasel-l10n-son -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/son/ddg.xml 45.0esr-2~ iceweasel-l10n-son -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/son/eBay-france.xml 45.0esr-2~ iceweasel-l10n-son -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/son/google.xml 45.0esr-2~ iceweasel-l10n-son -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/son/wikipedia-fr.xml 45.0esr-2~ iceweasel-l10n-son -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/son/yahoo-france.xml 45.0esr-2~ iceweasel-l10n-son -- "$@"
# End automatically added section
