#!/bin/sh
set -e
# Automatically added by dh_installinit/10.10.8
if [ "$1" = "purge" ] ; then
	update-rc.d gnocchi-api remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/10.10.8
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'gnocchi-api.service' >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'gnocchi-api.service' >/dev/null
		deb-systemd-helper unmask 'gnocchi-api.service' >/dev/null
	fi
fi
# End automatically added section
# Automatically added by dh_installdebconf/10.10.8
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section
