#!/bin/sh
set -e
if [ -f /etc/fireqos/fireqos.conf ]; then
	mv -f /etc/fireqos/fireqos.conf /etc/firehol/fireqos.conf
	echo
	echo
	echo "FireQOS has now its configuration in /etc/firehol/fireqos.conf"
	echo "Your existing configuration has been moved to its new place."
	echo
	if (rmdir /etc/fireqos 2> /dev/null); then
		echo "The now obsolete folder /etc/fireqos has been successfully removed."
	else
	  echo "The now obsolete folder /etc/fireqos could not been removed."
		echo "It is likely that it contains some local material; if so,"
		echo "you want to consider to move by hand the concerned material"
		echo "in /etc/firehol and then remove /etc/fireqos."
	fi
fi
# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/fireqos" ]; then
		update-rc.d fireqos defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d fireqos $_dh_action || exit $?
	fi
fi
# End automatically added section

