#!/bin/sh
set -e

if [ -x "/etc/init.d/dpm-srmv1" ]; then
	if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
		invoke-rc.d dpm-srmv1 stop || exit $?
	else
		/etc/init.d/dpm-srmv1 stop || exit $?
	fi
fi

if [ -x "/etc/init.d/dpm-srmv2" ]; then
	if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
		invoke-rc.d dpm-srmv2 stop || exit $?
	else
		/etc/init.d/dpm-srmv2 stop || exit $?
	fi
fi

if [ -x "/etc/init.d/dpm-srmv2.2" ]; then
	if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
		invoke-rc.d dpm-srmv2.2 stop || exit $?
	else
		/etc/init.d/dpm-srmv2.2 stop || exit $?
	fi
fi

if [ "$1" = "remove" ] ; then
	update-alternatives --remove dpm-srmv1 /usr/lib/dpm-postgres/dpm-srmv1
	update-alternatives --remove dpm-srmv2 /usr/lib/dpm-postgres/dpm-srmv2
	update-alternatives --remove dpm-srmv2.2 /usr/lib/dpm-postgres/dpm-srmv2.2
fi


