#!/bin/sh

set -e

case "$1" in
    remove|deconfigure)
        update-alternatives --remove autokey /usr/bin/autokey-qt
    ;;
esac


# Automatically added by dh_python2:
if which pyclean >/dev/null 2>&1; then
	pyclean -p autokey-qt 
else
	dpkg -L autokey-qt | grep \.py$ | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section


exit 0
