#!/bin/sh

set -e

if [ "$1" = "upgrade" ] && dpkg --compare-versions "$2" lt "1.6.1-2" ; then
	update-alternatives --remove-all mutt
fi

# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/Muttrc.d/sidebar.rc 1.6.2-1~ mutt -- "$@"
# End automatically added section


exit 0
