#!/bin/sh
set -e
# Automatically added by dh_systemd_start
if [ -d /run/systemd/system ]; then
	deb-systemd-invoke stop urfkill.service >/dev/null
fi
# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/urfkill" ]; then
	invoke-rc.d urfkill stop || exit $?
fi
# End automatically added section
