#!/bin/sh
set -e

# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p qgis-plugin-grass-common /usr/share/qgis/grass/scripts
fi

# End automatically added section
