#!/bin/sh

set -e

case "$1" in
  purge)
        rm -f /var/log/prometheus/prometheus-bind-exporter.log \
              /var/run/prometheus/prometheus-bind-exporter.pid
        ;;
esac

# Automatically added by dh_installinit/11.4.1
if [ "$1" = "purge" ] ; then
	update-rc.d prometheus-bind-exporter remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.4.1
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'prometheus-bind-exporter.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'prometheus-bind-exporter.service' >/dev/null || true
		deb-systemd-helper unmask 'prometheus-bind-exporter.service' >/dev/null || true
	fi
fi
# End automatically added section

