#!/bin/sh

set -e

if [ "$1" = "configure" ]; then
    update-alternatives \
	--install /usr/bin/phpdbg phpdbg /usr/bin/phpdbg7.3 73 \
	--slave /usr/share/man/man1/phpdbg.1.gz phpdbg.1.gz /usr/share/man/man1/phpdbg7.3.1.gz
fi

CONFDIR=/etc/php/7.3/phpdbg/conf.d

if [ "$1" = "configure" ]; then
    phpini="/etc/php/7.3/phpdbg/php.ini"

    if [ "phpdbg" = "cli" ]; then
	ucf /usr/lib/php/7.3/php.ini-production.phpdbg $phpini
    else
	ucf /usr/lib/php/7.3/php.ini-production $phpini
    fi
    ucfr php7.3-phpdbg $phpini

    if [ -e /usr/lib/php/php-maintscript-helper ]; then
	. /usr/lib/php/php-maintscript-helper
	
	mods=$(phpquery -M -v 7.3)
	for mod in $mods; do
	    php_invoke enmod 7.3 phpdbg $mod
	done
    fi

    if [ -n "$2" ] && dpkg --compare-versions "$2" lt "7.0.3-2~"; then
	rm -f /etc/php/7.3/phpdbg/conf.d/20-opcache.ini;
    fi	    
fi



exit 0
