#!/bin/sh
set -e

# Automatically added by dhpython:
if which pycompile >/dev/null 2>&1; then
	pycompile -p p4vasp 
fi

if which pycompile >/dev/null 2>&1; then
	pycompile -p p4vasp /usr/share/p4vasp
fi

# End automatically added section
