#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/neutron-l2gateway-agent" ]; then
		update-rc.d neutron-l2gateway-agent defaults >/dev/null
		invoke-rc.d neutron-l2gateway-agent start || true
	fi
fi
# End automatically added section
