#!/bin/sh
set -e
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ca/bing.xml 45.0esr-2~ iceweasel-l10n-ca -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ca/ddg.xml 45.0esr-2~ iceweasel-l10n-ca -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ca/diec2.xml 45.0esr-2~ iceweasel-l10n-ca -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ca/google.xml 45.0esr-2~ iceweasel-l10n-ca -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ca/twitter.xml 45.0esr-2~ iceweasel-l10n-ca -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ca/wikipedia-ca.xml 45.0esr-2~ iceweasel-l10n-ca -- "$@"
# End automatically added section
