#!/bin/bash
set -euo pipefail

if [[ ${1:-} == configure ]]; then
	pkill -HUP -x syncthing || true
fi

# Automatically added by dh_systemd_enable/10.8
# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask syncthing-resume.service >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled syncthing-resume.service; then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable syncthing-resume.service >/dev/null || true
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state syncthing-resume.service >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_start/10.8
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
	deb-systemd-invoke start syncthing-resume.service >/dev/null || true
fi
# End automatically added section

