#! /bin/sh
# postinst script for perdition-ldap



set -e

if [ "$1" = "configure" ]; then
	if [ -f /etc/init.d/perdition ]; then
		invoke-rc.d perdition stop
	fi
	if [ -f /etc/init.d/perdition ]; then
		invoke-rc.d perdition start
	fi
fi

exit 0
