#!/bin/sh

set -e

case $1 in
        remove|purge)
                invoke-rc.d neutron-server stop
esac

# Automatically added by dh_installinit/10.10.9
if [ -x "/etc/init.d/neutron-server" ] && [ "$1" = remove ]; then
	invoke-rc.d neutron-server stop || true
fi
# End automatically added section

