#!/bin/sh

set -e

ONE_GROUP=oneadmin
ONE_USER=oneadmin

if [ "$1" = "configure" ]; then
    chown $ONE_USER:$ONE_GROUP /var/log/one
fi

# Automatically added by dh_systemd_enable
# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask opennebula-gate.service >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled opennebula-gate.service; then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable opennebula-gate.service >/dev/null || true
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state opennebula-gate.service >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/opennebula-gate" ]; then
		update-rc.d opennebula-gate defaults >/dev/null
		invoke-rc.d opennebula-gate start || exit $?
	fi
fi
# End automatically added section

