#!/bin/sh

set -e

. /usr/share/debconf/confmodule


# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p zope2.13 /usr/lib/zope2.13 -V 2.7
fi

# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/zope2.13" ]; then
	update-rc.d zope2.13 defaults >/dev/null
	invoke-rc.d zope2.13 start || exit $?
fi
# End automatically added section


db_stop
exit 0
