#!/bin/sh
set -e
# Automatically added by dh_installdeb/10.10.5
dpkg-maintscript-helper symlink_to_dir /usr/share/doc/gnustep-base-runtime /usr/share/doc/gnustep-base-common 1.25.0-1\~ gnustep-base-runtime -- "$@"
# End automatically added section
