#!/bin/sh
set -e
# Automatically added by dh_installdeb/10.10.5
dpkg-maintscript-helper symlink_to_dir /usr/share/doc/gnustep-base-runtime /usr/share/doc/gnustep-base-common 1.25.0-1\~ gnustep-base-runtime -- "$@"
# End automatically added section
# Automatically added by dh_installinit/10.10.5
if [ -x "/etc/init.d/gdomap" ] && [ "$1" = remove ]; then
	invoke-rc.d gdomap stop || exit $?
fi
# End automatically added section
