#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.4
dpkg-maintscript-helper mv_conffile /etc/xdg/menus/enlightenment-applications.menu /etc/xdg/menus/e-applications.menu 0.21.2-2\~ enlightenment-data -- "$@"
# End automatically added section
