#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.3.5
dpkg-maintscript-helper rm_conffile /etc/xdg/katerc 4:15.12.0-1\~\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/xdg/ktexteditor_codesnippets_core.knsrc 4:15.12.0-1\~\~ -- "$@"
# End automatically added section
