#!/bin/sh
set -e
# Automatically added by dh_systemd_start/10.7.2
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/10.7.2
if [ "$1" = "purge" ] ; then
	update-rc.d booth remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/10.7.2
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask booth-arbitrator.service booth.service >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge booth-arbitrator.service booth.service >/dev/null
		deb-systemd-helper unmask booth-arbitrator.service booth.service >/dev/null
	fi
fi
# End automatically added section
