#!/bin/sh
set -e
# Automatically added by dh_systemd_start/10.7.2
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop booth-arbitrator.service >/dev/null
fi
# End automatically added section
# Automatically added by dh_installinit/10.7.2
if [ -x "/etc/init.d/booth" ] && [ "$1" = remove ]; then
	invoke-rc.d booth stop || exit $?
fi
# End automatically added section
