#!/bin/sh
set -e

# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p variety 
fi

if which pycompile >/dev/null 2>&1; then
	pycompile -p variety /usr/share/variety -V 2.7
fi

# End automatically added section
