#!/bin/sh

set -e

if [ -f /usr/share/debconf/confmodule ]; then
    . /usr/share/debconf/confmodule
    db_purge
fi
if [ -f /usr/share/dbconfig-common/dpkg/postrm.pgsql ]; then
    . /usr/share/dbconfig-common/dpkg/postrm.pgsql
    dbc_go mailman3-core "$@"
fi

case "$1" in
    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    remove)
    ;;

    purge)
        for ext in .ucf-new .ucf-old .ucf-dist ""; do
            rm -f "/etc/mailman3/mailman.cfg$ext"
        done
        if which ucf >/dev/null 2>&1; then
            ucf --purge /etc/mailman3/mailman.cfg
        fi
        if which ucfr >/dev/null 2>&1; then
            ucfr --purge mailman3-core /etc/mailman3/mailman.cfg
        fi
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# Automatically added by dh_installinit/10.10.9
if [ "$1" = "purge" ] ; then
	update-rc.d mailman3-core remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/10.10.9
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'mailman3-core.service' >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'mailman3-core.service' >/dev/null
		deb-systemd-helper unmask 'mailman3-core.service' >/dev/null
	fi
fi
# End automatically added section
# Automatically added by dh_installdebconf/10.10.9
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


exit 0
