#!/bin/sh
set -e

# Automatically added by dh_dkms/UNDECLARED
DKMS_NAME=zfs
DKMS_VERSION=0.7.12

case "$1" in
    remove|upgrade|deconfigure)
      if [  "$(dkms status -m $DKMS_NAME -v $DKMS_VERSION)" ]; then
         dkms remove -m $DKMS_NAME -v $DKMS_VERSION --all
      fi
    ;;
esac
# End automatically added section


if [ "$1" = "remove" ]; then
        rm -f /etc/zfs/zpool.cache
fi
