#!/bin/sh
# postinst script for ocsinventory-reports
#
# see: dh_installdeb(1)

set -e

pkgpath="/usr/share/ocsinventory-reports"
varpath="/var/lib/ocsinventory-reports"
logpath="/var/log/ocsinventory-reports"
dbconfpath="/etc/ocsinventory/dbconfig.inc.php"

# Allow php to write in $varpath
for dirname in ipd download snmp; do
 chown -R www-data:www-data $varpath/$dirname
 chmod -R g+w               $varpath/$dirname
done

# Allow php to write in $logpath
for dirname in logs scripts; do
 chown -R www-data:www-data $logpath/$dirname
 chmod -R g+w               $logpath/$dirname
done

for dirname in $pkgpath; do
 chown -R www-data:www-data $dirname
done 

if [ "$1" = "configure" ]; then
  # create empty /etc/ocsinventory/dbconfig.inc.php if missing
  if [ ! -e $dbconfpath ]; then
    cat << EOS > $dbconfpath
<?php

?>
EOS
  fi

  # Allow php to update it
  chown www-data:www-data $dbconfpath
fi

# Automatically added by dh_apache2
if true; then
	if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
		. /usr/share/apache2/apache2-maintscript-helper
		for conf in ocsinventory-reports  ; do
			apache2_invoke enconf $conf  || exit $?
		done
	fi
fi
# End automatically added section


exit 0
