#!/bin/sh

set -e


case "$1" in
  install|upgrade)
    if [ -e /etc/network/network-routes ] ; then
    # There was a bug in the package (<< 0.15). We need to
    # move the file to the new location
        if dpkg-maintscript-helper supports mv_conffile; then
         dpkg-maintscript-helper mv_conffile \
            /etc/network/network-routes /etc/network/routes 0.14 -- "$@"
        fi
    fi
  ;;
esac





# vim:tabstop=2:expandtab:shiftwidth=2
