#!/bin/sh
set -e
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/gd/yahoo-en-GB.xml 45.0esr-2~ iceweasel-l10n-gd -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/gd/wikipedia-gd.xml 45.0esr-2~ iceweasel-l10n-gd -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/gd/google.xml 45.0esr-2~ iceweasel-l10n-gd -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/gd/faclair-beag.xml 45.0esr-2~ iceweasel-l10n-gd -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/gd/duckduckgo.xml 45.0esr-2~ iceweasel-l10n-gd -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/gd/ddg.xml 45.0esr-2~ iceweasel-l10n-gd -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/gd/bbc-alba.xml 45.0esr-2~ iceweasel-l10n-gd -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/gd/amazon-en-GB.xml 45.0esr-2~ iceweasel-l10n-gd -- "$@"
# End automatically added section
