#! /bin/bash

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d atopacct remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d atop remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask atopacct.service >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge atopacct.service >/dev/null
		deb-systemd-helper unmask atopacct.service >/dev/null
	fi
fi
# End automatically added section
# Automatically added by dh_systemd_enable
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask atop.service >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge atop.service >/dev/null
		deb-systemd-helper unmask atop.service >/dev/null
	fi
fi
# End automatically added section


set -e

if dpkg-maintscript-helper supports rm_conffile; then
	dpkg-maintscript-helper rm_conffile \
		/etc/logrotate.d/atop 1.26-2~ -- "$@"
fi

if [ "$1" = "purge" ]
then
	rm -rf /var/log/atop
fi

