#!/bin/sh
set -e
# Automatically added by dh_icons
if which update-icon-caches >/dev/null 2>&1 ; then
	update-icon-caches /usr/share/icons/gtkwave_256x256x32.png /usr/share/icons/gtkwave_files_256x256x32.png /usr/share/icons/gtkwave_savefiles_256x256x32.png
fi
# End automatically added section
