#!/bin/sh

set -e

SYSUSER=tarantool

case "$1" in
    configure)
        if ! getent passwd $SYSUSER > /dev/null; then
            adduser \
                --system \
                --group \
                --quiet \
                --home \
                /var/spool/$SYSUSER \
                --no-create-home \
                --disabled-login \
                    tarantool
        fi

        # Use setgid to allow `adm` members to read logs
        install -d -o$SYSUSER -gadm -m2750 /var/log/tarantool
        install -d -o$SYSUSER -g$SYSUSER -m750 /var/run/tarantool
        install -d -o$SYSUSER -g$SYSUSER -m750 /var/lib/tarantool

        # Enable example.lua by default
        if [ -z $2 ] && [ ! -e /etc/tarantool/instances.enabled/example.lua ] &&
           [ -d /etc/tarantool/instances.enabled ] &&
           [ -d /etc/tarantool/instances.available/ ]; then
          ln -s /etc/tarantool/instances.available/example.lua \
                /etc/tarantool/instances.enabled/example.lua
        fi
    ;;
esac

# Automatically added by dh_systemd_enable/10.8
# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask tarantool.service >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled tarantool.service; then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable tarantool.service >/dev/null || true
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state tarantool.service >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/10.8
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/tarantool" ]; then
		update-rc.d tarantool defaults >/dev/null
		invoke-rc.d tarantool start || exit $?
	fi
fi
# End automatically added section

