#!/bin/sh
set -e
# Automatically added by dh_installinit/11.5.3
if [ -x "/etc/init.d/heat-engine" ] && [ "$1" = remove ]; then
	invoke-rc.d heat-engine stop || true
fi
# End automatically added section
