#!/bin/sh

set -e

GROUP="eviacam"

. /usr/share/debconf/confmodule

# Automatically added by dh_installdebconf/11.2.1
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


case "$1" in
	purge)
		if sg "$GROUP" true 2>/dev/null; then
			delgroup --quiet --only-if-empty "$GROUP" >/dev/null 2>&1 || true
		fi
		;;	
	*)
		;;
esac

