#!/bin/sh
set -e

case "$1" in
    configure)
      update-alternatives --install /usr/bin/run-escript run-escript /usr/bin/run-escript2-mpi 30
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
      update-alternatives --install /usr/bin/run-escript run-escript /usr/bin/run-escript2-mpi 30
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac


# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p python-escript-mpi /usr/lib/python-escript-mpi/esys -V 2.7
fi

# End automatically added section


exit 0
