#! /bin/sh -e

prio=1050

update-alternatives --quiet \
    --install /usr/bin/java java /usr/bin/gij-5 $prio \
    #--slave /usr/share/man/man1/java.1.gz java.1.gz /usr/share/man/man1/gij-5.1.gz

update-alternatives --quiet \
    --install /usr/bin/rmiregistry rmiregistry /usr/bin/grmiregistry-5 $prio \
    --slave /usr/share/man/man1/rmiregistry.1.gz rmiregistry.1.gz /usr/share/man/man1/grmiregistry-5.1.gz

update-alternatives --quiet \
    --install /usr/bin/keytool keytool /usr/bin/gkeytool-5 $prio \
    --slave /usr/share/man/man1/keytool.1.gz keytool.1.gz /usr/share/man/man1/gkeytool-5.1.gz

update-alternatives --quiet \
    --install /usr/bin/orbd orbd /usr/bin/gorbd-5 $prio \
    --slave /usr/share/man/man1/orbd.1.gz orbd.1.gz /usr/share/man/man1/gorbd-5.1.gz

update-alternatives --quiet \
    --install /usr/bin/rmid rmid /usr/bin/grmid-5 $prio \
    --slave /usr/share/man/man1/rmid.1.gz rmid.1.gz /usr/share/man/man1/grmid-5.1.gz

case "$1" in
configure)
    if [ ! -f /var/lib/gcj-5/classmap.db ]; then
	uname=$(uname -m)
	mkdir -p /var/lib/gcj-5
	if gcj-dbtool-5 -n /var/lib/gcj-5/classmap.db; then
	    case "$uname" in arm*|m68k|parisc*)
	        echo >&2 "gcj-dbtool succeeded unexpectedly"
	    esac
	else
	    case "$uname" in
	    arm*|m68k|parisc*)
	        echo >&2 "ERROR: gcj-dbtool did fail; known problem on $uname";;
	    *)
		exit 2
	    esac
	    touch /var/lib/gcj-5/classmap.db
	fi
    fi
esac



exit 0
