#!/bin/sh

set -e

. /usr/share/debconf/confmodule

adduser --system --disabled-password --disabled-login --home /var/lib/puppetdb \
        --no-create-home --quiet --force-badname --group puppetdb

if ! dpkg-statoverride --list /var/log/puppetdb >/dev/null 2>&1; then
    dpkg-statoverride --update --add puppetdb adm 0750 /var/log/puppetdb
fi

if ! dpkg-statoverride --list /var/lib/puppetdb >/dev/null 2>&1; then
    dpkg-statoverride --update --add puppetdb puppetdb 0750 /var/lib/puppetdb
fi

. /usr/share/dbconfig-common/dpkg/postinst.pgsql

dbc_generate_include_args="-o template_infile=/usr/share/puppetdb/database.ini.template"
dbc_generate_include="template:/etc/puppetdb/conf.d/database.ini"
dbc_generate_include_owner="root:puppetdb"
dbc_generate_include_perms="0640"
dbc_pgsql_createdb_encoding="UTF8"
dbc_go puppetdb $@

if [ "$1" = "configure" ]; then
    ucfr puppetdb /etc/puppetdb/conf.d/database.ini
fi

# Automatically added by dh_systemd_enable/11.4.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# This will only remove masks created by d-s-h on package removal.
	deb-systemd-helper unmask 'puppetdb.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'puppetdb.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'puppetdb.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'puppetdb.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installinit/11.4.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/puppetdb" ]; then
		update-rc.d puppetdb defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d puppetdb $_dh_action || exit 1
	fi
fi
# End automatically added section


exit 0
