#!/bin/sh
set -e

if [ -x "/etc/init.d/dpnsdaemon" ]; then
	invoke-rc.d dpnsdaemon stop || exit 1
fi

if [ "$1" = "remove" ] ; then
	update-alternatives --remove dpnsdaemon /usr/lib/dpm-mysql/dpnsdaemon
fi


