#!/bin/sh

set -e

dpkg-maintscript-helper mv_conffile \
    /var/lib/gridsite/.gacl /etc/gridsite/.gacl \
    1.7.25-2~ gridsite -- "$@"
dpkg-maintscript-helper mv_conffile \
    /var/lib/gridsite/gridsitefoot.txt /etc/gridsite/gridsitefoot.txt \
    1.7.25-2~ gridsite -- "$@"
dpkg-maintscript-helper mv_conffile \
    /var/lib/gridsite/gridsitehead.txt /etc/gridsite/gridsitehead.txt \
    1.7.25-2~ gridsite -- "$@"


