#!/bin/sh
set -e
# Automatically added by dh_vdrplugin_enable
#
# Automatically create symlink in /etc/vdr/conf.d to enable the VDR plugin
# if the plugin was installed or upgraded from a version which did not
# supported the conf.d mechanism.
#
dh_vdrplugin_create_symlinks() {
  while [ $# -gt 1 ] ; do
    local config=$1
    local priority=$2
    shift 2
    if [ -e "/etc/vdr/conf.d/$priority-$config.dpkg-vdrplugin-enable" ] ; then
      rm "/etc/vdr/conf.d/$priority-$config.dpkg-vdrplugin-enable"
      if [ -e "/etc/vdr/conf.avail/$config" ] ; then
        ln -sr "/etc/vdr/conf.avail/$config" "/etc/vdr/conf.d/$priority-$config"
      fi
    fi
  done
}

if [ "$1" = configure ]; then
  dh_vdrplugin_create_symlinks hello.conf 50 osddemo.conf 50 pictures.conf 50 rcu.conf 50 skincurses.conf 50 status.conf 50 svccli.conf 50 svcsvr.conf 50 svdrpdemo.conf 50
fi
# End automatically added section
