#!/bin/sh

set -e

STENOTYPE=/usr/sbin/stenotype

if [ "$1" = "purge" ] ; then
    if dpkg-statoverride --list $STENOTYPE >/dev/null 2>&1 ; then
        dpkg-statoverride --remove $STENOTYPE
    fi
fi

# Automatically added by dh_installsystemd/11.3.2
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.3.2
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'stenographer.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'stenographer.service' >/dev/null || true
		deb-systemd-helper unmask 'stenographer.service' >/dev/null || true
	fi
fi
# End automatically added section

