#!/bin/sh

set -e

STENOTYPE=/usr/sbin/stenotype

if [ "$1" = configure ]; then
    if which setcap > /dev/null; then
        if setcap 'CAP_NET_RAW,CAP_NET_ADMIN=ep CAP_IPC_LOCK=ep' "$STENOTYPE"; then
            echo "setcap on $STENOTYPE worked."
            if ! dpkg-statoverride --list $STENOTYPE >/dev/null 2>&1; then
                dpkg-statoverride \
                    --quiet --update \
                    --add stenographer root 0744 $STENOTYPE
            fi
            # twice, since caps seem to be reset after the call above
            setcap 'CAP_NET_RAW,CAP_NET_ADMIN=ep CAP_IPC_LOCK=ep' "$STENOTYPE"
        else
            echo "setcap on $STENOTYPE failed, falling back to setuid."
            if ! dpkg-statoverride --list $STENOTYPE >/dev/null 2>&1; then
                dpkg-statoverride \
                    --quiet --update \
                    --add root stenographer 4754 $STENOTYPE
            fi
        fi
    fi
fi

# Automatically added by dh_installsystemd/11.3.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if deb-systemd-helper debian-installed 'stenographer.service'; then
		# This will only remove masks created by d-s-h on package removal.
		deb-systemd-helper unmask 'stenographer.service' >/dev/null || true

		if deb-systemd-helper --quiet was-enabled 'stenographer.service'; then
			# Create new symlinks, if any.
			deb-systemd-helper enable 'stenographer.service' >/dev/null || true
		fi
	fi

	# Update the statefile to add new symlinks (if any), which need to be cleaned
	# up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'stenographer.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.3.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			deb-systemd-invoke try-restart 'stenographer.service' >/dev/null || true
		fi
	fi
fi
# End automatically added section

