#!/bin/sh -e

if [ -d /usr/lib/monodoc/search_index ]; then
	rm -r /usr/lib/monodoc/search_index
fi

# Automatically added by dh_installmenu
if [ "$1" = "configure" ] && [ -x "`which update-menus 2>/dev/null`" ]; then
	update-menus
fi
# End automatically added section


exit 0
