#!/bin/sh
# prerm script for dbeacon

set -e

if [ $1 = 'remove' ]; then
	deluser Debian-dbeacon
fi

# Automatically added by dh_systemd_start
if [ -d /run/systemd/system ]; then
	deb-systemd-invoke stop dbeacon.service >/dev/null
fi
# End automatically added section


exit 0
