#!/bin/sh
set -eu

if test "$1" = purge; then
    rm -rf /var/lib/salt/pki/master
    rmdir --ignore-fail-on-non-empty /var/lib/salt/pki /var/lib/salt
fi

# Automatically added by dh_installinit/11.5.4
if [ "$1" = "purge" ] ; then
	update-rc.d salt-master remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.5.4
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'salt-master.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'salt-master.service' >/dev/null || true
		deb-systemd-helper unmask 'salt-master.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
