#!/bin/sh
set -e
# Automatically added by dh_installinit/11.4.1
if [ -x "/etc/init.d/arpon" ] && [ "$1" = remove ]; then
	invoke-rc.d arpon stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installdeb/11.4.1
dpkg-maintscript-helper rm_conffile /etc/arpon.sarpi 3.0-ng\+dfsg1-1\~ -- "$@"
# End automatically added section
