#!/bin/sh
set -e

# Automatically added by dhpython:
if which pycompile >/dev/null 2>&1; then
	pycompile -p lava-coordinator 
fi

if which pycompile >/dev/null 2>&1; then
	pycompile -p lava-coordinator /usr/share/lava-coordinator -V 2.7
fi

# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/lava-coordinator" ]; then
	update-rc.d lava-coordinator defaults >/dev/null
	invoke-rc.d lava-coordinator start || exit $?
fi
# End automatically added section
