#!/bin/sh
set -e

# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p python-mini-buildd 
fi

# End automatically added section
# Automatically added by dh_installdeb/11.3.2
dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/mini-buildd-tool.bash-completion -- "$@"
# End automatically added section
