#! /bin/sh
# prerm script for BindGraph
# by Jose Luis Tallon <jltallon@adv-solutions.net>

set -e

# summary of how this script can be called:
#        * <prerm> `remove'
#        * <old-prerm> `upgrade' <new-version>
#        * <new-prerm> `failed-upgrade' <old-version>
#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
#        * <deconfigured's-prerm> `deconfigure' `in-favour'
#          <package-being-installed> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    remove|deconfigure)
        ;;
    upgrade)
	;;
    failed-upgrade)
        ;;
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# Automatically added by dh_installinit/11.1.5
if [ -x "/etc/init.d/bindgraph" ] && [ "$1" = remove ]; then
	invoke-rc.d bindgraph stop || exit 1
fi
# End automatically added section


exit 0
