#!/bin/sh

set -e

if [ "${1}" = "remove" ] || [ "${1}" = "upgrade" ] || [ "${1}" = "deconfigure" ] ; then
	update-alternatives --remove puppet-module-logrotate /usr/share/puppet/modules.available/rodjek-logrotate
fi



exit 0
