#! /bin/sh
# postrm script for scanbd

set -e

case "$1" in
    purge)
      find /etc/scanbd -maxdepth 1 -type l -name *.conf -delete
      rm -f /etc/scanbd/dll.conf
      if [ -x /usr/sbin/update-inetd ]; then
        update-inetd --remove 'sane-port'
      fi
    ;;
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d scanbd remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section


exit 0
