#!/bin/sh
set -e
# Automatically added by dh_installinit/11.5.4
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/qemu-guest-agent" ]; then
		update-rc.d qemu-guest-agent defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d --skip-systemd-native qemu-guest-agent $_dh_action || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.5.4
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if deb-systemd-helper debian-installed 'qemu-guest-agent.service'; then
		# This will only remove masks created by d-s-h on package removal.
		deb-systemd-helper unmask 'qemu-guest-agent.service' >/dev/null || true

		if deb-systemd-helper --quiet was-enabled 'qemu-guest-agent.service'; then
			# Create new symlinks, if any.
			deb-systemd-helper enable 'qemu-guest-agent.service' >/dev/null || true
		fi
	fi

	# Update the statefile to add new symlinks (if any), which need to be cleaned
	# up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'qemu-guest-agent.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.5.4
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			deb-systemd-invoke try-restart 'qemu-guest-agent.service' >/dev/null || true
		fi
	fi
fi
# End automatically added section
