#!/bin/sh

set -e

if [ "$1" = "purge" ]; then
  if [ -d /run/ladvd ]; then
    rm -rf /run/ladvd
  fi
fi

dpkg-maintscript-helper rm_conffile /etc/default/ladvd 1.0.4~ ladvd -- "$@"

# Automatically added by dh_installinit/11.3.5
if [ "$1" = "purge" ] ; then
	update-rc.d ladvd remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/11.3.5
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'ladvd.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'ladvd.service' >/dev/null || true
		deb-systemd-helper unmask 'ladvd.service' >/dev/null || true
	fi
fi
# End automatically added section

