#!/bin/bash -e

# This is the default postrm file from the blends-dev package which is used
# in all meta packages.  If there is a certain need to provide extra
# postrm files for some meta packages this template will be appended.  Thus
# it will be checked whether debconf was just initialized.
#
# You should not insert the _DEBHELPER_ template in the special postscript
# file because it is in the end of this template anyway.

###########################################################################
# If the user menus are not needed/wished for a Blend (like for instance
# Debian Edu there is no need to install blends-common package.  Thus we
# have to make sure that postinst does not try to include the menu stuff
if [ -d /etc/blends -a -f /etc/blends/blends.conf ] ; then
    # Also verify that this Blend provides special configuration
    # If not there is no need to execute the user menu code
    if [ -d /etc/blends/ezgo -a -f /etc/blends/ezgo/ezgo.conf ] ; then

	test -x /usr/sbin/blend-update-menus && blend-update-menus --blend ezgo 

	test -s /etc/blends/blends.conf         && . /etc/blends/blends.conf
	test -s /etc/blends/ezgo/ezgo.conf && . /etc/blends/ezgo/ezgo.conf

	if [ -x /usr/sbin/blend-update-usermenus ] ; then
	    # Initialize debconf if not yet done
	    if [ _"$DEBCONF_REDIR" = _"" ]; then
    		. /usr/share/debconf/confmodule
    		db_version 2.0
	    fi

	    . /etc/blends/blends.conf
	    if [ -s /etc/blends/ezgo/ezgo.conf ] ; then . /etc/blends/ezgo/ezgo.conf ; fi

	    case "$1" in
		abort-install|abort-upgrade|failed-upgrade|upgrade)
		    ;;
		remove|purge)
		    db_get "shared/ezgo-config/usermenus" || true
		    case "$RET" in
			"Each package installation")
			    blend-update-usermenus ezgo
			;;
			"End of installation")
			    touch /var/run/ezgo-config.usermenu
			;;
		    esac
		    ;;
		*)
		    echo "postrm called with unknown argument \`$1'" >&2
		    exit 1
		    ;;
	    esac
	fi
    fi
fi


