#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.3.5
dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/youtube-dl.bash-completion 2016.08.17-1\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/fish/completions/youtube-dl.fish 2016.08.17-1\~ -- "$@"
# End automatically added section
