#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/ceilometer-agent-notification" ] && [ "$1" = remove ]; then
	invoke-rc.d ceilometer-agent-notification stop || true
fi
# End automatically added section
