#!/bin/sh
set -e

# Automatically added by dh_installdebconf
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


aliasfile=/etc/X11/fonts/misc/xfonts-base.alias

case "$1" in
purge)
	for file in	/etc/X11/app-defaults/XTerm \
			/etc/X11/fonts/misc/xfonts-base.alias; do
		rm -f $file.tmp
		for f in $file.trad $file.old.not-trad $file.backup.trad;
			do rm -f $f $f.tmp
		done
	done
	;;
esac
