#!/bin/sh
set -e

if [ "$1" = "remove" ]; then
    update-alternatives --remove php /usr/bin/hhvm
fi

# Automatically added by dh_installinit/11.3.5
if [ -x "/etc/init.d/hhvm" ] && [ "$1" = remove ]; then
	invoke-rc.d hhvm stop || exit 1
fi
# End automatically added section

