#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper symlink_to_dir /usr/share/doc/python3-regex python-regex 0.1.20171212-2\~ -- "$@"
# End automatically added section
