#! /bin/sh

set -e

case "$1" in
purge)
    rm -f /etc/default/krb5-admin-server
    ;;
esac

# Automatically added by dh_installinit/12
if [ "$1" = "purge" ] ; then
	update-rc.d krb5-admin-server remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_systemd_enable/12
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'krb5-admin-server.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'krb5-admin-server.service' >/dev/null || true
		deb-systemd-helper unmask 'krb5-admin-server.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installdebconf/12
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

