#!/bin/sh
set -e
# Automatically added by dh_installinit/11.5.3
if [ -x "/etc/init.d/clamav-milter" ] && [ "$1" = remove ]; then
	invoke-rc.d clamav-milter stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installdeb/11.5.3
dpkg-maintscript-helper rm_conffile /etc/default/clamav-milter 0.98.5\~beta1\+dfsg-3\~ clamav-milter -- "$@"
# End automatically added section
