#!/bin/sh -e
set -e

if [ x"$1" = "xpurge" ]; then
  rm -rf /etc/dqcache /var/lib/dqcache
  deluser --force dqcache || :
fi

# Automatically added by dh_installsystemd/11.4.1
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.4.1
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'dqcache.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'dqcache.service' >/dev/null || true
		deb-systemd-helper unmask 'dqcache.service' >/dev/null || true
	fi
fi
# End automatically added section

