#!/bin/sh
set -e
# Automatically added by installdeb-aspell
SCRIPT="update-dictcommon-aspell"

if [ "$1" = "configure" ] ; then
    if which $SCRIPT > /dev/null 2>&1; then
	$SCRIPT  
    else
	echo "Error: $SCRIPT not present or executable. Missing dependency on dictionaries-common?" >&2
	exit 1
    fi
fi
# End automatically added section
# Automatically added by installdeb-aspell
dico_class="aspell"
dico_compat="uk.compat"

for i in $dico_compat; do
    if [ "$1" = "reconfigure" ] || [ -n "$DEBCONF_RECONFIGURE" ] || [ ! -e "/var/lib/$dico_class/$i" ]
    then
	>"/var/lib/$dico_class/$i"
    fi
done
# End automatically added section
