#!/bin/sh

set -e

if [ "$1" = "configure" ]; then
    if ! getent group oslo > /dev/null 2>&1; then
        addgroup --system oslo > /dev/null
    fi
    if ! getent passwd oslo > /dev/null 2>&1; then
        adduser --system --home /var/lib/oslo --ingroup oslo \
            --no-create-home --shell /bin/false oslo
    fi
fi

# Automatically added by dh_systemd_enable/10.10.9
# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask 'oslo-messaging-zmq-receiver.service' >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled 'oslo-messaging-zmq-receiver.service'; then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable 'oslo-messaging-zmq-receiver.service' >/dev/null || true
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'oslo-messaging-zmq-receiver.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/10.10.9
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/oslo-messaging-zmq-receiver" ]; then
		update-rc.d oslo-messaging-zmq-receiver defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d oslo-messaging-zmq-receiver $_dh_action || true
	fi
fi
# End automatically added section

