#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.5.3
dpkg-maintscript-helper rm_conffile /etc/apparmor.d/torbrowser.start-tor-browser 0.2.8-5~ torbrowser-launcher -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.5.3
dpkg-maintscript-helper rm_conffile /etc/apparmor.d/usr.bin.torbrowser-launcher 0.2.8-4~ torbrowser-launcher -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.5.3
dpkg-maintscript-helper rm_conffile /etc/apparmor.d/local/torbrowser.Browser.firefox 0.2.9-5~ torbrowser-launcher -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.5.3
dpkg-maintscript-helper rm_conffile /etc/apparmor.d/local/torbrowser.Browser.plugin-container 0.2.9-5~ torbrowser-launcher -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.5.3
dpkg-maintscript-helper rm_conffile /etc/apparmor.d/local/torbrowser.Tor.tor 0.2.9-5~ torbrowser-launcher -- "$@"
# End automatically added section
