#!/bin/sh

set -e

if [ "$1" = purge ]; then
    dpkg-statoverride --remove /var/cache/forked-daapd

    if [ -d /var/cache/forked-daapd ]; then
	rm -f /var/cache/forked-daapd/songs3.db
	rmdir --ignore-fail-on-non-empty /var/cache/forked-daapd
    fi
fi

# Automatically added by dh_installinit/10.10.9
if [ "$1" = "purge" ] ; then
	update-rc.d forked-daapd remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/10.10.9
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'forked-daapd.service' >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'forked-daapd.service' >/dev/null
		deb-systemd-helper unmask 'forked-daapd.service' >/dev/null
	fi
fi
# End automatically added section

