#!/bin/sh
set -e
# Automatically added by dh_installwm
if [ "$1" = "remove" ]; then
	update-alternatives --remove x-window-manager /usr/bin/cinnamon-session-cinnamon2d
fi
# End automatically added section
# Automatically added by dh_installwm
if [ "$1" = "remove" ]; then
	update-alternatives --remove x-window-manager /usr/bin/cinnamon-session-cinnamon
fi
# End automatically added section
