#!/bin/sh

set -e

# Code for meeting decision of technical committee for doc symlink transition from FSSTND to FHS
# No longer required

#if [ "$1" = "configure" ]; then
#  if [ -d /usr/doc -a ! -e /usr/doc/aranym -a -d /usr/share/doc/aranym ]; then
#    ln -sf ../share/doc/aranym /usr/doc/aranym
#  fi
#fi

# Automatically added by dh_installmenu/11.1.3
if [ "$1" = "configure" ] && [ -x "`which update-menus 2>/dev/null`" ]; then
	update-menus
fi
# End automatically added section


