#!/bin/sh
set -e
# Automatically added by dh_installinit/11.4.1
if [ "$1" = "purge" ] ; then
	update-rc.d avahi-dnsconfd remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdeb/11.4.1
dpkg-maintscript-helper rm_conffile /etc/default/avahi-dnsconfd 0.6.26-1\~ avahi-dnsconfd -- "$@"
# End automatically added section
# Automatically added by dh_systemd_enable/11.4.1
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'avahi-dnsconfd.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'avahi-dnsconfd.service' >/dev/null || true
		deb-systemd-helper unmask 'avahi-dnsconfd.service' >/dev/null || true
	fi
fi
# End automatically added section
