#!/bin/sh
set -e
# Automatically added by dh_installinit/11.4
if [ -x "/etc/init.d/redis-sentinel" ] && [ "$1" = remove ]; then
	invoke-rc.d redis-sentinel stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installdeb/11.4
dpkg-maintscript-helper rm_conffile /etc/redis/redis-sentinel.post-down.d/00_example 4:4.0.2-3\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/redis/redis-sentinel.post-up.d/00_example 4:4.0.2-3\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/redis/redis-sentinel.pre-down.d/00_example 4:4.0.2-3\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/redis/redis-sentinel.pre-up.d/00_example 4:4.0.2-3\~ -- "$@"
# End automatically added section
