#!/bin/sh

set -e

if [ "$1" = "configure" ]
then
        CLOJUREVER=1.9
        PRIORITY=190
        update-alternatives --install /usr/share/java/clojure.jar \
            libclojure /usr/share/java/clojure-${CLOJUREVER}.jar ${PRIORITY}
fi

