#!/bin/sh -e

if [ \( "$1" = "upgrade" -o "$1" = "remove" \) -a -L /usr/doc/nas ]; then
 	rm -f /usr/doc/nas
fi

# Automatically added by dh_installinit
if [ -x "/etc/init.d/nas" ]; then
	invoke-rc.d nas stop || exit $?
fi
# End automatically added section

