#!/bin/sh
set -e



case "$1" in
       purge)
                echo -n "Removing diffmon cache... "
                echo -n "/var/cache/diffmon"
                rm -rf /var/cache/diffmon
		echo -n ", config file directory"
		rmdir --ignore-fail-on-non-empty /etc/diffmon
                echo ". Done."
esac


