#! /bin/sh
# postrm script for spip
#
# see: dh_installdeb(1)

set -e

case "$1" in
    purge)
        rm -rf /etc/spip /var/lib/spip
    ;;
    *)
    ;;
esac


# Automatically added by dh_apache2/UNDECLARED
if [ "$1" = "purge" ] ; then
	if true; then
		if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
			. /usr/share/apache2/apache2-maintscript-helper

			for conf in spip  ; do
				apache2_invoke disconf $conf  || exit 1
			done
		fi
	fi
fi
# End automatically added section


exit 0

