#!/bin/sh
# based on arpwatch.preinst: v4 2004/08/14 KELEMEN Peter <fuji@debian.org>
# arpalert.preinst: v1 2006/10/12 Jan Wagner <waja@cyconet.org>

set -e

NAME=arpalert
DBDIR=/var/lib/$NAME
DBFILE=arp.dat
BACKUPDIR=/var/backups

# Back up collected ARP databases.
if [ -d $DBDIR -a -d $BACKUPDIR ]; then
	if [ -d $BACKUPDIR/$NAME ]; then
		rm -r $BACKUPDIR/$NAME
	fi
	cp -rp $DBDIR $BACKUPDIR/$NAME
fi


