#!/bin/sh
set -e

case $1 in
	remove)
	dpkg-divert --package ivtools-bin --rename --remove /usr/bin/dclock
	dpkg-divert --package ivtools-bin --rename --remove /usr/share/man/man1/dclock.1.gz
	;;
esac

# Automatically added by dh_installmenu
if [ -x "`which update-menus 2>/dev/null`" ]; then update-menus ; fi
# End automatically added section

