#!/bin/sh
set -e
# Automatically added by dh_installinit/11.3.5
if [ -x "/etc/init.d/alljoyn-daemon-1504" ] && [ "$1" = remove ]; then
	invoke-rc.d alljoyn-daemon-1504 stop || exit 1
fi
# End automatically added section
