#!/bin/sh

set -e
machine_policy=/etc/dbus-1/system.d/org.freedesktop.machine1.conf
if [ "$1" = configure ] && [ -z "$2" ] && [ -f ${machine_policy}.dpkg-bak ] ; then
    md5sum="$(md5sum ${machine_policy} | sed -e 's/ .*//')"
    old_md5sum="$(dpkg-query -W -f='${Conffiles}' systemd-container | \
                        sed -n -e "\' ${machine_policy} ' { s/ obsolete$//; s/.* //; p }")"
    # On new installs, if the policy file was preserved on systemd upgrade
    # by dpkg-maintscript helper, copy it back if the new file has not been modified yet
    if [ "$md5sum" = "$old_md5sum" ] ; then
        mv ${machine_policy}.dpkg-bak ${machine_policy}
    fi
fi

# Enable machines.target by default on new installs and upgrades
if dpkg --compare-versions "$2" lt "232-4~"; then
    systemctl enable machines.target || true
fi

# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	# In case this system is running systemd, we need to ensure that all
	# necessary tmpfiles (if any) are created before starting.
	if [ -d /run/systemd/system ] ; then
		systemd-tmpfiles --create /usr/lib/tmpfiles.d/systemd-nspawn.conf >/dev/null || true
	fi
fi
# End automatically added section

