#!/bin/sh

set -e

if [ "$1" = "purge" ]; then
    if [ -f /etc/debian-edu/xdebian-edu-firstboot ]; then
        rm -f /etc/debian-edu/xdebian-edu-firstboot
    fi
fi

# Automatically added by dh_installinit/11.3.5
if [ "$1" = "purge" ] ; then
	update-rc.d xdebian-edu-firstboot remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installdebconf/11.3.5
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

