#! /bin/sh

set -e

case "$1" in
  purge|remove)
    if dpkg-statoverride --list /usr/games/geki2 >/dev/null; then
      dpkg-statoverride --remove /usr/games/geki2
    fi
    rm -f /var/games/geki2.scores
    ;;
  upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;
  *)
    echo "postrm called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac



