#!/bin/sh
set -e
# Automatically added by dh_installinit/11.1.6
if [ -x "/etc/init.d/pybit-client" ]; then
	invoke-rc.d pybit-client stop || exit 1
fi
# End automatically added section

# Automatically added by dh_python2:
if which pyclean >/dev/null 2>&1; then
	pyclean -p pybit-client 
else
	dpkg -L pybit-client | grep '\.py$' | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section
