#!/bin/sh
set -e
# Automatically added by dh_installdeb/10.8
dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/epix 1.2.16-2\~ -- "$@"
# End automatically added section
# Automatically added by dh_installemacsen/10.8
if [ -e /var/lib/emacsen-common/state/package/installed/emacsen-common -a -x /usr/lib/emacsen-common/emacs-package-remove ] ; then
	/usr/lib/emacsen-common/emacs-package-remove --prerm epix
fi
# End automatically added section
