#!/bin/sh
set -e
# Automatically added by dh_installdeb/10.7.2
dpkg-maintscript-helper rm_conffile /etc/gunicorn.d/django.example 19.6.0-3 gunicorn-examples -- "$@"
dpkg-maintscript-helper rm_conffile /etc/gunicorn.d/wsgi.example 19.6.0-3 gunicorn-examples -- "$@"
# End automatically added section
