#!/bin/sh -e
set -e

rmdir /usr/local/lib/xemacs/site-lisp > /dev/null 2>&1 && \
   rmdir /usr/local/lib/xemacs > /dev/null 2>&1 || \
   true 

if [ -L /usr/lib/xemacs-21.4.24/etc ]; then
	rm -f /usr/lib/xemacs-21.4.24/etc
fi
if [ -L /usr/lib/xemacs-21.4.24/lisp ]; then
	rm -f /usr/lib/xemacs-21.4.24/lisp
fi

##
