#!/bin/sh

set -eu

USER="redis"
GROUP="$USER"
CONFFILE="/etc/redis/sentinel.conf"

if [ "$1" = "configure" ]
then
	if ! dpkg-statoverride --list ${CONFFILE} >/dev/null 2>&1
	then
		dpkg-statoverride --update --add ${USER} ${GROUP} 640 ${CONFFILE}
	fi
fi

# Automatically added by dh_systemd_enable/10.10.9
# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask 'redis-sentinel.service' >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled 'redis-sentinel.service'; then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable 'redis-sentinel.service' >/dev/null || true
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'redis-sentinel.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/10.10.9
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/redis-sentinel" ]; then
		update-rc.d redis-sentinel defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d redis-sentinel $_dh_action || exit $?
	fi
fi
# End automatically added section
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/redis/redis-sentinel.pre-up.d/00_example 4:4.0.2-3\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/redis/redis-sentinel.pre-down.d/00_example 4:4.0.2-3\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/redis/redis-sentinel.post-up.d/00_example 4:4.0.2-3\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/redis/redis-sentinel.post-down.d/00_example 4:4.0.2-3\~ -- "$@"
# End automatically added section


if [ "$1" = "configure" ]
then
	find /etc/redis -maxdepth 1 -type d -name 'redis-sentinel.*.d' -empty -delete
fi

exit 0
