#!/bin/sh

set -e

if [ "$1" = "upgrade" ] || [ "$1" = "configure" ]; then
    update-alternatives --quiet --remove mipsel-linux-gnu-gcc /usr/bin/mipsel-linux-gnu-gcc-5
    update-alternatives --quiet --remove mipsel-linux-gnu-gcov /usr/bin/mipsel-linux-gnu-gcov-5
fi



exit 0
