#!/bin/sh

set -e

# Lock user account
if [ "$1" = "purge" ]; then
	usermod -L -e 1 bucardo
fi

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d bucardo remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section


