#!/bin/sh -e

if [ "$1" = "purge" ]; then
	rm -f /etc/iftab
fi

# Automatically added by dh_installinit/11.4
if [ "$1" = "purge" ] ; then
	update-rc.d ifrename remove >/dev/null
fi
# End automatically added section

