#!/bin/sh

set -e



if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ]; then
    if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
        . /usr/share/apache2/apache2-maintscript-helper
        apache2_invoke dismod zembperl
    fi
fi

exit 0
