#!/bin/sh
set -e

# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p antimony 
fi
if which pypy3compile >/dev/null 2>&1; then
	pypy3compile -p antimony  || true
fi

if which py3compile >/dev/null 2>&1; then
	py3compile -p antimony /usr/share/antimony
fi
if which pypy3compile >/dev/null 2>&1; then
	pypy3compile -p antimony /usr/share/antimony || true
fi

# End automatically added section
