#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/ftp-proxy" ]; then
		update-rc.d ftp-proxy defaults >/dev/null
		invoke-rc.d ftp-proxy start || exit $?
	fi
fi
# End automatically added section
