#!/bin/sh -e

if [ "$1" = "purge" ]; then
  rm -rf /var/lib/zorp/keybridge-cache/
  rmdir /var/lib/zorp
fi

# Automatically added by dh_installinit/10.6.4
if [ "$1" = "purge" ] ; then
	update-rc.d zorp remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section

