#!/bin/bash
set -e

fix_named_conf() {
    # The following sed script:
    #   - scopes the named.conf changes to dynamic-db
    #   - replaces arg "name value" syntax with name "value"
    #   - changes dynamic-db header to dyndb
    #   - uses the new way the define path to the library
    #   - removes no longer supported arguments (library, cache_ttl,
    #       psearch, serial_autoincrement, zone_refresh)

    while read -r PATTERN
    do
        SEDSCRIPT+="$PATTERN"
    done <<EOF
/^\s*dynamic-db/,/};/ {
  s/\(\s*\)arg\s\+\(["']\)\([a-zA-Z_]\+\s\)/\1\3\2/g;
  s/^dynamic-db/dyndb/;
  s@\(dyndb "[^"]\+"\)@\1 "/usr/lib/bind/ldap.so"@;
  s@\(dyndb '[^']\+'\)@\1 '/usr/lib/bind/ldap.so'@;
  /\s*library[^;]\+;/d;
  /\s*cache_ttl[^;]\+;/d;
  /\s*psearch[^;]\+;/d;
  /\s*serial_autoincrement[^;]\+;/d;
  /\s*zone_refresh[^;]\+;/d;
}
EOF
    sed -i.bak -e "$SEDSCRIPT" /etc/bind/named.conf
}

if [ $1 = "configure" ]; then
    chown root:bind /var/cache/bind/dynamic /var/cache/bind/dyndb-ldap
    chmod 0770 /var/cache/bind/dynamic /var/cache/bind/dyndb-ldap

    if dpkg --compare-versions "$2" lt "11.1-4"; then
        fix_named_conf
    fi
fi


