#!/bin/sh
set -e
. /usr/share/debconf/confmodule
blis_pri=37

update-alternatives --install /usr/lib/x86_64-linux-gnu/libblas.so \
                    libblas.so-x86_64-linux-gnu \
                    /usr/lib/x86_64-linux-gnu/libblis.so \
                    $blis_pri \
                    --slave /usr/include/x86_64-linux-gnu/cblas.h \
                    cblas.h-x86_64-linux-gnu \
                    /usr/include/x86_64-linux-gnu/cblas-blis.h


exit 0
