#!/bin/sh
set -e
# Automatically added by dh_monoaot
if [ "$1" = "configure" ]
then
	MONOARCH=`mono --version | grep Architecture | sed 's/.*:  //' | sed 's/el,.*//'`
	mkdir -p /usr/lib/mono/aot-cache/${MONOARCH}/
	/usr/bin/mono --aot=outfile=/usr/lib/mono/aot-cache/${MONOARCH}/`basename /usr/lib/mono/4.5/mcs.exe.so` -O=all /usr/lib/mono/4.5/mcs.exe > /dev/null 2>&1 || true
fi
# End automatically added section
