#!/bin/sh
set -e
# Automatically added by dh_monoaot
rm -f /usr/lib/mono/aot-cache/`mono --version | grep Architecture | sed 's/.*:  //' | sed 's/el,.*//'`/`basename /usr/lib/mono/4.5/mcs.exe.so`
# End automatically added section
