#!/bin/sh
set -e
# Automatically added by dh_dkms/UNDECLARED
DKMS_NAME=openrazer-driver
DKMS_VERSION=2.4.0

case "$1" in
    remove|upgrade|deconfigure)
      if [  "$(dkms status -m $DKMS_NAME -v $DKMS_VERSION)" ]; then
         dkms remove -m $DKMS_NAME -v $DKMS_VERSION --all
      fi
    ;;
esac
# End automatically added section
