#!/bin/sh

set -e

CONFIGFILE="/etc/gnarwl.cfg"

# Automatically added by dh_installdebconf/11.4.1
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


if [ "$1" = "purge" ]; then
    for ext in '~' '%' .bak .ucf-new .ucf-old .ucf-dist;  do
        rm -f $CONFIGFILE$ext
    done

    rm -f $CONFIGFILE

    if which ucf >/dev/null; then
        ucf --purge $CONFIGFILE
    fi
fi
