#!/bin/sh
set -e
# Automatically added by dh_installdeb/12
dpkg-maintscript-helper rm_conffile /etc/init.d/glustereventsd 4.0.1-1 -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/12
dpkg-maintscript-helper rm_conffile /etc/init.d/glusterd 4.0.1-1 -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/12
dpkg-maintscript-helper rm_conffile /etc/init.d/glusterfs-server 3.10.1-2 -- "$@"
# End automatically added section
# Automatically added by dh_systemd_start/12
if [ -d /run/systemd/system ]; then
	deb-systemd-invoke stop 'glusterd.service' 'glustereventsd.service' >/dev/null || true
fi
# End automatically added section
