#!/bin/sh

set -e
#set -x

. /usr/share/debconf/confmodule
. /usr/share/dbconfig-common/dpkg/prerm
dbc_go bley $@

# Automatically added by dh_installinit
if [ -x "/etc/init.d/bley" ]; then
	invoke-rc.d bley stop || exit $?
fi
# End automatically added section

# Automatically added by dhpython:
if which pyclean >/dev/null 2>&1; then
	pyclean -p bley 
else
	dpkg -L bley | grep \.py$ | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section

