#!/bin/sh
set -e
# Automatically added by dh_installinit/11.1.4
if [ -x "/etc/init.d/prometheus-bind-exporter" ] && [ "$1" = remove ]; then
	invoke-rc.d prometheus-bind-exporter stop || exit 1
fi
# End automatically added section
