#!/bin/sh
set -e
# Automatically added by dh_installinit/10.9
if [ -x "/etc/init.d/kubelet" ]; then
	invoke-rc.d kubelet stop || exit $?
fi
# End automatically added section
# Automatically added by dh_installinit/10.9
if [ -x "/etc/init.d/kube-proxy" ]; then
	invoke-rc.d kube-proxy stop || exit $?
fi
# End automatically added section
