#!/bin/sh
set -e
# Automatically added by dh_installinit/11.5.3
if [ -x "/etc/init.d/neutron-linuxbridge-agent" ] && [ "$1" = remove ]; then
	invoke-rc.d neutron-linuxbridge-agent stop || true
fi
# End automatically added section
