#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/resiprocate-turn-server" ]; then
	invoke-rc.d resiprocate-turn-server stop || exit $?
fi
# End automatically added section
