#!/bin/sh
set -e

case "$1" in
    remove|upgrade|deconfigure)
        find /usr/share/mma/lib -type f -name .mmaDB -exec rm -f {} \;
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac


# Automatically added by dh_python2:
if which pyclean >/dev/null 2>&1; then
	pyclean -p mma 
else
	dpkg -L mma | grep \.py$ | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section


exit 0
