#!/bin/sh
set -e
# Automatically added by dh_installdeb/10.8
dpkg-maintscript-helper rm_conffile /etc/default/sks 1.1.6-11\~ sks -- "$@"
# End automatically added section
# Automatically added by dh_systemd_start/10.8
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop sks-recon.service >/dev/null
fi
# End automatically added section
# Automatically added by dh_installinit/10.8
if [ -x "/etc/init.d/sks" ] && [ "$1" = remove ]; then
	invoke-rc.d sks stop || exit $?
fi
# End automatically added section
