#!/bin/sh
# prerm script for citadel-server

set -e

case "$1" in
    remove|upgrade|deconfigure)
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# Automatically added by dh_installinit
if [ -x "/etc/init.d/citadel" ] && [ "$1" = remove ]; then
	invoke-rc.d citadel stop || exit $?
fi
# End automatically added section


exit 0
