#! /bin/sh
# postrm script for liquidsoap
set -e

if [ "$1" = "purge" ] && [ -d /usr/share/liquidsoap ]; then
    if ! rmdir /usr/share/liquidsoap; then
        echo "leaving /usr/share/liquidsoap in place"
    fi
fi

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d liquidsoap remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section

