#!/bin/sh

set -e

# Ask D-Bus to reload its configuration.
if [ "$1" = configure -a -x "/etc/init.d/dbus" ]; then
	invoke-rc.d dbus force-reload || true
fi

# Automatically added by dh_systemd_start/11.3.5
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'fprintd.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
