#!/bin/sh

set -e

if [ "$1" = "configure" ]; then
	ldconfig
        if [ -d /usr/doc -a -h /usr/doc/libshhmsg1 -a -d /usr/share/doc/libshhmsg1 ]; then
                rm -f /usr/doc/libshhmsg1
        fi
fi
# Automatically added by dh_makeshlibs
if [ "$1" = "configure" ]; then
	ldconfig
fi
# End automatically added section


exit 0
