#!/bin/sh
set -e
# Automatically added by dh_systemd_enable
if deb-systemd-helper debian-installed booth-arbitrator.service; then
	# This will only remove masks created by d-s-h on package removal.
	deb-systemd-helper unmask booth-arbitrator.service >/dev/null || true

	if deb-systemd-helper --quiet was-enabled booth-arbitrator.service; then
		# Create new symlinks, if any.
		deb-systemd-helper enable booth-arbitrator.service >/dev/null || true
	fi
fi

# Update the statefile to add new symlinks (if any), which need to be cleaned
# up on purge. Also remove old symlinks.
deb-systemd-helper update-state booth-arbitrator.service >/dev/null || true
# End automatically added section
# Automatically added by dh_systemd_enable
if deb-systemd-helper debian-installed booth.service; then
	# This will only remove masks created by d-s-h on package removal.
	deb-systemd-helper unmask booth.service >/dev/null || true

	if deb-systemd-helper --quiet was-enabled booth.service; then
		# Create new symlinks, if any.
		deb-systemd-helper enable booth.service >/dev/null || true
	fi
fi

# Update the statefile to add new symlinks (if any), which need to be cleaned
# up on purge. Also remove old symlinks.
deb-systemd-helper update-state booth.service >/dev/null || true
# End automatically added section
# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/booth" ]; then
		update-rc.d booth defaults >/dev/null
		invoke-rc.d booth start || exit $?
	fi
fi
# End automatically added section
