#! /bin/sh

set -e

# summary of how this script can be called:
#        * <postrm> `remove'
#        * <postrm> `purge'
#        * <old-postrm> `upgrade' <new-version>
#        * <new-postrm> `failed-upgrade' <old-version>
#        * <new-postrm> `abort-install'
#        * <new-postrm> `abort-install' <old-version>
#        * <new-postrm> `abort-upgrade' <old-version>
#        * <disappearer's-postrm> `disappear' <r>overwrit>r> <new-version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


revert_seedd_conf()
{
    local oldconf='/etc/default/seedd'

    # Check that the old file hasn't already been removed, and that it hasn't
    # been usurped by some other package (which is unlikely, but would be Bad
    # for what we're going to do next).
    [ -e "${oldconf}.dpkg-remove" ] || return 0
    dpkg-query -L bit-babbler | grep -F -q -x "$oldconf" || return 0

    # Put things back to how they started before the upgrade.
    mv "${oldconf}.dpkg-remove" "$oldconf"
}

case "$1" in
    abort-install|abort-upgrade)
	# Version 0.8 adds /etc/bit-babbler/seedd.conf, replacing the previous
	# daemon configuration options which were set in /etc/default/seedd.
	dpkg --compare-versions -- "$2" ge-nl '0.8~' || revert_seedd_conf
    ;;

    remove|purge|upgrade|failed-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# Automatically added by dh_installinit/11.1.4
if [ "$1" = "purge" ] ; then
	update-rc.d seedd remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_start/11.1.4
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/11.1.4
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'seedd-wait.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'seedd-wait.service' >/dev/null || true
		deb-systemd-helper unmask 'seedd-wait.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_systemd_enable/11.1.4
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'seedd.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'seedd.service' >/dev/null || true
		deb-systemd-helper unmask 'seedd.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0

# vi:sts=4:sw=4:noet
