#!/bin/sh
set -e

if [ -x "/etc/init.d/dpm-rfiod" ]; then
	if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
		invoke-rc.d dpm-rfiod stop || exit $?
	else
		/etc/init.d/dpm-rfiod stop || exit $?
	fi
fi


