#!/bin/sh
set -e
# Automatically added by dh_installinit/11.3.5
if [ -x "/etc/init.d/designate-worker" ] && [ "$1" = remove ]; then
	invoke-rc.d designate-worker stop || true
fi
# End automatically added section
