#!/bin/sh

set -e

rm -f /etc/logcheck/ignore.d.*/lirc
rm -f /etc/init.d/lirc
rm -f /etc/*/?0?lircmd
rm -f /etc/*/?0?lircd
rm -rf /usr/lib/*/python3/dist-packages/lirc/__pycache__


# Automatically added by dh_systemd_start/10.9.1
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'irexec.service' 'lircd-setup.service' 'lircd-uinput.service' >/dev/null
fi
# End automatically added section
# Automatically added by dh_installinit/10.9.1
if [ -x "/etc/init.d/lircmd" ] && [ "$1" = remove ]; then
	invoke-rc.d lircmd stop || exit $?
fi
# End automatically added section
# Automatically added by dh_installinit/10.9.1
if [ -x "/etc/init.d/lircd" ] && [ "$1" = remove ]; then
	invoke-rc.d lircd stop || exit $?
fi
# End automatically added section

# Automatically added by dh_python3:
if which py3clean >/dev/null 2>&1; then
	py3clean -p lirc 
else
	dpkg -L lirc | perl -ne 's,/([^/]*)\.py$,/__pycache__/\1.*, or next; unlink $_ or die $! foreach glob($_)'
	find /usr/lib/python3/dist-packages/ -type d -name __pycache__ -empty -print0 | xargs --null --no-run-if-empty rmdir
fi

# End automatically added section

