#!/bin/sh

set -e

if [ "$1" = "upgrade" ] || [ "$1" = "configure" ]; then
    update-alternatives --quiet --remove sparc64-linux-gnu-gcc /usr/bin/sparc64-linux-gnu-gcc-8
    update-alternatives --quiet --remove sparc64-linux-gnu-gcov /usr/bin/sparc64-linux-gnu-gcov-8
fi



exit 0
