#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.3.5
dpkg-maintscript-helper rm_conffile /etc/xdg/autostart/polkit-kde-authentication-agent-1.desktop 0.99.0-4\~ -- "$@"
# End automatically added section
