#!/bin/sh
set -e
# Automatically added by dh_installinit/10.10.5
if [ -x "/etc/init.d/zabbix-agent" ] && [ "$1" = remove ]; then
	invoke-rc.d zabbix-agent stop || exit $?
fi
# End automatically added section
