#!/bin/sh

set -e

if [ "$1" = "configure" ] ; then
	update-alternatives --install /usr/bin/dib-block-device dib-block-device /usr/bin/python3-dib-block-device 200
	update-alternatives --install /usr/bin/dib-lint dib-lint /usr/bin/python3-dib-lint 200
	update-alternatives --install /usr/bin/disk-image-create disk-image-create /usr/bin/python3-disk-image-create 200
	update-alternatives --install /usr/bin/element-info element-info /usr/bin/python3-element-info 200
	update-alternatives --install /usr/bin/ramdisk-image-create ramdisk-image-create /usr/bin/python3-ramdisk-image-create 200
fi


# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p python3-diskimage-builder 
fi

# End automatically added section


exit 0
