#!/bin/sh
set -e
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/an/bing.xml 45.0esr-2~ iceweasel-l10n-an -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/an/ddg.xml 45.0esr-2~ iceweasel-l10n-an -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/an/eBay-es.xml 45.0esr-2~ iceweasel-l10n-an -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/an/google.xml 45.0esr-2~ iceweasel-l10n-an -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/an/twitter.xml 45.0esr-2~ iceweasel-l10n-an -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/an/wikipedia-an.xml 45.0esr-2~ iceweasel-l10n-an -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/an/yahoo-es.xml 45.0esr-2~ iceweasel-l10n-an -- "$@"
# End automatically added section
