#!/bin/sh
# postrm script for sympow-data
set -e
SYMPOW_PKGCACHEDIR=/var/cache/sympow

case "${1}" in
	purge)
    if [ -d $SYMPOW_PKGCACHEDIR ]; then
			rm -rf $SYMPOW_PKGCACHEDIR
		fi
		;;
	*)
		;;
esac
exit 0
