#!/bin/sh
set -e
# Automatically added by dh_installsystemd/11.5.3
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# In case this system is running systemd, we need to ensure that all
	# necessary tmpfiles (if any) are created before starting.
	if [ -d /run/systemd/system ] ; then
		systemd-tmpfiles --create wesnoth-1.14-server.conf >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installinit/11.5.3
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/wesnoth-1.14-server" ]; then
		update-rc.d wesnoth-1.14-server defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d wesnoth-1.14-server $_dh_action || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.5.3
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if deb-systemd-helper debian-installed 'wesnoth-1.14-server.service'; then
		# This will only remove masks created by d-s-h on package removal.
		deb-systemd-helper unmask 'wesnoth-1.14-server.service' >/dev/null || true

		if deb-systemd-helper --quiet was-enabled 'wesnoth-1.14-server.service'; then
			# Create new symlinks, if any.
			deb-systemd-helper enable 'wesnoth-1.14-server.service' >/dev/null || true
		fi
	fi

	# Update the statefile to add new symlinks (if any), which need to be cleaned
	# up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'wesnoth-1.14-server.service' >/dev/null || true
fi
# End automatically added section
