#!/bin/sh
set -e
# Automatically added by dh_installinit/11.5.3
if [ -x "/etc/init.d/wesnoth-1.14-server" ] && [ "$1" = remove ]; then
	invoke-rc.d wesnoth-1.14-server stop || exit 1
fi
# End automatically added section
