#!/bin/sh
# postrm script for prometheus-blackbox-exporter
# Script executed after the package is removed.

set -e

case "$1" in
  purge)
        rm -rf /var/log/prometheus/prometheus-blackbox-exporter.log \
            /var/run/prometheus/prometheus-blackbox-exporter.pid
	# We do NOT remove the system user.
	;;
esac

# Automatically added by dh_installinit/12
if [ "$1" = "purge" ] ; then
	update-rc.d prometheus-blackbox-exporter remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/12
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'prometheus-blackbox-exporter.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'prometheus-blackbox-exporter.service' >/dev/null || true
		deb-systemd-helper unmask 'prometheus-blackbox-exporter.service' >/dev/null || true
	fi
fi
# End automatically added section

