#!/bin/sh
# Remove old /etc/50debian-el file that may still be on systems from
# previous versions of debian-el
set -e

case "$1" in
    configure)

        if [ -f /etc/emacs/site-start.d/50debian-el ]; then 
            rm -f /etc/emacs/site-start.d/50debian-el
        fi
        ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        ;;
esac

# Automatically added by dh_installemacsen
if [ "$1" = "configure" ] && [ -e /var/lib/emacsen-common/state/package/installed/emacsen-common -a -x /usr/lib/emacsen-common/emacs-package-install ]
then
	/usr/lib/emacsen-common/emacs-package-install --postinst debian-el
fi
# End automatically added section

