#!/bin/sh
set -e
# Automatically added by dh_installinit/11.5.3
if [ "$1" = "purge" ] ; then
	update-rc.d davmail remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_icons/11.5.3
if which update-icon-caches >/dev/null 2>&1 ; then
	update-icon-caches /usr/share/icons/davmail.png
fi
# End automatically added section
# Automatically added by dh_systemd_enable/11.5.3
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'davmail.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'davmail.service' >/dev/null || true
		deb-systemd-helper unmask 'davmail.service' >/dev/null || true
	fi
fi
# End automatically added section
