#!/bin/sh

set -e

# Remove old files left behind by previous versions of package
rm -f /usr/lib/python2.3/site-packages/CedarBackup2/*.pyc
rm -f /usr/lib/python2.3/site-packages/CedarBackup2/*.pyo
rm -f /usr/lib/python2.3/site-packages/CedarBackup2/extend/*.pyc
rm -f /usr/lib/python2.3/site-packages/CedarBackup2/extend/*.pyo



