#!/bin/sh
set -e

if [ "$1" = configure ]; then
	. /etc/ikiwiki-hosting/ikiwiki-hosting.conf || true
	if [ -n "$gitdaemondir" ] && [ -n "$gitdaemonuser" ]; then
		adduser --quiet --system --group --no-create-home --home "$gitdaemondir" "$gitdaemonuser"
	fi
fi

# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/ikiwiki-hosting-web" ]; then
		update-rc.d ikiwiki-hosting-web defaults >/dev/null
		invoke-rc.d ikiwiki-hosting-web start || exit $?
	fi
fi
# End automatically added section


a2enmod suexec
a2enmod ssl
if which invoke-rc.d >/dev/null 2>&1; then
	invoke-rc.d apache2 restart
else
	/etc/init.d/apache2 restart
fi
