#!/bin/sh

set -e

. /usr/share/debconf/confmodule
. /usr/share/dbconfig-common/dpkg/prerm.mysql

dbc_go kopano-server $@

# Automatically added by dh_installinit/10.10.2
if [ -x "/etc/init.d/kopano-server" ] && [ "$1" = remove ]; then
	invoke-rc.d kopano-server stop || exit $?
fi
# End automatically added section


