#!/bin/sh
set -e
# Automatically added by dh_installmenu/10.7.2
if [ "$1" = "configure" ] && [ -x "`which update-menus 2>/dev/null`" ]; then
	update-menus
fi
# End automatically added section
# Automatically added by dh_installdeb/10.7.2
dpkg-maintscript-helper rm_conffile /etc/xdg/autostart/nemo-autostart.desktop 2.2.3-3~ -- "$@"
# End automatically added section
