#!/bin/sh
set -e
# Automatically added by dh_systemd_start
if [ -d /run/systemd/system ]; then
	deb-systemd-invoke stop chasquid-smtp.socket chasquid-submission.socket chasquid.service >/dev/null
fi
# End automatically added section
