#!/bin/sh
set -e

if test "$1" = "configure"; then
    if dpkg --compare-versions "$2" lt-nl "2017.7.3~"; then
        # Move salt-minion pki directory (unless configured by the user)
        if test -d /etc/salt/pki/minion && ! grep -rq "^\s*pki_dir:" /etc/salt/minion /etc/salt/minion.d/; then
            mkdir -p /var/lib/salt/pki
            mv /etc/salt/pki/minion /var/lib/salt/pki
        fi
    fi
fi

# Automatically added by dh_installinit/11.1.5
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/salt-minion" ]; then
		update-rc.d salt-minion defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d salt-minion $_dh_action || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.1.5
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# This will only remove masks created by d-s-h on package removal.
	deb-systemd-helper unmask 'salt-minion.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'salt-minion.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'salt-minion.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'salt-minion.service' >/dev/null || true
	fi
fi
# End automatically added section

