#!/bin/sh
set -e
# Automatically added by dh_installinit/11.5.4
if [ "$1" = "purge" ] ; then
	update-rc.d fastnetmon remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.5.4
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'fastnetmon.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'fastnetmon.service' >/dev/null || true
		deb-systemd-helper unmask 'fastnetmon.service' >/dev/null || true
	fi
fi
# End automatically added section
