#!/bin/sh
set -e

# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p tryton-modules-stock-product-location 
fi
if which pypy3compile >/dev/null 2>&1; then
	pypy3compile -p tryton-modules-stock-product-location  || true
fi

# End automatically added section
