#!/bin/sh -e

remove_servers() {
	update-inetd --remove 'kerberos-adm[ \t].*[ \t]/usr/lib/heimdal-servers/kadmind'
	update-inetd --remove 'krb_prop[ \t].*[ \t]/usr/sbin/hpropd'
}

case "$1" in
abort-install | remove | abort-upgrade | upgrade | failed-upgrade | disappear)
	;;
purge)
	# If netbase is not installed, then we don't need to do the remove.
	if command -v update-inetd >/dev/null 2>&1; then
		remove_servers
	fi
	;;
*)
	echo "$0: incorrect arguments: $*" >&2
	exit 1
	;;
esac

if [ "$1" = "purge" ]
then
	rm -f /var/log/heimdal-kdc.log*
	rm -rf /var/lib/heimdal-kdc
	rm -f /etc/heimdal-kdc/.configured
	rm -f /etc/heimdal-kdc/kdc.conf
	rm -f /etc/heimdal-kdc/kadmind.acl
fi

if [ "$1" = "purge" -a -e /usr/share/debconf/confmodule ]; then
    . /usr/share/debconf/confmodule
    db_purge
fi

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d heimdal-kdc remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installdebconf
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

