#!/bin/sh
set -e
# Automatically added by dh_installsystemd/11.5.3
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'prelude-lml.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installdeb/11.5.3
dpkg-maintscript-helper rm_conffile /etc/init.d/prelude-lml 3.1.0-0.1\~ prelude-lml -- "$@"
# End automatically added section
