#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/hr/yahoo.xml 45.0esr-2~ iceweasel-l10n-hr -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/hr/wikipedia-hr.xml 45.0esr-2~ iceweasel-l10n-hr -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/hr/twitter.xml 45.0esr-2~ iceweasel-l10n-hr -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/hr/google.xml 45.0esr-2~ iceweasel-l10n-hr -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/hr/eudict.xml 45.0esr-2~ iceweasel-l10n-hr -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/hr/eBay-en-GB.xml 45.0esr-2~ iceweasel-l10n-hr -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/hr/ddg.xml 45.0esr-2~ iceweasel-l10n-hr -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/hr/bing.xml 45.0esr-2~ iceweasel-l10n-hr -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/hr/amazon-en-GB.xml 45.0esr-2~ iceweasel-l10n-hr -- "$@"
# End automatically added section
