#!/bin/sh
set -e
# Automatically added by dh_installdeb/10.9
dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/yafc 1.3.0-1~ -- "$@"
# End automatically added section
# Automatically added by dh_installmenu/10.9
if [ -x "`which update-menus 2>/dev/null`" ]; then update-menus ; fi
# End automatically added section
