#!/bin/sh
set -e
# Automatically added by dh_installinit/11.5.3
if [ -x "/etc/init.d/gnocchi-metricd" ] && [ "$1" = remove ]; then
	invoke-rc.d gnocchi-metricd stop || true
fi
# End automatically added section
