#!/bin/sh

set -e

if [ "${1}" = purge ] ; then
	rm -f /var/log/ceilometer/ceilometer-agent-central.log*
	[ -d /var/log/ceilometer ] && rmdir --ignore-fail-on-non-empty /var/log/ceilometer
fi

# Automatically added by dh_installinit/11.5.3
if [ "$1" = "purge" ] ; then
	update-rc.d ceilometer-agent-central remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_systemd_enable/11.5.3
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'ceilometer-agent-central.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'ceilometer-agent-central.service' >/dev/null || true
		deb-systemd-helper unmask 'ceilometer-agent-central.service' >/dev/null || true
	fi
fi
# End automatically added section

