#!/bin/sh
set -e
# Automatically added by dh_systemd_enable/10.9
# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask usbguard-dbus.service >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled usbguard-dbus.service; then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable usbguard-dbus.service >/dev/null || true
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state usbguard-dbus.service >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/10.9
# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask usbguard.service >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled usbguard.service; then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable usbguard.service >/dev/null || true
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state usbguard.service >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_start/10.9
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
	if [ -n "$2" ]; then
		_dh_action=try-restart
	else
		_dh_action=start
	fi
	deb-systemd-invoke $_dh_action usbguard-dbus.service usbguard.service >/dev/null || true
fi
# End automatically added section
