#!/bin/sh
set -e
# Automatically added by dh_installinit/11.1.5
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/fetch-crl-boot" ]; then
		update-rc.d fetch-crl-boot defaults-disabled >/dev/null
		invoke-rc.d fetch-crl-boot start || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installinit/11.1.5
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/fetch-crl-cron" ]; then
		update-rc.d fetch-crl-cron defaults >/dev/null
		invoke-rc.d fetch-crl-cron start || exit 1
	fi
fi
# End automatically added section
