#!/bin/sh
set -e
# Automatically added by dh_installdeb/11
dpkg-maintscript-helper rm_conffile /etc/init.d/sudo 1.8.21p2-2\~ -- "$@"
# End automatically added section
# Automatically added by dh_installinit/11
if [ -x "/etc/init.d/sudo-ldap" ] && [ "$1" = remove ]; then
	invoke-rc.d sudo-ldap stop || exit $?
fi
# End automatically added section
