#!/bin/sh
set -e
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper mv_conffile /etc/apache2/mods-available/mod-dnssd.conf /etc/apache2/mods-available/dnssd.conf -- "$@"
dpkg-maintscript-helper mv_conffile /etc/apache2/mods-available/mod-dnssd.load /etc/apache2/mods-available/dnssd.load -- "$@"
# End automatically added section
