#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.1.3
dpkg-maintscript-helper dir_to_symlink /usr/lib/GNUstep/Applications/Grr.app/Resources/English.lproj /usr/share/GNUstep/Grr.app/English.lproj 1.0-1~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.1.3
dpkg-maintscript-helper dir_to_symlink /usr/lib/GNUstep/Applications/Grr.app/Resources/German.lproj /usr/share/GNUstep/Grr.app/German.lproj 1.0-1~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.1.3
dpkg-maintscript-helper dir_to_symlink /usr/lib/GNUstep/Applications/Grr.app/Resources/ArticleOperations.grrc/Resources /usr/share/GNUstep/Grr.app/ArticleOperations.grrc 1.0-1~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.1.3
dpkg-maintscript-helper dir_to_symlink /usr/lib/GNUstep/Applications/Grr.app/Resources/ArticleTable.grrc/Resources /usr/share/GNUstep/Grr.app/ArticleTable.grrc 1.0-1~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.1.3
dpkg-maintscript-helper dir_to_symlink /usr/lib/GNUstep/Applications/Grr.app/Resources/ArticleView.grrc/Resources /usr/share/GNUstep/Grr.app/ArticleView.grrc 1.0-1~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.1.3
dpkg-maintscript-helper dir_to_symlink /usr/lib/GNUstep/Applications/Grr.app/Resources/DatabaseOperations.grrc/Resources /usr/share/GNUstep/Grr.app/DatabaseOperations.grrc 1.0-1~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.1.3
dpkg-maintscript-helper dir_to_symlink /usr/lib/GNUstep/Applications/Grr.app/Resources/DatabaseTreeView.grrc/Resources /usr/share/GNUstep/Grr.app/DatabaseTreeView.grrc 1.0-1~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.1.3
dpkg-maintscript-helper dir_to_symlink /usr/lib/GNUstep/Applications/Grr.app/Resources/Fonts.grrc/Resources /usr/share/GNUstep/Grr.app/Fonts.grrc 1.0-1~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.1.3
dpkg-maintscript-helper dir_to_symlink /usr/lib/GNUstep/Applications/Grr.app/Resources/Proxy.grrc/Resources /usr/share/GNUstep/Grr.app/Proxy.grrc 1.0-1~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.1.3
dpkg-maintscript-helper dir_to_symlink /usr/lib/GNUstep/Applications/Grr.app/Resources/Searching.grrc/Resources /usr/share/GNUstep/Grr.app/Searching.grrc 1.0-1~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.1.3
dpkg-maintscript-helper dir_to_symlink /usr/lib/GNUstep/Applications/Grr.app/Resources/SubscriptionPanel.grrc/Resources /usr/share/GNUstep/Grr.app/SubscriptionPanel.grrc 1.0-1~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.1.3
dpkg-maintscript-helper dir_to_symlink /usr/lib/GNUstep/Applications/Grr.app/Resources/TreeDatabase.grrdb/Resources /usr/share/GNUstep/Grr.app/TreeDatabase.grrdb 1.0-1~ -- "$@"
# End automatically added section
