#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.3.2
dpkg-maintscript-helper rm_conffile /etc/lemonldap-ng/handler-nginx.conf 1.9.1-2\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/lemonldap-ng/handler-apache2.X.conf 1.9.1-2\~ -- "$@"
# End automatically added section
