#!/bin/sh
set -e
# Automatically added by dh_installinit/10.9.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/uwsgi" ]; then
		update-rc.d uwsgi defaults >/dev/null
		invoke-rc.d uwsgi start || exit $?
	fi
fi
# End automatically added section
