#!/bin/sh
set -e
# Automatically added by dh_installdebconf
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section
# Automatically added by dh_installzopeinstance
PKG=zope2.13-sandbox
INSTANCE=sandbox
ZVER=2.13
DATABASE=ZODB

if [ -e /usr/share/debconf/confmodule ]; then
    . /usr/share/debconf/confmodule
fi

[ -n "$(echo $INSTANCE)" ] || exit 1

if command -v invoke-rc.d >/dev/null 2>&1; then
	INVOKE="invoke-rc.d zope$ZVER"
else
	INVOKE="/etc/init.d/zope$ZVER"
fi

case "$1" in
  failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

  upgrade)
    ;;

  remove)
    $INVOKE stop "INSTANCE=$INSTANCE" || true
    dzhandle -z $ZVER remove-instance $INSTANCE || true
    if [ "$DATABASE" = "ZEO" ]; then
	$INVOKE stop "ZEOSERVER=$INSTANCE" || true
        dzhandle -z $ZVER remove-zeoinstance $INSTANCE || true
    fi
    ;;

  purge)
    db_get $PKG/keep-data-on-purge 2>/dev/null || true
    if [ "$RET" = yes ]; then
	    echo >&2 "$PKG is configured to keep the data file on purge"
    else
        if [ "$DATABASE" = "ZEO" ]; then
            dzhandle -z $ZVER purge-zeoinstance $INSTANCE || true
        fi
        rm -rf "/var/lib/zope$ZVER/instance/$INSTANCE" \
               "/var/log/zope$ZVER/$INSTANCE" \
               "/etc/zope$ZVER/$INSTANCE"
    fi
    ;;

  *)
    echo "postrm called with unknown argument \`$1'" >&2
    exit 1

esac
# End automatically added section
