#!/bin/sh
set -e



if [ "$1" = "configure" ]; then
  update-alternatives --install /usr/bin/rasmol rasmol /usr/bin/rasmol-gtk 11
  update-alternatives --install /usr/bin/rasmol rasmol /usr/bin/rasmol-classic 10
fi
