#!/bin/sh

set -e

if [ "${1}" = "configure" ] ; then
	update-alternatives --install /usr/share/puppet/modules/rabbitmq puppet-module-rabbitmq /usr/share/puppet/modules.available/puppetlabs-rabbitmq 500
fi



exit 0
