#!/bin/sh
set -e
# Automatically added by dh_installdeb
dpkg-maintscript-helper mv_conffile /etc/sugarplum/apache.conf /etc/apache2/conf-available/sugarplum.conf 0.9.10-18~ -- "$@"
# End automatically added section
