#!/bin/sh
set -e

# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p geophar 
fi

if which pycompile >/dev/null 2>&1; then
	pycompile -p geophar /usr/share/geophar
fi

# End automatically added section
