#!/bin/sh
set -e
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/eo/amazondotcom.xml 45.0esr-2~ iceweasel-l10n-eo -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/eo/bing.xml 45.0esr-2~ iceweasel-l10n-eo -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/eo/creativecommons.xml 45.0esr-2~ iceweasel-l10n-eo -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/eo/ddg.xml 45.0esr-2~ iceweasel-l10n-eo -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/eo/eBay.xml 45.0esr-2~ iceweasel-l10n-eo -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/eo/google.xml 45.0esr-2~ iceweasel-l10n-eo -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/eo/reta-vortaro.xml 45.0esr-2~ iceweasel-l10n-eo -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/eo/wikipedia-eo.xml 45.0esr-2~ iceweasel-l10n-eo -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/eo/yahoo.xml 45.0esr-2~ iceweasel-l10n-eo -- "$@"
# End automatically added section
