#!/bin/sh
set -e
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ja/yahoo-jp.xml 45.0esr-2~ iceweasel-l10n-ja -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ja/yahoo-jp-auctions.xml 45.0esr-2~ iceweasel-l10n-ja -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ja/wikipedia-ja.xml 45.0esr-2~ iceweasel-l10n-ja -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ja/twitter-ja.xml 45.0esr-2~ iceweasel-l10n-ja -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ja/rakuten.xml 45.0esr-2~ iceweasel-l10n-ja -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ja/oshiete-goo.xml 45.0esr-2~ iceweasel-l10n-ja -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ja/google-jp.xml 45.0esr-2~ iceweasel-l10n-ja -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ja/ddg.xml 45.0esr-2~ iceweasel-l10n-ja -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ja/bing.xml 45.0esr-2~ iceweasel-l10n-ja -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ja/amazon-jp.xml 45.0esr-2~ iceweasel-l10n-ja -- "$@"
# End automatically added section
