#!/bin/sh
set -e
if [ ! -e /var/lib/emacsen-common/state/package/installed/emacsen-common ]; then
    # Fallback to emacsen-common 1.x
    if [ -x /usr/lib/emacsen-common/emacs-package-remove ]; then
	/usr/lib/emacsen-common/emacs-package-remove goby
    fi
else
# Automatically added by dh_installemacsen
if [ -e /var/lib/emacsen-common/state/package/installed/emacsen-common -a -x /usr/lib/emacsen-common/emacs-package-remove ] ; then
	/usr/lib/emacsen-common/emacs-package-remove --prerm goby
fi
# End automatically added section

fi
