#!/bin/sh
set -e
# Automatically added by dh_installinit/10.10.9
if [ -x "/etc/init.d/designate-agent" ] && [ "$1" = remove ]; then
	invoke-rc.d designate-agent stop || true
fi
# End automatically added section
