#!/bin/sh
set -e
# Automatically added by dh_installinit/11.3.2
if [ -x "/etc/init.d/heimdal-kcm" ] && [ "$1" = remove ]; then
	invoke-rc.d heimdal-kcm stop || exit 1
fi
# End automatically added section
