#!/bin/sh

set -e

case "$1" in
    purge)
        rm -fr  \
            /etc/tarantool \
            /var/log/tarantool \
            /var/run/tarantool \
            /var/lib/tarantool
    ;;
esac

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d tarantool remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section


