#!/bin/sh
set -e
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/gl/yahoo-es.xml 45.0esr-2~ iceweasel-l10n-gl -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/gl/wikipedia-gl.xml 45.0esr-2~ iceweasel-l10n-gl -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/gl/google.xml 45.0esr-2~ iceweasel-l10n-gl -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/gl/eBay-es.xml 45.0esr-2~ iceweasel-l10n-gl -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/gl/ddg.xml 45.0esr-2~ iceweasel-l10n-gl -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/gl/creativecommons.xml 45.0esr-2~ iceweasel-l10n-gl -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/gl/amazon-en-GB.xml 45.0esr-2~ iceweasel-l10n-gl -- "$@"
# End automatically added section
