#!/bin/sh
set -e
# Automatically added by dh_installinit/11.4
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/globus-gatekeeper" ]; then
		update-rc.d globus-gatekeeper defaults-disabled >/dev/null
		invoke-rc.d globus-gatekeeper start || exit 1
	fi
fi
# End automatically added section
