#!/bin/sh
set -e
# Automatically added by dh_systemd_start/11.2.1
if [ -d /run/systemd/system ]; then
	deb-systemd-invoke stop 'radium.service' 'rasplit.service' >/dev/null || true
fi
# End automatically added section
