#!/bin/sh
set -e
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/OpenCL/vendors/intel-beignet.icd 0.0~ beignet -- "$@" 0 -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/OpenCL/vendors/intel-beignet.icd 1.0.1-3~ -- "$@"
# End automatically added section
