#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.3.5
dpkg-maintscript-helper mv_conffile /etc/xdg/autostart/evolution-alarm-notify.desktop /etc/xdg/autostart/org.gnome.Evolution-alarm-notify.desktop 3.28.0-4\~ -- "$@"
# End automatically added section
