#!/bin/sh
set -e
# Automatically added by dh_installinit/10.10.9
if [ -x "/etc/init.d/designate-sink" ] && [ "$1" = remove ]; then
	invoke-rc.d designate-sink stop || true
fi
# End automatically added section
