#!/bin/sh
set -e
# Automatically added by dh_installdeb/10.10.5
dpkg-maintscript-helper symlink_to_dir /usr/share/doc/libgnustep-base-dev /usr/share/doc/gnustep-base-common 1.25.0-1\~ libgnustep-base-dev -- "$@"
# End automatically added section
