#! /bin/sh
set -e

case "$1" in
    purge)
	if [ -d /var/games/bombardier ]
	then
	    rm -Rf /var/games/bombardier
	fi
        ;;
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 0
esac

# Automatically added by dh_installmenu/11.2.1
if [ -x "`which update-menus 2>/dev/null`" ]; then update-menus ; fi
# End automatically added section



