#!/bin/sh

set -e

case "$1" in
  configure)
    if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
        . /usr/share/apache2/apache2-maintscript-helper
        apache2_invoke enconf cortado.conf || exit $?
    fi
    ;;
esac

# Automatically added by dh_installdeb
dpkg-maintscript-helper mv_conffile /etc/apache2/conf.d/cortado /etc/apache2/conf-available/cortado.conf -- "$@"
# End automatically added section


