#!/bin/sh

set -e

if [ "$1" = purge ]; then
    # This was the location of native.log in SP2:
    rm -rf /var/log/shibboleth-www
fi

# Automatically added by dh_apache2/UNDECLARED
if [ "$1" = "purge" ] ; then
	if true; then
		if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
			. /usr/share/apache2/apache2-maintscript-helper

			for conf in shib  ; do
				apache2_invoke disconf $conf  || exit 1
			done
		fi
	fi
fi
# End automatically added section
# Automatically added by dh_apache2/UNDECLARED
if [ "$1" = "purge" ] ; then
	if true; then
		if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
			. /usr/share/apache2/apache2-maintscript-helper

			for conf in shib  ; do
				apache2_invoke dismod $conf  || exit 1
			done
		fi
	fi
fi
# End automatically added section

