#! /bin/sh -e
#
# postinst script for Debian python packages.
# Written 1998 by Gregor Hoffleit <flight@debian.org>.
#


# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p xmldiff 
fi

# End automatically added section


exit 0
