#!/bin/sh

set -e

# Automatically added by dh_installinit/11.3.5
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/arc-datadelivery-service" ]; then
		update-rc.d arc-datadelivery-service defaults-disabled >/dev/null
		invoke-rc.d arc-datadelivery-service start || exit 1
	fi
fi
# End automatically added section


dpkg-maintscript-helper rm_conffile /etc/default/arc-datadelivery-service 5.4.2-2 -- "$@"
