#!/bin/sh
set -e

# source debconf library
. /usr/share/debconf/confmodule

if [ "$1" != "upgrade" ]; then

    update-alternatives --remove libblas.so-x86_64-linux-gnu \
                        /usr/lib/x86_64-linux-gnu/libblis.so

fi


exit 0
