#!/bin/sh

set -e

# Remove configuration if package is being purged
if [ "$1" = "purge" ]; then
	rm -f /etc/sbox.conf
	rm -rf /etc/sbox
	rm -f /var/log/sbox.log
fi

# Automatically added by dh_installdebconf
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


exit 0
