#!/bin/sh
set -e
# Automatically added by dh_installdeb/10.10
dpkg-maintscript-helper rm_conffile /etc/init.d/freedombox-create-uap0 0.9.2~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10
dpkg-maintscript-helper rm_conffile /etc/init.d/freedombox-client-proxy 0.0.44 -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10
dpkg-maintscript-helper rm_conffile /etc/init.d/proxy 0.0.43 -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10
dpkg-maintscript-helper rm_conffile /etc/init.d/freedombox-first-run 0.10 -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10
dpkg-maintscript-helper rm_conffile /etc/init.d/first-run 0.0.43 -- "$@"
# End automatically added section
