#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/wide-dhcpv6-server" ] && [ "$1" = remove ]; then
	invoke-rc.d wide-dhcpv6-server stop || true
fi
# End automatically added section
