#!/bin/sh
set -e
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper symlink_to_dir /usr/share/doc/openssh-client-ssh1 /usr/share/doc/openssh-client 1:7.5p1-8~ -- "$@"
# End automatically added section
