#!/bin/sh
set -e

# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p eog-plugin-export-to-folder /usr/lib/x86_64-linux-gnu/eog/plugins
fi

# End automatically added section
