#!/bin/sh
set -e

#
# Skip, if we are not in "configure" state
#
if [ "$1" != "remove" -a "$1" != "purge" ]; then
        exit 0
fi


## Source debconf library
if [ -f /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_version 2.0
fi

# source dbconfig-common stuff
if [ -f /usr/share/dbconfig-common/dpkg/postrm.mysql ]; then
	. /usr/share/dbconfig-common/dpkg/postrm.mysql
	dbc_go simba $@
fi

if [ "$1" = "purge" ]; then
    rm -rf /etc/simba
    rm -rf /var/log/simba.log
    ucf --purge /etc/simba/simba-db.cfg || exit 0
fi

# Automatically added by dh_installdebconf/11.5.3
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

exit 0

