#!/bin/sh
set -e
# Automatically added by dh_installinit/10.10.9
if [ -x "/etc/init.d/openafs-fileserver" ] && [ "$1" = remove ]; then
	invoke-rc.d openafs-fileserver stop || exit $?
fi
# End automatically added section
