#!/bin/sh

set -e



dpkg-maintscript-helper symlink_to_dir \
    /usr/share/doc/globus-gram-job-manager-scripts-doc \
    globus-gram-job-manager-scripts 6.7-2~ \
    globus-gram-job-manager-scripts-doc -- "$@"
