#!/bin/sh

set -e

case "$1" in
    purge)
        rm -rf /var/cache/google-android-build-tools-20-installer
        if [ -e /usr/share/debconf/confmodule ]
        then
            # Source debconf library.
            . /usr/share/debconf/confmodule
            # Unregister the package
            if db_get google-android-installers/mirror; then
                db_unregister google-android-installers/mirror
            fi
        fi
        ;;

    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

# Automatically added by dh_installdebconf
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


exit 0
