#!/bin/sh
# Post-install script for wmaloader

set -e

WMAUSER=wmaloader
WMAHOME=/usr/lib/wmaloader

chgrp "$WMAUSER" "$WMAHOME" 2>/dev/null || addgroup --system "$WMAUSER"
chown "$WMAUSER"."$WMAUSER" "$WMAHOME" 2>/dev/null || \
        adduser --system --home "$WMAHOME" --no-create-home --disabled-password --ingroup "$WMAUSER" "$WMAUSER"

# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/wmaloader" ]; then
		update-rc.d wmaloader defaults >/dev/null
		invoke-rc.d wmaloader start || exit $?
	fi
fi
# End automatically added section

