#!/bin/sh

set -e

if [ "$1" = "remove" ] ; then
	update-alternatives --remove barbican /usr/bin/python2-barbican
fi


# Automatically added by dhpython:
if which pyclean >/dev/null 2>&1; then
	pyclean -p python-barbicanclient 
else
	dpkg -L python-barbicanclient | grep \.py$ | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section


exit 0
