#!/bin/sh
set -e
# Automatically added by dh_installxfonts
if which update-fonts-dir >/dev/null 2>&1; then
	update-fonts-scale Type1;update-fonts-dir --x11r7-layout Type1
fi
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper mv_conffile /etc/X11/fonts/X11R7/Type1/xfonts-tipa.scale /etc/X11/fonts/Type1/xfonts-tipa.scale 2:1.3-14 -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/defoma/hints/xfonts-tipa.hints 2:1.3-14 -- "$@"
# End automatically added section
