#!/bin/sh
set -e
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/lv/ddg.xml 45.0esr-2~ iceweasel-l10n-lv -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/lv/dict-enlv.xml 45.0esr-2~ iceweasel-l10n-lv -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/lv/google.xml 45.0esr-2~ iceweasel-l10n-lv -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/lv/salidzinilv.xml 45.0esr-2~ iceweasel-l10n-lv -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/lv/sslv.xml 45.0esr-2~ iceweasel-l10n-lv -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/lv/wikipedia-lv.xml 45.0esr-2~ iceweasel-l10n-lv -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/lv/yahoo.xml 45.0esr-2~ iceweasel-l10n-lv -- "$@"
# End automatically added section
