#!/bin/sh
set -e

# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p tuned 
fi

if which pycompile >/dev/null 2>&1; then
	pycompile -p tuned /usr/lib/tuned
fi

# End automatically added section
# Automatically added by dh_systemd_enable/10.10.5
# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask 'tuned.service' >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled 'tuned.service'; then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable 'tuned.service' >/dev/null || true
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'tuned.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/10.10.5
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	# In case this system is running systemd, we need to ensure that all
	# necessary tmpfiles (if any) are created before starting.
	if [ -d /run/systemd/system ] ; then
		systemd-tmpfiles --create /usr/lib/tmpfiles.d/tuned.conf >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_systemd_start/10.10.5
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
	deb-systemd-invoke start 'tuned.service' >/dev/null || true
fi
# End automatically added section
