#!/bin/sh
set -e

# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p variety 
fi
if which pypy3compile >/dev/null 2>&1; then
	pypy3compile -p variety  || true
fi

if which py3compile >/dev/null 2>&1; then
	py3compile -p variety /usr/share/variety
fi
if which pypy3compile >/dev/null 2>&1; then
	pypy3compile -p variety /usr/share/variety || true
fi

# End automatically added section
