#!/bin/sh
set -e

# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p ukui-menu 
fi
if which pypy3compile >/dev/null 2>&1; then
	pypy3compile -p ukui-menu  || true
fi

if which py3compile >/dev/null 2>&1; then
	py3compile -p ukui-menu /usr/lib/ukui-menu
fi
if which pypy3compile >/dev/null 2>&1; then
	pypy3compile -p ukui-menu /usr/lib/ukui-menu || true
fi

# End automatically added section
