#!/bin/sh

set -e

if [ "$1" = "configure" ]; then
    if ! getent passwd onionbalance >/dev/null; then
        adduser --quiet --system --group --no-create-home --home /nonexistent onionbalance
        adduser onionbalance debian-tor
    fi
fi

chown onionbalance:adm /var/log/onionbalance
# rwxr-s---
chmod 02750 /var/log/onionbalance


# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p onionbalance 
fi

# End automatically added section
# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/onionbalance" ]; then
		update-rc.d onionbalance defaults >/dev/null
		invoke-rc.d onionbalance start || exit $?
	fi
fi
# End automatically added section


exit 0
