#!/bin/sh -e

# Remove logs and user account on purge

set -e

if [ "$1" = "purge" ]; then
    rm -rf /var/log/onionbalance/
    if getent passwd onionbalance >/dev/null; then
        deluser onionbalance debian-tor
        deluser onionbalance
    fi
fi

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d onionbalance remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section


exit 0
