#!/bin/sh
set -e
# Automatically added by dh_systemd_enable/10.10.7
# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask 'stubby.service' >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled 'stubby.service'; then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable 'stubby.service' >/dev/null || true
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'stubby.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/10.10.7
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/stubby" ]; then
		update-rc.d stubby defaults >/dev/null
		invoke-rc.d stubby start || exit $?
	fi
fi
# End automatically added section
# Automatically added by dh_systemd_start/10.10.7
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
	deb-systemd-invoke start 'stubby.service' >/dev/null || true
fi
# End automatically added section
