#!/bin/sh
set -e
# Automatically added by dh_installinit/10.10.9
if [ -x "/etc/init.d/shairport-sync" ] && [ "$1" = remove ]; then
	invoke-rc.d shairport-sync stop || exit $?
fi
# End automatically added section
