#! /bin/sh

set -e

if [ "$1" = purge ]; then
    rm -rf /var/lib/binfmts
fi

# Automatically added by dh_installdeb/10.7.2
dpkg-maintscript-helper rm_conffile /etc/init/binfmt-support.conf 2.1.8-1~ -- "$@"
# End automatically added section
# Automatically added by dh_installinit/10.7.2
if [ "$1" = "purge" ] ; then
	update-rc.d binfmt-support remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/10.7.2
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask binfmt-support.service >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge binfmt-support.service >/dev/null
		deb-systemd-helper unmask binfmt-support.service >/dev/null
	fi
fi
# End automatically added section


exit 0
