#!/bin/sh

set -e

# Version 1.10.0 starts using defaults-disabled
# Remove rc.d links if upgrading from an older version and the service is
# disabled in /etc/default

if [ -n "$2" ] ; then
	if dpkg --compare-versions "$2" "<<" "1.10.0" ; then
		[ -r /etc/default/dpmcopyd ] && . /etc/default/dpmcopyd
		if [ "${RUN_DPMCOPYDAEMON}" != "yes" ] ; then
			update-rc.d -f dpmcopyd remove >/dev/null
		fi
	fi
fi


