#!/bin/sh

set -e

if [ "$1" = "upgrade" ] ; then
    # If downgrading to version older than 2.6.0-2 stop service first. In this
    # version init scripts was rewritten and swift-init support was dropped
    if dpkg --compare-versions "$2" lt "2.6.0-2" ; then
        echo "Downgrading to < 2.6.0-2, need to stop services first"

        invoke-rc.d swift-container stop || true
        invoke-rc.d swift-container-auditor stop || true
        invoke-rc.d swift-container-reconciler stop || true
        invoke-rc.d swift-container-replicator stop || true
        invoke-rc.d swift-container-sharder stop || true
        invoke-rc.d swift-container-sync stop || true
        invoke-rc.d swift-container-updater stop || true
    fi
fi

# Automatically added by dh_installinit/11.3.5
if [ -x "/etc/init.d/swift-container" ] && [ "$1" = remove ]; then
	invoke-rc.d swift-container stop || true
fi
# End automatically added section
# Automatically added by dh_installinit/11.3.5
if [ -x "/etc/init.d/swift-container-updater" ] && [ "$1" = remove ]; then
	invoke-rc.d swift-container-updater stop || true
fi
# End automatically added section
# Automatically added by dh_installinit/11.3.5
if [ -x "/etc/init.d/swift-container-sync" ] && [ "$1" = remove ]; then
	invoke-rc.d swift-container-sync stop || true
fi
# End automatically added section
# Automatically added by dh_installinit/11.3.5
if [ -x "/etc/init.d/swift-container-sharder" ] && [ "$1" = remove ]; then
	invoke-rc.d swift-container-sharder stop || true
fi
# End automatically added section
# Automatically added by dh_installinit/11.3.5
if [ -x "/etc/init.d/swift-container-replicator" ] && [ "$1" = remove ]; then
	invoke-rc.d swift-container-replicator stop || true
fi
# End automatically added section
# Automatically added by dh_installinit/11.3.5
if [ -x "/etc/init.d/swift-container-reconciler" ] && [ "$1" = remove ]; then
	invoke-rc.d swift-container-reconciler stop || true
fi
# End automatically added section
# Automatically added by dh_installinit/11.3.5
if [ -x "/etc/init.d/swift-container-auditor" ] && [ "$1" = remove ]; then
	invoke-rc.d swift-container-auditor stop || true
fi
# End automatically added section


exit 0
