#!/bin/sh -e
if [ "$1" = "remove" ]; then
# Restore normal write and mesg
dpkg-divert --package orville-write --remove --rename \
--divert /usr/bin/std-mesg /usr/bin/mesg
dpkg-divert --package orville-write --remove --rename \
--divert /usr/share/man/man1/std-mesg.1.gz /usr/share/man/man1/mesg.1.gz
fi

if [ "$1" = "purge" ]; then
rm -f /var/log/write.log
fi

# Automatically added by dh_installdebconf
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

