#! /bin/sh
# postrm script for docbook-html-forms
# Maintainer: Mark Johnson <mrj@debian.org>

set -e

# Automatically added by dh_installcatalogs
if [ "$1" = "purge" ]; then
	rm -f /etc/sgml/docbook-html-forms.cat.old
fi
# End automatically added section


exit 0
