#!/bin/sh
set -e
# Automatically added by dh_installdeb/12
dpkg-maintscript-helper symlink_to_dir /usr/share/doc/elinks elinks-data 0.12\~pre6-11\~ -- "$@"
# End automatically added section
# Automatically added by dh_installmenu/12
if [ -x "`which update-menus 2>/dev/null`" ]; then update-menus ; fi
# End automatically added section
# Automatically added by dh_installdebconf/12
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section
