#!/bin/sh
set -e
# Automatically added by dh_installinit/10.8
if [ -x "/etc/init.d/restorecond" ] && [ "$1" = remove ]; then
	invoke-rc.d restorecond stop || exit $?
fi
# End automatically added section
