#!/bin/sh

set -e

case "$1" in
    configure)
        dpkg-trigger wine
        ;;
    triggered)
        # debian alternatives system
        case -stable in
            -stable)
                PRIORITY=70;;
            -development)
                PRIORITY=50;;
            *)
                echo "-stable unknown"; exit 1;;
        esac

        apps="wineserver
              msiexec
              regedit
              winecfg
              winedbg
              wineboot
              winefile
              winepath
              regsvr32
              wineconsole

              wine64

              wmc
              wrc
              widl
              winecpp
              winegcc
              wineg++
              winedump
              winebuild
              winemaker"

        slaves=
        for app in $apps; do
            slaves="$slaves
                    --slave /usr/bin/$app $app
                            /usr/bin/${app}-stable
                    --slave /usr/share/man/man1/${app}.1.gz ${app}.1.gz
                            /usr/share/man/man1/${app}-stable.1.gz"
        done

        update-alternatives --quiet \
            --install /usr/bin/wine wine /usr/bin/wine-stable $PRIORITY \
            $slaves \
            --slave /usr/share/man/man1/wine.1.gz wine.1.gz \
                    /usr/share/man/man1/wine-stable.1.gz \
            --slave /usr/share/man/de/man1/wine.1.gz wine.de.1.gz \
                    /usr/share/man/de/man1/wine-stable.1.gz \
            --slave /usr/share/man/fr/man1/wine.1.gz wine.fr.1.gz \
                    /usr/share/man/fr/man1/wine-stable.1.gz \
            --slave /usr/share/man/pl/man1/wine.1.gz wine.pl.1.gz \
                    /usr/share/man/pl/man1/wine-stable.1.gz \
            --slave /usr/share/man/de/man1/wineserver.1.gz wineserver.de.1.gz \
                    /usr/share/man/de/man1/wineserver-stable.1.gz \
            --slave /usr/share/man/fr/man1/wineserver.1.gz wineserver.fr.1.gz \
                    /usr/share/man/fr/man1/wineserver-stable.1.gz \
            --slave /usr/share/man/de/man1/winemaker.1.gz winemaker.de.1.gz \
                    /usr/share/man/de/man1/winemaker-stable.1.gz \
            --slave /usr/share/man/fr/man1/winemaker.1.gz winemaker.fr.1.gz \
                    /usr/share/man/fr/man1/winemaker-stable.1.gz \
            --slave /usr/share/icons/hicolor/scalable/apps/wine.svg wine.svg \
                    /usr/share/icons/hicolor/scalable/apps/wine-stable.svg
        ;;
esac



exit 0
