#!/bin/sh

set -e

case "${1}" in
	configure)
		if [ ! -e /var/log/secure ]
		then
			touch /var/log/secure
		fi
		;;

	abort-upgrade|abort-remove|abort-deconfigure)

		;;

	*)
		echo "postinst called with unknown argument \`${1}'" >&2
		exit 1
		;;
esac

# Automatically added by dh_installmenu
if [ "$1" = "configure" ] && [ -x "`which update-menus 2>/dev/null`" ]; then
	update-menus
fi
# End automatically added section
# Automatically added by dh_icons
if which update-icon-caches >/dev/null 2>&1 ; then
	update-icon-caches /usr/share/icons/gadmin-proftpd.png /usr/share/icons/gadmin-proftpd16.png /usr/share/icons/gadmin-proftpd32.png /usr/share/icons/gadmin-proftpd36.xpm /usr/share/icons/gadmin-proftpd48.png /usr/share/icons/gadmin-proftpd64.png
fi
# End automatically added section


exit 0
