#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/rawdns" ]; then
		update-rc.d rawdns defaults >/dev/null
		invoke-rc.d rawdns start || exit $?
	fi
fi
# End automatically added section
