#!/bin/sh

set -e



case "$1" in
    purge)
	# Remove generated fonts material
	rm -rf /var/cache/php-dompdf/fonts
    ;;

    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
