#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/fso-datad" ]; then
		update-rc.d fso-datad defaults >/dev/null
		invoke-rc.d fso-datad start || exit $?
	fi
fi
# End automatically added section
