#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.1.3
dpkg-maintscript-helper dir_to_symlink /usr/share/doc/libmpfi-dev /usr/share/doc/libmpfi-dev-common 1.5.1\+ds-3\~ -- "$@"
# End automatically added section
