#!/bin/sh

set -e

case "$1" in
    purge)
        rm -rf /var/log/celery
        if [ -x "$(command -v deluser)" ]; then
            deluser --quiet --system celery > /dev/null || true
            deluser --group --system --quiet --only-if-empty celery || true
        else
            echo >&2 "not removing celery system account, group and logfiles because deluser command was not found"
        fi
    ;;
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;
    *)
    echo "postrm called with unknown argument \`$1'" >&2
        exit 1
esac

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d celeryd remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d celerybeat remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section


exit 0
