#!/bin/sh

set -e

case "$1" in
    remove)
        vgcfgbackup >/dev/null 2>&1 || :
    ;;
esac

# Automatically added by dh_installsystemd/12
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'blk-availability.service' 'lvm2-monitor.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/12
if [ -x "/etc/init.d/lvm2-lvmpolld" ] && [ "$1" = remove ]; then
	invoke-rc.d lvm2-lvmpolld stop || exit 1
fi
# End automatically added section


exit 0
