#!/bin/sh -e

if [ "$1" = "purge" ] ; then
	# to remain backwards-compatible with inetd and the like:
	if which update-inetd >/dev/null 2>&1; then
		update-inetd --group OTHER --remove '5667\t\tstream\ttcp\tnowait\tnagios\t/usr/sbin/tcpd\t/usr/sbin/nsca -c /etc/nsca.cfg -- inetd' || true
	fi
fi

# Automatically added by dh_installinit/11.3.5
if [ "$1" = "purge" ] ; then
	update-rc.d nsca remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installdebconf/11.3.5
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

