#!/bin/sh
set -e
# Automatically added by dh_installdeb/10.9
dpkg-maintscript-helper rm_conffile /etc/fonts/conf.d/89-tlwg-waree-synthetic.conf 1:0.6.3-1\~ fonts-tlwg-waree -- "$@"
dpkg-maintscript-helper rm_conffile /etc/fonts/conf.avail/89-tlwg-waree-synthetic.conf 1:0.6.3-1\~ fonts-tlwg-waree -- "$@"
# End automatically added section
