#!/bin/sh
set -e
# Automatically added by dh_installinit/11.5.3
if [ -x "/etc/init.d/gnocchi-api" ] && [ "$1" = remove ]; then
	invoke-rc.d gnocchi-api stop || true
fi
# End automatically added section
