#!/bin/sh

set -e

if [ "${1}" = "remove" ] || [ "${1}" = "disappear" ]; then
	update-alternatives --remove puppet-module-ipaclient /usr/share/puppet/modules.available/joshuabaird-ipaclient
fi



exit 0
