#!/bin/sh

set -e

if [ "$1" = "purge" ]; then
    # Remove init.d configuration file
    rm -f /etc/default/isc-dhcp-relay
fi

# Automatically added by dh_installinit/11.5.3
if [ "$1" = "purge" ] ; then
	update-rc.d isc-dhcp-relay remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdebconf/11.5.3
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


exit 0
