#!/bin/sh
# postrm script for gap-scscp
set -e
DAEMONUSER=_gapd
# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d gapd remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section

case "${1}" in
	remove)
		rm -rf /var/run/${DAEMONUSER#_}
		;;
	purge)
		rm -rf /var/run/${DAEMONUSER#_}
		if getent passwd | grep -q "^${DAEMONUSER}:" ; then
			echo -n "Removing ${DAEMONUSER} system account..."
			if [ -x "$(command -v deluser)" ]; then
				DAEMONHOME=$(getent passwd | sed -e '/^'${DAEMONUSER}':/!d' | cut -d: -f6)
				deluser --quiet --system ${DAEMONUSER} || true
				rm -rf ${DAEMONHOME}
				rm -rf /var/log/${DAEMONUSER#_}
				echo " done"
			else
				echo " aborted because deluser command was not found" >&2
			fi
		fi
		;;
	*)
		;;
esac
