#!/bin/sh
set -e
# Automatically added by dh_installinit/11.5.1
if [ "$1" = "purge" ] ; then
	update-rc.d glance-api remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_systemd_enable/11.5.1
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'glance-api.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'glance-api.service' >/dev/null || true
		deb-systemd-helper unmask 'glance-api.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installdebconf/11.5.1
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section
