#!/bin/sh

set -e

update-alternatives --install /usr/bin/editor editor /usr/bin/yi 30 \
     --slave /usr/share/man/man1/editor.1.gz editor.1.gz /usr/share/man/man1/yi.1.gz

# Automatically added by dh_installmenu/11.5.1
if [ "$1" = "configure" ] && [ -x "`which update-menus 2>/dev/null`" ]; then
	update-menus
fi
# End automatically added section


exit 0
