#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.2.1
dpkg-maintscript-helper symlink_to_dir /usr/share/doc/gcompris gcompris-data 1:0.81-1\~ gcompris -- "$@"
# End automatically added section
