#!/bin/sh -e

set -e

. /usr/share/debconf/confmodule

# These are for the generic editor links
update-alternatives --install /usr/bin/editor editor /usr/bin/jove 60 \
  --slave /usr/share/man/man1/editor.1.gz editor.1.gz \
  /usr/share/man/man1/jove.1.gz
update-alternatives --install /usr/bin/emacs emacs /usr/bin/jove 0 \
  --slave /usr/share/man/man1/emacs.1.gz emacs.1.gz \
  /usr/share/man/man1/jove.1.gz

if dpkg --compare-versions "$2" le 4.16.0.70-3.1 ; then
  echo "Reinstalling init script for new runlevels ..." >&2
  # remove old init script symlinks; dh_installinit adds the proper
  # update-rc.d snippet later on
  update-rc.d -f jove remove >/dev/null
fi

# Automatically added by dh_installmenu/10.10.9
if [ "$1" = "configure" ] && [ -x "`which update-menus 2>/dev/null`" ]; then
	update-menus
fi
# End automatically added section
# Automatically added by dh_installinit/10.10.9
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/jove" ]; then
		update-rc.d jove start 20 2 3 4 5 . >/dev/null
		invoke-rc.d jove start || exit $?
	fi
fi
# End automatically added section

