#!/bin/sh

set -e

if [ "$1" = "upgrade" ] || [ "$1" = "configure" ]; then
    update-alternatives --quiet --remove powerpc64le-linux-gnu-gfortran /usr/bin/powerpc64le-linux-gnu-gfortran-7
fi



exit 0
