#!/bin/sh
set -e

# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p python3-eyed3 
fi

# End automatically added section
# Automatically added by dh_installdeb/11.2.1
dpkg-maintscript-helper symlink_to_dir /usr/share/doc/python3-eyed3 python-eyed3 0.8.4-2~ -- "$@"
# End automatically added section
