#!/bin/sh
# prerm script for roundcube
#
# see: dh_installdeb(1)

set -e

. /usr/share/debconf/confmodule
. /usr/share/dbconfig-common/dpkg/prerm 
dbc_go roundcube $@

case "$1" in
    remove|upgrade|deconfigure)
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/roundcube/main.inc.php 1.0.0+dfsg.1-1~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/roundcube/db.inc.php 1.0.0+dfsg.1-1~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper dir_to_symlink /var/lib/roundcube/config /etc/roundcube 1.1.2+dfsg.1-4 -- "$@"
# End automatically added section


exit 0


