#!/bin/sh
set -e

add-shell /usr/bin/xonsh


# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p xonsh 
fi
if which pypy3compile >/dev/null 2>&1; then
	pypy3compile -p xonsh  || true
fi

# End automatically added section

