#!/bin/sh
set -e
if [ -z "$(find /var/cache/command-not-found -mindepth 1)" ]; then
	echo "You need to run 'update-command-not-found' as root to update the cache."
elif [ "$1" = "configure" ] && dpkg --compare-versions $2 lt 0.2.38-1; then
	echo "Your cache files have been deleted for the upgrade."
	rm /var/cache/command-not-found/*.db
fi



# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p command-not-found /usr/share/command-not-found -V 2.5-
fi

# End automatically added section

