#!/bin/sh
set -e
# Automatically added by dh_installdeb/10.7.2
dpkg-maintscript-helper mv_conffile /etc/gplaycli/credentials.conf /etc/gplaycli/gplaycli.conf -- "$@"
# End automatically added section
