#!/bin/sh
set -e
# Automatically added by dh_sysuser/UNDECLARED
# -*- sh -*-
# -*- sh -*-
export CONF_HOME=/var/spool/cron
export CONF_PACKAGE=bcron-run
export CONF_USERNAME=cron

/lib/sysuser-helper/sysuser-helper postinst "$@"
# End automatically added section
# Automatically added by dh_sysuser/UNDECLARED
# -*- sh -*-
# -*- sh -*-
export CONF_HOME=/nonexistent
export CONF_PACKAGE=bcron-run
export CONF_USERNAME=_log-bcron-sched

/lib/sysuser-helper/sysuser-helper postinst "$@"
# End automatically added section
# Automatically added by dh_sysuser/UNDECLARED
# -*- sh -*-
# -*- sh -*-
export CONF_HOME=/nonexistent
export CONF_PACKAGE=bcron-run
export CONF_USERNAME=_log-bcron-spool

/lib/sysuser-helper/sysuser-helper postinst "$@"
# End automatically added section
# Automatically added by dh_sysuser/UNDECLARED
# -*- sh -*-
# -*- sh -*-
export CONF_HOME=/nonexistent
export CONF_PACKAGE=bcron-run
export CONF_USERNAME=_log-bcron-update

/lib/sysuser-helper/sysuser-helper postinst "$@"
# End automatically added section
