#!/bin/sh
set -e;

PACKAGE=sendmail-base;

# do we have debconf?
if [ -f /usr/share/debconf/confmodule ]; then
	DEBCONF=true;
	#. /usr/share/debconf/confmodule;
	#db_stop; # For testing
else
	DEBCONF='';
	fi;

if [ "$1" = "configure" ]; then
		#-----------------------------------------------------------
		# Tell users about new and interesting things...
		if [ -x /usr/share/sendmail/update_notices ]; then
		    /usr/share/sendmail/update_notices $2;
		    fi;

		#-----------------------------------------------------------
		# Create group/user smmta/smmsp iff needed
		touch /etc/mail/tsmmta;
        if ! chown root:smmta /etc/mail/tsmmta 2>/dev/null; then
            addgroup --system --quiet smmta;
            fi;
        if ! chown smmta:smmta /etc/mail/tsmmta 2>/dev/null; then
            adduser --system --ingroup smmta --home "/var/lib/sendmail" \
                --disabled-password \
                --quiet --gecos 'Mail Transfer Agent' smmta;
            fi;
        rm /etc/mail/tsmmta;	
		touch /etc/mail/tsmmsp;
		if ! chown root:smmsp /etc/mail/tsmmsp 2>/dev/null; then
			addgroup --system --quiet smmsp;
			fi;
		if ! chown smmsp:smmsp /etc/mail/tsmmsp 2>/dev/null; then
			adduser --system --ingroup smmsp --home "/var/lib/sendmail" \
				--disabled-password \
				--quiet --gecos 'Mail Submission Program' smmsp;
			fi;
		rm /etc/mail/tsmmsp;

		#-----------------------------------------------------------
		# With a dynamic uid/gid, have to set appropriate ownership herein
		chown root:smmsp /etc/mail/sasl;
		chown root:smmsp /etc/mail/tls;

		if [ -f "/var/run/sendmail/stampdir/reload" ]; then
			chown smmsp:smmsp "/var/run/sendmail/stampdir/reload"
		fi


		#-----------------------------------------------------------
		# Save the current configuration files in safe place...
		if [ -x /etc/cron.daily/sendmail ]; then
			echo "Saving current /etc/mail/sendmail.mc,cf to /var/backups";
			/etc/cron.daily/sendmail || true;
			fi;

		#-----------------------------------------------------------
		# Make sure inetd.conf has sendmail in it (but disabled)
		if [ -x /usr/sbin/update-inetd ]; then
			update-inetd --remove "^587";
			update-inetd --group MAIL --add \
				"smtp\tstream\ttcp\tnowait\troot\t/usr/sbin/sendmail sendmail -Am -bs";
			update-inetd --group MAIL --add \
				"submission\tstream\ttcp\tnowait\troot\t/usr/sbin/sendmail sendmail -Am -bs";
			update-inetd --group MAIL --add \
				"smtps\tstream\ttcp\tnowait\troot\t/usr/sbin/sendmail sendmail -Am -bs";
			update-inetd --group MAIL --multi --disable smtp,smtps,submission;
			fi;	
fi

# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/dhcp3/dhclient-exit-hooks.d/sendmail 8.14.4-2.2\~ -- "$@"
# End automatically added section

