#!/bin/sh
set -e
# Automatically added by dh_installinit/11.3.5
if [ -x "/etc/init.d/prometheus-pushgateway" ] && [ "$1" = remove ]; then
	invoke-rc.d prometheus-pushgateway stop || exit 1
fi
# End automatically added section
