#!/bin/sh

set -e

# Automatically added by dh_installinit/10.10.9
if [ "$1" = "purge" ] ; then
	update-rc.d lldpd remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/10.10.9
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'lldpd.service' >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'lldpd.service' >/dev/null
		deb-systemd-helper unmask 'lldpd.service' >/dev/null
	fi
fi
# End automatically added section


dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/lldpcli.bash-completion 0.7.15~ lldpd -- "$@"

case "$1" in
    purge)
	dpkg-statoverride --remove /usr/sbin/lldpcli
	dpkg-statoverride --quiet --remove /usr/sbin/lldpctl || true
        deluser --system _lldpd || true
        delgroup --system _lldpd || true

        rm -rf /var/run/lldpd
    ;;
    *)
    ;;
esac

exit 0
