#!/bin/sh

TANGO_USER=tango
TANGO_GROUP=tango

set -e
. /usr/share/debconf/confmodule
. /usr/share/dbconfig-common/dpkg/postinst.mysql

# Create the .my.cnf file
dbc_generate_include="template:/var/lib/tango/.my.cnf"
dbc_generate_include_args="-o template_infile=/usr/share/tango-db/my.cnf"
dbc_generate_include_owner="$TANGO_USER:$TANGO_GROUP"
dbc_generate_include_perms="600"
dbc_go tango-db $@

# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/tango-db" ]; then
		update-rc.d tango-db defaults >/dev/null
		invoke-rc.d tango-db start || exit $?
	fi
fi
# End automatically added section

