#!/bin/sh

set -e

create_target_dirs () {
        local VAR_UG_PKG_NAME
        VAR_UG_PKG_NAME=${1}

        # Create /var/{lib,log}/<package>
        if [ ! -d /var/lib/${VAR_UG_PKG_NAME} ] ; then
                mkdir -p /var/lib/${VAR_UG_PKG_NAME}
        fi
        chown root:root /var/lib/${VAR_UG_PKG_NAME}
        chmod 0750 /var/lib/${VAR_UG_PKG_NAME}
        if [ ! -d /var/log/${VAR_UG_PKG_NAME} ] ; then
                mkdir -p /var/log/${VAR_UG_PKG_NAME}
        fi
        chown root:root /var/log/${VAR_UG_PKG_NAME}
        chmod 0750 /var/log/${VAR_UG_PKG_NAME}
}

if [ "$1" = "configure" ] ; then
	create_target_dirs murano-agent
fi

# Automatically added by dh_systemd_enable/11.3.5
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# This will only remove masks created by d-s-h on package removal.
	deb-systemd-helper unmask 'murano-agent.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'murano-agent.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'murano-agent.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'murano-agent.service' >/dev/null || true
	fi
fi
# End automatically added section

# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p murano-agent 
fi

# End automatically added section
# Automatically added by dh_installinit/11.3.5
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/murano-agent" ]; then
		update-rc.d murano-agent defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d murano-agent $_dh_action || true
	fi
fi
# End automatically added section


exit 0
