#!/bin/sh
#
# Copyright (C) 2013 Arthur Vuillard <arthur@hashbang.fr>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#

set -e

if [ "$1" = "remove" ] || [ "$1" = "purge" ]
then
    # Restart incron
  if [ -f /etc/init.d/incron ]; then
    invoke-rc.d incron restart
  fi
fi

if [ "$1" = "purge" ]
then
    rm -f /var/lib/nagios2mantis/spool.sqlite
    rm -f /var/lib/nagios2mantis/nagios2mantis.inotify
    test ! -d /var/lib/nagios2mantis || rmdir --ignore-fail-on-non-empty /var/lib/nagios2mantis 
fi



exit 0
