#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/af/amazondotcom.xml 45.0esr-2~ iceweasel-l10n-af -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/af/bing.xml 45.0esr-2~ iceweasel-l10n-af -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/af/ddg.xml 45.0esr-2~ iceweasel-l10n-af -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/af/eBay.xml 45.0esr-2~ iceweasel-l10n-af -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/af/google.xml 45.0esr-2~ iceweasel-l10n-af -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/af/wikipedia-af.xml 45.0esr-2~ iceweasel-l10n-af -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/af/yahoo.xml 45.0esr-2~ iceweasel-l10n-af -- "$@"
# End automatically added section
