#!/bin/sh

set -e

if [ "$1" = "configure" ] ; then
	update-alternatives --install /usr/bin/barbican barbican /usr/bin/python2-barbican 300
fi


# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p python-barbicanclient 
fi

# End automatically added section


exit 0
