#!/bin/sh
set -e
# Automatically added by dh_installemacsen/11.5.4
if ( [ "$1" = "install" ] || [ "$1" = "upgrade" ] ) \
	&& [ -e /var/lib/emacsen-common/state/package/installed/emacsen-common -a -x /usr/lib/emacsen-common/emacs-package-install ]
then
	/usr/lib/emacsen-common/emacs-package-install --preinst w3m-el-snapshot
fi
# End automatically added section
