#!/bin/sh

set -e


ipmievd_initd_failed() {
	echo "Unable to start ipmievd during installation.  Trying to disable."
	if [ -f /etc/default/ipmievd ] && \
           grep -q ^ENABLED=\"false\" /etc/default/ipmievd ; then
	    :
	else
	    touch /etc/default/ipmievd
	    echo "ENABLED=\"false\"" >> /etc/default/ipmievd
	fi
}

# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/ipmievd" ]; then
		update-rc.d ipmievd defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d ipmievd $_dh_action || ipmievd_initd_failed
	fi
fi
# End automatically added section

