#! /bin/sh
# postinst script for nullmailer
#
# see: dh_installdeb(1)

set -e

. /usr/share/debconf/confmodule
db_version 2.0

umask 022

case "$1" in
    configure|reconfigure)

		db_get shared/mailname
		echo "$RET" > /etc/mailname

		db_get nullmailer/defaultdomain
		if [ "$RET" ]; then
			echo "$RET" > /etc/nullmailer/defaultdomain
		else
			echo -n > /etc/nullmailer/defaultdomain
		fi

		db_get nullmailer/relayhost
		# securely create nullmailer/remotes with mode 0600
		if [ ! -e /etc/nullmailer/remotes ]
		then
			M=$( umask )
			umask 077
			> /etc/nullmailer/remotes
			chown mail:mail /etc/nullmailer/remotes
			umask $M
		fi
		echo "$RET" | sed -r -e ':a s/(\[[^]:]*):/\1=/; ta' \
				     -e 's/[[:space:]]*:[[:space:]]*/\n/g' \
				     -e ':b s/(\[[^]=]*)=/\1:/; tb' \
				     -e 's/[][]//g' > /etc/nullmailer/remotes
		# zap debconf entry, as this key may contain sensitive data.
		db_set nullmailer/relayhost ""

		db_get nullmailer/adminaddr
		if [ "$RET" ]; then
			echo "$RET" > /etc/nullmailer/adminaddr
		else
			echo -n > /etc/nullmailer/adminaddr
		fi

		db_stop

    ;;

    abort-upgrade|abort-remove|abort-deconfigure)

    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# Automatically added by dh_systemd_enable/11
# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask 'nullmailer.service' >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled 'nullmailer.service'; then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable 'nullmailer.service' >/dev/null || true
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'nullmailer.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/11
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	# In case this system is running systemd, we need to ensure that all
	# necessary tmpfiles (if any) are created before starting.
	if [ -d /run/systemd/system ] ; then
		systemd-tmpfiles --create /usr/lib/tmpfiles.d/nullmailer.conf >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_systemd_start/11
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
	deb-systemd-invoke start 'nullmailer.service' >/dev/null || true
fi
# End automatically added section


exit 0
