#! /bin/sh
# postinst script for gnustep-base
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see /usr/share/doc/packaging-manual/
#
# quoting from the policy:
#     Any necessary prompting should almost always be confined to the
#     post-installation script, and should be protected with a conditional
#     so that unnecessary prompting doesn't happen if a package's
#     installation fails and the `postinst' is called with `abort-upgrade',
#     `abort-remove' or `abort-deconfigure'.

setup_config()
{
    f=/etc/GNUstep/gdomap_probes
    if [ ! -f $f ]; then
      if [ ! -d /etc/GNUstep ]; then mkdir /etc/GNUstep; fi
      cat > $f <<EOF
# Addresses to probe for GNUstep name service.
# If this file does not contain any valid addresses, the local networks
# are probed.
EOF
      for ip in `hostname -i`; do
        echo $ip >> $f
      done
    fi
}

case "$1" in
    configure)
	setup_config

    ;;

    abort-upgrade|abort-remove|abort-deconfigure)

    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac

# Automatically added by dh_installdeb/11.3
dpkg-maintscript-helper symlink_to_dir /usr/share/doc/gnustep-base-runtime /usr/share/doc/gnustep-base-common 1.25.0-1\~ gnustep-base-runtime -- "$@"
# End automatically added section
# Automatically added by dh_installinit/11.3
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/gdomap" ]; then
		update-rc.d gdomap defaults-disabled >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d gdomap $_dh_action || exit 1
	fi
fi
# End automatically added section


exit 0
