#!/bin/sh

set -e

case "${1}" in
    purge)
        rm -f /etc/systemd/system/gfmd.service \
              /etc/systemd/system/gfarm-pgsql.service
    ;;
esac

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d gfmd remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask gfmd.service >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge gfmd.service >/dev/null
		deb-systemd-helper unmask gfmd.service >/dev/null
	fi
fi
# End automatically added section

