#! /bin/sh

set -e

if [ "$1" = purge ]; then
        userdel -r asterisk 2>/dev/null || true
        rm -fR /var/log/asterisk

fi

# Automatically added by dh_installinit/11.4
if [ "$1" = "purge" ] ; then
	update-rc.d asterisk remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_systemd_enable/11.4
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'asterisk.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'asterisk.service' >/dev/null || true
		deb-systemd-helper unmask 'asterisk.service' >/dev/null || true
	fi
fi
# End automatically added section

