#!/bin/sh

set -e

TEMPDIR=$(mktemp -d) || exit 1

echo Fetching file...
wget -P $TEMPDIR http://www.opengroup.org/onlinepubs/007908799/download/susv2.tar.bz2

echo Verifying SHA512 checksum...
SHA512SUM="a9de99aa0e5e627012997ef894ebc1777eef752f6be308dea1a19c96aeb1731bccf5ae954eb12aed28155d89731d92f184b697a76df02399d12d9aeb108090de"
[ x"$(sha512sum $TEMPDIR/susv2.tar.bz2 | cut -f1 -d\ )" = x"$SHA512SUM" ] || (rm -rf $TEMPDIR; exit 1)

echo Untarring...
bunzip2 -cd $TEMPDIR/susv2.tar.bz2 | tar xf - -C /usr/share/doc/susv2 --no-same-permissions --no-same-owner

rm -rf $TEMPDIR

# Since the documents don't exist when the install-docs is first run
# we need to re-run install-docs to ensure that the doc-base files
# actually gets registered in the database
if [ -x /usr/sbin/install-docs ]; then
	install-docs --install /usr/share/doc-base/susv2
fi

## Note: Keep debhelper token after so that files exist when they're being
## registered.


