#!/bin/sh
set -e
# Automatically added by dh_installinit/11.1.5
if [ -x "/etc/init.d/wide-dhcpv6-client" ] && [ "$1" = remove ]; then
	invoke-rc.d wide-dhcpv6-client stop || true
fi
# End automatically added section
