#!/bin/sh

set -e

dpkg-maintscript-helper rm_conffile /etc/default/ntopng 1.2.1+dfsg1-1.1 -- "$@"

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d ntopng remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask ntopng.service >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge ntopng.service >/dev/null
		deb-systemd-helper unmask ntopng.service >/dev/null
	fi
fi
# End automatically added section

