#!/bin/sh

set -e

if [ "$1" = "remove" ] ; then
	update-alternatives --remove neutron-vpn-agent /usr/bin/python2-neutron-vpn-agent
	update-alternatives --remove neutron-vpn-netns-wrapper /usr/bin/python2-neutron-vpn-netns-wrapper
	update-alternatives --remove neutron-vyatta-agent /usr/bin/python2-neutron-vyatta-agent
fi


# Automatically added by dh_python2:
if which pyclean >/dev/null 2>&1; then
	pyclean -p python-neutron-vpnaas 
else
	dpkg -L python-neutron-vpnaas | grep \.py$ | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section


exit 0
