#!/bin/sh
set -e

# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p sabnzbdplus /usr/share/sabnzbdplus
fi

# End automatically added section
# Automatically added by dh_installinit/12
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/sabnzbdplus" ]; then
		update-rc.d sabnzbdplus defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d sabnzbdplus $_dh_action || exit 1
	fi
fi
# End automatically added section
