#!/bin/sh
set -e
# Automatically added by dh_installdeb/11
dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.freedesktop.import1.conf 233-3\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.freedesktop.machine1.conf 233-3\~ -- "$@"
# End automatically added section
