#!/bin/sh
set -e

# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p python3-relatorio 
fi
if which pypy3compile >/dev/null 2>&1; then
	pypy3compile -p python3-relatorio  || true
fi

if which py3compile >/dev/null 2>&1; then
	py3compile -p python3-relatorio /usr/share/python3-relatorio
fi
if which pypy3compile >/dev/null 2>&1; then
	pypy3compile -p python3-relatorio /usr/share/python3-relatorio || true
fi

# End automatically added section
