#!/bin/sh
set -e

# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p qiime 
fi

if which pycompile >/dev/null 2>&1; then
	pycompile -p qiime /usr/lib/qiime -V 2.7-
fi

# End automatically added section
