#!/bin/sh
set -e
# Automatically added by dh_installdeb/12
dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/rados 10.2.5-1\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/rbd 10.2.5-1\~ -- "$@"
# End automatically added section
