#!/bin/sh
set -e
# Automatically added by dh_installdeb/10.9
dpkg-maintscript-helper rm_conffile /etc/gdm3/greeter.gsettings 0.0.39-1 -- "$@"
dpkg-maintscript-helper rm_conffile /etc/X11/Xsession.d/25debian-edu-artwork 0.902-1 -- "$@"
# End automatically added section
