#!/bin/sh
set -e

case "$1" in
  remove)
    ldconfig
    ;;
esac
# Automatically added by dh_installmenu/10.6.4
if [ -x "`which update-menus 2>/dev/null`" ]; then update-menus ; fi
# End automatically added section

