#!/bin/sh
set -e

# Automatically added by dhpython:
if which pycompile >/dev/null 2>&1; then
	pycompile -p wsjt /usr/lib/wsjt -V 2.7
fi

if which pycompile >/dev/null 2>&1; then
	pycompile -p wsjt /usr/share/wsjt
fi

# End automatically added section
