#!/bin/sh

set -e

if [ "$1" = "remove" ] ; then
	update-alternatives --remove murano-pkg-check /usr/bin/python2-murano-pkg-check
fi


# Automatically added by dh_python2:
if which pyclean >/dev/null 2>&1; then
	pyclean -p python-murano-pkg-check 
else
	dpkg -L python-murano-pkg-check | grep \.py$ | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section


exit 0
