#!/bin/sh

set -e

if [ "$1" = "configure" ] ; then
	update-alternatives --install /usr/bin/gflags2man gflags2man /usr/bin/python3-gflags2man 200
fi


# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p python3-gflags 
fi

# End automatically added section


exit 0
