#!/bin/sh
# This script can be called in the following ways:
#
# After the package was installed:
#       <postinst> configure <old-version>
#
#
# If prerm fails during upgrade or fails on failed upgrade:
#       <old-postinst> abort-upgrade <new-version>
#
# If prerm fails during deconfiguration of a package:
#       <postinst> abort-deconfigure in-favour <new-package> <version>
#                  removing <old-package> <version>
#
# If prerm fails during replacement due to conflict:
#       <postinst> abort-remove in-favour <new-package> <version>

set -e

case "$1" in
    configure)
	# Rename old "mandos" user and group
	if dpkg --compare-versions "$2" lt "1.0.3-1"; then
	    case "`getent passwd mandos`" in
		*:Mandos\ password\ system,,,:/nonexistent:/bin/false)
		    usermod --login _mandos mandos
		    groupmod --new-name _mandos mandos
		    ;;
	    esac
	fi
	# Create new user and group
	if ! getent passwd _mandos >/dev/null; then
	    adduser --system --force-badname --quiet \
		--home /nonexistent --no-create-home --group \
		--disabled-password --gecos "Mandos password system" \
		_mandos
	elif dpkg --compare-versions "$2" eq 1.7.4-1 \
		|| dpkg --compare-versions "$2" eq "1.7.4-1~bpo8+1"
	then
	    start=no
	    if ! [ -f /var/lib/mandos/clients.pickle ]; then
		invoke-rc.d mandos stop
		start=yes
	    fi
	    chown _mandos:_mandos /var/lib/mandos/clients.pickle \
		  2>/dev/null || :
	    if [ "$start" = yes ]; then
		invoke-rc.d mandos start
	    fi
	fi
	if ! dpkg-statoverride --list "/var/lib/mandos" >/dev/null \
	     2>&1; then
	    chown _mandos:_mandos /var/lib/mandos
	    chmod u=rwx,go= /var/lib/mandos
	fi
	;;
    
    abort-upgrade|abort-deconfigure|abort-remove)
	;;
    
    *)
	echo "$0 called with unknown argument '$1'" 1>&2
	exit 1
	;;
esac

# Avahi version 0.6.31-2 and older provides "avahi" (instead of
# "avahi-daemon") in its /etc/init.d script header.  To make
# insserv(8) happy, we edit our /etc/init.d script header to contain
# the correct string before the code added by dh_installinit calls
# update.rc-d, which calls insserv.
avahi_version="`dpkg-query --showformat='${Version}' --show avahi-daemon`"
if dpkg --compare-versions "$avahi_version" le 0.6.31-2; then
    sed --in-place --expression='/^### BEGIN INIT INFO$/,/^### END INIT INFO$/s/^\(# Required-\(Stop\|Start\):.*avahi\)-daemon\>/\1/g' /etc/init.d/mandos
fi

# Automatically added by dh_systemd_enable/11.3.5
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# This will only remove masks created by d-s-h on package removal.
	deb-systemd-helper unmask 'mandos.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'mandos.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'mandos.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'mandos.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installinit/11.3.5
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# In case this system is running systemd, we need to ensure that all
	# necessary tmpfiles (if any) are created before starting.
	if [ -d /run/systemd/system ] ; then
		systemd-tmpfiles --create mandos.conf >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installinit/11.3.5
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/mandos" ]; then
		update-rc.d mandos defaults 25 15 >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d mandos $_dh_action || exit 1
	fi
fi
# End automatically added section


exit 0
