#!/bin/sh
set -e
# Automatically added by dh_icons/11
if which update-icon-caches >/dev/null 2>&1 ; then
	update-icon-caches /usr/share/icons/chocolate-doom.png /usr/share/icons/chocolate-setup.png
fi
# End automatically added section
