#!/bin/sh

set -e

adduser --system --group --disabled-password --disabled-login \
	--no-create-home --home /nonexistent --quiet debian-h2o

if ! dpkg-statoverride --list /var/log/h2o >/dev/null; then
	dpkg-statoverride --add root adm 2750 /var/log/h2o 
fi

# Automatically added by dh_installinit/11.3.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/h2o" ]; then
		update-rc.d h2o defaults >/dev/null
		invoke-rc.d h2o start || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.3.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# This will only remove masks created by d-s-h on package removal.
	deb-systemd-helper unmask 'h2o.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'h2o.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'h2o.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'h2o.service' >/dev/null || true
	fi
fi
# End automatically added section


# Gracefully reload any running instances of h2o
if [ -n "$2" ]; then
	invoke-rc.d h2o reload || true
fi

exit 0
