#!/bin/sh
set -e
# Automatically added by dh_elpa/UNDECLARED
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -e /var/lib/emacsen-common/state/package/installed/emacsen-common -a -x /usr/lib/emacsen-common/emacs-package-install ] ; then
		/usr/lib/emacsen-common/emacs-package-install --postinst rabbit-mode
	fi
fi
# End automatically added section
# Automatically added by dh_installdeb/11.3.5
dpkg-maintscript-helper rm_conffile /etc/emacs/site-start.d/50rabbit-mode.el -- "$@"
# End automatically added section
