#!/bin/sh

set -e

dpkg-maintscript-helper rm_conffile /etc/default/ntopng 1.2.1+dfsg1-1.1 -- "$@"

# Automatically added by dh_installinit/11.4.1
if [ "$1" = "purge" ] ; then
	update-rc.d ntopng remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_systemd_enable/11.4.1
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'ntopng.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'ntopng.service' >/dev/null || true
		deb-systemd-helper unmask 'ntopng.service' >/dev/null || true
	fi
fi
# End automatically added section

