#!/bin/sh
set -e

# Automatically added by dh_installinit/10.8
if [ "$1" = "purge" ] ; then
	update-rc.d nsd remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/10.8
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask nsd.service >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge nsd.service >/dev/null
		deb-systemd-helper unmask nsd.service >/dev/null
	fi
fi
# End automatically added section


if test "$1" = "purge"; then
    spool=/var/lib/nsd
    rm -f $spool/nsd.db $spool/ixfr.db $spool/xfrd.state
    rmdir $spool 2>/dev/null || true

    dpkg-statoverride --remove $spool >/dev/null 2>/dev/null || true
fi

exit 0
