#!/bin/bash

set -e

case "$1" in
    purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        rm -rf /var/cache/gbrowse
        
        if [ "$1" = "purge" ] ; then
            update-rc.d gbrowse-slave  remove  > /dev/null
            update-rc.d gbrowse-aws-balancer  remove  > /dev/null
            if [ -e /etc/init.d/gbrowse-slave ] ; then
                rm /etc/init.d/gbrowse-slave
            fi
            if [ -e /etc/default/gbrowse-slave ] ; then
                rm /etc/default/gbrowse-slave
            fi
            if [ -e /usr/share/gbrowse ] ; then
                rm -rf /usr/share/gbrowse
            fi
        fi
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac


# Automatically added by dh_apache2/UNDECLARED
if [ "$1" = "purge" ] ; then
	if true; then
		if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
			. /usr/share/apache2/apache2-maintscript-helper

			for conf in gbrowse  ; do
				apache2_invoke disconf $conf  || exit $?
			done
		fi
	fi
fi
# End automatically added section


