#!/bin/sh

set -e

# remove other ident daemons from inetd
if which update-inetd > /dev/null; then
	update-inetd --remove ident
fi

adduser --system --group --home / --no-create-home --quiet oident

# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/oidentd" ]; then
		update-rc.d oidentd defaults >/dev/null
		invoke-rc.d oidentd start || exit $?
	fi
fi
# End automatically added section

