#!/bin/sh
# post removal script for the Debian GNU/Linux oidentd package

set -e

if which update-inetd > /dev/null; then
	if which identd > /dev/null; then
		update-inetd --add "ident		stream	tcp	nowait	nobody	/usr/sbin/identd identd -i"
	fi
fi

if [ "$1" = purge ]; then
	if which deluser > /dev/null; then
		deluser --system --quiet oident
	fi
fi

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d oidentd remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section

