#!/bin/sh
set -e
# Automatically added by dh_systemd_start/10.9.1
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/10.9.1
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'glacier2router.service' >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'glacier2router.service' >/dev/null
		deb-systemd-helper unmask 'glacier2router.service' >/dev/null
	fi
fi
# End automatically added section
