#!/bin/sh
set -e
# Automatically added by dh_systemd_enable/10.9.1
# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask 'glacier2router.service' >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled 'glacier2router.service'; then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable 'glacier2router.service' >/dev/null || true
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'glacier2router.service' >/dev/null || true
fi
# End automatically added section
