#!/bin/sh
set -e

if [ "$1" = "purge" ] ; then
    # clean up NSS database (see debian/README.Debian for more
    # details)
    rm -f \
       /var/lib/ipsec/nss/*
fi

# Automatically added by dh_systemd_start/10.10.7
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/10.10.7
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'ipsec.service' >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'ipsec.service' >/dev/null
		deb-systemd-helper unmask 'ipsec.service' >/dev/null
	fi
fi
# End automatically added section

