#!/bin/sh
set -e

# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p fs-uae-arcade /usr/share/fs-uae-arcade
fi
if which pypy3compile >/dev/null 2>&1; then
	pypy3compile -p fs-uae-arcade /usr/share/fs-uae-arcade || true
fi

# End automatically added section
