#!/bin/sh
set -e
# Automatically added by dh_installemacsen
if [ "$1" = "configure" ] && [ -e /var/lib/emacsen-common/state/package/installed/emacsen-common ]
then
	/usr/lib/emacsen-common/emacs-package-install --postinst cmuscheme48-el
fi
# End automatically added section
