#!/bin/sh
set -e

if [ "$1" = "remove" ] && [ -x "/bin/systemctl" ]; then
    systemctl stop system-kresd.slice || true
fi

# Automatically added by dh_installinit/11.5.4
if [ "$1" = "purge" ] ; then
	update-rc.d kresd remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.5.4
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.5.4
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'kresd-tls.socket' 'kresd.socket' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'kresd-tls.socket' 'kresd.socket' >/dev/null || true
		deb-systemd-helper unmask 'kresd-tls.socket' 'kresd.socket' >/dev/null || true
	fi
fi
# End automatically added section

