#!/bin/sh

set -e

. /usr/share/debconf/confmodule
db_version 2.0

case "$1" in
	configure)
		db_get "apcupsd/warning" || true
		[ "$RET" = "false" ] && exit 0
		;;

	abort-upgrade|abort-remove|abort-deconfigure)

		;;

	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
		;;
esac

db_stop

# Automatically added by dh_systemd_enable/10.9
# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask apcupsd.service >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled apcupsd.service; then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable apcupsd.service >/dev/null || true
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state apcupsd.service >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/10.9
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/apcupsd" ]; then
		update-rc.d apcupsd defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d apcupsd $_dh_action || exit $?
	fi
fi
# End automatically added section


exit 0
