#!/bin/sh

set -e

if dpkg-maintscript-helper supports mv_conffile 2>/dev/null; then
    dpkg-maintscript-helper mv_conffile \
        /etc/init/radosgw.conf /etc/init/radosgw-instance.conf \
        0.72.1-3~ radosgw -- "$@"
fi

# Automatically added by dh_installinit/12
if [ "$1" = "purge" ] ; then
	update-rc.d radosgw remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdeb/12
dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/radosgw-admin 10.2.5-1\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/init/radosgw-all-starter.conf 10.2.5-1\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/init/radosgw-all.conf 10.2.5-1\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/init/radosgw-instance.conf 10.2.5-1\~ -- "$@"
# End automatically added section
# Automatically added by dh_systemd_start/12
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/12
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'ceph-radosgw.target' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'ceph-radosgw.target' >/dev/null || true
		deb-systemd-helper unmask 'ceph-radosgw.target' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
