#!/bin/sh
set -e
# Automatically added by dh_installinit/11.3.5
if [ -x "/etc/init.d/minissdpd" ] && [ "$1" = remove ]; then
	invoke-rc.d minissdpd stop || exit 1
fi
# End automatically added section
