#!/bin/sh

set -e

. /usr/share/debconf/confmodule

if db_get perlindex/removeindexonpurge; then
    CURRENT=$RET
fi

db_title perlindex configuration

db_set perlindex/removeindexonpurge ${CURRENT:-true}
db_input high perlindex/removeindexonpurge || true
db_go || true
