#!/bin/sh

set -e

if [ "$1" = remove ] || [ "$1" = deconfigure ]; then
	update-alternatives --remove postfwd /usr/sbin/postfwd1
	update-alternatives --remove postfwd /usr/sbin/postfwd2
fi

# Automatically added by dh_installinit
if [ -x "/etc/init.d/postfwd" ]; then
	invoke-rc.d postfwd stop || exit $?
fi
# End automatically added section

