#!/bin/sh
set -e

if dpkg-statoverride --list /lib/systemd-cron/crontab_setgid > /dev/null ; then
    dpkg-statoverride --remove /lib/systemd-cron/crontab_setgid
fi

if [ "$1" = "purge" ]; then 
    rm -f /var/lib/systemd/timers/stamp-cron-*.timer
fi

rm -f /lib/systemd/system-generators/__pycache__/systemd-crontab-generator*.pyc
rmdir /lib/systemd/system-generators/__pycache__/ 2> /dev/null || true

# Automatically added by dh_installsystemd/11.1.5
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.1.5
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'cron.target' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'cron.target' >/dev/null || true
		deb-systemd-helper unmask 'cron.target' >/dev/null || true
	fi
fi
# End automatically added section

