#!/bin/bash
set -e

# Automatically added by dh_installinit/11.4.1
if [ "$1" = "purge" ] ; then
	update-rc.d ovirt-guest-agent remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.4.1
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'ovirt-guest-agent.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'ovirt-guest-agent.service' >/dev/null || true
		deb-systemd-helper unmask 'ovirt-guest-agent.service' >/dev/null || true
	fi
fi
# End automatically added section


if test "x$1" == "xremove" || test "x$1" == "xpurge"; then
    VIRTIO=`grep "^device" /etc/ovirt-guest-agent.conf | awk '{ print $3; }'`
    if [ -w $VIRTIO ]; then
        echo -e '{"__name__": "uninstalled"}\n' | dd of=$VIRTIO oflag=nonblock status=noxfer conv=nocreat 1>& /dev/null || :
    fi
fi
exit 0
