#!/bin/sh
set -e

BINDIR=/usr/bin
case $1 in
remove) update-alternatives --remove acpixtract $BINDIR/acpixtract-acpica
    	update-alternatives --remove acpidump $BINDIR/acpidump-acpica
	;;
*)	;;
esac



exit 0
