#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.5.3
dpkg-maintscript-helper mv_conffile /etc/apache2/conf.d/sitesummary /etc/apache2/conf-available/sitesummary.conf 0.1.10 -- "$@"
# End automatically added section
