#!/bin/sh
set -e
# Automatically added by dh_installinit/11.3.2
if [ -x "/etc/init.d/grr-server@" ]; then
	invoke-rc.d grr-server@ stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installinit/11.3.2
if [ -x "/etc/init.d/grr-server" ]; then
	invoke-rc.d grr-server stop || exit 1
fi
# End automatically added section
# Automatically added by dh_systemd_start/11.3.2
if [ -d /run/systemd/system ]; then
	deb-systemd-invoke stop 'grr-server.service' >/dev/null || true
fi
# End automatically added section

# Automatically added by dh_python2:
if which pyclean >/dev/null 2>&1; then
	pyclean -p grr-server 
else
	dpkg -L grr-server | grep '\.py$' | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section
