#!/bin/sh

set -e

if [ "${1}" = "remove" ] || [ "${1}" = "disappear" ]; then
	update-alternatives --remove puppet-module-rabbitmq /usr/share/puppet/modules.available/puppetlabs-rabbitmq
fi



exit 0
