#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/kk/ddg.xml 45.0esr-2~ iceweasel-l10n-kk -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/kk/flip.xml 45.0esr-2~ iceweasel-l10n-kk -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/kk/google.xml 45.0esr-2~ iceweasel-l10n-kk -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/kk/kaz-kk.xml 45.0esr-2~ iceweasel-l10n-kk -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/kk/twitter.xml 45.0esr-2~ iceweasel-l10n-kk -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/kk/wikipedia-kk.xml 45.0esr-2~ iceweasel-l10n-kk -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/kk/yandex.xml 45.0esr-2~ iceweasel-l10n-kk -- "$@"
# End automatically added section
