#!/bin/sh
set -e
# Automatically added by dh_installinit/11.1.5
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/rawdns" ]; then
		update-rc.d rawdns defaults >/dev/null
		invoke-rc.d rawdns start || exit 1
	fi
fi
# End automatically added section
