#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.4.1
dpkg-maintscript-helper symlink_to_dir /usr/share/horde/js/jquery.mobile/images /usr/share/javascript/jquery-mobile/images 2.27.6\+debian1-1\~ -- "$@"
# End automatically added section
