#! /bin/sh

set -e

if [ "$1" = "remove" ]; then
    [ -f /etc/logrotate.d/syslog-ng ] && mv -f /etc/logrotate.d/syslog-ng /etc/logrotate.d/syslog-ng.disabled

    rm -f /var/lib/syslog-ng/syslog-ng.ctl /var/lib/syslog-ng/syslog-ng.persist
    [ -d /var/lib/syslog-ng/ ] && rmdir --ignore-fail-on-non-empty /var/lib/syslog-ng/
fi

# remove disabled files on purge or complete overwrite.
if [ "$1" = "purge" -o "$1" = "disappear" ]; then
    [ -f /etc/logrotate.d/syslog-ng.disabled ] && rm -f /etc/logrotate.d/syslog-ng.disabled

    rm -f /var/lib/syslog-ng/syslog-ng.ctl /var/lib/syslog-ng/syslog-ng.persist
    [ -d /var/lib/syslog-ng/ ] && rmdir --ignore-fail-on-non-empty /var/lib/syslog-ng/
fi

# Automatically added by dh_installinit/11.4.1
if [ "$1" = "purge" ] ; then
	update-rc.d syslog-ng remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_systemd_enable/11.4.1
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'syslog-ng.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'syslog-ng.service' >/dev/null || true
		deb-systemd-helper unmask 'syslog-ng.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
