#!/bin/sh
set -e
# Automatically added by dh_systemd_enable
if deb-systemd-helper debian-installed direwolf.service; then
	# This will only remove masks created by d-s-h on package removal.
	deb-systemd-helper unmask direwolf.service >/dev/null || true

	if deb-systemd-helper --quiet was-enabled direwolf.service; then
		# Create new symlinks, if any.
		deb-systemd-helper enable direwolf.service >/dev/null || true
	fi
fi

# Update the statefile to add new symlinks (if any), which need to be cleaned
# up on purge. Also remove old symlinks.
deb-systemd-helper update-state direwolf.service >/dev/null || true
# End automatically added section
# Automatically added by dh_systemd_start
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
	deb-systemd-invoke start direwolf.service >/dev/null || true
fi
# End automatically added section
