#!/bin/sh

action=$1
version=$2

## Source debconf library
. /usr/share/debconf/confmodule
if [ -f /usr/share/dbconfig-common/dpkg/config.mysql ]; then
	# source dbconfig-common stuff
	. /usr/share/dbconfig-common/dpkg/config.mysql
	dbc_first_version="0.6.1-1"
	dbc_load_include="perl:/etc/simba/simba-db.cfg"

	dbc_go simba $@
fi


exit 0
