#!/bin/sh

set -e

if ! /usr/bin/getent passwd gkrellmd >/dev/null; then
  useradd --system --no-user-group gkrellmd
fi

# Automatically added by dh_installinit/11.2.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/gkrellmd" ]; then
		update-rc.d gkrellmd defaults 21 >/dev/null
		invoke-rc.d gkrellmd start || exit 1
	fi
fi
# End automatically added section


exit 0
