#!/bin/sh

set -e

if [ "$1" = "purge" ] ; then
	(
		cd /etc/sitesummary
		rm -f config.d/00debconf
		rm -f hostclass site sitecontact sitegroup
		rmdir config.d 2>/dev/null || true
	)
fi

# Automatically added by dh_installinit/11.5.3
if [ "$1" = "purge" ] ; then
	update-rc.d sitesummary-client remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdebconf/11.5.3
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

