#!/bin/sh
set -e
# Automatically added by dh_installsystemd/11.3.5
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.3.5
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'vanguards.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'vanguards.service' >/dev/null || true
		deb-systemd-helper unmask 'vanguards.service' >/dev/null || true
	fi
fi
# End automatically added section
