#!/bin/sh
set -e
# Automatically added by dh_systemd_start/11.3.2
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'thermald.service' >/dev/null || true
fi
# End automatically added section
