#! /bin/sh
#
# postinst script for the Debian idle-python3.6 package.
# Written 1998 by Gregor Hoffleit <flight@debian.org>.
#

set -e

DIRLIST="/usr/lib/python3.6/idlelib"

case "$1" in
    configure|abort-upgrade|abort-remove|abort-deconfigure)

        for i in $DIRLIST ; do
	    /usr/bin/python3.6 /usr/lib/python3.6/compileall.py -q $i
	    if grep -sq '^byte-compile[^#]*optimize' /etc/python/debian_config
	    then
		/usr/bin/python3.6 -O /usr/lib/python3.6/compileall.py -q $i
	    fi
	done
    ;;

    *)
	echo "postinst called with unknown argument \`$1'" >&2
	exit 1
    ;;

esac



exit 0
