#!/bin/sh
set -e
# Automatically added by dh_installinit/11.2.1
if [ -x "/etc/init.d/corosync-qdevice" ] && [ "$1" = remove ]; then
	invoke-rc.d corosync-qdevice stop || exit 1
fi
# End automatically added section
