#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/pcapdump" ]; then
		update-rc.d pcapdump start 90 2 3 4 5 . stop 05 0 1 6 . >/dev/null
		invoke-rc.d pcapdump start || exit $?
	fi
fi
# End automatically added section
