#!/bin/sh

set -e

# Stop the socket on remove so rsyslog is not restarted via socket activation
if [ -d /run/systemd/system ] && [ "$1" = remove ] ; then
	systemctl stop syslog.socket || true
fi

# Automatically added by dh_installinit/11.3.5
if [ -x "/etc/init.d/rsyslog" ] && [ "$1" = remove ]; then
	invoke-rc.d rsyslog stop || exit 1
fi
# End automatically added section

