#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/fso-frameworkd" ]; then
	invoke-rc.d fso-frameworkd stop || exit $?
fi
# End automatically added section

# Automatically added by dhpython:
if which pyclean >/dev/null 2>&1; then
	pyclean -p fso-frameworkd 
else
	dpkg -L fso-frameworkd | grep \.py$ | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section
