#!/bin/sh
set -e
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ar/yahoo.xml 45.0esr-2~ iceweasel-l10n-ar -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ar/wikipedia-ar.xml 45.0esr-2~ iceweasel-l10n-ar -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ar/google.xml 45.0esr-2~ iceweasel-l10n-ar -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ar/eBay.xml 45.0esr-2~ iceweasel-l10n-ar -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ar/ddg.xml 45.0esr-2~ iceweasel-l10n-ar -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ar/bing.xml 45.0esr-2~ iceweasel-l10n-ar -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ar/amazondotcom.xml 45.0esr-2~ iceweasel-l10n-ar -- "$@"
# End automatically added section
