#!/bin/sh

set -e

case "$1" in
    configure|reconfigure)
        adduser --system --disabled-password --disabled-login --home /nonexistent \
       	    --no-create-home --quiet --force-badname --group _serf
        ;;
esac

# Automatically added by dh_installinit/11
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/serf" ]; then
		update-rc.d serf defaults >/dev/null
		invoke-rc.d serf start || exit $?
	fi
fi
# End automatically added section


exit 0
