#!/bin/sh
set -e
# Automatically added by dh_installinit/10.10.9
if [ -x "/etc/init.d/aodh-notifier" ] && [ "$1" = remove ]; then
	invoke-rc.d aodh-notifier stop || true
fi
# End automatically added section
