#!/bin/sh

set -e

# Cleanup the old systemd unit state, if applicable
if dpkg --compare-versions "$2" lt-nl "8.9.5-1~"; then
	if deb-systemd-helper debian-installed drbd.service; then
		deb-systemd-helper purge drbd.service >/dev/null
		deb-systemd-helper unmask drbd.service >/dev/null
	fi
fi

# Disable the DRBD service by default on new installations
if [ -z "$2" ]; then
	update-rc.d drbd defaults >/dev/null || true
	update-rc.d drbd disable >/dev/null || true
fi

# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/drbd" ]; then
		update-rc.d drbd defaults >/dev/null || exit $?
	fi
fi
# End automatically added section

