#!/bin/sh

set -e

. /usr/share/debconf/confmodule

if [ "$1" = "configure" ]; then
    db_get apt-listdifferences/initialize
    test "$RET" = "false" || test ! -z "$2" || apt-listdifferences --initialize
fi


