#!/bin/sh

set -e

if [ "$1" = "configure" ]; then
	adduser --system --quiet --ingroup video --no-create-home --force-badname \
		Debian-tvoe --home /run/tvoe --disabled-password
fi

# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/tvoe" ]; then
		update-rc.d tvoe defaults >/dev/null
		invoke-rc.d tvoe start || exit $?
	fi
fi
# End automatically added section

