#!/bin/sh
set -e
# Automatically added by dh_systemd_start/11
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'autosuspend-detect-suspend.service' 'autosuspend.service' >/dev/null
fi
# End automatically added section
