#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.5.4
dpkg-maintscript-helper symlink_to_dir /usr/share/doc/povray-includes /usr/share/doc/povray 1:3.7.0.0-5\~ -- "$@"
# End automatically added section
