#!/bin/sh

set -e

if [ "${1}" = "remove" ] || [ "${1}" = "disappear" ]; then
	update-alternatives --remove puppet-module-mcollective /usr/share/puppet/modules.available/puppet-community-mcollective
fi



exit 0
