#!/bin/sh

set -e

if [ "${1}" = "configure" ] ; then
	update-alternatives --install /usr/share/puppet/modules/mcollective puppet-module-mcollective /usr/share/puppet/modules.available/puppet-community-mcollective 500
fi



exit 0
