#!/bin/sh
set -e

# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p python3-sympy 
fi
if which pypy3compile >/dev/null 2>&1; then
	pypy3compile -p python3-sympy  || true
fi

# End automatically added section
# Automatically added by dh_installmenu/11.4.1
if [ "$1" = "configure" ] && [ -x "`which update-menus 2>/dev/null`" ]; then
	update-menus
fi
# End automatically added section
