#!/bin/sh
set -e
# Automatically added by dh_installdeb/10.10.5
dpkg-maintscript-helper dir_to_symlink /usr/lib/GNUstep/Applications/Gomoku.app/Resources /usr/share/GNUstep/Gomoku.app 1.2.9-2~ -- "$@"
# End automatically added section
