#!/bin/sh
set -e

# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p epylog 
fi

if which pycompile >/dev/null 2>&1; then
	pycompile -p epylog /usr/share/epylog -V 2.3-
fi

# End automatically added section
