#!/bin/sh
set -e
# Automatically added by dh_installinit/11.5.3
if [ "$1" = "purge" ] ; then
	update-rc.d iwpmd remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.5.3
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
