#!/bin/sh

set -e

case "$1" in
    purge)
        if [ -e /etc/default/wide-dhcpv6-relay ]; then
            rm -f /etc/default/wide-dhcpv6-relay
	fi
        ;;
    *)
        # Nothing to do...
        ;;
esac

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d wide-dhcpv6-relay remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installdebconf
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


exit 0
