#! /bin/sh

set -e

case "$1" in remove)
	rm -f /usr/lib/python3.[01]/*-packages/bsddb3/*.py[co]
esac


# Automatically added by dhpython:
if which py3clean >/dev/null 2>&1; then
	py3clean -p python3-bsddb3 
else
	dpkg -L python3-bsddb3 | perl -ne 's,/([^/]*)\.py$,/__pycache__/\1.*, or next; unlink $_ or die $! foreach glob($_)'
	find /usr/lib/python3/dist-packages/ -type d -name __pycache__ -empty -print0 | xargs --null --no-run-if-empty rmdir
fi

# End automatically added section


exit 0
