#!/bin/sh

set -e

case "$1" in
  configure)
    if ! getent passwd Debian-ufoai >/dev/null; then
      adduser --disabled-password --quiet --system \
        --home /var/games/ufoai-server --no-create-home \
        --gecos "UFO Alien Invasion dedicated server" \
        --ingroup games --force-badname Debian-ufoai
    fi
    install -d /var/games
    install -d /var/games/ufoai-server
    chown Debian-ufoai:games /var/games/ufoai-server
  ;;
  abort-upgrade|abort-remove|abort-deconfigure)
  ;;
  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac

# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/ufoai-server" ]; then
		update-rc.d ufoai-server defaults >/dev/null
		invoke-rc.d ufoai-server start || exit $?
	fi
fi
# End automatically added section

