#!/bin/sh

# This file is based heavily on the wireshark-common postrm script with some
# modifications.

set -e

GROUP=xastir-ax25

if [ "$1" = "purge" ]; then
  if getent group $GROUP >/dev/null; then
    if which delgroup >/dev/null; then
      echo "Removing xastir-ax25 group..."
      delgroup --system $GROUP || echo "Could not remove xastir-ax25 group."
    fi
  fi
fi

# Automatically added by dh_installmenu/10.8
if [ -x "`which update-menus 2>/dev/null`" ]; then update-menus ; fi
# End automatically added section
# Automatically added by dh_installdebconf/10.8
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


