#!/bin/sh

# This file is based heavily on the wireshark-common postinst file with some
# modifications.

set -e

. /usr/share/debconf/confmodule
PROGRAM=/usr/bin/xastir
GROUP=xastir-ax25

# We only care about installing setuid on Linux, as kFreeBSD/Hurd do not have
# native AX.25 interfaces that libax25 can use.

if [ `uname` = Linux ]; then
  if ! dpkg-statoverride --list $PROGRAM > /dev/null; then
      db_get xastir/install-setuid
      if [ -e "$PROGRAM" ]; then
  	if [ "$RET" = "false" ] ; then
  	    chown root:root $PROGRAM
  	    chmod u=rwx,go=rx $PROGRAM
  	else
  	    if ! addgroup --quiet --system $GROUP; then
  		echo "Executing \"addgroup --quiet --system $GROUP\" failed."
  		echo "Most probably the $GROUP group exists, but is not a system group."
  		echo "Please delete the existing group or re-create it as a system group and try configuring xastir again."
  		exit 1
  	    fi
  	    chown root:$GROUP $PROGRAM
  	    if which setcap > /dev/null ; then
                  chmod u=rwx,g=rx,o=r $PROGRAM
                  if ! setcap cap_net_raw,cap_net_admin=eip $PROGRAM; then
  		    echo "Setting capabilities for xastir using Linux Capabilities failed."
  		    echo "Falling back to setting set-user-id bit."
  		    chmod u=rwxs,g=rx,o=r $PROGRAM
                  fi
  	    else
                  chmod u=rwxs,g=rx,o=r $PROGRAM
  	    fi
          fi
      fi
  else
      echo "Preserving owner and mode for $PROGRAM set by dpkg-statoverride:"
      dpkg-statoverride --list $PROGRAM
  fi
fi

# Automatically added by dh_installmenu/10.8
if [ "$1" = "configure" ] && [ -x "`which update-menus 2>/dev/null`" ]; then
	update-menus
fi
# End automatically added section


