#!/bin/sh

set -e

# Regenerate initramfs on upgrade
if [ "$1" = "configure" ]; then

  # We now install config to /usr/share/initramfs-tools instead of
  # /etc/initramfs-tools. This means we have to cleanup. 
  # Do not forget .dpkg-old files.
  D=/etc/initramfs-tools
  for i in \
    $(find $D/hooks -name "bootcdinitramfshook*")  \
    $(find $D/scripts/init-top -name "runbootcdmodprobe*") \
    $(find $D/scripts/init-premount/ -name "runbootcdproberoot*")
  do
    mkdir -p /etc/bootcd/initramfs-tools.oldconfig
    mv $i /etc/bootcd/initramfs-tools.oldconfig
  done

  update-initramfs -u
fi

# Automatically added by dh_systemd_enable
# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask bootcd.service >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled bootcd.service; then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable bootcd.service >/dev/null || true
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state bootcd.service >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/bootcd" ]; then
	update-rc.d bootcd defaults >/dev/null
	invoke-rc.d bootcd start || exit $?
fi
# End automatically added section

