#!/bin/sh
set -e

# Automatically added by dhpython:
if which pycompile >/dev/null 2>&1; then
	pycompile -p glipper 
fi

if which pycompile >/dev/null 2>&1; then
	pycompile -p glipper /usr/share/glipper -V 2.4-
fi

# End automatically added section
