#!/bin/sh
set -e

# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p ddupdate 
fi

if which py3compile >/dev/null 2>&1; then
	py3compile -p ddupdate /usr/share/ddupdate
fi

# End automatically added section
# Automatically added by dh_installsystemd/11.3.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if deb-systemd-helper debian-installed 'ddupdate.timer'; then
		# This will only remove masks created by d-s-h on package removal.
		deb-systemd-helper unmask 'ddupdate.timer' >/dev/null || true

		if deb-systemd-helper --quiet was-enabled 'ddupdate.timer'; then
			# Create new symlinks, if any.
			deb-systemd-helper enable 'ddupdate.timer' >/dev/null || true
		fi
	fi

	# Update the statefile to add new symlinks (if any), which need to be cleaned
	# up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'ddupdate.timer' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.3.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'ddupdate.timer' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.3.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if deb-systemd-helper debian-installed 'ddupdate.service'; then
		# This will only remove masks created by d-s-h on package removal.
		deb-systemd-helper unmask 'ddupdate.service' >/dev/null || true

		if deb-systemd-helper --quiet was-enabled 'ddupdate.service'; then
			# Create new symlinks, if any.
			deb-systemd-helper enable 'ddupdate.service' >/dev/null || true
		fi
	fi

	# Update the statefile to add new symlinks (if any), which need to be cleaned
	# up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'ddupdate.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.3.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'ddupdate.service' >/dev/null || true
	fi
fi
# End automatically added section
