#!/bin/sh 

set -e

# transitional bw compatibility links (1.0.4-6)
SCRIPTS="sb_xmlrpcserver sb_server sb_bnfilter sb_mailsort \
        sb_unheader sb_client sb_filter sb_mboxtrain sb_bnserver \
        sb_chkopts sb_upload sb_dbexpimp sb_imapfilter \
        sb_evoscore"


if [ "$1" = configure ] ; then
    for f in ${SCRIPTS}
    do
        ln -fs /usr/bin/${f} /usr/bin/${f}.py
    done
fi


# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p spambayes 
fi

# End automatically added section

