#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.4.1
dpkg-maintscript-helper rm_conffile /etc/selinux/strict/src/policy/file_contexts/misc/pam_mount.fc 2.16-7\~ libpam-mount -- "$@"
# End automatically added section
