#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/gearman-server" ]; then
		update-rc.d gearman-server defaults >/dev/null
		invoke-rc.d gearman-server start || exit $?
	fi
fi
# End automatically added section
