#!/bin/sh

# exit if any errors occur
set -e

# Automatically added by dh_installdebconf
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section
# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d distributed-net remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section


# Remove the configuration, logs and buffers
if [ "$1" = "purge" ] ; then
	rm -f /var/log/distributed-net*.log*
	rm -rf /var/lib/distributed-net
	rm -f /etc/distributed-net.conf
fi
