#!/bin/sh -e

# Extract the .pfb files
case "$1" in
    configure)
        # remove /usr/share/doc/cm-super directory and make it a link
	if ! [ -L /usr/share/doc/cm-super ] ; then
	  # it should not contain anything by now ...
	  if [ -d usr/share/doc/cm-super ] ; then
	    rmdir /usr/share/doc/cm-super
	    ln -s cm-super-minimal /usr/share/doc/cm-super
	  fi
	fi
    	cd /usr/share/texmf/fonts/type1/public/cm-super
	tempfile=`mktemp -p /tmp cm-super.checkrun.XXXXXXXX`
	echo -n "Creating fonts. This may take some time..."
	set +e
	t1c2pfb </usr/share/cm-super/cm-super.t1c > $tempfile 2>&1
	if [ $? = 0 ] ; then
	  rm -f $tempfile
	  : > /usr/share/cm-super/cm-super.t1c
	  echo " done."
	else
          echo
          echo "Font generation failed. Output has been stored in"
          echo "$tempfile"
          echo "Please include this file if you report a bug."
          echo
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac


# Automatically added by dh_installtex/1
##
## postinst-tex
##
## postinst snippets for everything TeX related
## simply call update-texmf-config triggers
##
## Authors:
##       Norbert Preining <preining@logic.at>
##
#

case "$1" in
    configure|abort-upgrade|abort-remove|abort-deconfigure)
        update-texmf-config map
    ;;
esac

# End automatically added section
# Automatically added by dh_installdeb/11.4
dpkg-maintscript-helper rm_conffile /etc/texmf/updmap.d/50cm-super.cfg 0.3.4-4 -- "$@"
# End automatically added section


exit 0
