#!/bin/sh
set -e
# Automatically added by dh_installinit/10.10.9
if [ -x "/etc/init.d/logd" ] && [ "$1" = remove ]; then
	invoke-rc.d logd stop || exit $?
fi
# End automatically added section

# Automatically added by dh_python3:
if which py3clean >/dev/null 2>&1; then
	py3clean -p cluster-glue 
else
	dpkg -L cluster-glue | perl -ne 's,/([^/]*)\.py$,/__pycache__/\1.*, or next; unlink $_ or die $! foreach glob($_)'
	find /usr/lib/python3/dist-packages/ -type d -name __pycache__ -empty -print0 | xargs --null --no-run-if-empty rmdir
fi

# End automatically added section
