#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/eu/yahoo.xml 45.0esr-2~ iceweasel-l10n-eu -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/eu/wikipedia-eu.xml 45.0esr-2~ iceweasel-l10n-eu -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/eu/google.xml 45.0esr-2~ iceweasel-l10n-eu -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/eu/elebila.xml 45.0esr-2~ iceweasel-l10n-eu -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/eu/eBay-es.xml 45.0esr-2~ iceweasel-l10n-eu -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/eu/ddg.xml 45.0esr-2~ iceweasel-l10n-eu -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/eu/creativecommons.xml 45.0esr-2~ iceweasel-l10n-eu -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/eu/bing.xml 45.0esr-2~ iceweasel-l10n-eu -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/eu/amazon-en-GB.xml 45.0esr-2~ iceweasel-l10n-eu -- "$@"
# End automatically added section
