#!/bin/sh

set -e

# Automatically added by dh_systemd_start/11.4.1
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/11.4.1
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'nfs-server.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'nfs-server.service' >/dev/null || true
		deb-systemd-helper unmask 'nfs-server.service' >/dev/null || true
	fi
fi
# End automatically added section


case "$1" in
    purge)
	update-rc.d nfs-kernel-server remove >/dev/null

	for FILE in /etc/default/nfs-kernel-server /etc/exports; do
	    # Taken from the ucf example postrm
	    for ext in '~' '%' .bak .dpkg-tmp .dpkg-new .dpkg-old .dpkg-dist;  do
		rm -f $FILE$ext
	    done
	    rm -f $FILE
	    if [ -x /usr/bin/ucf ]; then
		ucf --purge $FILE
	    fi
	done

	rm -f /var/lib/nfs/etab  \
              /var/lib/nfs/rmtab \
              /var/lib/nfs/xtab
	;;
esac

