#!/bin/sh

set -e

if [ "$BANDWIDTHD_PACKAGE_DEBUG" != "" ]; then
	echo "bandwidthd-pgsql.prerm: $*"
fi

# Hook up the dbconfig-common library.
. /usr/share/debconf/confmodule
. /usr/share/dbconfig-common/dpkg/prerm
dbc_go bandwidthd-pgsql $@

# Automatically added by dh_installinit
if [ -x "/etc/init.d/bandwidthd" ]; then
	invoke-rc.d bandwidthd stop || exit $?
fi
# End automatically added section


