#!/bin/sh

set -e

if [ "$1" = "remove" ]; then
	rm -f /etc/graphite/*.pyc
	rm -f /var/lib/graphite/search_index
	rm -rf /var/lib/graphite/.fontconfig
fi


# Automatically added by dh_python3:
if which py3clean >/dev/null 2>&1; then
	py3clean -p graphite-web 
else
	dpkg -L graphite-web | perl -ne 's,/([^/]*)\.py$,/__pycache__/\1.*, or next; unlink $_ or die $! foreach glob($_)'
	find /usr/lib/python3/dist-packages/ -type d -name __pycache__ -empty -print0 | xargs --null --no-run-if-empty rmdir
fi

# End automatically added section


exit 0

