#!/bin/sh
set -e
# Automatically added by dh_installdeb
dpkg-maintscript-helper mv_conffile /etc/ulatencyd/rules/scheduler_desktop.lua /etc/ulatencyd/scheduler/desktop.lua 0.4.10-1 -- "$@"
# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/ulatencyd" ]; then
	invoke-rc.d ulatencyd stop || exit $?
fi
# End automatically added section
