#!/bin/sh
set -e
# Automatically added by dh_systemd_enable/10.10.5
# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask 'pacemaker.service' >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled 'pacemaker.service'; then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable 'pacemaker.service' >/dev/null || true
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'pacemaker.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/10.10.5
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/pacemaker" ]; then
		update-rc.d pacemaker defaults >/dev/null
		invoke-rc.d pacemaker start || exit $?
	fi
fi
# End automatically added section
