#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/prometheus-node-exporter" ]; then
	invoke-rc.d prometheus-node-exporter stop || exit $?
fi
# End automatically added section
