#!/bin/sh -e
set -e

if [ -e /usr/bin/xemacs21 ];then
    update-alternatives --install /usr/bin/xemacs xemacs /usr/bin/xemacs21 -10 --slave /usr/share/man/man1/xemacs.1.gz xemacs.1.gz /usr/share/man/man1/xemacs.xemacs21.1.gz

    update-alternatives --install /usr/bin/editor editor /usr/bin/xemacs21 -100
fi


