#!/bin/sh

set -e



action="$1"
oldversion="$2"

update-alternatives --install /usr/bin/x-terminal-emulator \
                              x-terminal-emulator /usr/bin/xvt 10 \
                    --slave /usr/share/man/man1/x-terminal-emulator.1.gz \
                            x-terminal-emulator.1.gz \
                            /usr/share/man/man1/xvt.1.gz

setgid() {
  if ! dpkg-statoverride --list "$1" >/dev/null ; then
    chown root:utmp "$1"
    chmod 2755 "$1"
  fi
}

if [ "$action" = "configure" ]; then
  setgid /usr/bin/xvt
fi

