#!/bin/sh
set -e
# Automatically added by dh_icons/11.1.5
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if which update-icon-caches >/dev/null 2>&1 ; then
		update-icon-caches /usr/share/icons/elementary-xfce /usr/share/icons/elementary-xfce-dark /usr/share/icons/elementary-xfce-darker /usr/share/icons/ubuntu-mono-dark /usr/share/icons/ubuntu-mono-light
	fi
fi
# End automatically added section
