#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/busybox-klogd" ]; then
	invoke-rc.d busybox-klogd stop || exit $?
fi
# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/busybox-syslogd" ]; then
	invoke-rc.d busybox-syslogd stop || exit $?
fi
# End automatically added section
