#!/bin/sh

set -e

if [ "$1" = "configure" ]; then
    adduser --quiet --system --home /var/lib/pyscrabble --no-create-home \
        --gecos "PyScrabble server" pyscrabble
    install -d -opyscrabble -m2750 /var/lib/pyscrabble 
    install -d -opyscrabble -gadm -m2750 /var/log/pyscrabble 
fi


# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p pyscrabble-server /usr/share/games/pyscrabble/python
fi

# End automatically added section
# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/pyscrabble-server" ]; then
		update-rc.d pyscrabble-server defaults >/dev/null
		invoke-rc.d pyscrabble-server start || exit $?
	fi
fi
# End automatically added section

