#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/pyscrabble-server" ] && [ "$1" = remove ]; then
	invoke-rc.d pyscrabble-server stop || exit $?
fi
# End automatically added section

# Automatically added by dh_python2:
if which pyclean >/dev/null 2>&1; then
	pyclean -p pyscrabble-server 
else
	dpkg -L pyscrabble-server | grep \.py$ | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section
