#! /bin/sh
# prerm script for chameleon-cursor-theme
# (based on prerm of comixcursors by Sune Vuorela)

set -e

ICONDIR=/usr/share/icons

case "$1" in
    remove|upgrade|deconfigure)
        for theme in `find "$ICONDIR" -regex '.*Chameleon-\(Anthracite\|DarkSkyBlue\|Pearl\|White\|SkyBlue\|Mint\|Purple\)-.*theme$'`; do
            update-alternatives --remove x-cursor-theme "$theme"
        done
    ;;
    failed-upgrade)
    ;;
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac



exit 0
