#!/bin/sh -e

if [ -f /usr/games/fortune.en ]; then 
   rm -f /usr/games/fortune
   dpkg-divert --package fortunes-de --remove --rename \
                --divert /usr/games/fortune.en /usr/games/fortune
fi

if [ -f /usr/share/man/man6/fortune.en.6.gz ]; then
   rm -f  /usr/share/man/man6/fortune.6.gz
   dpkg-divert --package fortunes-de --remove --rename \
                --divert /usr/share/man/man6/fortune.en.6.gz /usr/share/man/man6/fortune.6.gz
fi


