#! /bin/sh -e

pam-auth-update --package


# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p libpam-mklocaluser /usr/lib/libpam-mklocaluser
fi

# End automatically added section

