#! /bin/sh
set -e
PACKAGE=rail

if [ ! -e /var/lib/emacsen-common/state/package/installed/emacsen-common ]
then
    # Fallback to emacsen-common 1.x
    if [ "$1" = "configure" ] && [ -x /usr/lib/emacsen-common/emacs-package-install ]
    then
        /usr/lib/emacsen-common/emacs-package-install $PACKAGE
    fi
else
    mkdir -p -m 0755 /var/lib/emacsen-common/state/package/installed
    touch /var/lib/emacsen-common/state/package/installed/$PACKAGE
# Automatically added by dh_elpa/UNDECLARED
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -e /var/lib/emacsen-common/state/package/installed/emacsen-common -a -x /usr/lib/emacsen-common/emacs-package-install ] ; then
		/usr/lib/emacsen-common/emacs-package-install --postinst rail
	fi
fi
# End automatically added section
# Automatically added by dh_installdeb/11.3.5
dpkg-maintscript-helper rm_conffile /usr/share/emacs/site-start.d/50rail.el -- "$@"
# End automatically added section

fi
