#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.3.2
dpkg-maintscript-helper rm_conffile /etc/defoma/hints/ttf-unfonts-extra.hints 1.0.2-080608-1\~ ttf-unfonts-extra -- "$@"
dpkg-maintscript-helper rm_conffile /etc/fonts/conf.avail/90-ttf-unfonts-extra.conf 1.0.2-080608-3\~ ttf-unfonts-extra -- "$@"
dpkg-maintscript-helper rm_conffile /etc/fonts/conf.avail/gbp.conf 1.0.2-080608\+dfsg-2\~ fonts-unfonts-extra -- "$@"
dpkg-maintscript-helper rm_conffile /etc/fonts/conf.avail/90-fonts-unfonts-extra.conf 1.0.2-080608\+dfsg-4\~ fonts-unfonts-extra -- "$@"
# End automatically added section
