#!/bin/sh
set -e

# Automatically added by dh_installdebconf
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


case $1 in
	purge)
		if `which ucf >/dev/null 2>&1` ; then
			ucf --purge /etc/msmtprc
		fi

		rm -f /etc/msmtprc
		;;
	*)
		;;
esac
