#!/bin/sh
set -e

# Automatically added by dh_python2:
if which pyclean >/dev/null 2>&1; then
	pyclean -p libslepc3.10-dev-examples 
else
	dpkg -L libslepc3.10-dev-examples | grep '\.py$' | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section
