#!/bin/sh

set -e

if [ "$1" = "purge" ] ; then
	# Disable cobbler
	a2dissite cobbler_web.conf || true
	invoke-rc.d apache2 reload || true
	for i in webui_sessions webui_cache ; do
		rm -rf /var/lib/cobbler/$i
	done
	rm -f /etc/cobbler/settings.py
fi



exit 0
