#!/bin/sh

set -e

# ensure the server process has been killed before calling userdel(1)
# Automatically added by dh_installinit/11.5.3
if [ "$1" = "purge" ] ; then
	update-rc.d debug-me remove >/dev/null
fi
# End automatically added section


# on a purge, delete the _debug-me user and group, and the logs dir
if [ "$1" = "purge" ]; then
    userdel _debug-me || true
    # userdel may or may not remove the group (see USERGROUPS_ENAB in
    # userdel(8)), so we make an attempt to delete it
    groupdel _debug-me || true
    rm -rf /var/log/debug-me
fi
