#!/bin/sh
set -e
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/task.sh 2.4.3\+dfsg-2 -- "$@"
dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/task 2.4.4\+dfsg-1 -- "$@"
dpkg-maintscript-helper rm_conffile /etc/fish/completions/task.fish 2.4.4\+dfsg-1 -- "$@"
# End automatically added section
