#!/bin/sh
set -e

# Replace documentation directory with symlink
docdir="/usr/share/doc/libphone-utils-dev"
if [ -d $docdir ] && [ ! -L $docdir ]; then
    if rmdir $docdir 2>/dev/null; then
        ln -sf libphone-utils0 $docdir
    fi
fi



exit 0
