#!/bin/sh

set -e

if [ -f /usr/share/debconf/confmodule ]; then
    . /usr/share/debconf/confmodule
    if [ -f /usr/share/dbconfig-common/dpkg/postrm ]; then
            . /usr/share/dbconfig-common/dpkg/postrm
            dbc_go bareos-database-common $@
    fi
fi

# Automatically added by dh_installdebconf/11.2.1
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

