#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/trove-taskmanager" ] && [ "$1" = remove ]; then
	invoke-rc.d trove-taskmanager stop || true
fi
# End automatically added section
