#!/bin/sh

set -e

if [ "$1" = "configure" ]; then
	if ! id -u spf-milter-python >/dev/null 2>&1; then
		adduser --quiet --system --group --home /var/run/spf-milter-python spf-milter-python
	elif [ -n "$2" ]; then
		addgroup --quiet --system spf-milter-python
		usermod -g spf-milter-python spf-milter-python
	fi
	chown -R spf-milter-python:spf-milter-python /var/log/spf-milter-python
fi

# Automatically added by dh_installinit/11.1.4
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/spf-milter-python" ]; then
		update-rc.d spf-milter-python defaults >/dev/null
		invoke-rc.d spf-milter-python start || exit 1
	fi
fi
# End automatically added section


exit 0

