#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/bacula-director" ] && [ "$1" = remove ]; then
	invoke-rc.d bacula-director stop || exit $?
fi
# End automatically added section
