#!/bin/sh
set -e

# Automatically added by dh_installinit/11.3.5
if [ "$1" = "purge" ] ; then
	update-rc.d ulogd2 remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installdeb/11.3.5
dpkg-maintscript-helper rm_conffile /etc/init/ulogd2.conf 2.0.7-1\~ -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/11.3.5
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'ulogd2.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'ulogd2.service' >/dev/null || true
		deb-systemd-helper unmask 'ulogd2.service' >/dev/null || true
	fi
fi
# End automatically added section


# Clean up the log directory
if [ "$1" = "purge" ]; then
	if [ -d /var/log/ulog ]; then
		rm -rf /var/log/ulog
	fi
fi
