#!/bin/sh
set -e
# Automatically added by dh_installinit/11.3.5
if [ -x "/etc/init.d/ulogd2" ] && [ "$1" = remove ]; then
	invoke-rc.d ulogd2 stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installdeb/11.3.5
dpkg-maintscript-helper rm_conffile /etc/init/ulogd2.conf 2.0.7-1\~ -- "$@"
# End automatically added section
