#!/bin/sh
# postrm script for #PACKAGE#

set -e

case "$1" in
    purge)
	for scorefile in easy hard Normal Timed; do
	    rm -f /var/games/gweled.${scorefile}.scores;
	done
    ;;
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac



exit 0
