#!/bin/sh
set -e
# Automatically added by dh_installinit/10.10.5
if [ -x "/etc/init.d/ceilometer-api" ] && [ "$1" = remove ]; then
	invoke-rc.d ceilometer-api stop || true
fi
# End automatically added section
