#!/bin/sh

set -e

. /usr/share/debconf/confmodule
db_version 2.0

srcdir=/usr/share/gnome-speech/sources/swift
if [ "$1" = "configure" ]; then
  db_get gnome-speech-swift/swift_dir
  swift_dir="$RET"
  if [ -d "$swift_dir" -a -d "$swift_dir/include" -a -d "$swift_dir/lib" ]; then
    # compile code here
    swift_CFLAGS="-I$srcdir -I/usr/include/gnome-speech-1.0 -I$swift_dir/include -DORBIT2=1 -pthread -I/usr/include/bonobo-activation-2.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/orbit-2.0 -I/usr/include/libbonobo-2.0   -Wall -g -O2"
    gcc $swift_CFLAGS -o /usr/bin/swift-synthesis-driver \
      $srcdir/swiftsynthesisdriver.c $srcdir/swiftspeaker.c \
      -Wl,--export-dynamic -lgnomespeech -lbonobo-2 -lbonobo-activation -lgmodule-2.0 -ldl -lORBit-2 -lgthread-2.0 -lrt -lgobject-2.0 -lglib-2.0 -L$swift_dir/lib -lswift -lm
    sed -e 's,@prefix@,/usr,' \
      <$srcdir/GNOME_Speech_SynthesisDriver_Swift.server.in \
      >/usr/lib/bonobo/servers/GNOME_Speech_SynthesisDriver_Swift.server
    if [ "$swift_dir" != "/opt/swift" -a ! -f /etc/swift.xml ]; then
      if [ ! -f /opt/swift/etc/swift.xml ]; then
        ln -s $swift_dir/etc/swift.xml /etc/swift.xml
      fi
    fi
  fi
fi


