#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.2.1
dpkg-maintscript-helper rm_conffile /etc/init.d/quagga 1.1.0-1\~ quagga -- "$@"
dpkg-maintscript-helper rm_conffile /etc/logrotate.d/quagga 1.1.0-1\~ quagga -- "$@"
dpkg-maintscript-helper rm_conffile /etc/quagga/daemons 1.1.0-1\~ quagga -- "$@"
dpkg-maintscript-helper rm_conffile /etc/quagga/debian.conf 1.1.0-1\~ quagga -- "$@"
# End automatically added section
