#!/bin/sh

set -e



dpkg-maintscript-helper symlink_to_dir \
    /usr/share/doc/libglobus-gram-job-manager-callout-error-doc \
    libglobus-gram-job-manager-callout-error-dev 3.5-2~ \
    libglobus-gram-job-manager-callout-error-doc -- "$@"
