#!/bin/sh

set -e

# Remove /etc/courier/maildroprc on purge
if [ "$1" = "purge" -a -h /etc/courier/maildroprc ]; then
    rm -f /etc/courier/maildroprc
    rmdir --ignore-fail-on-non-empty /etc/courier
fi

# Automatically added by dh_installdebconf/10.8
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

