#!/bin/sh
set -e

# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p lvm2-dbusd 
fi

# End automatically added section
# Automatically added by dh_installsystemd/10.10.9
# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask 'lvm2-lvmdbusd.service' >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled 'lvm2-lvmdbusd.service'; then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable 'lvm2-lvmdbusd.service' >/dev/null || true
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'lvm2-lvmdbusd.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/10.10.9
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
	if [ -n "$2" ]; then
		_dh_action=restart
	else
		_dh_action=start
	fi
	deb-systemd-invoke $_dh_action 'lvm2-lvmdbusd.service' >/dev/null || true
fi
# End automatically added section
