#!/bin/sh
set -e
# Automatically added by dh_icons
if which update-icon-caches >/dev/null 2>&1 ; then
	update-icon-caches /usr/share/icons/wmcpuload-16x16.xpm /usr/share/icons/wmcpuload-32x32.xpm /usr/share/icons/wmcpuload-48x48.xpm
fi
# End automatically added section
# Automatically added by dh_installmenu
if [ -x "`which update-menus 2>/dev/null`" ]; then update-menus ; fi
# End automatically added section
