#!/bin/sh
set -e

if [ "$1" = configure ]; then
    if [ -e /usr/share/apache2/apache2-maintscript-helper ]; then
        . /usr/share/apache2/apache2-maintscript-helper
	if [ ! -e /etc/apache2/mods-enabled/auth_gssapi.load ]; then
            apache2_invoke enmod auth_gssapi || exit $?
        fi
	if [ ! -e /etc/apache2/mods-enabled/authz_user.load ]; then
            apache2_invoke enmod authz_user || exit $?
        fi
	if [ ! -e /etc/apache2/mods-enabled/deflate.load ]; then
            apache2_invoke enmod deflate || exit $?
        fi
	if [ ! -e /etc/apache2/mods-enabled/expires.load ]; then
            apache2_invoke enmod expires || exit $?
        fi
	if [ ! -e /etc/apache2/mods-enabled/headers.load ]; then
            apache2_invoke enmod headers || exit $?
        fi
	if [ ! -e /etc/apache2/mods-enabled/proxy.load ]; then
            apache2_invoke enmod proxy || exit $?
        fi
	if [ ! -e /etc/apache2/mods-enabled/proxy_ajp.load ]; then
            apache2_invoke enmod proxy_ajp || exit $?
        fi
	if [ ! -e /etc/apache2/mods-enabled/proxy_http.load ]; then
            apache2_invoke enmod proxy_http || exit $?
        fi
	if [ ! -e /etc/apache2/mods-enabled/rewrite.load ]; then
            apache2_invoke enmod rewrite || exit $?
        fi
    fi

    # check if IPA is set up
    is_configured=`python2 -c 'from ipaserver.install import installutils; print "yes" if installutils.is_ipa_configured() else "no";'`
    if [ $is_configured = yes ]; then
        echo "Running ipa-server-upgrade..."
        ipa-server-upgrade --quiet >/dev/null
    fi
fi

if [ ! -e /run/ipa_memcached ]; then
    mkdir -m 0700 /run/ipa_memcached
    chown www-data:www-data /run/ipa_memcached
fi

if [ ! -e /run/apache2/ipa ]; then
    mkdir -m 0700 /run/apache2/ipa
    chown www-data:www-data /run/apache2/ipa

    if [ ! -e /run/apache2/ipa/clientcaches ]; then
        mkdir -m 0700 /run/apache2/ipa/clientcaches
        chown www-data:www-data /run/apache2/ipa/clientcaches
    fi
    if [ ! -e /run/apache2/ipa/krbcache ]; then
        mkdir -m 0700 /run/apache2/ipa/krbcache
        chown www-data:www-data /run/apache2/ipa/krbcache
    fi
fi

# Automatically added by dh_systemd_enable/10.10.9
if deb-systemd-helper debian-installed 'ipa.service'; then
	# This will only remove masks created by d-s-h on package removal.
	deb-systemd-helper unmask 'ipa.service' >/dev/null || true

	if deb-systemd-helper --quiet was-enabled 'ipa.service'; then
		# Create new symlinks, if any.
		deb-systemd-helper enable 'ipa.service' >/dev/null || true
	fi
fi

# Update the statefile to add new symlinks (if any), which need to be cleaned
# up on purge. Also remove old symlinks.
deb-systemd-helper update-state 'ipa.service' >/dev/null || true
# End automatically added section
# Automatically added by dh_systemd_enable/10.10.9
if deb-systemd-helper debian-installed 'ipa_memcached.service'; then
	# This will only remove masks created by d-s-h on package removal.
	deb-systemd-helper unmask 'ipa_memcached.service' >/dev/null || true

	if deb-systemd-helper --quiet was-enabled 'ipa_memcached.service'; then
		# Create new symlinks, if any.
		deb-systemd-helper enable 'ipa_memcached.service' >/dev/null || true
	fi
fi

# Update the statefile to add new symlinks (if any), which need to be cleaned
# up on purge. Also remove old symlinks.
deb-systemd-helper update-state 'ipa_memcached.service' >/dev/null || true
# End automatically added section
# Automatically added by dh_systemd_enable/10.10.9
if deb-systemd-helper debian-installed 'ipa-dnskeysyncd.service'; then
	# This will only remove masks created by d-s-h on package removal.
	deb-systemd-helper unmask 'ipa-dnskeysyncd.service' >/dev/null || true

	if deb-systemd-helper --quiet was-enabled 'ipa-dnskeysyncd.service'; then
		# Create new symlinks, if any.
		deb-systemd-helper enable 'ipa-dnskeysyncd.service' >/dev/null || true
	fi
fi

# Update the statefile to add new symlinks (if any), which need to be cleaned
# up on purge. Also remove old symlinks.
deb-systemd-helper update-state 'ipa-dnskeysyncd.service' >/dev/null || true
# End automatically added section
# Automatically added by dh_systemd_enable/10.10.9
if deb-systemd-helper debian-installed 'ipa-custodia.service'; then
	# This will only remove masks created by d-s-h on package removal.
	deb-systemd-helper unmask 'ipa-custodia.service' >/dev/null || true

	if deb-systemd-helper --quiet was-enabled 'ipa-custodia.service'; then
		# Create new symlinks, if any.
		deb-systemd-helper enable 'ipa-custodia.service' >/dev/null || true
	fi
fi

# Update the statefile to add new symlinks (if any), which need to be cleaned
# up on purge. Also remove old symlinks.
deb-systemd-helper update-state 'ipa-custodia.service' >/dev/null || true
# End automatically added section
# Automatically added by dh_systemd_enable/10.10.9
if deb-systemd-helper debian-installed 'ipa-ods-exporter.service'; then
	# This will only remove masks created by d-s-h on package removal.
	deb-systemd-helper unmask 'ipa-ods-exporter.service' >/dev/null || true

	if deb-systemd-helper --quiet was-enabled 'ipa-ods-exporter.service'; then
		# Create new symlinks, if any.
		deb-systemd-helper enable 'ipa-ods-exporter.service' >/dev/null || true
	fi
fi

# Update the statefile to add new symlinks (if any), which need to be cleaned
# up on purge. Also remove old symlinks.
deb-systemd-helper update-state 'ipa-ods-exporter.service' >/dev/null || true
# End automatically added section
# Automatically added by dh_installinit/10.10.9
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	# In case this system is running systemd, we need to ensure that all
	# necessary tmpfiles (if any) are created before starting.
	if [ -d /run/systemd/system ] ; then
		systemd-tmpfiles --create /usr/lib/tmpfiles.d/freeipa-server.conf >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_systemd_start/10.10.9
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
	deb-systemd-invoke start 'ipa-custodia.service' 'ipa-dnskeysyncd.service' 'ipa-ods-exporter.service' 'ipa-ods-exporter.socket' 'ipa-otpd.socket' 'ipa.service' 'ipa_memcached.service' >/dev/null || true
fi
# End automatically added section

