#!/bin/sh

set -e

if [ "$1" = "configure" ] ; then
	update-alternatives --install /usr/bin/sql2subunit sql2subunit /usr/bin/python2-sql2subunit 300
	update-alternatives --install /usr/bin/subunit2sql subunit2sql /usr/bin/python2-subunit2sql 300
	update-alternatives --install /usr/bin/subunit2sql-db-manage subunit2sql-db-manage /usr/bin/python2-subunit2sql-db-manage 300
	update-alternatives --install /usr/bin/subunit2sql-graph subunit2sql-graph /usr/bin/python2-subunit2sql-graph 300
fi


# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p python-subunit2sql 
fi

# End automatically added section


exit 0
