#!/bin/sh
set -e

if [ "$1" = "purge" ]
then 
    rm -rf /var/run/prelude-lml >/dev/null
    rm -rf /var/spool/prelude-lml >/dev/null
    rm -rf /var/lib/prelude-lml >/dev/null
    rm -rf /etc/prelude-lml >/dev/null
    rm -rf /etc/prelude/profile/prelude-lml >/dev/null
fi

# Automatically added by dh_installsystemd/11.2.1
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installdeb/11.2.1
dpkg-maintscript-helper rm_conffile /etc/init.d/prelude-lml 3.1.0-0.1\~ prelude-lml -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/11.2.1
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'prelude-lml.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'prelude-lml.service' >/dev/null || true
		deb-systemd-helper unmask 'prelude-lml.service' >/dev/null || true
	fi
fi
# End automatically added section

