#!/bin/sh
set -e

# Deactivate the old qtsmbstatusd initscript that has dependencies
# incompatible with the new samba initscript. This will allow to
# configure the new samba package and qtsmbstatus-server afterwards.
if [ "$1" = "upgrade" ] || [ "$1" = "install" ]; then
	if [ -x "/etc/init.d/qtsmbstatusd" ]; then
		version=$(dpkg-query -f '${Config-Version} ${Version}' -W qtsmbstatus-server 2>/dev/null | awk '{ print $1 }')
		if dpkg --compare-versions "$version" lt-nl "2.2.1-3~" ; then
			echo "Deactivating qtsmbstatusd temporarily..."
			invoke-rc.d qtsmbstatusd stop
			update-rc.d -f qtsmbstatusd remove
		fi
	fi
fi

# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/network/if-up.d/samba 2:3.6.5-6~ samba -- "$@"
# End automatically added section

