#!/bin/sh
set -e
# Automatically added by dh_installinit/12
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/uwsgi" ]; then
		update-rc.d uwsgi defaults >/dev/null
		invoke-rc.d uwsgi start || exit 1
	fi
fi
# End automatically added section
