#!/bin/sh
# postrm script for dicod
#
# see: dh_installdeb(1)

set -e


case "$1" in
  remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
  ;;
  purge)
    rm -f /var/lib/dicod/dictorg-db.list
    rmdir --ignore-fail-on-non-empty /var/lib/dicod/  || true
    # remove user, group and home directory dicod
    deluser --remove-home dicod >/dev/null 2>&1 || true
  ;;

  *)
      echo "postrm called with unknown argument \`$1'" >&2
      exit 1
  ;;
esac

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d dicod remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section


exit 0
