#!/bin/sh
set -e
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/OpenCL/vendors/intel-beignet.icd 1.0.1-3\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/OpenCL/vendors/intel-beignet.icd 0.0\~ beignet -- \"\$\@\" 0 -- "$@"
# End automatically added section
