#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.3.2
dpkg-maintscript-helper rm_conffile /etc/logcheck/ignore.d.server/webmin 1.3.14\~ logcheck-database -- "$@"
dpkg-maintscript-helper rm_conffile /etc/logcheck/ignore.d.server/puppetd 1.3.16\~ logcheck-database -- "$@"
dpkg-maintscript-helper rm_conffile /etc/logcheck/ignore.d.server/dkim-filter 1.3.17\~ logcheck-database -- "$@"
# End automatically added section
