#!/bin/sh

set -e

if [ "$1" = "configure" ] ; then
	update-alternatives --install /usr/bin/check-uuid check-uuid /usr/bin/python3-check-uuid 200
	update-alternatives --install /usr/bin/run-tempest-stress run-tempest-stress /usr/bin/python3-run-tempest-stress 200
	update-alternatives --install /usr/bin/skip-tracker skip-tracker /usr/bin/python3-skip-tracker 200
	update-alternatives --install /usr/bin/tempest tempest /usr/bin/python3-tempest 200
	update-alternatives --install /usr/bin/tempest-account-generator tempest-account-generator /usr/bin/python3-tempest-account-generator 200
	update-alternatives --install /usr/bin/tempest-cleanup tempest-cleanup /usr/bin/python3-tempest-cleanup 200
	update-alternatives --install /usr/bin/verify-tempest-config verify-tempest-config /usr/bin/python3-verify-tempest-config 200
	update-alternatives --install /usr/bin/subunit-describe-calls subunit-describe-calls /usr/bin/python3-subunit-describe-calls 200
fi


# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p python3-tempest 
fi

# End automatically added section


exit 0
