#!/bin/sh

set -e

[ "$1" = "purge" ] && rm -rf /etc/chkrootkit.conf /var/cache/chkrootkit/ /var/log/chkrootkit/

# Automatically added by dh_installdebconf/11.2.1
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

