#!/bin/sh
set -e

# Divert the regular cursor back into place now that our version is gone.
if [ "$1" = remove ]; then
	dpkg-divert --package big-cursor --remove --rename --divert \
		/usr/share/fonts/X11/misc/cursor.pcf.gz-small \
		/usr/share/fonts/X11/misc/cursor.pcf.gz 
fi
		
# Automatically added by dh_installxfonts
if [ -x "`which update-fonts-dir 2>/dev/null`" ]; then
	update-fonts-dir --x11r7-layout misc
fi
# End automatically added section

