#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/mpt-statusd" ]; then
		update-rc.d mpt-statusd defaults >/dev/null
		invoke-rc.d mpt-statusd start || exit $?
	fi
fi
# End automatically added section
