#!/bin/sh
set -e
# Automatically added by dh_installinit/11.5.1
if [ "$1" = "purge" ] ; then
	update-rc.d laptop-mode remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.5.1
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.5.1
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'laptop-mode.service' 'laptop-mode.timer' 'lmt-poll.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'laptop-mode.service' 'laptop-mode.timer' 'lmt-poll.service' >/dev/null || true
		deb-systemd-helper unmask 'laptop-mode.service' 'laptop-mode.timer' 'lmt-poll.service' >/dev/null || true
	fi
fi
# End automatically added section
