#! /bin/sh
# postinst script for ratpoison

set -e

case "$1" in
    configure|abort-remove|abort-deconfigure)
# 20 to start with,
## when depending again on 9menu:
## plus 20 as we have menu support configured 
## plus 10 as it can restart other wm's with :newwm or menu
          update-alternatives --install /usr/bin/x-window-manager \
                x-window-manager /usr/bin/ratpoison 20 \
		--slave /usr/share/man/man1/x-window-manager.1.gz \
		x-window-manager.1.gz /usr/share/man/man1/ratpoison.1.gz
    ;;

    abort-upgrade)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# Automatically added by dh_installemacsen
if [ "$1" = "configure" ] && [ -e /var/lib/emacsen-common/state/package/installed/emacsen-common -a -x /usr/lib/emacsen-common/emacs-package-install ]
then
	/usr/lib/emacsen-common/emacs-package-install --postinst ratpoison
fi
# End automatically added section
# Automatically added by dh_installmenu
inst=/etc/menu-methods/ratpoison
if [ -f $inst ]; then
	chmod a+x $inst
	if [ -x "`which update-menus 2>/dev/null`" ]; then
		update-menus
	fi
fi
# End automatically added section


exit 0


