#!/bin/sh -e

DEB_HOST_MULTIARCH=x86_64-linux-gnu

SONAME=3.7

SLEPC_VERSION=3.7.4
SLEPC_ARCH=${DEB_HOST_MULTIARCH}
SLEPC_COMPLEX_ARCH=${SLEPC_ARCH}-complex

SLEPC_DIR_COMPLEX=/usr/lib/slepcdir/${SLEPC_VERSION}/${SLEPC_COMPLEX_ARCH}

# Remove alternatives links
if [ "$1" = "remove" ]; then
  update-alternatives --remove slepc /usr/lib/slepcdir/${SLEPC_VERSION}/${SLEPC_COMPLEX_ARCH}
  update-alternatives --remove libslepc_complex.so /usr/lib/${DEB_HOST_MULTIARCH}/libslepc_complex.so.${SLEPC_VERSION}

  update-alternatives --remove slepc${SONAME} ${SLEPC_DIR_COMPLEX}
  update-alternatives --remove slepc${SONAME}-complex ${SLEPC_DIR_COMPLEX}
fi


