#! /bin/sh -e

if ! getent passwd yubikeyd> /dev/null; then
   useradd -U -r -d /nonexistent yubikeyd
fi

# Automatically added by dh_installinit/11.5.3
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/yubikey-server-c" ]; then
		update-rc.d yubikey-server-c defaults >/dev/null
		invoke-rc.d yubikey-server-c start || exit 1
	fi
fi
# End automatically added section

