#!/bin/sh
set -e

# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p gaupol /usr/share/gaupol
fi
if which pypy3compile >/dev/null 2>&1; then
	pypy3compile -p gaupol /usr/share/gaupol || true
fi

# End automatically added section
