#!/bin/sh -e
#
# preinst script for the Debian GNU/Linux libquantlib0-dev package
#
# Written and GPL'ed by Dirk Eddelbuettel <edd@debian.org>   

case "$1" in

    install|upgrade)     
        # We want to remove previous versions' documentation directory
	test -d /usr/share/doc/libquantlib0-dev && \
		rm -rf /usr/share/doc/libquantlib0-dev 
	;;

    abort-upgrade)
        ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        ;;

esac



exit 0                 

