#!/bin/sh
set -e

if [ "$1" = configure ]
then
    . /usr/share/debconf/confmodule

    default_format="\
# Start statnetd at boot time? 0 or 1
run_statnetd=%s
# Specify additional statnetd options here (see manpage).
"

    # Determine whether to start watchdog at boot time.
    db_get netdiag/run_statnetd
    case $RET in
    false)  run_statnetd=0;;
    *)      run_statnetd=1;;
    esac

    # Create an up-to-date copy of the default file.
    {
	# If it already exists, preserve everything except our comment
	# and $run_statnetd.
	if [ -f /etc/default/netdiag ]
	then
	    printf "$default_format" '.*' '.*' \
		| grep -vxf - /etc/default/netdiag \
		| grep -v statnetd_options || true
	fi

	# Append our comment and the current value.
	printf "$default_format" "$run_statnetd" 

	# And finally preserve the statnetd_options setting.
	if [ -f /etc/default/netdiag ]
	then
		grep statnetd_options /etc/default/netdiag || echo "statnetd_options="
	fi
    } > /etc/default/netdiag.dpkg-new

    # Replace the original file atomically.
    mv /etc/default/netdiag.dpkg-new /etc/default/netdiag

    #
    # stop debconf
    #
    db_stop
fi

# Automatically added by dh_installmenu/11.2.1
if [ "$1" = "configure" ] && [ -x "`which update-menus 2>/dev/null`" ]; then
	update-menus
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.2.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# This will only remove masks created by d-s-h on package removal.
	deb-systemd-helper unmask 'netdiag.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'netdiag.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'netdiag.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'netdiag.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.2.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'netdiag.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installinit/11.2.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/netdiag" ]; then
		update-rc.d netdiag defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d netdiag $_dh_action || exit 1
	fi
fi
# End automatically added section


