#!/bin/sh
set -e
# Automatically added by dh_installinit/11.2.1
if [ -x "/etc/init.d/netdiag" ] && [ "$1" = remove ]; then
	invoke-rc.d netdiag stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.2.1
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'netdiag.service' >/dev/null || true
fi
# End automatically added section
