#!/bin/sh
set -e
# Automatically added by dh_systemd_start/11.4.1
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/11.4.1
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'strongswan-swanctl.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'strongswan-swanctl.service' >/dev/null || true
		deb-systemd-helper unmask 'strongswan-swanctl.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_apparmor/2.13-8
if [ "$1" = "purge" ] && ! [ -e "/etc/apparmor.d/usr.sbin.charon-systemd" ] ; then
    rm -f "/etc/apparmor.d/disable/usr.sbin.charon-systemd" || true
    rm -f "/etc/apparmor.d/force-complain/usr.sbin.charon-systemd" || true
    rm -f "/etc/apparmor.d/local/usr.sbin.charon-systemd" || true
    rmdir /etc/apparmor.d/disable 2>/dev/null || true
    rmdir /etc/apparmor.d/local   2>/dev/null || true
    rmdir /etc/apparmor.d         2>/dev/null || true
fi
# End automatically added section
