#!/bin/sh
# postrm script for freeipmi-bmc-watchdog
#
# see: dh_installdeb(1)

set -e

dpkg-maintscript-helper mv_conffile /etc/default/freeipmi-bmc-watchdog /etc/default/bmc-watchdog 0.7.17~beta2-1 -- "$@"
dpkg-maintscript-helper mv_conffile /etc/init.d/freeipmi-bmc-watchdog /etc/init.d/bmc-watchdog 0.7.17~beta2-1 -- "$@"
dpkg-maintscript-helper mv_conffile /etc/logrotate.d/freeipmi-bmc-watchdog /etc/logrotate.d/bmc-watchdog 1.4.5-2~ -- "$@"

# Automatically added by dh_installinit/10.10.4
if [ "$1" = "purge" ] ; then
	update-rc.d bmc-watchdog remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section


exit 0
