#!/bin/sh

set -e

case "$1" in
  configure)
    if ! getent passwd Debian-minetest >/dev/null; then
      adduser \
          --disabled-password \
          --quiet \
          --system \
          --home /var/games/minetest-server \
          --no-create-home \
          --gecos "Minetest dedicated server" \
          --ingroup games \
          --force-badname Debian-minetest
    fi
    install -d /var/games
    install -d /var/games/minetest-server
    install -d /var/log/minetest
    chown Debian-minetest:games /var/games/minetest-server
    chown Debian-minetest:games /var/log/minetest
  ;;
  abort-upgrade|abort-remove|abort-deconfigure)
  ;;
  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac

# Automatically added by dh_installinit/11.3.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/minetest-server" ]; then
		update-rc.d minetest-server defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d minetest-server $_dh_action || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.3.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# This will only remove masks created by d-s-h on package removal.
	deb-systemd-helper unmask 'minetest-server.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'minetest-server.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'minetest-server.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'minetest-server.service' >/dev/null || true
	fi
fi
# End automatically added section

