#!/bin/sh
set -e
# Automatically added by dh_installinit/11.3.2
if [ -x "/etc/init.d/minetest-server" ] && [ "$1" = remove ]; then
	invoke-rc.d minetest-server stop || exit 1
fi
# End automatically added section
