#!/bin/sh
set -e

LOGFILE=/var/log/ipaclient-upgrade.log

if [ "$1" = configure ]; then
    python2 -c 'from ipapython.certdb import update_ipa_nssdb; update_ipa_nssdb()' \
        > $LOGFILE 2>&1
fi

if [ ! -e /run/ipa ]; then
    mkdir -m 0700 /run/ipa
fi

# Automatically added by dh_installinit/10.10.9
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	# In case this system is running systemd, we need to ensure that all
	# necessary tmpfiles (if any) are created before starting.
	if [ -d /run/systemd/system ] ; then
		systemd-tmpfiles --create /usr/lib/tmpfiles.d/freeipa-client.conf >/dev/null || true
	fi
fi
# End automatically added section

