#!/bin/sh
set -e

# Automatically added by dh_installinit/10.6.4
if [ "$1" = "purge" ] ; then
	update-rc.d gdnsd remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/10.6.4
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask gdnsd.service >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge gdnsd.service >/dev/null
		deb-systemd-helper unmask gdnsd.service >/dev/null
	fi
fi
# End automatically added section


deluser --quiet --system gdnsd 2> /dev/null || true

exit 0
