#!/bin/sh
set -e
# Automatically added by dh_systemd_start/11.5.3
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'flatpak-system-helper.service' >/dev/null || true
fi
# End automatically added section
