#!/bin/sh
# $Id: postinst 47 2009-08-30 10:25:53Z robert $
set -e


if [ "$1" = configure ]; then
	# create v4l devices ?
	if [ ! -d /dev/v4l ] || [ ! -c /dev/video0 ] ; then
		if [ -x /dev/MAKEDEV ]; then
			(cd /dev;  ./MAKEDEV v4l)
		fi
	fi
fi



exit 0
