#! /bin/sh
# prerm script for havp
#
# see: dh_installdeb(1)

set -e

init_error() {
echo "E: Error stopping service, ignoring..."
}

# Automatically added by dh_installinit
if [ -x "/etc/init.d/havp" ]; then
	invoke-rc.d havp stop || init_error
fi
# End automatically added section


