#!/bin/sh
# vim:ft=sh:cindent:ts=4:sts=4:et:sw
#
# Debian postrm script for dwww.
#

set -e

if [ "X$1" = "Xpurge" ]; then
    ! which ucf  > /dev/null || ucf --purge /etc/dwww/dwww.conf
    ! which ucfr > /dev/null || ucfr --purge dwww /etc/dwww/dwww.conf
    if [ -d /etc/dwww ] ; then
        echo -n "Purging configuration data in /etc/dwww/ ... "
        rm -rf /etc/dwww
        echo "done."
    fi
fi


# Automatically added by dh_installdeb
dpkg-maintscript-helper mv_conffile /etc/dwww/apache.conf /etc/apache2/conf-available/dwww.conf 1.12.0\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/common/dwww.xml 1.13.2\~ -- "$@"
# End automatically added section
# Automatically added by dh_installdebconf
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section
# Automatically added by dh_apache2
if [ "$1" = "purge" ] ; then
	if true; then
		if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
			. /usr/share/apache2/apache2-maintscript-helper

			for conf in dwww  ; do
				apache2_invoke disconf $conf  || exit $?
			done
		fi
	fi
fi
# End automatically added section


exit 0
