#!/bin/sh
set -e
# Automatically added by dh_installsystemd/11.4.1
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'galileo-daemon.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_sysuser/UNDECLARED
# -*- sh -*-
export CONF_HOME=/nonexistent
export CONF_PACKAGE=galileo-daemon
export CONF_USERNAME=galileo

/lib/sysuser-helper/sysuser-helper prerm "$@"
# End automatically added section
