#!/bin/sh
set -e
# Automatically added by dh_installsystemd/11.1.5
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/11.1.5
if [ "$1" = "purge" ] ; then
	update-rc.d sbd remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.1.5
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'sbd.service' 'sbd_remote.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'sbd.service' 'sbd_remote.service' >/dev/null || true
		deb-systemd-helper unmask 'sbd.service' 'sbd_remote.service' >/dev/null || true
	fi
fi
# End automatically added section
