#!/bin/sh
set -e

if [ "$1" = 'configure' ]; then
	if ! getent passwd docker-registry > /dev/null; then
		adduser --system \
			--home /var/lib/docker-registry \
			--no-create-home \
			--group \
			--gecos 'Docker Registry' \
			docker-registry
	fi

	# Ensure config directory permissions
	#  On a fresh install, $2 = '' and dpkg treat that as a
	#  lower version, so the permissions get fixed too.
	if dpkg --compare-versions "$2" le '2.4.1~ds1-1'; then
	    chmod 0755 /etc/docker
	fi

	# ensure home directory ownership (logic borrowed from postgresql-common)
	mkdir -p /var/lib/docker-registry
	su -s /bin/sh docker-registry -c '
		set -e
		test -O /var/lib/docker-registry
		test -G /var/lib/docker-registry
	' || chown docker-registry:docker-registry /var/lib/docker-registry
fi

# Automatically added by dh_systemd_enable/11.2.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# This will only remove masks created by d-s-h on package removal.
	deb-systemd-helper unmask 'docker-registry.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'docker-registry.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'docker-registry.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'docker-registry.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installinit/11.2.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/docker-registry" ]; then
		update-rc.d docker-registry defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d docker-registry $_dh_action || exit 1
	fi
fi
# End automatically added section


exit 0
