#!/bin/sh
set -e

# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p yokadi 
fi

if which pycompile >/dev/null 2>&1; then
	pycompile -p yokadi /usr/share/yokadi
fi

# End automatically added section
