#!/bin/sh

set -e

mandir=/usr/share/man

if [ "$1" = "configure" ] ; then
	update-alternatives --install /usr/bin/activipy_tester activipy_tester /usr/bin/python2-activipy_tester 200 \
		--slave $mandir/man1/activipy_tester.1.gz activipy_tester.1.gz $mandir/man1/python2-activipy_tester.1.gz
fi


# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p python-activipy 
fi

# End automatically added section


exit 0
