#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.1.2
dpkg-maintscript-helper symlink_to_dir /usr/share/doc/sawfish-lisp-source /usr/share/doc/sawfish-data 1:1.11-1~ -- "$@"
# End automatically added section
