#!/bin/sh
set -e
# Automatically added by dh_installemacsen
if [ -e /var/lib/emacsen-common/state/package/installed/emacsen-common ] ; then
	/usr/lib/emacsen-common/emacs-package-remove --prerm gnuplot-mode
fi
# End automatically added section
