#!/bin/sh
set -e
# Automatically added by dh_installinit/11.3.5
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/kea-ctrl-agent" ]; then
		update-rc.d kea-ctrl-agent defaults >/dev/null
		invoke-rc.d kea-ctrl-agent start || exit 1
	fi
fi
# End automatically added section
