#! /bin/sh -e

if [ "$1" = upgrade ] && dpkg --compare-versions "$2" lt-nl 6.0.0-1
then
  if [ -f /etc/printcap.orig ]
  then
    if [ -f /etc/printcap ]
    then
      mkdir -p /etc/apsfilter
      cp -p /etc/printcap /etc/apsfilter/printcap.dpkg-old
      rm -f /etc/printcap.old
    fi
    mv /etc/printcap.orig /etc/printcap
  fi

  rm -rf /var/lib/apsfilter/filter /var/lib/apsfilter/filters_found

  for conffile in /etc/apsfilterrc*
  do
    if [ -f "$conffile" ]
    then
      mv "$conffile" "/etc/apsfilter/${conffile##*/}.dpkg-old"
    fi
  done
fi


