#!/bin/sh
set -e
# Automatically added by dh_installinit/11.3.5
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/argonaut-client" ]; then
		update-rc.d argonaut-client defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d argonaut-client $_dh_action || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.3.5
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if deb-systemd-helper debian-installed 'argonaut-client.service'; then
		# This will only remove masks created by d-s-h on package removal.
		deb-systemd-helper unmask 'argonaut-client.service' >/dev/null || true

		if deb-systemd-helper --quiet was-enabled 'argonaut-client.service'; then
			# Create new symlinks, if any.
			deb-systemd-helper enable 'argonaut-client.service' >/dev/null || true
		fi
	fi

	# Update the statefile to add new symlinks (if any), which need to be cleaned
	# up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'argonaut-client.service' >/dev/null || true
fi
# End automatically added section
