#!/bin/sh -e

# activate udev rule before cme tries to upgrade the configuration
udevadm trigger --action=change

# Automatically added by dh_cme_upgrade/UNDECLARED
# In case of error (error in configuration file or model bug), the
# configuration file is left as is.

. /usr/share/debconf/confmodule

db_get  lcdproc/auto-upgrade-config

# testing perl is required to avoid problem in embedded environments
if [ "$RET" = true ] && [ -x "/usr/bin/perl" ] && [ -x "/usr/bin/cme" ] 
then
	cme fix lcdproc -create -backup dpkg-old -try-app-as-model -force || \
	echo "WARNING: upgrade with cme failed: Run 'sudo cme migrate lcdproc -force'."
fi
# End automatically added section
# Automatically added by dh_installinit/11.2.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/LCDd" ]; then
		update-rc.d LCDd defaults >/dev/null
		invoke-rc.d LCDd start || exit 1
	fi
fi
# End automatically added section

