#!/bin/sh
set -e
# Automatically added by dh_installdeb/10.10.8
dpkg-maintscript-helper rm_conffile /etc/apache/conf.d/dpkg-www 2.55\~ -- "$@"
dpkg-maintscript-helper mv_conffile /etc/apache2/conf.d/dpkg-www /etc/apache2/conf-available/dpkg-www.conf 2.55\~ -- "$@"
# End automatically added section
# Automatically added by dh_apache2/UNDECLARED
if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ] ; then
	if true; then
		if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
			. /usr/share/apache2/apache2-maintscript-helper

			for conf in dpkg-www  ; do
				apache2_invoke disconf $conf  || exit $?
			done
		fi
	fi
fi
# End automatically added section
