#!/bin/sh
# prerm script for ocsinventory-server
#
# see: dh_installdeb(1)

set -e

# source debconf stuff
. /usr/share/debconf/confmodule
# source dbconfig-common stuff
. /usr/share/dbconfig-common/dpkg/prerm.mysql
dbc_go prelude-manager $@

# Automatically added by dh_installdeb/11
dpkg-maintscript-helper rm_conffile /etc/init.d/prelude-manager 3.1.0-0.2\~ prelude-manager -- "$@"
dpkg-maintscript-helper rm_conffile /etc/default/prelude-manager 3.1.0-0.2\~ prelude-manager -- "$@"
# End automatically added section
# Automatically added by dh_systemd_start/11
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'prelude-manager.service' >/dev/null
fi
# End automatically added section


exit 0
