#!/bin/sh
set -e
# Automatically added by dh_installinit/10.10.5
if [ -x "/etc/init.d/openbsd-inetd" ] && [ "$1" = remove ]; then
	invoke-rc.d openbsd-inetd stop || exit $?
fi
# End automatically added section
