#!/bin/sh
set -e
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/mai/bing.xml 45.0esr-2~ iceweasel-l10n-mai -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/mai/ddg.xml 45.0esr-2~ iceweasel-l10n-mai -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/mai/eBay-in.xml 45.0esr-2~ iceweasel-l10n-mai -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/mai/google.xml 45.0esr-2~ iceweasel-l10n-mai -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/mai/twitter.xml 45.0esr-2~ iceweasel-l10n-mai -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/mai/wikipedia-hi.xml 45.0esr-2~ iceweasel-l10n-mai -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/mai/yahoo-in.xml 45.0esr-2~ iceweasel-l10n-mai -- "$@"
# End automatically added section
