#!/bin/sh

set -e

if [ "$1" = "configure" ] ; then
        update-alternatives --install /usr/bin/oslo-config-generator oslo-config-generator /usr/bin/python3-oslo-config-generator 400
fi


# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p python3-oslo.config 
fi
if which pypy3compile >/dev/null 2>&1; then
	pypy3compile -p python3-oslo.config  || true
fi

# End automatically added section


exit 0
