#!/bin/sh
set -e
# Automatically added by dh_systemd_start
if [ -d /run/systemd/system ]; then
	deb-systemd-invoke stop debci-collector.service debci-update.service debci-update.timer >/dev/null
fi
# End automatically added section
