#! /bin/sh

set -e

FPCDIR=/usr/lib/x86_64-linux-gnu/fpc

# add alternatives
update-alternatives \
    --install ${FPCDIR}/default fp-utils ${FPCDIR}/3.0.4 3000400 \
    --slave ${FPCDIR}/lexyacc fplexyacc ${FPCDIR}/3.0.4/lexyacc \
	--slave /usr/bin/chmcmd chmcmd /usr/bin/chmcmd-3.0.4 \
	--slave /usr/bin/chmls chmls /usr/bin/chmls-3.0.4 \
	--slave /usr/bin/ifpc ifpc /usr/bin/ifpc-3.0.4 \
	--slave /usr/bin/fppkg fppkg /usr/bin/fppkg-3.0.4 \
	--slave /usr/bin/grab_vcsa grab_vcsa /usr/bin/grab_vcsa-3.0.4 \
	--slave /usr/bin/instantfpc instantfpc /usr/bin/ifpc-3.0.4 \
	--slave /usr/bin/ppufiles ppufiles /usr/bin/ppufiles-3.0.4 \
	--slave /usr/bin/ppudump ppudump /usr/bin/ppudump-3.0.4 \
	--slave /usr/bin/ppumove ppumove /usr/bin/ppumove-3.0.4 \
	--slave /usr/bin/ppdep ppdep /usr/bin/ppdep-3.0.4 \
	--slave /usr/bin/ptop ptop /usr/bin/ptop-3.0.4 \
	--slave /usr/bin/rstconv rstconv /usr/bin/rstconv-3.0.4 \
	--slave /usr/bin/data2inc data2inc /usr/bin/data2inc-3.0.4 \
	--slave /usr/bin/bin2obj bin2obj /usr/bin/bin2obj-3.0.4 \
	--slave /usr/bin/delp delp /usr/bin/delp-3.0.4 \
	--slave /usr/bin/plex plex /usr/bin/plex-3.0.4 \
	--slave /usr/bin/pyacc pyacc /usr/bin/pyacc-3.0.4 \
	--slave /usr/bin/h2pas h2pas /usr/bin/h2pas-3.0.4 \
	--slave /usr/bin/h2paspp h2paspp /usr/bin/h2paspp-3.0.4 \
	--slave /usr/bin/postw32 postw32 /usr/bin/postw32-3.0.4 \
	--slave /usr/bin/fpclasschart fpclasschart /usr/bin/fpclasschart-3.0.4 \
	--slave /usr/bin/fpcmake fpcmake /usr/bin/fpcmake-3.0.4 \
	--slave /usr/bin/fpcsubst fpcsubst /usr/bin/fpcsubst-3.0.4 \
	--slave /usr/bin/fprcp fprcp /usr/bin/fprcp-3.0.4 \
	--slave /usr/bin/fpdoc fpdoc /usr/bin/fpdoc-3.0.4 \
	--slave /usr/bin/makeskel makeskel /usr/bin/makeskel-3.0.4 \
	--slave /usr/bin/relpath relpath /usr/bin/relpath-3.0.4 \
	--slave /usr/bin/rmcvsdir rmcvsdir /usr/bin/rmcvsdir-3.0.4 \
	--slave /usr/bin/unitdiff unitdiff /usr/bin/unitdiff-3.0.4 \
	--slave /usr/share/man/man1/chmcmd.1.gz chmcmd.1.gz /usr/share/man/man1/chmcmd-3.0.4.1.gz \
	--slave /usr/share/man/man1/chmls.1.gz chmls.1.gz /usr/share/man/man1/chmls-3.0.4.1.gz \
	--slave /usr/share/man/man1/ifpc.1.gz ifpc.1.gz /usr/share/man/man1/ifpc-3.0.4.1.gz \
	--slave /usr/share/man/man1/fppkg.1.gz fppkg.1.gz /usr/share/man/man1/fppkg-3.0.4.1.gz \
	--slave /usr/share/man/man1/instantfpc.1.gz instantfpc.1.gz /usr/share/man/man1/ifpc-3.0.4.1.gz \
	--slave /usr/share/man/man1/bin2obj.1.gz bin2obj.1.gz /usr/share/man/man1/bin2obj-3.0.4.1.gz \
	--slave /usr/share/man/man1/data2inc.1.gz data2inc.1.gz /usr/share/man/man1/data2inc-3.0.4.1.gz \
	--slave /usr/share/man/man1/fprcp.1.gz fprcp.1.gz /usr/share/man/man1/fprcp-3.0.4.1.gz \
	--slave /usr/share/man/man1/h2paspp.1.gz h2paspp.1.gz /usr/share/man/man1/h2paspp-3.0.4.1.gz \
	--slave /usr/share/man/man1/makeskel.1.gz makeskel.1.gz /usr/share/man/man1/makeskel-3.0.4.1.gz \
	--slave /usr/share/man/man1/postw32.1.gz postw32.1.gz /usr/share/man/man1/postw32-3.0.4.1.gz \
	--slave /usr/share/man/man1/relpath.1.gz relpath.1.gz /usr/share/man/man1/relpath-3.0.4.1.gz \
	--slave /usr/share/man/man1/rmcvsdir.1.gz rmcvsdir.1.gz /usr/share/man/man1/rmcvsdir-3.0.4.1.gz \
	--slave /usr/share/man/man1/unitdiff.1.gz unitdiff.1.gz /usr/share/man/man1/unitdiff-3.0.4.1.gz \
	--slave /usr/share/man/man1/delp.1.gz delp.1.gz /usr/share/man/man1/delp-3.0.4.1.gz \
	--slave /usr/share/man/man1/fpcmake.1.gz fpcmake.1.gz /usr/share/man/man1/fpcmake-3.0.4.1.gz \
	--slave /usr/share/man/man1/fpcsubst.1.gz fpcsubst.1.gz /usr/share/man/man1/fpcsubst-3.0.4.1.gz \
	--slave /usr/share/man/man1/h2pas.1.gz h2pas.1.gz /usr/share/man/man1/h2pas-3.0.4.1.gz \
	--slave /usr/share/man/man1/plex.1.gz plex.1.gz /usr/share/man/man1/plex-3.0.4.1.gz \
	--slave /usr/share/man/man1/ppdep.1.gz ppdep.1.gz /usr/share/man/man1/ppdep-3.0.4.1.gz \
	--slave /usr/share/man/man1/ppudump.1.gz ppudump.1.gz /usr/share/man/man1/ppudump-3.0.4.1.gz \
	--slave /usr/share/man/man1/ppufiles.1.gz ppufiles.1.gz /usr/share/man/man1/ppufiles-3.0.4.1.gz \
	--slave /usr/share/man/man1/ppumove.1.gz ppumove.1.gz /usr/share/man/man1/ppumove-3.0.4.1.gz \
	--slave /usr/share/man/man1/ptop.1.gz ptop.1.gz /usr/share/man/man1/ptop-3.0.4.1.gz \
	--slave /usr/share/man/man1/pyacc.1.gz pyacc.1.gz /usr/share/man/man1/pyacc-3.0.4.1.gz \
	--slave /usr/share/man/man1/rstconv.1.gz rstconv.1.gz /usr/share/man/man1/rstconv-3.0.4.1.gz \
	--slave /usr/share/man/man1/fpdoc.1.gz fpdoc.1.gz /usr/share/man/man1/fpdoc-3.0.4.1.gz \
	--slave /usr/share/man/man1/fpclasschart.1.gz fpclasschart.1.gz /usr/share/man/man1/fpclasschart-3.0.4.1.gz \
	--slave /usr/share/man/man5/fpcmake.5.gz fpcmake.5.gz /usr/share/man/man5/fpcmake-3.0.4.5.gz \
	--slave /usr/share/man/man5/ptop.cfg.5.gz ptop.cfg.5.gz /usr/share/man/man5/ptop-3.0.4.cfg.5.gz

# Debhelper code

