#!/bin/sh
set -e

# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p youtube-dl 
fi
if which pypy3compile >/dev/null 2>&1; then
	pypy3compile -p youtube-dl  || true
fi

# End automatically added section
# Automatically added by dh_installdeb/11.5.1
dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/youtube-dl.bash-completion 2016.08.17-1\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/fish/completions/youtube-dl.fish 2016.08.17-1\~ -- "$@"
# End automatically added section
