#!/bin/sh
set -e
# Automatically added by dh_installmenu
if [ "$1" = "configure" ] && [ -x "`which update-menus 2>/dev/null`" ]; then
	update-menus
fi
# End automatically added section

# Automatically added by dhpython:
if which pycompile >/dev/null 2>&1; then
	pycompile -p screenlets 
fi

if which pycompile >/dev/null 2>&1; then
	pycompile -p screenlets /usr/share/screenlets -V 2.4-
fi

# End automatically added section
