#!/bin/sh
set -e

if [ "$1" = "purge" ]; then
	rm -f /etc/default/i2pd
	rm -rf /etc/i2pd
	rm -rf /var/lib/i2pd
	rm -rf /var/log/i2pd
	rm -rf /var/run/i2pd
fi

# Automatically added by dh_installinit/11.3.5
if [ "$1" = "purge" ] ; then
	update-rc.d i2pd remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.3.5
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'i2pd.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'i2pd.service' >/dev/null || true
		deb-systemd-helper unmask 'i2pd.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
