#!/bin/sh

set -e

if [ "$1" = "configure" ]; then
	# If the log directory does not exist, create it and restart ntpd to
	# enable logging.
	if ! [ -d /var/log/ntpsec ]; then
		# This has to be duplicated from the ntpsec postinst so the
		# user and group exist for the install command below. This
		# package intentionally does not depend on ntpsec.  Even if it
		# did, a Pre-Depends would be required, which Policy frowns
		# upon.
		addgroup --system --quiet ntpsec
		adduser --system --quiet --ingroup ntpsec \
			--no-create-home --home /nonexistent ntpsec

		install -o ntpsec -g ntpsec -d /var/log/ntpsec
		invoke-rc.d ntpsec restart
	fi

	if [ "$1" = "configure" ] && [ -n "$2" ] &&
	   dpkg --compare-versions "$2" le-nl "1.1.0+dfsg1-2~"; then
		mv -n /var/lib/ntp/ntpviz/day/* /var/lib/ntpsec/ntpviz/day/ \
			2> /dev/null || true
		mv -n /var/lib/ntp/ntpviz/week/* /var/lib/ntpsec/ntpviz/week/ \
			2> /dev/null || true
		rmdir /var/lib/ntp/ntpviz/day \
		      /var/lib/ntp/ntpviz/week \
		      /var/lib/ntp/ntpviz \
		      /var/lib/ntp \
			2> /dev/null || true
	fi
fi

# Automatically added by dh_apache2/UNDECLARED
if true; then
	if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
		. /usr/share/apache2/apache2-maintscript-helper
		for conf in ntpsec-ntpviz  ; do
			apache2_invoke enconf $conf  || exit 1
		done
	fi
fi
# End automatically added section
# Automatically added by dh_systemd_enable/11.3.5
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# This will only remove masks created by d-s-h on package removal.
	deb-systemd-helper unmask 'ntploggps.timer' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'ntploggps.timer'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'ntploggps.timer' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'ntploggps.timer' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_systemd_enable/11.3.5
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# This will only remove masks created by d-s-h on package removal.
	deb-systemd-helper unmask 'ntplogtemp.timer' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'ntplogtemp.timer'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'ntplogtemp.timer' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'ntplogtemp.timer' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_systemd_enable/11.3.5
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# This will only remove masks created by d-s-h on package removal.
	deb-systemd-helper unmask 'ntpviz-daily.timer' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'ntpviz-daily.timer'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'ntpviz-daily.timer' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'ntpviz-daily.timer' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_systemd_enable/11.3.5
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# This will only remove masks created by d-s-h on package removal.
	deb-systemd-helper unmask 'ntpviz-weekly.timer' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'ntpviz-weekly.timer'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'ntpviz-weekly.timer' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'ntpviz-weekly.timer' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_systemd_start/11.3.5
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'ntploggps.timer' 'ntplogtemp.timer' 'ntpviz-daily.timer' 'ntpviz-weekly.timer' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installdeb/11.3.5
dpkg-maintscript-helper mv_conffile /etc/ntp.d/ntpviz.conf /etc/ntpsec/ntp.d/ntpviz.conf 1.1.0\+dfsg1-2\~ ntpsec-ntpviz -- "$@"
# End automatically added section


if [ "$1" = "configure" ] && [ -n "$2" ] &&
   dpkg --compare-versions "$2" le-nl "1.1.0+dfsg1-2~"; then
	# We have completed the transition of /etc/ntp.d.
	rm -f /etc/ntp.d/ntpviz.conf
	rmdir /etc/ntp.d 2> /dev/null || true
fi
