#!/bin/sh

set -e

if [ "$1" = purge ] || [ "$1" = remove ]; then

        if [ -f /usr/share/guake/data/gschemas.compiled ]; then
                rm -rf /usr/share/guake/data/gschemas.compiled
        fi
fi



exit 0
