#!/bin/sh
set -e
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper symlink_to_dir /usr/share/gtk-doc/html/flatpak /usr/share/doc/libflatpak-doc/flatpak 0.9.99-2\~ -- "$@"
dpkg-maintscript-helper dir_to_symlink /usr/share/doc/libflatpak-doc/flatpak /usr/share/gtk-doc/html/flatpak 0.9.99-2\~ -- "$@"
# End automatically added section
