#!/bin/sh
set -e


if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ]; then

	update-alternatives --remove nvidia /usr/lib/nvidia/current
	dpkg-trigger --no-await register-glx-alternative-nvidia

fi


# Automatically added by dh_installdeb/11.4
dpkg-maintscript-helper rm_conffile /etc/nvidia/nvidia-modprobe.conf 352.55\~ -- "$@"
# End automatically added section

