#!/bin/sh
set -e
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/tr/yandex-tr.xml 45.0esr-2~ iceweasel-l10n-tr -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/tr/wikipedia-tr.xml 45.0esr-2~ iceweasel-l10n-tr -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/tr/twitter.xml 45.0esr-2~ iceweasel-l10n-tr -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/tr/google.xml 45.0esr-2~ iceweasel-l10n-tr -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/tr/eBay.xml 45.0esr-2~ iceweasel-l10n-tr -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/tr/ddg.xml 45.0esr-2~ iceweasel-l10n-tr -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/tr/amazondotcom.xml 45.0esr-2~ iceweasel-l10n-tr -- "$@"
# End automatically added section
