#!/bin/sh
set -e
# Automatically added by dh_installinit/11.2.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/gcpegg" ]; then
		update-rc.d gcpegg defaults >/dev/null
		invoke-rc.d gcpegg start || exit 1
	fi
fi
# End automatically added section
