#!/bin/sh

set -e

if [ "$1" = "configure" ] ; then
	update-alternatives --install /usr/bin/targetctl targetctl /usr/bin/targetctl-python2 300
	if [ ! -d /etc/rtslib-fb-target ] ; then
		mkdir -p /etc/rtslib-fb-target
	fi
	# If file doesn't exist or is of size zero, write it...
	if [ ! -s /etc/rtslib-fb-target/saveconfig.json ] ; then
		echo "{
  \"fabric_modules\": [],
  \"storage_objects\": [],
  \"targets\": []
}" >/etc/rtslib-fb-target/saveconfig.json
	fi
fi


# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p python-rtslib-fb 
fi

# End automatically added section
# Automatically added by dh_installinit/11.3.5
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/rtslib-fb-targetctl" ]; then
		update-rc.d rtslib-fb-targetctl defaults >/dev/null
		invoke-rc.d rtslib-fb-targetctl start || exit 1
	fi
fi
# End automatically added section

