#!/bin/sh

set -e

if [ "$1" = "remove" ] || [ "$1" = "disappear" ]; then
	update-alternatives --remove targetctl /usr/bin/targetctl-python2
fi
if [ "$1" = "purge" ] ; then
	rm -rf /etc/rtslib-fb-target
fi

# Automatically added by dh_installinit/11.3.5
if [ "$1" = "purge" ] ; then
	update-rc.d rtslib-fb-targetctl remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section

