#!/bin/sh
set -e
# Automatically added by dh_installdeb/10.7.2
dpkg-maintscript-helper mv_conffile /etc/rsyslog.d/haproxy.conf /etc/rsyslog.d/49-haproxy.conf 1.5.3-2~ -- "$@"
# End automatically added section
