#!/bin/sh
set -e
# Automatically added by dh_installdeb/10.9
dpkg-maintscript-helper symlink_to_dir /usr/share/doc/ipython-qtconsole ipython 4.2.1-2\~ ipython-qtconsole -- "$@"
# End automatically added section
