#!/bin/sh 
set -e

if [ "$1" = "purge" ]; then
    rm -f /etc/menu-methods/fbpanel
fi

# Automatically added by dh_installmenu/10.9.1
if [ -x "`which update-menus 2>/dev/null`" ]; then update-menus ; fi
# End automatically added section

