#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/apf-firewall" ]; then
		update-rc.d apf-firewall defaults >/dev/null
		invoke-rc.d apf-firewall start || exit $?
	fi
fi
# End automatically added section
