#!/bin/sh

set -e

if test "$1" = "remove"; then
    if test -x /usr/sbin/update-binfmts; then
        update-binfmts --package llvm-7-runtime \
            --remove llvm-7-runtime.binfmt /usr/bin/lli-7 || true
        if test -f /var/lib/binfmts/llvm-7.binfmt; then
            # Purge old file
            update-binfmts --package llvm-7-runtime \
                --remove llvm-7.binfmt /usr/bin/lli-7 || true
        fi
    fi
fi



