#!/bin/sh

set -e

. /usr/share/debconf/confmodule
. /usr/share/dbconfig-common/dpkg/prerm.pgsql
dbc_go pybit-web $@


# Automatically added by dh_python2:
if which pyclean >/dev/null 2>&1; then
	pyclean -p pybit-web 
else
	dpkg -L pybit-web | grep \.py$ | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section

