#! /bin/sh

set -e

remove_alternative () {
    update-alternatives --remove $1 /usr/bin/vigor
}

if [ "$1" = configure ] && dpkg --compare-versions "$2" lt-nl 0.016-26; then
    remove_alternative vi
    remove_alternative view
    remove_alternative editor
fi

# Automatically added by dh_installmenu/11.2.1
if [ "$1" = "configure" ] && [ -x "`which update-menus 2>/dev/null`" ]; then
	update-menus
fi
# End automatically added section


exit 0
