#!/bin/sh
set -e
# Automatically added by dh_php/UNDECLARED
for conf in wikidiff2; do
    dpkg-maintscript-helper rm_conffile /etc/php/mods-available/${conf}.ini -- "$@"
done

if [ -e /usr/lib/php/php-maintscript-helper ] ; then
    . /usr/lib/php/php-maintscript-helper

    for version in 7.2 ; do
        for conf in wikidiff2 ; do
            php_invoke enmod $version ALL $conf || exit 1
	done
    done
else
    for conf in wikidiff2 ; do
        phpenmod $conf
    done
fi
# End automatically added section
# Automatically added by dh_installdeb/11.3.5
dpkg-maintscript-helper rm_conffile /etc/mediawiki-extensions/extensions-enabled/wikidiff2.php 1.4.1-1 -- "$@"
dpkg-maintscript-helper rm_conffile /etc/mediawiki-extensions/extensions-available/wikidiff2.php 1.4.1-1 -- "$@"
# End automatically added section
