#!/bin/sh
set -e
# Automatically added by dh_php/UNDECLARED
for conf in wikidiff2; do
    dpkg-maintscript-helper rm_conffile /etc/php/mods-available/${conf}.ini -- "$@"
done

if [ "$1" = "upgrade" ]; then
    # Cleanup of the old symlinks (including broken symlinks)
    inidir=/etc/php/mods-available
    for dsoname in wikidiff2; do
	inifile=${dsoname}.ini
	find /etc/php/ -type l | \
	    while read symlink; do
		if [ "$(readlink $symlink)" = "${inidir}/$inifile" ]; then
		    rm -f "${symlink}"
		fi
	    done
    done
fi
# End automatically added section
# Automatically added by dh_installdeb/11.3.5
dpkg-maintscript-helper rm_conffile /etc/mediawiki-extensions/extensions-enabled/wikidiff2.php 1.4.1-1 -- "$@"
dpkg-maintscript-helper rm_conffile /etc/mediawiki-extensions/extensions-available/wikidiff2.php 1.4.1-1 -- "$@"
# End automatically added section
