#!/bin/sh

set -e

. /usr/share/debconf/confmodule

if [ -f /usr/share/dbconfig-common/dpkg/prerm.pgsql ]; then
	. /usr/share/dbconfig-common/dpkg/prerm.pgsql
	dbc_go sreview-master "$@"
fi

# Automatically added by dh_installinit/11.3.2
if [ -x "/etc/init.d/sreview-dispatch" ] && [ "$1" = remove ]; then
	invoke-rc.d sreview-dispatch stop || exit 1
fi
# End automatically added section
# Automatically added by dh_systemd_start/11.3.2
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'sreview-dispatch.service' >/dev/null || true
fi
# End automatically added section

