#!/bin/sh
set -e

# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p lyx-common /usr/share/lyx
fi

# End automatically added section
# Automatically added by dh_installtex/1
##
## postinst-tex
##
## postinst snippets for everything TeX related
## simply call update-texmf-config triggers
##
## Authors:
##       Norbert Preining <preining@logic.at>
##
#

case "$1" in
    configure|abort-upgrade|abort-remove|abort-deconfigure)
        update-texmf-config 
    ;;
esac

# End automatically added section
# Automatically added by dh_installdeb/10.9
dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/lyx 2.0.2-1 -- "$@"
# End automatically added section
