#!/bin/sh
set -e
# Automatically added by dh_installsystemd/10.10.9
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'lvm2-lvmlockd.service' 'lvm2-lvmlocking.service' >/dev/null
fi
# End automatically added section
