#!/bin/sh
set -e
# Automatically added by dh_installdeb/12
dpkg-maintscript-helper rm_conffile /etc/xdg/autostart/tracker-miner-user-guides.desktop 2.0.4-1\~ tracker-miner-fs -- "$@"
# End automatically added section
