#!/bin/sh
set -e
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/fr/amazon-france.xml 45.0esr-2~ iceweasel-l10n-fr -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/fr/bing.xml 45.0esr-2~ iceweasel-l10n-fr -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/fr/cnrtl-tlfi-fr.xml 45.0esr-2~ iceweasel-l10n-fr -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/fr/ddg.xml 45.0esr-2~ iceweasel-l10n-fr -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/fr/eBay-france.xml 45.0esr-2~ iceweasel-l10n-fr -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/fr/google.xml 45.0esr-2~ iceweasel-l10n-fr -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/fr/wikipedia-fr.xml 45.0esr-2~ iceweasel-l10n-fr -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/fr/yahoo-france.xml 45.0esr-2~ iceweasel-l10n-fr -- "$@"
# End automatically added section
