#!/bin/sh
set -e
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/default/pushpin 1.9.0-2~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/pushpin/internal.conf 1.8.0-1~ -- "$@"
# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/pushpin" ]; then
	invoke-rc.d pushpin stop || exit $?
fi
# End automatically added section
