#!/bin/sh
set -e
# Automatically added by dh_installxmlcatalogs/UNDECLARED
if [ "$1" = "configure" ]; then
	update-xmlcatalog --sort --add --type public --id "-//Steve Cheng//DTD Man-XML V0.8.6//EN" --package docbook2x --local /usr/share/docbook2X/dtd/catalog.xml
	update-xmlcatalog --sort --add --type public --id "-//Steve Cheng//DTD Texi-XML V0.8.6//EN" --package docbook2x --local /usr/share/docbook2X/dtd/catalog.xml
	update-xmlcatalog --sort --add --type system --id "http://docbook2x.sourceforge.net/latest/dtd/" --package docbook2x --local /usr/share/docbook2X/dtd/catalog.xml
	update-xmlcatalog --sort --add --type system --id "http://docbook2x.sf.net/latest/dtd/" --package docbook2x --local /usr/share/docbook2X/dtd/catalog.xml
	update-xmlcatalog --sort --add --type public --id "-//Steve Cheng//DOCUMENT DocBook Texinfo Stylesheet//EN" --package docbook2x --local /usr/share/docbook2X/xslt/catalog.xml
	update-xmlcatalog --sort --add --type public --id "-//Steve Cheng//DOCUMENT DocBook Man-page Stylesheet//EN" --package docbook2x --local /usr/share/docbook2X/xslt/catalog.xml
	update-xmlcatalog --sort --add --type system --id "http://docbook2x.sourceforge.net/latest/xslt/" --package docbook2x --local /usr/share/docbook2X/xslt/catalog.xml
	update-xmlcatalog --sort --add --type system --id "http://docbook2x.sf.net/latest/xslt/" --package docbook2x --local /usr/share/docbook2X/xslt/catalog.xml

	update-xmlcatalog --sort --add --type public --id "-//Steve Cheng//DTD" --package docbook2x --root
	update-xmlcatalog --sort --add --type public --id "-//Steve Cheng//DOCUMENT DocBook" --package docbook2x --root
	update-xmlcatalog --sort --add --type system --id "http://docbook2x.sf.net/latest/" --package docbook2x --root
	update-xmlcatalog --sort --add --type system --id "http://docbook2x.sourceforge.net/latest/" --package docbook2x --root

fi
# End automatically added section
