#!/bin/sh
set -e
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/fi/yahoo-fi.xml 45.0esr-2~ iceweasel-l10n-fi -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/fi/wikipedia-fi.xml 45.0esr-2~ iceweasel-l10n-fi -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/fi/google.xml 45.0esr-2~ iceweasel-l10n-fi -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/fi/eBay-fi.xml 45.0esr-2~ iceweasel-l10n-fi -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/fi/ddg.xml 45.0esr-2~ iceweasel-l10n-fi -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/fi/bookplus-fi.xml 45.0esr-2~ iceweasel-l10n-fi -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/fi/bing.xml 45.0esr-2~ iceweasel-l10n-fi -- "$@"
# End automatically added section
