#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.3.5
dpkg-maintscript-helper rm_conffile /etc/emacs/site-start.d/50dynare.el 4.5.3-2\~ dynare -- "$@"
# End automatically added section
# Automatically added by dh_elpa/UNDECLARED
if [ -e /var/lib/emacsen-common/state/package/installed/emacsen-common -a -x /usr/lib/emacsen-common/emacs-package-remove ] ; then
	/usr/lib/emacsen-common/emacs-package-remove --prerm dynare
fi
# End automatically added section
