#!/bin/sh -e

# Automatically added by dh_installinit/11.5.1
if [ -x "/etc/init.d/binkd" ] && [ "$1" = remove ]; then
	invoke-rc.d binkd stop || exit 1
fi
# End automatically added section


# must be executed after /etc/init.d/binkd stop
if [ -x /usr/sbin/update-inetd ]; then
  update-inetd --remove '^binkp[ \t]'
fi

