#!/bin/sh

set -e

# Automatically added by dh_installinit/11.5.3
if [ "$1" = "purge" ] ; then
	update-rc.d quake-server remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.5.3
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'quake-server.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'quake-server.service' >/dev/null || true
		deb-systemd-helper unmask 'quake-server.service' >/dev/null || true
	fi
fi
# End automatically added section


if [ "$1" = "purge" ] ; then
    # Lock account on purge
    if [ -f /etc/shadow ]; then
        usermod -L -e 1 quake-server
    else
        usermod -L quake-server
    fi
    rm -r /var/games/quake-server
    rmdir --ignore-fail-on-non-empty /var/games
fi
