#!/bin/sh

set -e

case "$1" in
  configure)
    if ! getent passwd quake-server >/dev/null; then
      adduser --disabled-password --quiet --system \
        --home /var/games/quake-server --no-create-home \
        --gecos "Quake dedicated server" \
	--ingroup games --force-badname quake-server
    fi
    # Unlock account, if it was locked by our postrm
    if [ -f /etc/shadow ]; then
      usermod -U -e '' quake-server
    else
      usermod -U quake-server
    fi
    install -d /var/games
    install -d -o quake-server -g games /var/games/quake-server
  ;;
  abort-upgrade|abort-remove|abort-deconfigure)
  ;;
  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac


# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p quake-server /usr/share/games/quake
fi
if which pypy3compile >/dev/null 2>&1; then
	pypy3compile -p quake-server /usr/share/games/quake || true
fi

# End automatically added section
# Automatically added by dh_installinit/11.5.3
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/quake-server" ]; then
		update-rc.d quake-server defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d quake-server $_dh_action || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.5.3
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# This will only remove masks created by d-s-h on package removal.
	deb-systemd-helper unmask 'quake-server.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'quake-server.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'quake-server.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'quake-server.service' >/dev/null || true
	fi
fi
# End automatically added section

