#!/bin/sh

set -e

if [ "$1" = "purge" ] ; then
    rm -f /var/log/nova/nova-scheduler.log*
fi


# Automatically added by dh_installinit/11.5.3
if [ "$1" = "purge" ] ; then
	update-rc.d nova-scheduler remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_systemd_enable/11.5.3
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'nova-scheduler.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'nova-scheduler.service' >/dev/null || true
		deb-systemd-helper unmask 'nova-scheduler.service' >/dev/null || true
	fi
fi
# End automatically added section

