#!/bin/sh

set -e

if [ "${1}" = "configure" ] ; then
	update-alternatives --install /usr/share/puppet/modules/vcsrepo puppet-module-vcsrepo /usr/share/puppet/modules.available/puppetlabs-vcsrepo 500
fi



exit 0
