#!/bin/sh

set -e

# Automatically added by dh_installinit/11.3.5
if [ "$1" = "purge" ] ; then
	update-rc.d snapserver remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/11.3.5
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'snapserver.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'snapserver.service' >/dev/null || true
		deb-systemd-helper unmask 'snapserver.service' >/dev/null || true
	fi
fi
# End automatically added section


USERNAME=_snapserver
HOMEDIR=/var/lib/snapserver

if [ "$1" = "purge" ]; then
  rm -rf $HOMEDIR

  if [ -x "$(command -v deluser)" ]; then
    deluser --quiet --system $USERNAME > /dev/null || true
  else
    echo >&2 "not removing $USERNAME system account because deluser command was not found"
  fi
fi
