#!/bin/sh
set -e
# Automatically added by dh_installinit/11.5.3
if [ -x "/etc/init.d/quasselcore" ] && [ "$1" = remove ]; then
	invoke-rc.d quasselcore stop || exit
fi
# End automatically added section
