#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/prometheus-pgbouncer-exporter" ]; then
	invoke-rc.d prometheus-pgbouncer-exporter stop || exit $?
fi
# End automatically added section

# Automatically added by dhpython:
if which py3clean >/dev/null 2>&1; then
	py3clean -p prometheus-pgbouncer-exporter 
else
	dpkg -L prometheus-pgbouncer-exporter | perl -ne 's,/([^/]*)\.py$,/__pycache__/\1.*, or next; unlink $_ or die $! foreach glob($_)'
	find /usr/lib/python3/dist-packages/ -type d -name __pycache__ -empty -print0 | xargs --null --no-run-if-empty rmdir
fi

# End automatically added section
