#!/bin/sh
set -e
# Automatically added by dh_metainit
if [ "$1" = "purge" -a -x /usr/sbin/update-metainit ] ; then
	/usr/sbin/update-metainit --remove infon-server --purge >/dev/null || exit $?
fi
# End automatically added section
