#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.1.5
dpkg-maintscript-helper dir_to_symlink /usr/share/doc/bogofilter-sqlite /usr/share/doc/bogofilter-common 1.2.4\+dfsg1-8\~ -- "$@"
# End automatically added section
