#!/bin/sh
set -e
# Automatically added by dh_installinit/10.10.5
if [ -x "/etc/init.d/apt-cacher-ng" ] && [ "$1" = remove ]; then
	invoke-rc.d apt-cacher-ng stop || exit $?
fi
# End automatically added section
