#!/bin/sh
set -e
# Automatically added by dh_installinit/11.3.5
if [ -x "/etc/init.d/tinyproxy" ] && [ "$1" = remove ]; then
	invoke-rc.d tinyproxy stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installdeb/11.3.5
dpkg-maintscript-helper mv_conffile /etc/tinyproxy.conf /etc/tinyproxy/tinyproxy.conf 1.8.4-2\~ tinyproxy -- "$@"
# End automatically added section
