#!/bin/sh

set -e

if [ "${1}" = "configure" ] ; then
	update-alternatives --install /usr/share/puppet/modules/corosync puppet-module-corosync /usr/share/puppet/modules.available/voxpupuli-corosync 500
fi



exit 0
