#! /bin/sh

set -e

# Load debconf
. /usr/share/debconf/confmodule

LIB_DIR="/usr/lib/x86_64-linux-gnu/fpc"
MAN_DIR="/usr/share/man/man1"

# Debhelper code


# add alternatives
update-alternatives \
    --install /usr/bin/fp fp /usr/bin/fp-3.0.4 3000400
