#!/bin/sh
set -e
# Automatically added by dh_installdeb
dpkg-maintscript-helper mv_conffile /usr/share/initramfs-tools/conf-hooks.d/dropbear /etc/initramfs-tools/conf-hooks.d/dropbear 2015.68-1~ dropbear -- "$@"
# End automatically added section
