#!/bin/sh
# pre-removal script for popa3d

set -e

# Automatically added by dh_installinit
if [ -x "/etc/init.d/popa3d" ]; then
	invoke-rc.d popa3d stop || exit $?
fi
# End automatically added section


update-inetd --disable pop3
