#!/bin/sh
set -e

# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p mysql-utilities 
fi

# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/mysql/mysql-fabric-doctrine-1.4.0.zip 1.6.3-1 -- "$@"
dpkg-maintscript-helper rm_conffile /etc/mysql/fabric.cfg -- "$@"
# End automatically added section
