#!/bin/sh
set -e
# Automatically added by dh_installinit/10.7.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/psad" ]; then
		update-rc.d psad defaults >/dev/null
		invoke-rc.d psad start || exit $?
	fi
fi
# End automatically added section
