#!/bin/sh

set -e

case "$1" in
  configure)
    if [ -e /var/lib/comitup/comitup.json.save ] ; then
      mv -f /var/lib/comitup/comitup.json.save /var/lib/comitup/comitup.json
    fi

    python /usr/share/comitup/comitup/wificheck.py || true
    ;;
esac


# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p comitup /usr/share/comitup -V 2.7-
fi

# End automatically added section
# Automatically added by dh_systemd_enable/10.10.7
# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask 'comitup.service' >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled 'comitup.service'; then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable 'comitup.service' >/dev/null || true
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'comitup.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/10.10.7
# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask 'comitup-web.service' >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled 'comitup-web.service'; then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable 'comitup-web.service' >/dev/null || true
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'comitup-web.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/10.10.7
# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask 'comitup.service' >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled 'comitup.service'; then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable 'comitup.service' >/dev/null || true
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'comitup.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_start/10.10.7
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
	deb-systemd-invoke start 'comitup-web.service' 'comitup.service' >/dev/null || true
fi
# End automatically added section


exit 0
