#!/bin/sh
set -e
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/texmf/fmt.d/40musixtex.cnf 1:1.17.ctan20150601-1~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/texmf/updmap.d/20musixtex.cfg 1:0.115-2 -- "$@"
# End automatically added section
