#!/bin/sh

set -e

### Start of included pkgos_postrm library
#!/bin/sh
# -*- mode: shell-script -*-

# Perform cleanups when removing a package
# Prototype: pkgos_postrm <template-prefix-name> <package-name> $@
# Example:   pkgos_postrm neutron                neutron-common $@
pkgos_dbc_postrm () {
	local PKPRM_TEMPLATE_PREFIX PKPRM_PACKAGE_NAME

	PKPRM_TEMPLATE_PREFIX=${1}
	PKPRM_PACKAGE_NAME=${2}
	shift
	shift

	if [ -f /usr/share/debconf/confmodule ] ; then
		. /usr/share/debconf/confmodule
		# If the package has the template, then it means we're having a db,
		# and therefore we can call the dbconfig-common clean function.
		db_get ${PKPRM_TEMPLATE_PREFIX}/configure_db
		if [ "$RET" = "true" ] ; then
			if [ -f /usr/share/dbconfig-common/dpkg/postrm ] ; then
				. /usr/share/dbconfig-common/dpkg/postrm
				dbc_go ${PKPRM_PACKAGE_NAME} $@
			else
				rm -f /etc/dbconfig-common/${PKPRM_PACKAGE_NAME}.conf
				if which ucf >/dev/null 2>&1; then
					ucf --purge /etc/dbconfig-common/${PKPRM_PACKAGE_NAME}.conf
					ucfr --purge ${PKPRM_PACKAGE_NAME} /etc/dbconfig-common/${PKPRM_PACKAGE_NAME}.conf
                                fi
                        fi
                fi
	fi

	rm -rf /var/lib/${PKPRM_TEMPLATE_PREFIX} /var/log/${PKPRM_TEMPLATE_PREFIX} /var/lock/${PKPRM_TEMPLATE_PREFIX}
}
### End of included pkgos_postrm library

if [ "$1" = "purge" ] ; then
	# Purge the db
	pkgos_dbc_postrm barbican barbican-common $@

	# Purge config files copied in postinst
	for i in barbican.conf vassals/barbican-admin.ini vassals/barbican-api.ini barbican-admin-paste.ini barbican-api.conf barbican-api-paste.ini barbican-functional.conf policy.json api_audit_map.conf ; do
		rm -f /etc/barbican/$i
	done
	# and the folders
	rmdir --ignore-fail-on-non-empty /etc/barbican/vassals || true
	rmdir --ignore-fail-on-non-empty /etc/barbican || true

	echo "Purging barbican. Backup of /var/lib/barbican can be found at /var/lib/barbican.tar.bz2" >&2
	[ -e /var/lib/barbican ] && rm -rf /var/lib/barbican
	[ -e /var/log/barbican ] && rm -rf /var/log/barbican
fi

# Automatically added by dh_installdebconf/11.3.5
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


exit 0
