#!/bin/sh
set -e
# Automatically added by debian/scripts/fix_conffiles

cfgdir="/etc/X11/afterstep"
ucfdir="/usr/share/afterstep/ucf"
cfgfiles="animate asmount autoexec banner base database gtkrc-2.0_template gtkrc_template kcsrc_template pager sound standard_categories wharf winlist wintabs"
package="afterstep-data"

if [ "$1" = "purge" ] ; then
   # check is ucf is still installed  (see Bug#325905)
   which ucf >/dev/null && HAS_UCF=yes || HAS_UCF=no
   which ucfr >/dev/null && HAS_UCFR=yes || HAS_UCFR=no

   for f in $cfgfiles; do
      cf="$cfgdir/${f%.menu-method}"
      # we mimic dpkg as closely as possible, so we remove configuration
      # files with dpkg backup extensions too:
      for ext in '~' '%' .bak .ucf-new .ucf-old .ucf-dist '';  do
         rm -f "${cf}${ext}"
      done
      if [ "$HAS_UCF" = "yes"  ]; then ucf  --purge "$cf"; fi
      if [ "$HAS_UCFR" = "yes" ]; then ucfr --purge "$package" "$cf"; fi
   done

   [ ! -d "$cfgdir" ] || rmdir --parents --ignore-fail-on-non-empty "$cfgdir"
fi

# End automatically added section
