#!/bin/sh
set -e
if [ "$1" = configure ]
then
    update-alternatives \
    --install /usr/bin/py-afl-fuzz py-afl-fuzz /usr/share/python3-afl/py-afl-fuzz 10 \
    --slave /usr/share/man/man1/py-afl-fuzz.1.gz py-afl-fuzz.1.gz /usr/share/man/man1/py-afl-fuzz.py3.1.gz
    update-alternatives \
    --install /usr/bin/py-afl-cmin py-afl-cmin /usr/share/python3-afl/py-afl-cmin 10
    update-alternatives \
    --install /usr/bin/py-afl-showmap py-afl-showmap /usr/share/python3-afl/py-afl-showmap 10
    update-alternatives \
    --install /usr/bin/py-afl-tmin py-afl-tmin /usr/share/python3-afl/py-afl-tmin 10
fi

