#!/bin/sh
set -e
# Automatically added by dh_installdeb
dpkg-maintscript-helper dir_to_symlink /usr/share/doc/bacula-sd bacula-common 7.0.5\+dfsg-4\~ -- "$@"
# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/bacula-sd" ] && [ "$1" = remove ]; then
	invoke-rc.d bacula-sd stop || exit $?
fi
# End automatically added section
