#!/bin/sh
set -e
# Automatically added by dh_installmenu/10.7.2
inst=/etc/menu-methods/jwm
if [ "$1" = "remove" ] && [ -f "$inst" ]; then chmod a-x $inst ; fi
if [ -x "`which update-menus 2>/dev/null`" ]; then update-menus ; fi
# End automatically added section
