#!/bin/sh

set -e

del_override() {
    if dpkg-statoverride --list $4 >/dev/null; then
	dpkg-statoverride --force --remove $4
    fi
}

if [ "$1" = "remove" ]; then
    dpkg-divert --package courier-mta --remove --rename \
		--divert /usr/bin/addcr.ucspi-tcp /usr/bin/addcr
    dpkg-divert --package courier-mta --remove --rename \
		--divert /usr/share/man/man1/addcr.ucspi-tcp.1.gz /usr/share/man/man1/addcr.1.gz
fi

if [ "$1" = "purge" ]; then
    # Removes possibly automatically produced files
    for f in aliases.dat defaultdomain dsnfrom esmtpacceptmailfor.dat hosteddomains.dat locals smtpaccess.dat; do
	for ext in "" "~"; do
	    rm -f /etc/courier/$f$ext
	done
    done

    # Remove configuration directories if empty
    for dir in aliasdir aliases esmtpacceptmailfor.dir hosteddomains smtpaccess; do
	[ -d /etc/courier/$dir ] && rmdir --ignore-fail-on-non-empty /etc/courier/$dir
    done

    # Remove message queues
    rm -rf /var/lib/courier/msgq
    rm -rf /var/lib/courier/msgs

    # Remove generated TLS certificate
    rm -f /etc/courier/esmtpd.pem

    # Remove generated random file
    rm -f /etc/courier/esmtpd.rand
    rm -f /usr/lib/courier/esmtpd.rand

    # Delete Courier SMTP overrides
    del_override root courier 4755 /usr/sbin/rmail
    del_override courier courier 2755 /usr/bin/mailq
    del_override courier courier 6755 /usr/bin/cancelmsg
    del_override root courier 2755 /usr/sbin/sendmail
    del_override courier courier 4755 /usr/lib/courier/courier/submitmkdir

    for dir in allfilters filters msgq msgs track; do
	del_override courier courier 0750 /var/lib/courier/$dir
    done
    del_override courier courier 0770 /var/lib/courier/tmp

    del_override root courier 0750 /etc/courier/aliasdir
    del_override root courier 0750 /etc/courier/aliases
    del_override root courier 0640 /etc/courier/aliases/system
    del_override root courier 0640 /etc/courier/esmtpauthclient
    del_override root courier 0750 /etc/courier/filters
    del_override root courier 0750 /etc/courier/filters/active

fi

# Automatically added by dh_installinit/11.5.1
if [ "$1" = "purge" ] ; then
	update-rc.d courier-msa remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installinit/11.5.1
if [ "$1" = "purge" ] ; then
	update-rc.d courier-mta-ssl remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installinit/11.5.1
if [ "$1" = "purge" ] ; then
	update-rc.d courier-mta remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installinit/11.5.1
if [ "$1" = "purge" ] ; then
	update-rc.d courierfilter remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installinit/11.5.1
if [ "$1" = "purge" ] ; then
	update-rc.d courier remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_systemd_enable/11.5.1
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'courier-mta.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'courier-mta.service' >/dev/null || true
		deb-systemd-helper unmask 'courier-mta.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installdebconf/11.5.1
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


exit 0
