#!/bin/sh

set -e

# Cleanup the old systemd unit state, if applicable
if dpkg --compare-versions "$2" lt-nl "8.9.5-1~"; then
	if deb-systemd-helper debian-installed drbd.service; then
		deb-systemd-helper purge drbd.service >/dev/null
		deb-systemd-helper unmask drbd.service >/dev/null
	fi
fi

# Automatically added by dh_installinit/11.3.5
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/drbd" ]; then
		update-rc.d drbd defaults-disabled >/dev/null || exit 1
	fi
fi
# End automatically added section

