#!/bin/sh
set -e
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ff/amazon-france.xml 45.0esr-2~ iceweasel-l10n-ff -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ff/bing.xml 45.0esr-2~ iceweasel-l10n-ff -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ff/cnrtl-tlfi-fr.xml 45.0esr-2~ iceweasel-l10n-ff -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ff/ddg.xml 45.0esr-2~ iceweasel-l10n-ff -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ff/eBay-france.xml 45.0esr-2~ iceweasel-l10n-ff -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ff/google.xml 45.0esr-2~ iceweasel-l10n-ff -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ff/wikipedia-fr.xml 45.0esr-2~ iceweasel-l10n-ff -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ff/yahoo-france.xml 45.0esr-2~ iceweasel-l10n-ff -- "$@"
# End automatically added section
