#!/bin/sh

set -e

PLUGINS="snmp_cpfw snmp_env snmp_int snmp_load snmp_mem snmp_process snmp_storage snmp_vrrp snmp_win"

if [ "$1" = "purge" ]; then
	if which ucf >/dev/null 2>&1; then
		have_ucf="yes"
	fi
	for f in $PLUGINS; do
		rm -f /etc/nagios-plugins/config/${f}.cfg
		if [ "$have_ucf" = "yes" ]; then
			ucf --purge /etc/nagios-plugins/config/${f}.cfg
		fi
	done
fi



exit 0
