#!/bin/sh -e

# #690128: if the old MOTD file has been amended by the admin from default,
# then rename it to the new non-conffile nnrpd MOTD file.
# If not then remove the old MOTD conffile, being sure to cater for rollback.
dpkg-maintscript-helper rm_conffile /etc/news/motd.news 2.5.3-1~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/news/radius.conf 2.6.1-3~ -- "$@"

if [ "$1" = "purge" ]; then
  update-rc.d inn2 remove >/dev/null
  if [ -e /var/lib/news/ ]; then
    rm -f /var/lib/news/.news.daily /var/lib/news/active* \
      /var/lib/news/newsgroups /var/lib/news/history*
    rmdir --ignore-fail-on-non-empty /var/lib/news/
  fi
fi



exit 0
