#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/fishpolld" ]; then
	update-rc.d fishpolld defaults >/dev/null
	invoke-rc.d fishpolld start || exit $?
fi
# End automatically added section
