#!/bin/sh
set -e

# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p libpetsc3.9-dev-examples /usr/share/doc/libpetsc3.9-dev-examples
fi

# End automatically added section
