#! /bin/sh

set -e

case "$1" in
    remove|upgrade|deconfigure)
		rm -f /var/spool/nullmailer/trigger
        ;;
    failed-upgrade)
        ;;
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# Automatically added by dh_systemd_start/11
if [ -d /run/systemd/system ]; then
	deb-systemd-invoke stop 'nullmailer.service' >/dev/null
fi
# End automatically added section


exit 0
