#!/bin/sh
set -e
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/default/avahi-dnsconfd 0.6.26-1~ avahi-dnsconfd -- "$@"
# End automatically added section
# Automatically added by dh_systemd_start
if [ -d /run/systemd/system ]; then
	deb-systemd-invoke stop avahi-daemon.socket >/dev/null
fi
# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/avahi-dnsconfd" ] && [ "$1" = remove ]; then
	invoke-rc.d avahi-dnsconfd stop || exit $?
fi
# End automatically added section
