#!/bin/sh

set -e

case "${1}" in
	configure)
		addgroup --system pkcs11
		adduser root pkcs11

		chown root:pkcs11 /var/lib/opencryptoki
		chmod 0775 /var/lib/opencryptoki
		;;

	abort-upgrade|abort-remove|abort-deconfigure)

		;;

	*)
		echo "postinst called with unknown argument \`${1}'" >&2
		exit 1
		;;
esac

# Automatically added by dh_systemd_enable/10.10.5
# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask 'pkcsslotd.service' >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled 'pkcsslotd.service'; then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable 'pkcsslotd.service' >/dev/null || true
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'pkcsslotd.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/10.10.5
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	# In case this system is running systemd, we need to ensure that all
	# necessary tmpfiles (if any) are created before starting.
	if [ -d /run/systemd/system ] ; then
		systemd-tmpfiles --create /usr/lib/tmpfiles.d/opencryptoki.conf >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installinit/10.10.5
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/pkcsslotd" ]; then
		update-rc.d pkcsslotd defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d pkcsslotd $_dh_action || exit $?
	fi
fi
# End automatically added section
# Automatically added by dh_installdeb/10.10.5
dpkg-maintscript-helper mv_conffile /etc/init.d/opencryptoki /etc/init.d/pkcsslotd -- "$@"
# End automatically added section


exit 0
