#!/bin/sh
set -e
# Automatically added by dh_installdeb/10.10.5
dpkg-maintscript-helper mv_conffile /etc/init.d/opencryptoki /etc/init.d/pkcsslotd -- "$@"
# End automatically added section
# Automatically added by dh_installinit/10.10.5
if [ -x "/etc/init.d/pkcsslotd" ] && [ "$1" = remove ]; then
	invoke-rc.d pkcsslotd stop || exit $?
fi
# End automatically added section
