#!/bin/sh
# postrm script for twms
set -e

if [ "$1" = "purge" ]; then
	rm -rf /var/log/twms /var/run/twms.pid /var/cache/twms
fi

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d twms remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask twms.service >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge twms.service >/dev/null
		deb-systemd-helper unmask twms.service >/dev/null
	fi
fi
# End automatically added section


exit 0
