#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/twms" ]; then
	invoke-rc.d twms stop || exit $?
fi
# End automatically added section

# Automatically added by dhpython:
if which pyclean >/dev/null 2>&1; then
	pyclean -p twms 
else
	dpkg -L twms | grep \.py$ | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section
