#!/bin/sh

set -e

case "$1" in
    configure|reconfigure)
        adduser \
            --system \
            --quiet \
            --home /nonexistent \
            --no-create-home \
            --group \
            nutcracker
        chown nutcracker:adm /var/log/nutcracker
        chmod 02755 /var/log/nutcracker
    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
        exit 0
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# Automatically added by dh_systemd_enable
# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask nutcracker.service >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled nutcracker.service; then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable nutcracker.service >/dev/null || true
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state nutcracker.service >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/nutcracker" ]; then
		update-rc.d nutcracker defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d nutcracker $_dh_action || exit $?
	fi
fi
# End automatically added section


exit 0

