#!/bin/sh

set -e

if [ "$1" = "purge" ]; then
    # logs, db and backup have to be removed according to policy.
    rm -rf /var/log/sks /var/lib/sks /var/backup/sks /var/backups/sks
    [ -d /var/backup ] && rmdir --ignore-fail-on-non-empty /var/backup

    # see https://wiki.debian.org/AccountHandlingInMaintainerScripts
    if [ -x "$(command -v deluser)" ]; then
        deluser --quiet --system debian-sks > /dev/null || true
    else
        echo >&2 "not removing debian-sks system account because deluser command was not found"
    fi
fi

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d sks remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section


exit 0
