#!/bin/sh

set -e

if [ "$1" = "remove" ] ; then
	update-alternatives --remove oslo_debug_helper /usr/bin/python2-oslo_debug_helper
	update-alternatives --remove oslo_run_pre_release_tests /usr/bin/python2-oslo_run_pre_release_tests
	update-alternatives --remove oslo_run_cross_tests /usr/bin/python2-oslo_run_cross_tests
fi


# Automatically added by dh_python2:
if which pyclean >/dev/null 2>&1; then
	pyclean -p python-oslotest 
else
	dpkg -L python-oslotest | grep '\.py$' | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section


exit 0

