#!/bin/sh
set -e
# Automatically added by dh_systemd_enable/11.2.1
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'ospfd.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'ospfd.service' >/dev/null || true
		deb-systemd-helper unmask 'ospfd.service' >/dev/null || true
	fi
fi
# End automatically added section
