#!/bin/sh

set -e

# Automatically added by dh_installinit/11.5.3
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/a-rex" ]; then
		update-rc.d a-rex defaults-disabled >/dev/null
		invoke-rc.d a-rex start || exit 1
	fi
fi
# End automatically added section


dpkg-maintscript-helper rm_conffile /etc/default/a-rex 5.4.2-2 -- "$@"
