#!/bin/sh

set -e

# Automatically added by dh_installinit/11.5.3
if [ "$1" = "purge" ] ; then
	update-rc.d a-rex remove >/dev/null
fi
# End automatically added section


dpkg-maintscript-helper rm_conffile /etc/default/a-rex 5.4.2-2 -- "$@"
