#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/tpm2-resourcemgr" ]; then
		update-rc.d tpm2-resourcemgr defaults >/dev/null
		invoke-rc.d tpm2-resourcemgr start || exit $?
	fi
fi
# End automatically added section
# Automatically added by dh_systemd_start
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
	deb-systemd-invoke start tpm2-resourcemgr.service >/dev/null || true
fi
# End automatically added section
