#!/bin/sh
set -e

# Automatically added by dh_installinit
if [ -x "/etc/init.d/cipux-rpcd" ]; then
	update-rc.d cipux-rpcd start 20 2 3 4 5 . stop 20 1 . >/dev/null
	invoke-rc.d cipux-rpcd start || exit $?
fi
# End automatically added section


# Check for an account named 'cipux-rpcdr'
if ! id cipux-rpcdr >/dev/null 2>&1; then
	# Create the new system account
	adduser --system --disabled-password --disabled-login \
	  --home /var/lib/cipux-rpcdr --group --quiet \
	  --gecos "CipUX RPC remote daemon" cipux-rpcdr || true
fi

# grant access to shared snakeoil cert
if ! getent group ssl-cert >/dev/null; then
	addgroup --quiet --system --force-badname ssl-cert
fi
adduser --quiet cipux-rpcdr ssl-cert

# Activate/refresh stunnel
if [ -x "/etc/init.d/stunnel4" ]; then
	if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
		invoke-rc.d stunnel4 force-reload || exit $?
	else
		/etc/init.d/stunnel4 force-reload || exit $?
	fi
fi
