#!/bin/sh
set -e

# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p gnuradio 
fi

if which pycompile >/dev/null 2>&1; then
	pycompile -p gnuradio /usr/share/gnuradio
fi

# End automatically added section
