#!/bin/sh

set -e

. /usr/share/debconf/confmodule

dpkg-maintscript-helper rm_conffile \
               /etc/init.d/wifi-radar -- "$@"

# Automatically added by dh_installmenu/10.6.4
if [ "$1" = "configure" ] && [ -x "`which update-menus 2>/dev/null`" ]; then
	update-menus
fi
# End automatically added section


