#!/bin/sh

set -e

case "$1" in
    purge|remove)
        if [ -n "$(grep "/var/lib/rkt" /proc/mounts)" ]; then
            printf "rkt/prerm error: detected active mounts in [/var/lib/rkt].\n"
            exit 1
        fi
        if [ -n "$(rkt list --no-legend | awk '{print $4}' | grep running)" ]; then
            printf "rkt/prerm error: detected running containers.\n"
            exit 1
        fi
    ;;
esac

# Automatically added by dh_installsystemd/11.4
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'rkt-gc.service' 'rkt-gc.timer' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.4
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'cni-dhcp.service' 'cni-dhcp.socket' >/dev/null || true
fi
# End automatically added section

