#!/bin/sh
set -e
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/udev/no-legacy-ptys.rules 0.5.1~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/init.d/selinux-basics 0.5.3~ -- "$@"
# End automatically added section
