#!/bin/sh
# postrm script for ntfs-config

set -e

case "$1" in
    purge|remove)  
    # Remove any fdi rule that could have been created by the program
    echo "Removing configuration files created by the program..."
    rm -f /etc/hal/fdi/policy/20-ntfs-config-write-policy.fdi
    rm -f /etc/hal/fdi/policy/20-ntfs-config-ro-policy.fdi 
    ;;

    failed-upgrade|upgrade)
    ;;


    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac



exit 0


