#!/bin/sh
set -e
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ta/creativecommons.xml 45.0esr-2~ iceweasel-l10n-ta -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ta/ddg.xml 45.0esr-2~ iceweasel-l10n-ta -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ta/eBay-in.xml 45.0esr-2~ iceweasel-l10n-ta -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ta/google.xml 45.0esr-2~ iceweasel-l10n-ta -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ta/wikipedia-ta.xml 45.0esr-2~ iceweasel-l10n-ta -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/ta/yahoo-in.xml 45.0esr-2~ iceweasel-l10n-ta -- "$@"
# End automatically added section
