#!/bin/sh
set -e

# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p patroni -V 3.5-
fi

# End automatically added section
# Automatically added by dh_installinit/10.9.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/patroni" ]; then
		update-rc.d patroni defaults >/dev/null
		invoke-rc.d patroni start || exit $?
	fi
fi
# End automatically added section
