#!/bin/sh
set -e

# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/default/unbound 1.5.7-2~ -- "$@"
# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/unbound" ] && [ "$1" = remove ]; then
	invoke-rc.d unbound stop || true
fi
# End automatically added section
# Automatically added by dh_systemd_start
if [ -d /run/systemd/system ]; then
	deb-systemd-invoke stop unbound.service >/dev/null
fi
# End automatically added section


exit 0
