#!/bin/sh
# -*- coding: utf-8 -*-
# Copyright © 2002,2003 Colin Walters <walters@debian.org>

set -e

if test -x /usr/bin/update-menus; then update-menus; fi

# Automatically added by dh_installmenu
if [ "$1" = "configure" ] && [ -x "`which update-menus 2>/dev/null`" ]; then
	update-menus
fi
# End automatically added section

