#!/bin/sh
set -e
# Automatically added by dh_installinit/10.10.2
if [ -x "/etc/init.d/kopano-search" ] && [ "$1" = remove ]; then
	invoke-rc.d kopano-search stop || exit $?
fi
# End automatically added section
