#!/bin/sh
set -e
# Automatically added by dh_systemd_start/11.3.2
if [ -d /run/systemd/system ]; then
	deb-systemd-invoke stop 'lava-slave.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_start/11.3.2
if [ -d /run/systemd/system ]; then
	deb-systemd-invoke stop 'lava-slave.service' >/dev/null || true
fi
# End automatically added section

# Automatically added by dh_python3:
if which py3clean >/dev/null 2>&1; then
	py3clean -p lava-dispatcher 
else
	dpkg -L lava-dispatcher | perl -ne 's,/([^/]*)\.py$,/__pycache__/\1.*, or next; unlink $_ or die $! foreach glob($_)'
	find /usr/lib/python3/dist-packages/ -type d -name __pycache__ -empty -print0 | xargs --null --no-run-if-empty rmdir
fi

# End automatically added section
