#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/th/yahoo.xml 45.0esr-2~ iceweasel-l10n-th -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/th/wikipedia-th.xml 45.0esr-2~ iceweasel-l10n-th -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/th/longdo.xml 45.0esr-2~ iceweasel-l10n-th -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/th/google.xml 45.0esr-2~ iceweasel-l10n-th -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/th/eBay.xml 45.0esr-2~ iceweasel-l10n-th -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/th/ddg.xml 45.0esr-2~ iceweasel-l10n-th -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/th/creativecommons.xml 45.0esr-2~ iceweasel-l10n-th -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/th/bing.xml 45.0esr-2~ iceweasel-l10n-th -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.3.4
dpkg-maintscript-helper rm_conffile /etc/iceweasel/searchplugins/locale/th/amazondotcom.xml 45.0esr-2~ iceweasel-l10n-th -- "$@"
# End automatically added section
