#!/bin/sh
set -e

# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p gpodder 
fi

if which py3compile >/dev/null 2>&1; then
	py3compile -p gpodder /usr/share/gpodder
fi

# End automatically added section
