#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.4.1
dpkg-maintscript-helper rm_conffile /etc/init.d/epoptes-client 1.0.1-2\~ epoptes-client -- "$@"
dpkg-maintscript-helper rm_conffile /etc/init/epoptes-client.conf 1.0.1-2\~ epoptes-client -- "$@"
dpkg-maintscript-helper rm_conffile /etc/network/if-up.d/epoptes-client 1.0.1-2\~ epoptes-client -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/11.4.1
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.4.1
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'epoptes-client.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'epoptes-client.service' >/dev/null || true
		deb-systemd-helper unmask 'epoptes-client.service' >/dev/null || true
	fi
fi
# End automatically added section
