#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/fso-gpsd" ]; then
		update-rc.d fso-gpsd defaults >/dev/null
		invoke-rc.d fso-gpsd start || exit $?
	fi
fi
# End automatically added section
