#!/bin/sh

set -e

if [ "$1" = "remove" ]; then
    wp-setup --purge-wp-content
fi

# Automatically added by dh_installdeb/11.3.5
dpkg-maintscript-helper rm_conffile /etc/wordpress/wp-config.php 3.4+dfsg -- "$@"
# End automatically added section

