#!/bin/sh
set -e
# Automatically added by dh_sysuser/UNDECLARED
# -*- sh -*-
export CONF_HOME=/nonexistent
export CONF_PACKAGE=mini-httpd-run
export CONF_USERNAME=_log-mini-httpd

/lib/sysuser-helper/sysuser-helper prerm "$@"
# End automatically added section
