#!/bin/sh
set -e

PACKAGE=sendmail-doc;

if [ -L /usr/share/doc/$PACKAGE ]; then
	# /usr/share/doc/$PACKAGE was a symlink to /usr/share/doc/sendmail
	rm /usr/share/doc/$PACKAGE
fi
if [ -L /usr/share/bug/$PACKAGE ]; then
	rm /usr/share/bug/$PACKAGE
fi

if [ "$1" = "upgrade" ] && dpkg --compare-versions "$2" lt "8.14.4-2.2~"; then
	# /usr/share/doc/$PACKAGE was a symlink to /usr/share/doc/sendmail
	rm -rf /usr/share/doc/sendmail/libmilter/
	rm -rf /usr/share/doc/sendmail/op/
	rm -rf /usr/share/doc/sendmail/sendmail/
	rm -f /usr/share/doc/sendmail/Debian-specific.gz
	rm -f /usr/share/doc/sendmail/KNOWNBUGS.gz
	rm -f /usr/share/doc/sendmail/README.Debian.sendmail-doc
	rm -f /usr/share/doc/sendmail/cf.README.gz
	rm -f /usr/share/doc/sendmail/faq.txt.gz
	rm -f /usr/share/doc/sendmail/site.config.m4.gz
	rm -f /usr/share/doc/sendmail/smrsh.README.gz
fi


