#!/bin/sh

set -e

if [ "$1" = "purge" ] && [ -e "/etc/default/o2cb" ]; then
        rm -f /etc/default/o2cb
fi

# Automatically added by dh_installinit/11.5.3
if [ "$1" = "purge" ] ; then
	update-rc.d ocfs2 remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installinit/11.5.3
if [ "$1" = "purge" ] ; then
	update-rc.d o2cb remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.5.3
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'ocfs2.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'ocfs2.service' >/dev/null || true
		deb-systemd-helper unmask 'ocfs2.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.5.3
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'o2cb.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'o2cb.service' >/dev/null || true
		deb-systemd-helper unmask 'o2cb.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installdebconf/11.5.3
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

