#!/bin/sh
set -e
# Automatically added by dh_installdeb/10.6.4
dpkg-maintscript-helper rm_conffile /etc/emacs/site-start.d/50silversearcher-ag-el.el 0.47-2\~ silversearcher-ag-el -- "$@"
# End automatically added section
