#!/bin/sh

set -e

. /usr/share/debconf/confmodule

# Use lt-nl test here, because an empty $2 means a new install.
# lt-nl means empty is always greater than any other version,
# so the first part of this test will not return true on a new install.
if dpkg --compare-versions "$2" lt-nl 0.0.7E6 ; then

  db_input medium slashem-common/backup-incompatible || true
  db_go

  db_get slashem-common/backup-incompatible

  db_set slashem-common/do-backup "$RET"
  if [ "$RET" = abort ]; then
    db_stop
    exit 1
  fi
else
  db_set slashem-common/do-backup "ignore"
fi

db_stop

exit 0
