#!/bin/sh
set -e
. /usr/share/debconf/confmodule

if [ "$1" != "upgrade" ]; then

    update-alternatives --remove libblas.so.3-x86_64-linux-gnu \
                        /usr/lib/x86_64-linux-gnu/libblis.so.1

fi


exit 0
