#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/gnukhata-core-engine" ]; then
	invoke-rc.d gnukhata-core-engine stop || exit $?
fi
# End automatically added section

# Automatically added by dhpython:
if which pyclean >/dev/null 2>&1; then
	pyclean -p gnukhata-core-engine 
else
	dpkg -L gnukhata-core-engine | grep \.py$ | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section
