#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/portreserve" ]; then
		update-rc.d portreserve start 17 2 3 4 5 . start 41 S . stop 99 2 3 4 5 . stop 12 0 1 6 . >/dev/null || exit $?
	fi
fi
# End automatically added section
