#!/bin/sh

set -e

if [ "$1" = "purge" ]; then
    rm -r /var/games/armagetronad
    rmdir --ignore-fail-on-non-empty /var/games
fi

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d armagetronad-dedicated remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask armagetronad-dedicated.service >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge armagetronad-dedicated.service >/dev/null
		deb-systemd-helper unmask armagetronad-dedicated.service >/dev/null
	fi
fi
# End automatically added section

