#!/bin/sh -e

if dpkg-maintscript-helper supports rm_conffile 2>/dev/null; then
  dpkg-maintscript-helper rm_conffile /etc/defoma/hints/cm-super-x11.hints 0.3.4-3 -- "$@"
fi

# Automatically added by dh_installxfonts/11.3.5
if [ -x "`which update-fonts-dir 2>/dev/null`" ]; then
	update-fonts-scale Type1;update-fonts-dir --x11r7-layout Type1
fi
# End automatically added section


exit 0
