#!/bin/sh
# postrm script for kopano-server
#
# see: dh_installdeb(1)

set -e

if [ -f /usr/share/debconf/confmodule ]; then
    . /usr/share/debconf/confmodule
fi
if [ -f /usr/share/dbconfig-common/dpkg/postrm.mysql ]; then
    . /usr/share/dbconfig-common/dpkg/postrm.mysql
    dbc_go kopano-server $@
fi

case "$1" in
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    purge)
        if which ucf >/dev/null 2>&1; then
            ucf --purge /etc/kopano/debian-db.cfg
        else
            rm -f /etc/kopano/debian-db.cfg
        fi
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# Automatically added by dh_installinit/11.3.5
if [ "$1" = "purge" ] ; then
	update-rc.d kopano-server remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installdebconf/11.3.5
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section
# Automatically added by dh_apparmor/2.13-4
if [ "$1" = "purge" ] && ! [ -e "/etc/apparmor.d/usr.sbin.kopano-server" ] ; then
    rm -f "/etc/apparmor.d/disable/usr.sbin.kopano-server" || true
    rm -f "/etc/apparmor.d/force-complain/usr.sbin.kopano-server" || true
    rm -f "/etc/apparmor.d/local/usr.sbin.kopano-server" || true
    rmdir /etc/apparmor.d/disable 2>/dev/null || true
    rmdir /etc/apparmor.d/local   2>/dev/null || true
    rmdir /etc/apparmor.d         2>/dev/null || true
fi
# End automatically added section


exit 0


