#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/ramond" ]; then
	update-rc.d ramond defaults >/dev/null
	invoke-rc.d ramond start || exit $?
fi
# End automatically added section
