#! /bin/sh -e

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d hylafax remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installdebconf
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


USERDEL=/usr/sbin/userdel

if [ "$1" = purge ]; then
    if getent passwd faxmaster >/dev/null 2>&1
    then
	[ -x $USERDEL ] && $USERDEL faxmaster
    fi

    for i in /etc/hylafax/setup.cache /etc/hylafax/setup.modem \
	/var/spool/hylafax/status/any.info /var/spool/hylafax/dev/null \
	/var/spool/hylafax/FIFO /var/spool/hylafax/bin/ps2fax \
	/var/spool/hylafax/bin/pdf2fax /var/spool/hylafax/bin/bin \
	/etc/default/hylafax
    do
	[ -e "$i" -o -L "$i" ] && rm "$i"
    done
fi

exit 0
