#! /bin/sh
#
#	Post removal script for the Debian GNU/Linux nis package
#

set -e

# Source debconf library.
if [ -f /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	if [ "$1" = "purge" ]; then
		db_purge
	fi
fi

case "$1" in
	purge)
		update-rc.d nis remove >/dev/null
		rm -f /etc/default/nis
		rm -f /etc/defaultdomain
		rm -r /var/yp
		exit 0
		;;
	remove)
		;;
	upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
		;;
esac

exit 0
