#!/bin/sh

set -e

case "$1" in
    purge)
        # Can be removed after Wheezy:
        ucf --purge /etc/zabbix/dbconfig.php || true

        # Remove config files created by the Zabbix setup wizard
        rm -f /etc/zabbix/zabbix.conf.php
    ;;
esac

# Automatically added by dh_apache2
if [ "$1" = "purge" ] ; then
	if true; then
		if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
			. /usr/share/apache2/apache2-maintscript-helper

			for conf in zabbix-frontend-php  ; do
				apache2_invoke disconf $conf  || exit $?
			done
		fi
	fi
fi
# End automatically added section

