#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/gangliarc" ]; then
		update-rc.d gangliarc defaults >/dev/null
		invoke-rc.d gangliarc start || exit $?
	fi
fi
# End automatically added section

# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p nordugrid-arc-gangliarc 
fi

# End automatically added section
