#!/bin/sh

set -e

case "$1" in
    configure)
        [ -x /usr/sbin/dictdconfig ] && dictdconfig -w
        if [ -x /etc/init.d/dictd ]; then
            if [ -x /usr/sbin/invoke-rc.d ]; then
                invoke-rc.d dictd force-reload
            fi
        fi
        ;;
    abort-upgrade|abort-remove|abort-deconfigure)
        ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac



exit 0
