#!/bin/sh
set -e
# Automatically added by dh_elpa
if [ -e /var/lib/emacsen-common/state/package/installed/emacsen-common -a -x /usr/lib/emacsen-common/emacs-package-remove ] ; then
	/usr/lib/emacsen-common/emacs-package-remove --prerm elpa-elisp-slime-nav
fi
# End automatically added section
