#! /bin/sh
set -e
PACKAGE=rail

if [ ! -e /var/lib/emacsen-common/state/package/installed/emacsen-common ]
then
    # Fallback to emacsen-common 1.x
    if [ "$1" = "configure" ] && [ -x /usr/lib/emacsen-common/emacs-package-install ]
    then
        /usr/lib/emacsen-common/emacs-package-install $PACKAGE
    fi
else
    mkdir -p -m 0755 /var/lib/emacsen-common/state/package/installed
    touch /var/lib/emacsen-common/state/package/installed/$PACKAGE
# Automatically added by dh_installemacsen
if [ "$1" = "configure" ] && [ -e /var/lib/emacsen-common/state/package/installed/emacsen-common ]
then
	/usr/lib/emacsen-common/emacs-package-install --postinst rail
fi
# End automatically added section

fi
