#! /bin/sh
set -e

#
# Drop diversions of locale files when upgrading from versions prior to 0.5.0-1
#
if [ "$1" = "install" -o "$1" = "upgrade" ]; then
    if dpkg --compare-versions "$2" lt "0.5.0-1"; then
        for lang in de_DE fi_FI fr_FR it_IT ru_RU sk_SK; do
            dpkg-divert --package vdr-plugin-streamdev-client --rename --remove /usr/share/locale/$lang/LC_MESSAGES/vdr-streamdev.mo
        done
    fi
fi

# Automatically added by dh_vdrplugin_enable/UNDECLARED
#
# To enable a vdr plugin, its config must be symlinked to /etc/vdr/conf.d.
# This must only be done when installing a plugin package or upgrading
# from an old package, which does not support the conf.d mechanism.
#
# Before installing, we remember if the plugin-config in conf.avail
# does not exist (because this is a new installation or an upgrade
# from an old installation or the config was removed by the admin)
# by creating a /etc/vdr/conf.d/*.dpkg-vdr-plugin-enable "tag"-file.
#
dh_vdrplugin_prepare_enable() {
  local pkgname="$1"
  shift
  while [ $# -gt 0 ] ; do
    local config=$1
    local priority=$2
    shift 2
    local old_md5sum="$(dpkg-query -W -f='${Conffiles}' $pkgname | sed -n -e "\' $config ' { s/ obsolete$//; s/.* //; p }")"
    if [ -z "$old_md5sum" ] ; then
      mkdir -p "/etc/vdr/conf.d"
      touch "/etc/vdr/conf.d/$priority-$config.dpkg-vdrplugin-enable"
    fi
  done
}

dh_vdrplugin_prepare_enable vdr-plugin-streamdev-client streamdev-client.conf 50
# End automatically added section

