#!/bin/sh
set -e
# Automatically added by dh_systemd_start/10.8
if [ -d /run/systemd/system ]; then
	deb-systemd-invoke stop syncthing-discosrv.service >/dev/null
fi
# End automatically added section
# Automatically added by dh_installinit/10.8
if [ -x "/etc/init.d/syncthing-discosrv" ]; then
	invoke-rc.d syncthing-discosrv stop || exit $?
fi
# End automatically added section
