#!/bin/sh

set -e

case "$1" in
	configure)
		adduser --system --ingroup audio --home /var/lib/muroard --quiet muroard || true
	;;
	abort-upgrade|abort-remove|abort-deconfigure)
	;;
	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
	;;
esac

# Automatically added by dh_installinit/10.10.5
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/muroard" ]; then
		update-rc.d muroard defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d muroard $_dh_action || exit $?
	fi
fi
# End automatically added section


exit 0
