#!/bin/sh

set -e

case "$1" in
	purge)
		if getent passwd|grep -q ^muroard: ; then
			userdel muroard 2>&1 > /dev/null || true
		fi
		rm -rf /var/lib/muroard
	;;
	remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	;;
	*)
		echo "postrm called with unknown argument \`$1'" >&2
		exit 1
esac

# Automatically added by dh_installinit/10.10.5
if [ "$1" = "purge" ] ; then
	update-rc.d muroard remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section


exit 0
