#!/bin/sh
set -e
# Automatically added by dh_installwm/12
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ]; then
	update-alternatives --install /usr/bin/x-window-manager \
		x-window-manager /usr/bin/metacity 60 \
		--slave /usr/share/man/man1/x-window-manager.1.gz \
		x-window-manager.1.gz /usr/share/man/man1/metacity.1.gz
fi
# End automatically added section
