#!/bin/sh

set -e

del_override() {
    if dpkg-statoverride --list $4 >/dev/null; then
	dpkg-statoverride --force --remove $4
    fi
}

if [ "$1" = "purge" ]; then
    del_override root courier 0640 /etc/courier/authdaemonrc
fi

# Automatically added by dh_installinit/11.4.1
if [ "$1" = "purge" ] ; then
	update-rc.d courier-authdaemon remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.4.1
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'courier-authdaemon.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'courier-authdaemon.service' >/dev/null || true
		deb-systemd-helper unmask 'courier-authdaemon.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
