#!/bin/sh
set -e
# Automatically added by dh_installinit/11.4.1
if [ -x "/etc/init.d/courier-authdaemon" ] && [ "$1" = remove ]; then
	invoke-rc.d courier-authdaemon stop || exit 1
fi
# End automatically added section
