#! /bin/sh -e

if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ]; then
    update-alternatives --quiet --remove javac /usr/bin/gcj-wrapper-6
    update-alternatives --quiet --remove jar /usr/bin/gjar-6
    update-alternatives --quiet --remove jarsigner /usr/bin/gjarsigner-6
    update-alternatives --quiet --remove javah /usr/bin/gjavah-6
    update-alternatives --quiet --remove javadoc /usr/bin/gjdoc-6
    update-alternatives --quiet --remove native2ascii /usr/bin/gnative2ascii-6
    update-alternatives --quiet --remove rmic /usr/bin/grmic-6
    update-alternatives --quiet --remove serialver /usr/bin/gserialver-6
    update-alternatives --quiet --remove tnameserv /usr/bin/gtnameserv-6
fi


