#!/bin/sh
set -e
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper dir_to_symlink /usr/share/doc/bacula-console bacula-common 7.0.5\+dfsg-4\~ -- "$@"
# End automatically added section
