#!/bin/sh
set -e
# Automatically added by dh_installemacsen
if [ "$1" = "configure" ] && [ -x /usr/lib/emacsen-common/emacs-package-install ]
then
	/usr/lib/emacsen-common/emacs-package-install idl-font-lock-el
fi
# End automatically added section
