#!/bin/sh
set -e
# Automatically added by dh_installinit/10.9
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/qemu-guest-agent" ]; then
		update-rc.d qemu-guest-agent defaults >/dev/null
		invoke-rc.d qemu-guest-agent start || exit $?
	fi
fi
# End automatically added section
