#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.2.1
dpkg-maintscript-helper rm_conffile /etc/fonts/conf.avail/64-22-tlwg-typist.conf 1:0.6.4-2\~ fonts-tlwg-typist -- "$@"
# End automatically added section
