#!/bin/sh
set -e

# Automatically added by dhpython:
if which pycompile >/dev/null 2>&1; then
	pycompile -p pysolfc /usr/share/games/pysolfc
fi

# End automatically added section
# Automatically added by dh_installmenu
if [ "$1" = "configure" ] && [ -x "`which update-menus 2>/dev/null`" ]; then
	update-menus
fi
# End automatically added section
# Automatically added by dh_icons
if which update-icon-caches >/dev/null 2>&1 ; then
	update-icon-caches /usr/share/icons/pysol01.png /usr/share/icons/pysol02.png
fi
# End automatically added section
