#!/bin/sh
set -e

# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p python3-dbus-tests /usr/lib/x86_64-linux-gnu/installed-tests/dbus-python/python3.5 -V 3.5
fi

# End automatically added section
