#!/bin/sh
# postrm script for barman

set -e

case "$1" in
    purge)
	rm -fr /var/log/barman /var/lib/barman
        userdel barman || true;
    ;;

    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac



exit 0
