#!/bin/sh
set -e
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/gitlab/initializers/devise_async.rb 8.8.2+dfsg-5 gitlab -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/gitlab/gitlab.teatro.yml 8.11.3+dfsg1-1 gitlab -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/gitlab/initializers/haml.rb 8.11.3+dfsg1-1 gitlab -- "$@"
# End automatically added section
