#!/bin/sh
set -e

inst="/etc/menu-methods/wmaker /etc/menu-methods/wmappearance"

case "$1" in
  remove)
    for file in $inst ; do
      if [ -f $file ] ; then
        chmod a-x $file
      fi
    done
  ;;
  purge)
    if which update-menus >/dev/null 2>&1 ; then
      update-menus
      rm -f /etc/GNUstep/Defaults/menu.hook /etc/GNUstep/Defaults/appearance.menu
    fi
  ;;
  upgrade|abort-install|disappear)
    # nothing to do
  ;;
  failed-upgrade)
    # this is an upgrade, and it has failed. What can fail?
    exit 1
  ;;
  abort-upgrade)
    # preinst failed, leave things like they were
  ;;
  *)
    echo "postrm called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac

# Automatically added by dh_installdeb
dpkg-maintscript-helper mv_conffile /etc/X11/WindowMaker/wmmacros /usr/share/WindowMaker/wmmacros 0.95.7-5~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper mv_conffile /etc/X11/WindowMaker/background.menu /usr/share/WindowMaker/background.menu 0.95.7-5~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/X11/WindowMaker/menu.prehook 0.95.7-5~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/X11/WindowMaker/menu.posthook 0.95.7-5~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/X11/WindowMaker/appearance.menu 0.95.7-5~ -- "$@"
# End automatically added section


exit 0
