#!/bin/sh
set -e
# Automatically added by dh_installsystemd/11.3.4
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'ipsec.service' >/dev/null || true
fi
# End automatically added section
