#!/bin/sh
set -e

# Automatically added by dh_systemd_enable/11.1.6
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# This will only remove masks created by d-s-h on package removal.
	deb-systemd-helper unmask 'tlp-sleep.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'tlp-sleep.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'tlp-sleep.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'tlp-sleep.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_systemd_enable/11.1.6
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# This will only remove masks created by d-s-h on package removal.
	deb-systemd-helper unmask 'tlp.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'tlp.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'tlp.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'tlp.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installdeb/11.1.6
dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/tlp -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.1.6
dpkg-maintscript-helper rm_conffile /etc/acpi/events/thinkpad-radiosw -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.1.6
dpkg-maintscript-helper rm_conffile /etc/acpi/thinkpad-radiosw.sh -- "$@"
# End automatically added section
# Automatically added by dh_installinit/11.1.6
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/tlp" ]; then
		update-rc.d tlp defaults 98 01 >/dev/null || exit 1
	fi
fi
# End automatically added section


PMD="/usr/lib/pm-utils/power.d"
ETD="/etc/pm/power.d"
NOP="/usr/share/tlp/tlp-nop"
SYD="/lib/systemd/system"
ESY="/etc/systemd/system"
NUL="/dev/null"
SRV="systemd-rfkill"

case "$1" in
    configure)
        # Mask conflicting pm-utils hooks:
        # creating a file in /etc/pm/power.d/ with the same name as the
        # hook script in /usr/lib/pm-utils/power.d/ is the documented
        # way to disable pm-utils' builtin hooks
        #
        if [ -d ${PMD} ] && [ -d ${ETD} ]; then
            for i in 95hdparm-apm disable_wol hal-cd-polling intel-audio-powersave harddrive \
                 laptop-mode journal-commit pci_devices pcie_aspm readahead sata_alpm \
                     sched-powersave usb_bluetooth wireless xfs_buffer; do
                if [ -x ${PMD}/${i} ]; then
                    # Executable hook in /usr/lib/pm-utils/power.d/ exists
                    if [ -f ${ETD}/${i} ]; then
                        # Exclude symlinks to tlp-nop
                        if ! readlink ${ETD}/${i} | egrep -q 'tlp-nop$' ; then
                            # Move aside superseding hook of same name in /etc/pm/power.d/
                            mv -n ${ETD}/${i} ${ETD}/${i}.tlp-save
                        fi
                    fi
                    # Make a soft link to tlp-nop in /etc/pm/power.d/
                    # to disable corresponding hook /usr/lib/pm-utils/power.d/
                    ln -sf ${NOP} ${ETD}/${i}
                fi
            done
        fi

        # Mask conflicting upstart jobs (Package rfkill in Ubuntu)
        for i in /etc/init/rfkill-*.conf; do
            if [ -f "$i" ] && [ ! -f "${i%.conf}.override" ]; then
                # Do this only when no .override exists
                echo "manual" > ${i%.conf}.override
            fi
        done

        # Mask conflicting systemd services
        for i in $(ls ${SYD} 2> ${NUL} | egrep "${SRV}"); do
            deb-systemd-helper mask $i 2> ${NUL} || true
        done
        ;;

esac
