#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.1.6
dpkg-maintscript-helper rm_conffile /etc/acpi/thinkpad-radiosw.sh -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.1.6
dpkg-maintscript-helper rm_conffile /etc/acpi/events/thinkpad-radiosw -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.1.6
dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/tlp -- "$@"
# End automatically added section
