#!/bin/sh

set -e

# Try to remove the /usr/share/GvRng/docs/lessons directory, if it exists
case "$1" in
  upgrade|install)
    if [ -h "/usr/share/GvRng/docs/lessons/html" ]; then
      rm "/usr/share/GvRng/docs/lessons/html"
    fi
    if [ -d "/usr/share/GvRng/docs/lessons" ]; then
      rmdir "/usr/share/GvRng/docs/lessons" 2> /dev/null || true
    fi
  ;;
esac



exit 0
