#!/bin/sh
set -e
# Automatically added by dh_installemacsen
if ( [ "$1" = "install" ] || [ "$1" = "upgrade" ] ) \
	&& [ -e /var/lib/emacsen-common/state/package/installed/emacsen-common -a -x /usr/lib/emacsen-common/emacs-package-install ]
then
	/usr/lib/emacsen-common/emacs-package-install --preinst t-code
fi
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper dir_to_symlink /usr/share/doc/t-code t-code-common 2:2.3.1-3.4 -- "$@"
# End automatically added section
