#!/bin/sh
set -e
# Automatically added by dh_installinit/10.10.9
if [ -x "/etc/init.d/nova-conductor" ] && [ "$1" = remove ]; then
	invoke-rc.d nova-conductor stop || true
fi
# End automatically added section
