#!/bin/sh

set -e

# Lock user account
if [ "$1" = "purge" ]; then
	usermod -L -e 1 bucardo
fi

# Automatically added by dh_installinit/11.5.3
if [ "$1" = "purge" ] ; then
	update-rc.d bucardo remove >/dev/null
fi
# End automatically added section


