#!/bin/sh
set -e

LOGDIR=/var/log/jmodeltest

case "$1" in
    purge)
        rm -rf $LOGDIR
    ;;
    remove|upgrade|deconfigure|failed-upgrade)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac



exit 0


