#!/bin/sh
set -e
# Automatically added by dh_php/UNDECLARED
for conf in IcePHP; do
    dpkg-maintscript-helper rm_conffile /etc/php/mods-available/${conf}.ini -- "$@"
done
# End automatically added section
