#!/bin/sh
set -e
# Automatically added by dh_installinit/10.10.5
if [ -x "/etc/init.d/ironic-conductor" ] && [ "$1" = remove ]; then
	invoke-rc.d ironic-conductor stop || true
fi
# End automatically added section
