#!/bin/sh
set -e
# Automatically added by dh_installinit/10.10.9
if [ -x "/etc/init.d/nordugrid-arc-inforeg" ]; then
	invoke-rc.d nordugrid-arc-inforeg stop || exit $?
fi
# End automatically added section
# Automatically added by dh_installinit/10.10.9
if [ -x "/etc/init.d/nordugrid-arc-slapd" ]; then
	invoke-rc.d nordugrid-arc-slapd stop || exit $?
fi
# End automatically added section
# Automatically added by dh_installinit/10.10.9
if [ -x "/etc/init.d/nordugrid-arc-ldap-infosys" ]; then
	invoke-rc.d nordugrid-arc-ldap-infosys stop || exit $?
fi
# End automatically added section
