#!/bin/sh

set -e

if [ "$1" = "remove" ] ; then
	update-alternatives --remove bandit /usr/bin/python3-bandit
	update-alternatives --remove bandit-config-generator /usr/bin/python3-bandit-config-generator
	update-alternatives --remove bandit-baseline /usr/bin/python3-bandit-baseline
fi


# Automatically added by dh_python3:
if which py3clean >/dev/null 2>&1; then
	py3clean -p python3-bandit 
else
	dpkg -L python3-bandit | perl -ne 's,/([^/]*)\.py$,/__pycache__/\1.*, or next; unlink $_ or die $! foreach glob($_)'
	find /usr/lib/python3/dist-packages/ -type d -name __pycache__ -empty -print0 | xargs --null --no-run-if-empty rmdir
fi

# End automatically added section


exit 0
