#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.3.5
dpkg-maintscript-helper mv_conffile /etc/apache2/conf.d/usemod-wiki /etc/apache2/conf-available/usemod-wiki.conf 1.0.5-1 -- "$@"
# End automatically added section
