#!/bin/sh

set -e

if ! getent passwd _debug-me >/dev/null; then
    # --force-badname needed until #521883 resolved
    adduser --system --group --disabled-login --disabled-password \
            --home /var/log/debug-me --force-badname _debug-me
fi
mkdir -p /var/log/debug-me
chmod 700 /var/log/debug-me
chown -R _debug-me:_debug-me /var/log/debug-me

# Automatically added by dh_installinit/11.3.5
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/debug-me" ]; then
		update-rc.d debug-me defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d debug-me $_dh_action || exit 1
	fi
fi
# End automatically added section

