#!/bin/sh
set -e

if [ "$1" = "configure" ]; then
  update-alternatives --install /usr/bin/x-terminal-emulator \
    x-terminal-emulator /usr/bin/rxvt-xterm 10 \
    --slave /usr/share/man/man1/x-terminal-emulator.1.gz \
    x-terminal-emulator.1.gz /usr/share/man/man1/rxvt-xterm.1.gz
  update-alternatives --install /usr/bin/x-terminal-emulator \
    x-terminal-emulator /usr/bin/rxvt-xpm 8 \
    --slave /usr/share/man/man1/x-terminal-emulator.1.gz \
    x-terminal-emulator.1.gz /usr/share/man/man1/rxvt-xpm.1.gz

  update-alternatives --install /usr/bin/rxvt \
    rxvt /usr/bin/rxvt-xterm 30 \
    --slave /usr/share/man/man1/rxvt.1.gz \
    rxvt.1.gz /usr/share/man/man1/rxvt-xterm.1.gz
  update-alternatives --install /usr/bin/rxvt \
    rxvt /usr/bin/rxvt-xpm 20 \
    --slave /usr/share/man/man1/rxvt.1.gz \
    rxvt.1.gz /usr/share/man/man1/rxvt-xpm.1.gz
fi

# Automatically added by dh_installmenu
inst=/etc/menu-methods/rxvt
if [ -f $inst ]; then
	chmod a+x $inst
	if [ -x "`which update-menus 2>/dev/null`" ]; then
		update-menus
	fi
fi
# End automatically added section

