#!/bin/sh
set -e
# Automatically added by dh_installinit/11.5.1
if [ "$1" = "purge" ] ; then
	update-rc.d debomatic remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.5.1
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'debomatic.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'debomatic.service' >/dev/null || true
		deb-systemd-helper unmask 'debomatic.service' >/dev/null || true
	fi
fi
# End automatically added section
