#!/bin/sh

set -e

case "${1}" in
	remove|upgrade|deconfigure)
		update-alternatives --quiet --remove container-tools_script /usr/share/container-tools/scripts/debootstrap
		update-alternatives --quiet --remove container-tools_script /usr/share/container-tools/scripts/curl
		update-alternatives --quiet --remove container-tools_script /usr/share/container-tools/scripts/progress-linux
		update-alternatives --quiet --remove container-tools_script /usr/share/container-tools/scripts/debian
		;;

	failed-upgrade)

		;;

	*)
		echo "prerm called with unknown argument \`${1}'" >&2
		exit 1
		;;
esac



exit 0
