#!/bin/sh
set -e
# Automatically added by dh_installxmlcatalogs
if [ "$1" = "configure" ]; then
	update-xmlcatalog --sort --add --type uri --id "http://xmlroff.org/release/libfo/" --package xmlroff --local /usr/share/xml/libfo/catalog.xml

	update-xmlcatalog --sort --add --type uri --id "http://xmlroff.org/release/libfo/" --package xmlroff --root

fi
# End automatically added section
