#!/bin/sh
set -e
# Automatically added by dh_installinit/11.4.1
if [ "$1" = "purge" ] ; then
	update-rc.d ironic-conductor remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_systemd_enable/11.4.1
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'ironic-conductor.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'ironic-conductor.service' >/dev/null || true
		deb-systemd-helper unmask 'ironic-conductor.service' >/dev/null || true
	fi
fi
# End automatically added section
