#!/bin/sh
set -e
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/default/nsca-ng-server -- "$@"
# End automatically added section
# Automatically added by dh_installinit/10.10.9
if [ -x "/etc/init.d/nsca-ng-server" ]; then
	invoke-rc.d nsca-ng-server stop || exit $?
fi
# End automatically added section
