#!/bin/sh
set -e
# Automatically added by dh_installtex/1
##
## postinst-tex
##
## postinst snippets for everything TeX related
## simply call update-texmf-config triggers
##
## Authors:
##       Norbert Preining <preining@logic.at>
##
#

case "$1" in
    configure|abort-upgrade|abort-remove|abort-deconfigure)
        update-texmf-config map
    ;;
esac

# End automatically added section
# Automatically added by dh_installxfonts/11.3.5
if which update-fonts-dir >/dev/null 2>&1; then
	update-fonts-scale Type1;update-fonts-dir --x11r7-layout Type1
fi
# End automatically added section
# Automatically added by dh_installdeb/11.3.5
dpkg-maintscript-helper rm_conffile /etc/defoma/hints/ttf-gyre.hints 2.004.1-2 -- "$@"
dpkg-maintscript-helper rm_conffile /etc/texmf/updmap.d/20tex-gyre.cfg 2.004.1-2.1 -- "$@"
# End automatically added section
