#!/bin/sh -e

if [ "$1" = "configure" ]; then
    # add the sendpage group
    if ! getent group sendpage >/dev/null; then
        addgroup --quiet --system sendpage
    fi
    # add the sendpage user
    if ! getent passwd sendpage >/dev/null; then
        adduser --quiet --system --disabled-password --ingroup sendpage \
            --gecos "Sendpage SNPP Daemon" \
            --home /var/spool/sendpage --no-create-home sendpage
    fi

    # chown files as needed
    if [ -d /var/spool/sendpage ]; then
        chown -R sendpage:sendpage /var/spool/sendpage
        chmod 0700 /var/spool/sendpage
    fi
fi

# Automatically added by dh_installinit
if [ -x "/etc/init.d/sendpage-server" ]; then
	update-rc.d sendpage-server defaults >/dev/null
	if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
		invoke-rc.d sendpage-server start || exit $?
	else
		/etc/init.d/sendpage-server start || exit $?
	fi
fi
# End automatically added section


exit 0
