#!/bin/sh -e

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d sendpage-server remove >/dev/null || exit $?
fi
# End automatically added section


# Clean up installed user and group
if [ "$1" = "purge" ]; then
    deluser --quiet --system sendpage >/dev/null || true
    delgroup --quiet --system sendpage >/dev/null || true
fi
