#!/bin/sh
set -e
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/createrepo 0.10.3-1~ -- "$@"
# End automatically added section

# Automatically added by dh_python2:
if which pyclean >/dev/null 2>&1; then
	pyclean -p createrepo 
else
	dpkg -L createrepo | grep \.py$ | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section
