#!/bin/sh
set -e
# Automatically added by dh_systemd_enable/11.3.5
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if deb-systemd-helper debian-installed 'burp.service'; then
		# This will only remove masks created by d-s-h on package removal.
		deb-systemd-helper unmask 'burp.service' >/dev/null || true

		if deb-systemd-helper --quiet was-enabled 'burp.service'; then
			# Create new symlinks, if any.
			deb-systemd-helper enable 'burp.service' >/dev/null || true
		fi
	fi

	# Update the statefile to add new symlinks (if any), which need to be cleaned
	# up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'burp.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_start/11.3.5
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'burp.service' >/dev/null || true
	fi
fi
# End automatically added section
