#!/bin/sh
set -e
. /usr/share/debconf/confmodule
blis_pri=37

update-alternatives --install /usr/lib/x86_64-linux-gnu/libblas.so.3 \
                    libblas.so.3-x86_64-linux-gnu \
                    /usr/lib/x86_64-linux-gnu/libblis.so.1 \
                    $blis_pri


exit 0
