#!/bin/sh
set -e
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/default/clamav-milter 0.98.5\~beta1\+dfsg-3\~ clamav-milter -- "$@"
# End automatically added section
# Automatically added by dh_installinit/10.10.9
if [ -x "/etc/init.d/clamav-milter" ] && [ "$1" = remove ]; then
	invoke-rc.d clamav-milter stop || exit $?
fi
# End automatically added section
