#!/bin/sh
set -e

if [ "$1" = "purge" ] ; then
	update-alternatives --display dpm-srmv1 > /dev/null || \
		update-rc.d dpm-srmv1 remove > /dev/null || exit $?
	update-alternatives --display dpm-srmv2 > /dev/null || \
		update-rc.d dpm-srmv2 remove > /dev/null || exit $?
	update-alternatives --display dpm-srmv2.2 > /dev/null || \
		update-rc.d dpm-srmv2.2 remove > /dev/null || exit $?
fi


