#!/bin/sh

set -e

case "${1}" in
    purge)
        if [ -x "$(which deluser)" ]; then
            deluser --quiet lizardfs > /dev/null || true
            rm -f "/etc/security/limits.d/10-lizardfs.conf" "/etc/pam.d/lizardfs"
        fi
    ;;
esac


