#!/bin/sh

set -e

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d syncache remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section


case "$1" in
	purge)
	# remove user, group, and home directory
	deluser --remove-home syncache >/dev/null 2>&1 || true
	;;

	remove|upgrade|disappearfailed-install|abort-install|abort-upgrade|failed-upgrade)
	;;

	*)
	echo "postrm called with unknown argument \`$1'" >&2;
	;;
esac

exit 0
