#!/bin/sh

set -e

invoke-rc.d isc-dhcp-relay stop

# Automatically added by dh_installinit
if [ -x "/etc/init.d/isc-dhcp-relay" ]; then
	invoke-rc.d isc-dhcp-relay stop || exit $?
fi
# End automatically added section


exit 0
