#!/bin/sh -e
# postinst

USERNAME="Debian-console-log"

[ -n "$CONLOGDEBUG" ] && set -x

# Add user
if [ "$1" = "configure" ]; then
    echo >&2 'Adding system user'
    adduser --system --group --home /nonexistent \
	    --no-create-home --disabled-login --force-badname $USERNAME
    adduser $USERNAME adm
fi
    
# Automatically added by dh_installinit/10.9
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/console-log" ]; then
		update-rc.d console-log defaults >/dev/null
		invoke-rc.d console-log start || exit $?
	fi
fi
# End automatically added section


# end of file
