#!/bin/sh

set -e

# Automatically added by dh_installinit/11
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/virtualbox-guest-utils" ]; then
		update-rc.d virtualbox-guest-utils defaults >/dev/null || exit $?
	fi
fi
# End automatically added section


if [ "$1" = configure ] && [ -n "$2" ] && \
   [ -x /usr/share/update-notifier/notify-reboot-required ] && \
   pidof VBoxService > /dev/null;
then
	/usr/share/update-notifier/notify-reboot-required || true
fi

if [ "$1" = configure ] && [ -z `getent group vboxsf` ]; then
	addgroup --system --quiet vboxsf
fi
