#!/bin/sh
set -e
# Automatically added by dh_installinit/11.5.1
if [ -x "/etc/init.d/lyskom-server" ] && [ "$1" = remove ]; then
	invoke-rc.d lyskom-server stop || exit 1
fi
# End automatically added section
