#!/bin/sh
set -e
if [ ! -e /var/lib/emacsen-common/state/package/installed/emacsen-common ]; then
    # Fallback to emacsen-common 1.x
    if [ "$1" = "configure" ] && [ -x /usr/lib/emacsen-common/emacs-package-install ]; then
	/usr/lib/emacsen-common/emacs-package-install w3m-el
    fi
else
# Automatically added by dh_installemacsen
if [ "$1" = "configure" ] && [ -e /var/lib/emacsen-common/state/package/installed/emacsen-common -a -x /usr/lib/emacsen-common/emacs-package-install ]
then
	/usr/lib/emacsen-common/emacs-package-install --postinst w3m-el
fi
# End automatically added section

fi
