#!/bin/sh

set -e

# Automatically added by dh_installinit/10.10.8
if [ "$1" = "purge" ] ; then
	update-rc.d tircd remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section


if [ "$1" = "purge" ]; then
	deluser --quiet --system tircd >/dev/null || true
	rm -rf /var/log/tircd
fi
