#!/bin/sh

set -e

if [ "$1" = "configure" ]; then
	adduser --system --quiet --group --no-create-home --home /nonexistent tircd || true
	mkdir -p /var/log/tircd
	chown -R tircd:tircd /var/log/tircd
	chown -R tircd:tircd /var/lib/tircd
fi

# Automatically added by dh_installinit/10.10.8
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/tircd" ]; then
		update-rc.d tircd defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d tircd $_dh_action || exit $?
	fi
fi
# End automatically added section

