#! /bin/sh -x
# postrm script for routino-www
#
set -e

if [ "$DPKG_DEBUG" = "developer" ]; then
  set -x
fi

apache_uninstall() {
        COMMON_STATE=$(dpkg-query -f '${Status}' -W 'apache2.2-common' 2>/dev/null | awk '{print $3}' || true)

        if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
                . /usr/share/apache2/apache2-maintscript-helper
                apache2_invoke disconf routino-www || exit $?
        elif [ "$COMMON_STATE" = "installed" ] || [ "$COMMON_STATE" = "unpacked" ] ; then
                [ ! -L /etc/apache2/conf.d/routino-www.conf ] || rm /etc/apache2/conf.d/routino-www.conf
        fi

        rm -f /etc/apache2/conf-available/routino-www.conf
}

if [ "$1" = "deconfigure" ]; then
    apache_uninstall
fi



