#! /bin/sh

set -e

# summary of how this script can be called:
#        * <postrm> `remove'
#        * <postrm> `purge'
#        * <old-postrm> `upgrade' <new-version>
#        * <new-postrm> `failed-upgrade' <old-version>
#        * <new-postrm> `abort-install'
#        * <new-postrm> `abort-install' <old-version>
#        * <new-postrm> `abort-upgrade' <old-version>
#        * <disappearer's-postrm> `disappear' <r>overwrit>r> <new-version>
# for details, see /usr/doc/packaging-manual/

if [ "$1" = "purge" ]; then
    dpkg-statoverride --remove /var/games/lmarbles || test $? -eq 2
    dpkg-statoverride --remove /var/games/lmarbles/lmarbles.prfs || test $? -eq 2
    dpkg-statoverride --remove /usr/games/lmarbles || test $? -eq 2
    rm -rf /var/games/lmarbles
    rmdir --ignore-fail-on-non-empty /var/games
fi


