#!/bin/sh

set -e

# Automatically added by dh_installinit/10.10.5
if [ "$1" = "purge" ] ; then
	update-rc.d rtcw-server remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/10.10.5
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'rtcw-server.service' >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'rtcw-server.service' >/dev/null
		deb-systemd-helper unmask 'rtcw-server.service' >/dev/null
	fi
fi
# End automatically added section
# Automatically added by dh_apparmor/2.11.1-3
if [ "$1" = "purge" ] && ! [ -e "/etc/apparmor.d/usr.lib.rtcw.iowolfded" ] ; then
    rm -f "/etc/apparmor.d/disable/usr.lib.rtcw.iowolfded" || true
    rm -f "/etc/apparmor.d/force-complain/usr.lib.rtcw.iowolfded" || true
    rm -f "/etc/apparmor.d/local/usr.lib.rtcw.iowolfded" || true
    rmdir /etc/apparmor.d/disable 2>/dev/null || true
    rmdir /etc/apparmor.d/local   2>/dev/null || true
    rmdir /etc/apparmor.d         2>/dev/null || true
fi
# End automatically added section


if [ "$1" = "purge" ] ; then
    # Lock account on purge
    if [ -f /etc/shadow ]; then
        usermod -L -e 1 rtcw-server
    else
        usermod -L rtcw-server
    fi
    rm -r /var/games/rtcw-server
    rmdir --ignore-fail-on-non-empty /var/games
fi
