#!/bin/sh
set -e
# Automatically added by dh_installinit/10.10.5
if [ -x "/etc/init.d/rtcw-server" ] && [ "$1" = remove ]; then
	invoke-rc.d rtcw-server stop || exit $?
fi
# End automatically added section
