#!/bin/sh
set -e
# Automatically added by dh_installinit/11.3.5
if [ -x "/etc/init.d/winbind" ] && [ "$1" = remove ]; then
	invoke-rc.d winbind stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installdeb/11.3.5
dpkg-maintscript-helper rm_conffile /etc/init/winbind.conf 2:4.6.5\+dfsg-5\~ -- "$@"
# End automatically added section
