#!/bin/sh

set -e

if [ "$1" = "remove" ] ; then
  update-alternatives --remove pyscss /usr/bin/python2-pyscss
fi


# Automatically added by dh_python2:
if which pyclean >/dev/null 2>&1; then
	pyclean -p python-scrapy 
else
	dpkg -L python-scrapy | grep '\.py$' | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section


exit 0
