#!/bin/sh
set -e

# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p tryton-modules-sale-stock-quantity 
fi
if which pypy3compile >/dev/null 2>&1; then
	pypy3compile -p tryton-modules-sale-stock-quantity  || true
fi

# End automatically added section
