#!/bin/sh

set -e

# Automatically added by dh_systemd_start/11.1.4
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_start/11.1.4
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/11.1.4
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'painintheapt-daily.timer' 'painintheapt-weekly.timer' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'painintheapt-daily.timer' 'painintheapt-weekly.timer' >/dev/null || true
		deb-systemd-helper unmask 'painintheapt-daily.timer' 'painintheapt-weekly.timer' >/dev/null || true
	fi
fi
# End automatically added section


case "$1" in
   remove)
       ;;
   purge)
       rm -rf /var/lib/painintheapt/
esac

