#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/pyro-nsd" ]; then
	invoke-rc.d pyro-nsd stop || exit $?
fi
# End automatically added section

# Automatically added by dh_python2:
if which pyclean >/dev/null 2>&1; then
	pyclean -p pyro 
else
	dpkg -L pyro | grep \.py$ | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section
