#!/bin/sh
set -e

# Automatically added by dh_installmenu
if [ "$1" = "configure" ] && [ -x "`which update-menus 2>/dev/null`" ]; then
	update-menus
fi
# End automatically added section


if [ "$1" = "configure" ]; then
  update-alternatives --install /usr/bin/rasmol rasmol /usr/bin/rasmol-gtk 11
  update-alternatives --install /usr/bin/rasmol rasmol /usr/bin/rasmol-classic 10
fi
