#!/bin/sh

set -e

if [ "${1}" = "remove" ] && [ -r /usr/share/debconf/confmodule ] && [ -r /usr/share/dbconfig-common/dpkg/prerm ] ; then
	. /usr/share/debconf/confmodule
	db_get novaapi/configure_db || true
	if [ "$RET" = "true" ] ; then
		. /usr/share/dbconfig-common/dpkg/prerm
		dbc_go nova-api $@
	fi
fi

# Automatically added by dh_installinit/11.5.3
if [ -x "/etc/init.d/nova-api" ] && [ "$1" = remove ]; then
	invoke-rc.d nova-api stop || true
fi
# End automatically added section


exit 0
