#! /bin/sh

set -e

LAZARUS_DIR=/usr/lib/lazarus/1.6.2

# Add alternatives
update-alternatives \
	--install /usr/bin/lazarus-ide lazarus-ide ${LAZARUS_DIR}/startlazarus 1060200 \
    --slave /usr/bin/startlazarus startlazarus ${LAZARUS_DIR}/startlazarus \
	--slave /usr/share/pixmaps/lazarus.xpm lazarus.xpm /usr/share/pixmaps/lazarus-1.6.2.xpm

# Debhelper code
# Automatically added by dh_installmenu
if [ "$1" = "configure" ] && [ -x "`which update-menus 2>/dev/null`" ]; then
	update-menus
fi
# End automatically added section

