#!/bin/sh
set -e

# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p pitivi /usr/lib/x86_64-linux-gnu/pitivi/python/pitivi -V 3.6
fi

# End automatically added section
