#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.1.5
dpkg-maintscript-helper mv_conffile /etc/xdg/autostart/mpDris2.desktop /etc/xdg/autostart/mpdris2.desktop 0.4~ mpdris2 -- "$@"
# End automatically added section
