#!/bin/sh
set -e
# Automatically added by dh_installinit/10.7.2
if [ -x "/etc/init.d/alljoyn-daemon-1604" ]; then
	invoke-rc.d alljoyn-daemon-1604 stop || exit $?
fi
# End automatically added section
