#!/bin/sh

set -e

case "$1" in
    remove)
        # Calling the init script during removal
	if [ -x "/etc/init.d/enable-nat" ] ; then
	    if [ -x "`which invoke-rc.d 2>/dev/null`" ] ; then
		invoke-rc.d enable-nat stop || exit $?
	    else
		/etc/init.d/enable-nat stop || exit $?
	    fi
	fi
	# cleanup from debian-edu-ltsp-audiodivert
	if dpkg --compare-versions "$2" le "1.931~" && [ -f /usr/bin/gtick.ltsp ] ; then
	    rm /usr/bin/gtick
	    dpkg-divert --package debian-edu-config --rename --remove /usr/bin/gtick
	    rm /usr/bin/gtick.ltsp
	fi
	;;
    purge)
	# Generated in the postinst
	rm -f /etc/default/enable-nat
	rm -f /etc/kde-user-profile
	rm -f /etc/kderc
	if [ ! -s /var/lib/dovecot/auth_success ] ; then
	    rm -f /var/lib/dovecot/auth_success
	fi

	# remove /var/lib/dovecot directory (this does not
	# interfere with dovecot-core, if installed)
	if [ -e /var/lib/dovecot ] ; then
	    rmdir --ignore-fail-on-non-empty /var/lib/dovecot
	fi
esac

# Automatically added by dh_installdeb/11
dpkg-maintscript-helper mv_conffile /etc/apache2/sites-available/debian-edu-default /etc/apache2/sites-available/debian-edu-default.conf 1.719 -- "$@"
dpkg-maintscript-helper mv_conffile /etc/apache2/sites-available/debian-edu-ssl-default /etc/apache2/sites-available/debian-edu-ssl-default.conf 1.719 -- "$@"
dpkg-maintscript-helper mv_conffile /etc/apache2/conf.d/debian-edu-config-doc /etc/apache2/conf-available/debian-edu-config-doc.conf 1.719 -- "$@"
dpkg-maintscript-helper rm_conffile /etc/cfengine/debian-edu/cf.pdns 1.811 -- "$@"
dpkg-maintscript-helper rm_conffile /etc/insserv.conf.d/debian-edu-config 1.811 -- "$@"
dpkg-maintscript-helper rm_conffile /etc/powerdns/pdns.d/pdns-debian-edu.conf 1.811 -- "$@"
dpkg-maintscript-helper rm_conffile /etc/cfengine/debian-edu/cf.kdm 1.906 -- "$@"
dpkg-maintscript-helper rm_conffile /etc/insserv/overrides/kdm 1.906 -- "$@"
dpkg-maintscript-helper rm_conffile /etc/ldap/slapd-debian-edu.conf 1.911 -- "$@"
dpkg-maintscript-helper rm_conffile /etc/ldap/slapd-lenny_debian-edu.conf 1.911 -- "$@"
dpkg-maintscript-helper rm_conffile /etc/X11/Xsession.d/06debian-edu-iceweasel-ltsp 1.818\+deb8u1 -- "$@"
dpkg-maintscript-helper rm_conffile /etc/apt/apt.conf.d/99-edu-prefer-iceweasel 1.818\+deb8u1 -- "$@"
dpkg-maintscript-helper rm_conffile /etc/init.d/iceweasel-ldapconf 1.818\+deb8u1 -- "$@"
dpkg-maintscript-helper rm_conffile /etc/cfengine/debian-edu/cf.iceweasel 1.818\+deb8u1 -- "$@"
dpkg-maintscript-helper rm_conffile /usr/share/debian-edu-config/iceweacel-networked-prefs.js 1.818\+deb8u1 -- "$@"
# End automatically added section
# Automatically added by dh_installinit/11
if [ "$1" = "purge" ] ; then
	update-rc.d enable-nat remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/11
if [ "$1" = "purge" ] ; then
	update-rc.d chromium-ldapconf remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/11
if [ "$1" = "purge" ] ; then
	update-rc.d firefox-ldapconf remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/11
if [ "$1" = "purge" ] ; then
	update-rc.d fetch-ldap-cert remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installdebconf/11
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

