#!/bin/sh
set -e
# Automatically added by dh_installinit/12
if [ -x "/etc/init.d/bacula-fd" ] && [ "$1" = remove ]; then
	invoke-rc.d bacula-fd stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installdeb/12
dpkg-maintscript-helper dir_to_symlink /usr/share/doc/bacula-fd bacula-common 7.0.5\+dfsg-4\~ -- "$@"
# End automatically added section
