#!/bin/sh
set -e

LIBDIR=/usr/lib/x86_64-linux-gnu/sssd

case "$1" in
    configure)
        chown root:sssd $LIBDIR/krb5_child $LIBDIR/ldap_child
        chmod 4754 $LIBDIR/krb5_child $LIBDIR/ldap_child
    ;;
esac



