#!/bin/sh
set -e
# Automatically added by dh_installinit/11.5.3
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/globus-gridftp-server" ]; then
		update-rc.d globus-gridftp-server defaults-disabled >/dev/null
		invoke-rc.d globus-gridftp-server start || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installinit/11.5.3
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/globus-gridftp-sshftp" ]; then
		update-rc.d globus-gridftp-sshftp defaults-disabled >/dev/null
		invoke-rc.d globus-gridftp-sshftp start || exit 1
	fi
fi
# End automatically added section
