#!/bin/sh
set -e

. /usr/share/debconf/confmodule

if [ "$1" = "purge" ]; then
    if getent group dirsrv > /dev/null; then
        deluser --system dirsrv || true
    fi
    rm -f /etc/systemd/system/dirsrv.target.wants/dirsrv@*.service
    rm -rf /etc/dirsrv
    rm -rf /var/lib/dirsrv
    rm -rf /var/log/dirsrv
fi

# Automatically added by dh_installsystemd/11.3.5
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.3.5
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'dirsrv-snmp.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'dirsrv-snmp.service' >/dev/null || true
		deb-systemd-helper unmask 'dirsrv-snmp.service' >/dev/null || true
	fi
fi
# End automatically added section

