#!/bin/sh

set -e

. /usr/share/debconf/confmodule
. /usr/share/dbconfig-common/dpkg/prerm.pgsql

dbc_go puppetdb $@

# Automatically added by dh_installinit/10.7.2
if [ -x "/etc/init.d/puppetdb" ] && [ "$1" = remove ]; then
	invoke-rc.d puppetdb stop || exit $?
fi
# End automatically added section


exit 0
