#!/bin/sh

set -e

case "${1}" in
    purge|remove)
        if [ -x "$(which delgroup)" ]; then
            delgroup --quiet --system --only-if-empty xpra || true
        fi
    ;;
esac

# Automatically added by dh_icons/10.7.2
if which update-icon-caches >/dev/null 2>&1 ; then
	update-icon-caches /usr/share/icons/xpra.png
fi
# End automatically added section

