#!/bin/sh

set -e

if [ "$1" = "purge" ]; then
	deluser e2guardian > /dev/null || true
	rm -rf /var/log/e2guardian
	rm -rf /etc/e2guardian
fi

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d e2guardian remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section

