#!/bin/sh
set -e
# Automatically added by dh_systemd_start
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask entropybroker.service >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge entropybroker.service >/dev/null
		deb-systemd-helper unmask entropybroker.service >/dev/null
	fi
fi
# End automatically added section
# Automatically added by dh_systemd_enable
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask eb_client_egd.service eb_client_file.service eb_client_kernel_generic.service eb_client_linux_kernel.service eb_proxy_knuth_b.service eb_proxy_knuth_m.service eb_server_Araneus_Alea.service eb_server_ComScire_R2000KU.service eb_server_audio.service eb_server_egd.service eb_server_ext_proc.service eb_server_linux_kernel.service eb_server_push_file.service eb_server_smartcard.service eb_server_stream.service eb_server_timers.service eb_server_usb.service eb_server_v4l.service entropybroker.service >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge eb_client_egd.service eb_client_file.service eb_client_kernel_generic.service eb_client_linux_kernel.service eb_proxy_knuth_b.service eb_proxy_knuth_m.service eb_server_Araneus_Alea.service eb_server_ComScire_R2000KU.service eb_server_audio.service eb_server_egd.service eb_server_ext_proc.service eb_server_linux_kernel.service eb_server_push_file.service eb_server_smartcard.service eb_server_stream.service eb_server_timers.service eb_server_usb.service eb_server_v4l.service entropybroker.service >/dev/null
		deb-systemd-helper unmask eb_client_egd.service eb_client_file.service eb_client_kernel_generic.service eb_client_linux_kernel.service eb_proxy_knuth_b.service eb_proxy_knuth_m.service eb_server_Araneus_Alea.service eb_server_ComScire_R2000KU.service eb_server_audio.service eb_server_egd.service eb_server_ext_proc.service eb_server_linux_kernel.service eb_server_push_file.service eb_server_smartcard.service eb_server_stream.service eb_server_timers.service eb_server_usb.service eb_server_v4l.service entropybroker.service >/dev/null
	fi
fi
# End automatically added section
