#!/bin/sh

set -e

if [ "$1" = purge ]; then
    rm -f /etc/tinc/nets.boot
fi

# Automatically added by dh_installinit/11.4.1
if [ "$1" = "purge" ] ; then
	update-rc.d tinc remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_systemd_enable/11.4.1
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'tinc.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'tinc.service' >/dev/null || true
		deb-systemd-helper unmask 'tinc.service' >/dev/null || true
	fi
fi
# End automatically added section

