#!/bin/sh

set -e

PACKAGE=emacs-calfw

case "$1" in
  failed-upgrade)
    if dpkg --compare-versions "$2" eq "1.2-1"; then
      ELCDIR=/usr/share/emacs23/site-lisp/${PACKAGE}
      if [ -d ${ELCDIR} ] ; then
        rm -rf ${ELCDIR}/*
      fi
	fi
  ;;
esac

# Automatically added by dh_installemacsen
if [ -e /var/lib/emacsen-common/state/package/installed/emacsen-common -a -x /usr/lib/emacsen-common/emacs-package-remove ] ; then
	/usr/lib/emacsen-common/emacs-package-remove --prerm emacs-calfw
fi
# End automatically added section


