#!/bin/sh
set -e
# Automatically added by dh_installinit/11.2.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/openipmi" ]; then
		update-rc.d openipmi defaults 21 20 >/dev/null || exit 1
	fi
fi
# End automatically added section
