#!/bin/sh
set -e

# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p volatility 
fi

if which pycompile >/dev/null 2>&1; then
	pycompile -p volatility /usr/share/volatility
fi

# End automatically added section
