#!/bin/sh
set -e

# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p jigsaw-generator /usr/share/jigsaw-generator
fi
if which pypy3compile >/dev/null 2>&1; then
	pypy3compile -p jigsaw-generator /usr/share/jigsaw-generator || true
fi

# End automatically added section
