#!/bin/sh
set -e

dpkg-maintscript-helper mv_conffile /etc/ipmidetectd.conf /etc/freeipmi/ipmidetectd.conf 0.8.12-3 -- "$@"

# Automatically added by dh_installinit/10.10.4
if [ "$1" = "purge" ] ; then
	update-rc.d ipmidetectd remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section


exit 0
