#!/bin/sh
set -e
# Automatically added by dh_php/UNDECLARED
for conf in uploadprogress; do
    dpkg-maintscript-helper rm_conffile /etc/php/mods-available/${conf}.ini -- "$@"
done

if [ -e /usr/lib/php/php-maintscript-helper ] ; then
    . /usr/lib/php/php-maintscript-helper

    for version in 7.3 7.2 ; do
        for conf in uploadprogress ; do
            php_invoke enmod $version ALL $conf || exit 1
	done
    done
else
    for conf in uploadprogress ; do
        phpenmod $conf
    done
fi
# End automatically added section
