#!/bin/sh

set -e

# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/modprobe.d/mt-st.conf 1.3-1~ mt-st -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/init.d/mt-st 1.3-1~ mt-st -- "$@"
# End automatically added section


exit 0
