#!/bin/sh
set -e
# Automatically added by dh_installudev
if [ "$1" = install ] || [ "$1" = upgrade ]; then
	if [ -e "/etc/udev/rules.d/z60_mt-st.rules" ]; then
		if [ "`md5sum \"/etc/udev/rules.d/z60_mt-st.rules\" | sed -e \"s/ .*//\"`" = \
		     "`dpkg-query -W -f='${Conffiles}' mt-st | sed -n -e \"\\\\' /etc/udev/rules.d/z60_mt-st.rules '{s/ obsolete$//;s/.* //p}\"`" ]
		then
			rm -f "/etc/udev/rules.d/z60_mt-st.rules"
		fi
	fi
fi
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/init.d/mt-st 1.3-1~ mt-st -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/modprobe.d/mt-st.conf 1.3-1~ mt-st -- "$@"
# End automatically added section
