#!/bin/sh
set -e
# Automatically added by dh_systemd_start/10.6.4
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop approx.socket >/dev/null
fi
# End automatically added section
