#!/bin/sh
set -e

if [ "$1" = "configure" ]; then
  update-alternatives --install /usr/bin/x-terminal-emulator \
    x-terminal-emulator /usr/bin/crxvt 8 \
    --slave /usr/share/man/man1/x-terminal-emulator.1.gz \
    x-terminal-emulator.1.gz /usr/share/man/man1/crxvt.1.gz
  update-alternatives --install /usr/bin/x-terminal-emulator \
    x-terminal-emulator /usr/bin/krxvt 9 \
    --slave /usr/share/man/man1/x-terminal-emulator.1.gz \
    x-terminal-emulator.1.gz /usr/share/man/man1/krxvt.1.gz
  update-alternatives --install /usr/bin/x-terminal-emulator \
    x-terminal-emulator /usr/bin/grxvt 8 \
    --slave /usr/share/man/man1/x-terminal-emulator.1.gz \
    x-terminal-emulator.1.gz /usr/share/man/man1/grxvt.1.gz

  update-alternatives --install /usr/bin/rxvt \
    rxvt /usr/bin/grxvt 20 \
    --slave /usr/share/man/man1/rxvt.1.gz \
    rxvt.1.gz /usr/share/man/man1/grxvt.1.gz
  update-alternatives --install /usr/bin/rxvt \
    rxvt /usr/bin/krxvt 25 \
    --slave /usr/share/man/man1/rxvt.1.gz \
    rxvt.1.gz /usr/share/man/man1/krxvt.1.gz
  update-alternatives --install /usr/bin/rxvt \
    rxvt /usr/bin/crxvt 20 \
    --slave /usr/share/man/man1/rxvt.1.gz \
    rxvt.1.gz /usr/share/man/man1/crxvt.1.gz
fi

# Automatically added by dh_installmenu
if [ "$1" = "configure" ] && [ -x "`which update-menus 2>/dev/null`" ]; then
	update-menus
fi
# End automatically added section

