#!/bin/sh
set -e

# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p jhbuild 
fi

if which pycompile >/dev/null 2>&1; then
	pycompile -p jhbuild /usr/share/jhbuild -V 2.6-
fi

# End automatically added section
