#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.5.1
dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/colormgr-completion.bash 1.0.3-1~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.5.1
dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.freedesktop.colord-sane.conf 1.0.3-1~ -- "$@"
# End automatically added section
# Automatically added by dh_systemd_start/11.5.1
if [ -d /run/systemd/system ]; then
	deb-systemd-invoke stop 'colord.service' >/dev/null || true
fi
# End automatically added section
