#!/bin/sh
# prerm script for webkit-image-qt
#
# see: dh_installdeb(1)

set -e

case "$1" in
    remove|upgrade|deconfigure)
        if [ -f /usr/bin/webkit-image-qt ]; then
            update-alternatives --remove webkit-image /usr/bin/webkit-image-qt
        fi
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac



exit 0
