#!/bin/sh
set -e

if [ "$1" = purge ]; then
  rm -f /var/log/binkd/binkd*
  rmdir --ignore-fail-on-non-empty /var/log/binkd/ 2>/dev/null || true
fi

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d binkd remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask binkd.service >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge binkd.service >/dev/null
		deb-systemd-helper unmask binkd.service >/dev/null
	fi
fi
# End automatically added section


