#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/glance-registry" ] && [ "$1" = remove ]; then
	invoke-rc.d glance-registry stop || true
fi
# End automatically added section
