#!/bin/sh
set -e
# Automatically added by dh_installinit/11.3.5
if [ -x "/etc/init.d/octavia-housekeeping" ] && [ "$1" = remove ]; then
	invoke-rc.d octavia-housekeeping stop || true
fi
# End automatically added section
