#!/bin/sh
set -e
# Automatically added by dh_dkms
DKMS_NAME=open-vm-tools
DKMS_VERSION=10.1.5

case "$1" in
    remove|upgrade|deconfigure)
      if [  "$(dkms status -m $DKMS_NAME -v $DKMS_VERSION)" ]; then
         dkms remove -m $DKMS_NAME -v $DKMS_VERSION --all
      fi
    ;;
esac
# End automatically added section
