#!/bin/sh
set -e
# Automatically added by dh_installinit/11.4
if [ -x "/etc/init.d/neutron-taas-openvswitch-agent" ] && [ "$1" = remove ]; then
	invoke-rc.d neutron-taas-openvswitch-agent stop || true
fi
# End automatically added section
