#!/bin/sh

set -e

[ "$1" = "remove" ] && ldconfig

php_enable() { return 0; }

if [ "$1" = "purge" ]; then
    phpini=/etc/php/7.3/embed/php.ini
    # remove the flag to remember the original state
    if [ -e /etc/php/7.3/embed/.start ]; then
	rm -f /etc/php/7.3/embed/.start
    fi
    for ext in '~' '%' .bak .ucf-new .ucf-old .ucf-dist;  do
	rm -f $phpini$ext
    done
    rm -f $phpini
    if which ucf >/dev/null; then
	ucf --purge $phpini
    fi
    if which ucfr >/dev/null; then
	ucfr --purge libphp7.3-embed $phpini
    fi

    for dir in \
	/etc/php/7.3/embed/conf.d \
	/etc/php/7.3/embed \
	/etc/php/7.3 \
	/etc/php;
    do
	if [ -d $dir ]; then
	    rmdir --ignore-fail-on-non-empty $dir
	fi
    done
fi



exit 0
