#!/bin/sh

set -e

case "$1" in
    configure)
        chown jabber:jabber /etc/jabberd2
        chmod 750 /etc/jabberd2
        chown jabber:jabber /var/lib/jabberd2
        chmod 750 /var/lib/jabberd2
        chown jabber:jabber /var/log/jabberd2
        chmod 750 /var/log/jabberd2
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# Automatically added by dh_systemd_enable/10.10.7
# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask 'jabberd-c2s.service' >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled 'jabberd-c2s.service'; then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable 'jabberd-c2s.service' >/dev/null || true
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'jabberd-c2s.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/10.10.7
# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask 'jabberd-router.service' >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled 'jabberd-router.service'; then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable 'jabberd-router.service' >/dev/null || true
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'jabberd-router.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/10.10.7
# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask 'jabberd-s2s.service' >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled 'jabberd-s2s.service'; then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable 'jabberd-s2s.service' >/dev/null || true
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'jabberd-s2s.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/10.10.7
# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask 'jabberd-sm.service' >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled 'jabberd-sm.service'; then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable 'jabberd-sm.service' >/dev/null || true
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'jabberd-sm.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/10.10.7
# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask 'jabberd.service' >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled 'jabberd.service'; then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable 'jabberd.service' >/dev/null || true
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'jabberd.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/10.10.7
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/jabberd2" ]; then
		update-rc.d jabberd2 defaults >/dev/null
		invoke-rc.d jabberd2 start || exit $?
	fi
fi
# End automatically added section
# Automatically added by dh_systemd_start/10.10.7
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
	deb-systemd-invoke start 'jabberd-c2s.service' 'jabberd-router.service' 'jabberd-s2s.service' 'jabberd-sm.service' >/dev/null || true
fi
# End automatically added section


exit 0
