#!/bin/sh
set -e
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/init.d/uptimed.sh 1:0.3.16-3.1 -- "$@"
# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/uptimed" ] && [ "$1" = remove ]; then
	invoke-rc.d uptimed stop || exit $?
fi
# End automatically added section
