#!/bin/sh
set -e
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/init.d/hibernate 1.99-1.1 -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper mv_conffile /etc/hibernate/suspend2.conf /etc/hibernate/tuxonice.conf 1.99-1.1 -- "$@"
# End automatically added section
