#!/bin/sh

set -e

if [ "${1}" = "configure" ] ; then
	update-alternatives --install /usr/share/puppet/modules/tftp puppet-module-tftp /usr/share/puppet/modules.available/puppetlabs-tftp 500
fi



exit 0
