#!/bin/sh
set -e

# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p game-data-packager /usr/share/games/game-data-packager
fi
if which pypy3compile >/dev/null 2>&1; then
	pypy3compile -p game-data-packager /usr/share/games/game-data-packager || true
fi

# End automatically added section
# Automatically added by dh_installdeb/11.5.3
dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/game-data-packager 42\~ -- "$@"
dpkg-maintscript-helper mv_conffile /etc/game-data-packager/rott-mirrors /etc/game-data-packager/3drealms-mirrors 60\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/game-data-packager/alioth-mirrors 60\~ -- "$@"
# End automatically added section
