#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.5.3
dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/game-data-packager 42\~ -- "$@"
dpkg-maintscript-helper mv_conffile /etc/game-data-packager/rott-mirrors /etc/game-data-packager/3drealms-mirrors 60\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/game-data-packager/alioth-mirrors 60\~ -- "$@"
# End automatically added section
