#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.5.3
dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/game-data-packager 42\~ -- "$@"
dpkg-maintscript-helper mv_conffile /etc/game-data-packager/rott-mirrors /etc/game-data-packager/3drealms-mirrors 60\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/game-data-packager/alioth-mirrors 60\~ -- "$@"
# End automatically added section

# Automatically added by dh_python3:
if which py3clean >/dev/null 2>&1; then
	py3clean -p game-data-packager 
else
	dpkg -L game-data-packager | perl -ne 's,/([^/]*)\.py$,/__pycache__/\1.*, or next; unlink $_ or die $! foreach glob($_)'
	find /usr/lib/python3/dist-packages/ -type d -name __pycache__ -empty -print0 | xargs --null --no-run-if-empty rmdir
fi

# End automatically added section
