#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/ipip" ]; then
		update-rc.d ipip defaults >/dev/null
		invoke-rc.d ipip start || exit $?
	fi
fi
# End automatically added section
