#!/bin/sh
set -e
# Automatically added by dh_installinit/11.3.5
if [ -x "/etc/init.d/aodh-expirer" ] && [ "$1" = remove ]; then
	invoke-rc.d aodh-expirer stop || true
fi
# End automatically added section
