#!/bin/sh

set -e

case "${1}" in
	configure)
		if [ -x /usr/sbin/update-initramfs ] && [ -e /etc/initramfs-tools/initramfs.conf ]
		then
			update-initramfs -u
		fi
		;;

	abort-upgrade|abort-remove|abort-deconfigure)

		;;

	*)
		echo "postinst called with unknown argument \`${1}'" >&2
		exit 1
		;;
esac

# Automatically added by dh_installdeb/11
dpkg-maintscript-helper rm_conffile /etc/initramfs-tools/hooks/reiserfsprogs 1:3.6.27-2\~ reiserfsprogs -- "$@"
# End automatically added section


exit 0
