#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/a-rex" ]; then
		update-rc.d a-rex defaults >/dev/null
		invoke-rc.d a-rex start || exit $?
	fi
fi
# End automatically added section
