#!/bin/sh

set -e

del_override() {
    if dpkg-statoverride --list $4 >/dev/null; then
	dpkg-statoverride --force --remove $4
    fi
}

if [ "$1" = "purge" ]; then
    del_override root courier 0640 /etc/courier/authdaemonrc
fi

# Automatically added by dh_installinit/10.8
if [ "$1" = "purge" ] ; then
	update-rc.d courier-authdaemon remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section


exit 0
