#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.3.5
dpkg-maintscript-helper symlink_to_dir /usr/share/doc/libetpan-dev /usr/share/doc/libetpan20 1.8.0-1\~ -- "$@"
# End automatically added section
