#!/bin/sh
set -e
# Automatically added by dh_systemd_enable
if deb-systemd-helper debian-installed argonaut-server.service; then
	# This will only remove masks created by d-s-h on package removal.
	deb-systemd-helper unmask argonaut-server.service >/dev/null || true

	if deb-systemd-helper --quiet was-enabled argonaut-server.service; then
		# Create new symlinks, if any.
		deb-systemd-helper enable argonaut-server.service >/dev/null || true
	fi
fi

# Update the statefile to add new symlinks (if any), which need to be cleaned
# up on purge. Also remove old symlinks.
deb-systemd-helper update-state argonaut-server.service >/dev/null || true
# End automatically added section
# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/argonaut-server" ]; then
		update-rc.d argonaut-server defaults >/dev/null
		invoke-rc.d argonaut-server start || exit $?
	fi
fi
# End automatically added section
