#!/bin/sh
set -e

OUT=/dev/null

if [ "$1" = configure ]; then
    if ! getent passwd kdcproxy  > $OUT; then
        adduser --quiet --system --home / \
            --shell /usr/sbin/nologin --group \
            --no-create-home --gecos "IPA KDC Proxy User" \
            kdcproxy > $OUT
    fi
    if ! getent passwd ipaapi  > $OUT; then
        adduser --quiet --system --home / \
            --shell /usr/sbin/nologin --group \
            --no-create-home --gecos "IPA Framework User" \
            ipaapi > $OUT
    fi

    # add www-data to ipaapi group
    if ! id -Gn www-data | grep '\bipaapi\b' >/dev/null; then
        usermod www-data -a -G ipaapi
    fi

    if [ -e /usr/share/apache2/apache2-maintscript-helper ]; then
        . /usr/share/apache2/apache2-maintscript-helper
	if [ ! -e /etc/apache2/mods-enabled/auth_gssapi.load ]; then
            apache2_invoke enmod auth_gssapi || exit $?
        fi
	if [ ! -e /etc/apache2/mods-enabled/authz_user.load ]; then
            apache2_invoke enmod authz_user || exit $?
        fi
	if [ ! -e /etc/apache2/mods-enabled/deflate.load ]; then
            apache2_invoke enmod deflate || exit $?
        fi
	if [ ! -e /etc/apache2/mods-enabled/expires.load ]; then
            apache2_invoke enmod expires || exit $?
        fi
	if [ ! -e /etc/apache2/mods-enabled/headers.load ]; then
            apache2_invoke enmod headers || exit $?
        fi
	if [ ! -e /etc/apache2/mods-enabled/lookup_identity.load ]; then
            apache2_invoke enmod lookup_identity || exit $?
        fi
	if [ ! -e /etc/apache2/mods-enabled/proxy.load ]; then
            apache2_invoke enmod proxy || exit $?
        fi
	if [ ! -e /etc/apache2/mods-enabled/proxy_ajp.load ]; then
            apache2_invoke enmod proxy_ajp || exit $?
        fi
	if [ ! -e /etc/apache2/mods-enabled/proxy_http.load ]; then
            apache2_invoke enmod proxy_http || exit $?
        fi
	if [ ! -e /etc/apache2/mods-enabled/rewrite.load ]; then
            apache2_invoke enmod rewrite || exit $?
        fi
    fi

    # check if IPA is set up
    is_configured=`python2 -c 'from ipaserver.install import installutils; print "yes" if installutils.is_ipa_configured() else "no";'`
    if [ $is_configured = yes ]; then
        echo "Running ipa-server-upgrade..."
        ipa-server-upgrade --quiet >/dev/null
    fi
fi

if [ ! -e /run/apache2/ipa ]; then
    mkdir -m 0700 /run/apache2/ipa
    chown www-data:www-data /run/apache2/ipa

    if [ ! -e /run/apache2/ipa/clientcaches ]; then
        mkdir -m 0700 /run/apache2/ipa/clientcaches
        chown www-data:www-data /run/apache2/ipa/clientcaches
    fi
    if [ ! -e /run/apache2/ipa/krbcache ]; then
        mkdir -m 0700 /run/apache2/ipa/krbcache
        chown www-data:www-data /run/apache2/ipa/krbcache
    fi
fi

# Automatically added by dh_systemd_enable/11.3.5
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if deb-systemd-helper debian-installed 'ipa.service'; then
		# This will only remove masks created by d-s-h on package removal.
		deb-systemd-helper unmask 'ipa.service' >/dev/null || true

		if deb-systemd-helper --quiet was-enabled 'ipa.service'; then
			# Create new symlinks, if any.
			deb-systemd-helper enable 'ipa.service' >/dev/null || true
		fi
	fi

	# Update the statefile to add new symlinks (if any), which need to be cleaned
	# up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'ipa.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/11.3.5
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if deb-systemd-helper debian-installed 'ipa-dnskeysyncd.service'; then
		# This will only remove masks created by d-s-h on package removal.
		deb-systemd-helper unmask 'ipa-dnskeysyncd.service' >/dev/null || true

		if deb-systemd-helper --quiet was-enabled 'ipa-dnskeysyncd.service'; then
			# Create new symlinks, if any.
			deb-systemd-helper enable 'ipa-dnskeysyncd.service' >/dev/null || true
		fi
	fi

	# Update the statefile to add new symlinks (if any), which need to be cleaned
	# up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'ipa-dnskeysyncd.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/11.3.5
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if deb-systemd-helper debian-installed 'ipa-custodia.service'; then
		# This will only remove masks created by d-s-h on package removal.
		deb-systemd-helper unmask 'ipa-custodia.service' >/dev/null || true

		if deb-systemd-helper --quiet was-enabled 'ipa-custodia.service'; then
			# Create new symlinks, if any.
			deb-systemd-helper enable 'ipa-custodia.service' >/dev/null || true
		fi
	fi

	# Update the statefile to add new symlinks (if any), which need to be cleaned
	# up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'ipa-custodia.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/11.3.5
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if deb-systemd-helper debian-installed 'ipa-ods-exporter.service'; then
		# This will only remove masks created by d-s-h on package removal.
		deb-systemd-helper unmask 'ipa-ods-exporter.service' >/dev/null || true

		if deb-systemd-helper --quiet was-enabled 'ipa-ods-exporter.service'; then
			# Create new symlinks, if any.
			deb-systemd-helper enable 'ipa-ods-exporter.service' >/dev/null || true
		fi
	fi

	# Update the statefile to add new symlinks (if any), which need to be cleaned
	# up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'ipa-ods-exporter.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/11.3.5
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# In case this system is running systemd, we need to ensure that all
	# necessary tmpfiles (if any) are created before starting.
	if [ -d /run/systemd/system ] ; then
		systemd-tmpfiles --create ipa.conf >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_systemd_start/11.3.5
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		deb-systemd-invoke start 'ipa-custodia.service' 'ipa-dnskeysyncd.service' 'ipa-ods-exporter.service' 'ipa-ods-exporter.socket' 'ipa-otpd.socket' 'ipa.service' >/dev/null || true
	fi
fi
# End automatically added section

