#!/bin/sh
set -e
# Automatically added by dh_systemd_start/10.7.2
if [ -d /run/systemd/system ]; then
	deb-systemd-invoke stop iio-sensor-proxy.service >/dev/null
fi
# End automatically added section
