#!/bin/sh
set -e

# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p shedskin 
fi

if which pycompile >/dev/null 2>&1; then
	pycompile -p shedskin /usr/share/shedskin
fi

# End automatically added section
