#!/bin/sh

set -eu

# Remove directories and symlinks created during postinst.
if [ "$1" = "remove" ]; then
     rm -rf /usr/share/python-django-countries/locale
fi


# Automatically added by dh_python2:
if which pyclean >/dev/null 2>&1; then
	pyclean -p python-django-countries 
else
	dpkg -L python-django-countries | grep '\.py$' | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section

