#! /bin/sh

set -e

case "$1" in
  triggered|configure)
    if test -x /usr/bin/xine-list-1.2; then
      {
	cat /usr/share/gxine/gxine.desktop.in
	/usr/bin/xine-list-1.2
	echo
      } >/var/lib/xine/gxine.desktop.new
      echo "Updated the MIME types in gxine's menu file."
      mv /var/lib/xine/gxine.desktop.new /var/lib/xine/gxine.desktop
      dpkg-trigger /usr/share/applications
    else
      echo "Not updating the MIME types in gxine's menu file."
    fi
    ;;
esac

# Automatically added by dh_installmenu
if [ "$1" = "configure" ] && [ -x "`which update-menus 2>/dev/null`" ]; then
	update-menus
fi
# End automatically added section

