#!/bin/sh

set -e

# Automatically added by dh_installinit/11
if [ "$1" = "purge" ] ; then
	update-rc.d quake3-server remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/11
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'quake3-server.service' >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'quake3-server.service' >/dev/null
		deb-systemd-helper unmask 'quake3-server.service' >/dev/null
	fi
fi
# End automatically added section


if [ "$1" = "purge" ] ; then
    # Lock account on purge
    if [ -f /etc/shadow ]; then
        usermod -L -e 1 Debian-quake3
    else
        usermod -L Debian-quake3
    fi
    rm -r /var/games/quake3-server
    rmdir --ignore-fail-on-non-empty /var/games
fi
