#!/bin/sh

set -e

case "$1" in
  configure)
    if ! getent passwd Debian-quake3 >/dev/null; then
      adduser --disabled-password --quiet --system \
        --home /var/games/quake3-server --no-create-home \
        --gecos "Quake III Arena dedicated server" \
	--ingroup games --force-badname Debian-quake3
    fi
    # Unlock account, if it was locked by our postrm
    if [ -f /etc/shadow ]; then
      usermod -U -e '' Debian-quake3
    else
      usermod -U Debian-quake3
    fi
    install -d /var/games
    install -d /var/games/quake3-server
    chown Debian-quake3:games /var/games/quake3-server
    if [ -d /var/games/quake3-server/.q3a ] && ! [ -e /var/games/quake3-server/server.q3a ]; then
        # we use com_homepath to redirect server stuff to a non-hidden
        # directory and be ready for multi-instance; migrate old configuration
        ln -s .q3a /var/games/quake3-server/server.q3a
    fi
  ;;
  abort-upgrade|abort-remove|abort-deconfigure)
  ;;
  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac

# Automatically added by dh_systemd_enable/11
# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask 'quake3-server.service' >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled 'quake3-server.service'; then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable 'quake3-server.service' >/dev/null || true
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'quake3-server.service' >/dev/null || true
fi
# End automatically added section

# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p quake3-server /usr/share/games/quake3
fi

# End automatically added section
# Automatically added by dh_installinit/11
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/quake3-server" ]; then
		update-rc.d quake3-server defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d quake3-server $_dh_action || exit $?
	fi
fi
# End automatically added section

