#!/bin/sh

set -e

if [ "$1" != "upgrade" ] ; then
    update-alternatives --remove waitress-serve /usr/bin/waitress-serve-python3
fi


# Automatically added by dh_python3:
if which py3clean >/dev/null 2>&1; then
	py3clean -p python3-waitress 
else
	dpkg -L python3-waitress | perl -ne 's,/([^/]*)\.py$,/__pycache__/\1.*, or next; unlink $_ or die $! foreach glob($_)'
	find /usr/lib/python3/dist-packages/ -type d -name __pycache__ -empty -print0 | xargs --null --no-run-if-empty rmdir
fi

# End automatically added section

