#!/bin/bash

set -e

if [ "$1" = purge ] && [ -e /var/games/circuslinux/scorefile ]; then
  rm /var/games/circuslinux/scorefile
fi

# Automatically added by dh_installmenu
if [ -x "`which update-menus 2>/dev/null`" ]; then update-menus ; fi
# End automatically added section

