#!/bin/sh
set -e

# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p obfsproxy 
fi

# End automatically added section
# Automatically added by dh_installdeb/10.10.9
dpkg-maintscript-helper rm_conffile /etc/apparmor.d/usr.bin.obfsproxy 0.2.13-3~ obfsproxy -- "$@"
# End automatically added section
