#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.5.3
dpkg-maintscript-helper rm_conffile /etc/grub.d/10_hurd 2.00-14~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.5.3
dpkg-maintscript-helper rm_conffile /etc/grub.d/10_freebsd 2.00-14~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.5.3
dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/grub 2.02+dfsg1-9~ -- "$@"
# End automatically added section
