#!/bin/sh
set -e
# Automatically added by dh_installinit/10.10.9
if [ -x "/etc/init.d/clamav-daemon" ] && [ "$1" = remove ]; then
	invoke-rc.d clamav-daemon stop || exit $?
fi
# End automatically added section
