#!/bin/sh

set -e

DEF_FILE=/etc/default/nova-consoleproxy

if [ "${1}" = "configure" ] || [ "$1" = "reconfigure" ] ; then
	if [ ! -e ${DEF_FILE} ] && [ -r /usr/share/nova-consoleproxy/default ] ; then
		cp /usr/share/nova-consoleproxy/default ${DEF_FILE}
	fi
	if [ ! -r ${DEF_FILE} ] ; then
		exit 0
	fi

	. /usr/share/debconf/confmodule
	db_get nova-consoleproxy/daemon_type
	DAEMON_TYPE=$RET
	if ! grep -E -q "^[- \t]*NOVA_CONSOLE_PROXY_TYPE=" ${DEF_FILE} ; then
		echo "xenapi_connection_url=" >> ${DEF_FILE}
	fi
	sed -i "s#^[- \t]*NOVA_CONSOLE_PROXY_TYPE=.*#NOVA_CONSOLE_PROXY_TYPE=${DAEMON_TYPE}#" ${DEF_FILE}
	db_stop
fi

# Automatically added by dh_installinit/10.10.9
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/nova-novncproxy" ]; then
		update-rc.d nova-novncproxy defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d nova-novncproxy $_dh_action || exit $?
	fi
fi
# End automatically added section
# Automatically added by dh_installinit/10.10.9
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/nova-spicehtml5proxy" ]; then
		update-rc.d nova-spicehtml5proxy defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d nova-spicehtml5proxy $_dh_action || exit $?
	fi
fi
# End automatically added section
# Automatically added by dh_installinit/10.10.9
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/nova-xenvncproxy" ]; then
		update-rc.d nova-xenvncproxy defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d nova-xenvncproxy $_dh_action || exit $?
	fi
fi
# End automatically added section


exit 0
