#!/bin/bash -e

handle_init_errs ()
{
	RET=$?
	if [ "$RET" = "6" ]; then
		return 0
	else
		exit $RET
	fi
	set -e
}

# Automatically added by dh_installinit
if [ -x "/etc/init.d/spampd" ]; then
	invoke-rc.d spampd stop || handle_init_errs
fi
# End automatically added section


case "$1" in
	purge)
		deluser spampd > /dev/null 2>&1 || true
		delgroup spampd > /dev/null 2>&1 || true
		;;
	*)
		;;
esac
