#!/bin/sh
set -e

if dpkg-maintscript-helper supports mv_conffile 2>/dev/null; then
	dpkg-maintscript-helper mv_conffile /etc/apache2/mods-available/mod-evasive.load /etc/apache2/mods-available/evasive.load 1.10.1-1 -- "$@"
fi




