#!/bin/sh

set -e

if [ "$1" = "configure" ] ; then
	update-alternatives --install /usr/bin/oslo-messaging-send-notification oslo-messaging-send-notification /usr/bin/python2-oslo-messaging-send-notification 300
	update-alternatives --install /usr/bin/oslo-messaging-zmq-broker oslo-messaging-zmq-broker /usr/bin/python2-oslo-messaging-zmq-broker 300
fi


# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p python-oslo.messaging 
fi

# End automatically added section


exit 0
