#!/bin/sh
set -e

# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p aptoncd 
fi

if which pycompile >/dev/null 2>&1; then
	pycompile -p aptoncd /usr/share/aptoncd
fi

# End automatically added section
