#!/bin/sh
set -e
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/init.d/ulogd 2.0.4-2\~ ulogd -- \"\$\@\" 0 -- "$@"
# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/ulogd2" ] && [ "$1" = remove ]; then
	invoke-rc.d ulogd2 stop || exit $?
fi
# End automatically added section
