#!/bin/sh -e

# Automatically added by dh_installinit/11.4.1
if [ "$1" = "purge" ] ; then
	update-rc.d obsworker remove >/dev/null
fi
# End automatically added section


if [ "$1" = "purge" ]; then
    [ -d "/srv/obs/worker" ] && rm -rf /srv/obs/worker
    [ -d "/run/obs" ] && rm -rf /run/obs
    rmdir /srv/obs 2>/dev/null || true
    deluser --system --quiet obsworker || true
    delgroup --system --quiet obsworker || true
fi

