#!/bin/sh
set -e
# Automatically added by dh_installinit/11.5.4
if [ -x "/etc/init.d/cups-browsed" ] && [ "$1" = remove ]; then
	invoke-rc.d cups-browsed stop || exit 1
fi
# End automatically added section
