#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/sftpcloudfs" ]; then
	invoke-rc.d sftpcloudfs stop || true
fi
# End automatically added section

# Automatically added by dh_python2:
if which pyclean >/dev/null 2>&1; then
	pyclean -p sftpcloudfs 
else
	dpkg -L sftpcloudfs | grep \.py$ | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section
