#!/bin/sh
set -e
# Automatically added by dh_installdeb/10.7.2
dpkg-maintscript-helper symlink_to_dir /usr/share/gocode/src/github.com/sirupsen/logrus ../Sirupsen/logrus 1.0.2-2~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/10.7.2
dpkg-maintscript-helper dir_to_symlink /usr/share/gocode/src/github.com/Sirupsen/logrus ../sirupsen/logrus 1.0.2-2~ -- "$@"
# End automatically added section
