#!/bin/sh
set -e
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/default/ltsp-client-setup 5.5.4-3~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/init.d/ltsp-client-setup 5.5.4-3~ -- "$@"
# End automatically added section
