#!/bin/sh

# $Id: postinst 68 2006-05-16 17:48:07Z branden $

# Debian ctwm package post-installation script
# Copyright 1999, 2006 Branden Robinson.
# Licensed under the GNU General Public License, version 2.  See the file
# /usr/share/common-licenses/GPL or <http://www.gnu.org/copyleft/gpl.txt>.

set -e

trap "echo ;\
      echo 'Received signal.  Aborting configuration of ctwm package.' ;\
      echo ;\
      exit 1" 1 2 3 15

# Automatically added by dh_installmenu
inst=/etc/menu-methods/ctwm
if [ -f $inst ]; then
	chmod a+x $inst
	if [ -x "`which update-menus 2>/dev/null`" ]; then
		update-menus
	fi
fi
# End automatically added section


update-alternatives --install /usr/bin/x-window-manager x-window-manager \
    /usr/bin/ctwm 40 --slave /usr/share/man/man1/x-window-manager.1.gz \
    x-window-manager.1.gz /usr/share/man/man1/ctwm.1x.gz

exit

# vim:set ai et sw=4 ts=4 tw=80:
