#!/bin/sh
set -e

# Automatically added by dhpython:
if which pycompile >/dev/null 2>&1; then
	pycompile -p patool 
fi

# End automatically added section

# Automatically added by dhpython:
if which py3compile >/dev/null 2>&1; then
	py3compile -p patool -V 3.5-
fi

# End automatically added section
