#!/bin/sh

set -e

case "$1" in
    configure|reconfigure)
        adduser --system --disabled-password --disabled-login --home /var/run/lldpd \
       	    --no-create-home --quiet --force-badname --group _lldpd

        for i in /usr/sbin/lldpcli; do
            if ! dpkg-statoverride --list $i > /dev/null 2>&1; then
                dpkg-statoverride --update --add _lldpd adm 4750 $i
            fi
        done
        ;;
esac

dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/lldpcli.bash-completion 0.7.15~ lldpd -- "$@"

# Automatically added by dh_systemd_enable
# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask lldpd.service >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled lldpd.service; then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable lldpd.service >/dev/null || true
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state lldpd.service >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/lldpd" ]; then
		update-rc.d lldpd defaults >/dev/null
		invoke-rc.d lldpd start || exit $?
	fi
fi
# End automatically added section


exit 0
