#! /bin/sh
# prerm script for xymon

set -e

# Workaround for http://bugs.debian.org/560317 in case debconf is too old like on Squeeze
export DPKG_MAINTSCRIPT_PACKAGE=${DPKG_MAINTSCRIPT_PACKAGE:-xymon-client}
export DPKG_MAINTSCRIPT_NAME=${DPKG_MAINTSCRIPT_NAME:-prerm}

# Automatically added by dh_installdeb
dpkg-maintscript-helper mv_conffile /etc/hobbit/clientlaunch.cfg /etc/xymon/clientlaunch.cfg 4.3.7-1~~ xymon-client -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper mv_conffile /etc/hobbit/hobbitclient.cfg /etc/xymon/xymonclient.cfg 4.3.7-1~~ xymon-client -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper mv_conffile /etc/hobbit/localclient.cfg /etc/xymon/localclient.cfg 4.3.7-1~~ xymon-client -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper mv_conffile /etc/logrotate.d/hobbit-client /etc/logrotate.d/xymon-client 4.3.7-1~~ xymon-client -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper mv_conffile /etc/init.d/hobbit-client /etc/init.d/xymon-client 4.3.7-1~~ xymon-client -- "$@"
# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/xymon-client" ]; then
	invoke-rc.d xymon-client stop || exit $?
fi
# End automatically added section


exit 0
