#!/bin/sh

set -e

if dpkg-maintscript-helper supports rm_conffile; then
       dpkg-maintscript-helper rm_conffile \
               /etc/bash_completion.d/dzil 5.043-1~ libdist-zilla-perl -- "$@"
fi


