#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/lyskom-server" ] && [ "$1" = remove ]; then
	invoke-rc.d lyskom-server stop || exit $?
fi
# End automatically added section
