#!/bin/sh
set -e

if [ -x "/etc/init.d/dpnsdaemon" ]; then
	if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
		invoke-rc.d dpnsdaemon stop || exit $?
	else
		/etc/init.d/dpnsdaemon stop || exit $?
	fi
fi

if [ "$1" = "remove" ] ; then
	update-alternatives --remove dpnsdaemon /usr/lib/dpm-mysql/dpnsdaemon
fi


