#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/lemonldap-ng-fastcgi-server" ]; then
	invoke-rc.d lemonldap-ng-fastcgi-server stop || exit $?
fi
# End automatically added section
