#!/bin/sh

set -e

if [ "${1}" = "remove" ] || [ "${1}" = "disappear" ]; then
	update-alternatives --remove puppet-module-galera /usr/share/puppet/modules.available/michaeltchapman-galera
fi



exit 0
