#!/bin/sh -e

case "$1" in
	remove|purge)

		if [ "$1" = "purge" -a -e /usr/share/debconf/confmodule ]; then
		# Source debconf library.
			. /usr/share/debconf/confmodule
			# Remove my changes to the db.
			db_purge
		fi
		;;

	upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
		;;
esac

# Automatically added by dh_installinit/10.7.2
if [ "$1" = "purge" ] ; then
	update-rc.d nas remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installdebconf/10.7.2
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

