#!/bin/sh
set -e


if [ "$1" = "triggered" ]; then

	for trigger in $2
	do
		case $trigger in
			*--ping)
				dpkg-trigger --no-await ${trigger%--ping}--pong
				;;
		esac
	done

fi


# Automatically added by dh_installdeb/11.5.4
dpkg-maintscript-helper symlink_to_dir /usr/share/doc/update-glx glx-diversions 0.7.4\~ -- "$@"
# End automatically added section

